import {NextRequest,NextResponse} from 'next/server';
import {CoachAuthError,requireCoach,type CoachIdentity} from '@/lib/server/requireCoach';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_ANON_KEY;
function headers(actor:CoachIdentity,extra:HeadersInit={}){if(!URL||!KEY)throw new Error('Supabase access is not configured.');const h=new Headers(extra);h.set('apikey',KEY);h.set('Authorization',`Bearer ${actor.accessToken}`);h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');return h;}
async function rest<T>(actor:CoachIdentity,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:headers(actor,init.headers),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Coach communication failed (${r.status}) ${t.slice(0,300)}`);return (t?JSON.parse(t):null) as T;}
const txt=(v:unknown,n=5000)=>String(v??'').trim().slice(0,n);const uuid=(v:unknown)=>{const s=txt(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null};
const authError=(e:unknown)=>e instanceof CoachAuthError?NextResponse.json({error:e.message},{status:e.status}):null;
function allows(actor:CoachIdentity,org:string,team:string){return actor.isSuperUser||actor.assignments.some(a=>a.organization_id===org&&(a.team_id===team||a.team_id===null));}

export async function GET(request:NextRequest){try{const actor=await requireCoach(request);const u=new URL(request.url);const teamId=uuid(u.searchParams.get('team_id'))??actor.assignments.find(a=>a.team_id)?.team_id??null;const assignment=actor.assignments.find(a=>!teamId||a.team_id===teamId||a.team_id===null);const organizationId=assignment?.organization_id??null;if(!teamId||!organizationId||!allows(actor,organizationId,teamId))return NextResponse.json({error:'Authorized Coach team is required.'},{status:403});
const [members,policies,threads]=await Promise.all([
rest<any[]>(actor,`team_memberships?team_id=eq.${teamId}&status=eq.active&select=athlete_id,person_id,athletes(id,person_id,primary_family_id,people:person_id(id,first_name,last_name,birth_date))`),
rest<any[]>(actor,`communication_safeguarding_policies?organization_id=eq.${organizationId}&status=eq.active&select=*&order=effective_from.desc`),
rest<any[]>(actor,`communication_threads?team_id=eq.${teamId}&select=id,title,thread_type,minor_safe_mode,status,created_at&order=created_at.desc&limit=25`)
]);
const athleteIds=members.map(m=>m.athlete_id).filter(Boolean);const links=athleteIds.length?await rest<any[]>(actor,`communication_guardian_links?athlete_id=in.(${athleteIds.join(',')})&status=eq.active&select=athlete_id,guardian_person_id,communication_scope,status,valid_until`):[];const guardianIds=[...new Set(links.map(l=>l.guardian_person_id).filter(Boolean))];const guardians=guardianIds.length?await rest<any[]>(actor,`people?id=in.(${guardianIds.join(',')})&select=id,first_name,last_name`):[];const guardianById=new Map(guardians.map(g=>[g.id,g]));const linkByAthlete=new Map<string,any[]>();for(const l of links){const a=linkByAthlete.get(l.athlete_id)||[];a.push({...l,guardian:guardianById.get(l.guardian_person_id)||null});linkByAthlete.set(l.athlete_id,a)}
const now=new Date();const roster=members.map(m=>{const p=m.athletes?.people;const birth=p?.birth_date?new Date(`${p.birth_date}T00:00:00Z`):null;let age:null|number=null;if(birth){age=now.getUTCFullYear()-birth.getUTCFullYear();const md=now.getUTCMonth()-birth.getUTCMonth();if(md<0||(md===0&&now.getUTCDate()<birth.getUTCDate()))age--;}const minor=age!==null&&age<18;return {athlete_id:m.athlete_id,person_id:m.athletes?.person_id??m.person_id,name:[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Athlete',age,is_minor:minor,guardian_links:linkByAthlete.get(m.athlete_id)||[]};});
return NextResponse.json({source:'LS1Sports canonical Communications + Athlete + Family data',mission:'Coach decides. ERP executes. Agents watch.',organization_id:organizationId,team_id:teamId,policies,threads,roster,summary:{athletes:roster.length,minors:roster.filter(r=>r.is_minor).length,minors_without_guardian_link:roster.filter(r=>r.is_minor&&!r.guardian_links.length).length,active_policies:policies.length}});
}catch(e){const a=authError(e);if(a)return a;return NextResponse.json({error:e instanceof Error?e.message:'Communication workspace failed.'},{status:500});}}

export async function POST(request:NextRequest){try{const actor=await requireCoach(request);if(!actor.personId)return NextResponse.json({error:'Canonical Coach identity required.'},{status:409});const b=await request.json();const action=txt(b.action,60),organizationId=uuid(b.organization_id),teamId=uuid(b.team_id);if(!organizationId||!teamId||!allows(actor,organizationId,teamId))return NextResponse.json({error:'Authorized Coach team is required.'},{status:403});
if(action==='prepare-team-message'){const body=txt(b.body,8000),title=txt(b.title,180)||'Coach team update';if(!body)return NextResponse.json({error:'Message body is required.'},{status:400});const members=await rest<any[]>(actor,`team_memberships?team_id=eq.${teamId}&status=eq.active&select=athlete_id,person_id,athletes(id,person_id,primary_family_id,people:person_id(id,birth_date))`);const athleteIds=members.map(m=>m.athlete_id).filter(Boolean);const links=athleteIds.length?await rest<any[]>(actor,`communication_guardian_links?athlete_id=in.(${athleteIds.join(',')})&status=eq.active&select=athlete_id,guardian_person_id`):[];const policies=await rest<any[]>(actor,`communication_safeguarding_policies?organization_id=eq.${organizationId}&status=eq.active&select=*`);const requiresGuardian=policies.some(p=>p.applies_to_minors&&p.guardian_visibility_required);const now=new Date();const recipients=new Set<string>();let minors=0,blocked=0;for(const m of members){const p=m.athletes?.people;const birth=p?.birth_date?new Date(`${p.birth_date}T00:00:00Z`):null;let age=99;if(birth){age=now.getUTCFullYear()-birth.getUTCFullYear();const md=now.getUTCMonth()-birth.getUTCMonth();if(md<0||(md===0&&now.getUTCDate()<birth.getUTCDate()))age--;}if(age<18){minors++;const gs=links.filter(l=>l.athlete_id===m.athlete_id).map(l=>l.guardian_person_id).filter(Boolean);if(requiresGuardian&&!gs.length){blocked++;continue;}gs.forEach(g=>recipients.add(g));if(!requiresGuardian&&m.athletes?.person_id)recipients.add(m.athletes.person_id);}else if(m.athletes?.person_id||m.person_id)recipients.add(m.athletes?.person_id||m.person_id);}const proposal={title,body,audience:'team',recipient_person_ids:[...recipients],safeguarding:{minors,guardian_visibility_required:requiresGuardian,blocked_minor_records:blocked,policy_count:policies.length},prepared_from:'canonical team roster + guardian links + safeguarding policy'};const row=(await rest<any[]>(actor,'coach_agent_proposals',{method:'POST',body:JSON.stringify({organization_id:organizationId,coach_person_id:actor.personId,team_id:teamId,agent_type:'communication',proposal_type:'team_message',title:`Prepared communication · ${title}`,summary:`Prepared for ${recipients.size} canonical recipients; ${blocked} minor records blocked pending guardian linkage.`,proposal,confidence:blocked?0.65:0.9,status:'pending_review',requires_coach_approval:true,source_evidence:{tables:['team_memberships','communication_guardian_links','communication_safeguarding_policies']}})}))[0];return NextResponse.json(row,{status:201});}
if(action==='approve-team-message'){const proposalId=uuid(b.proposal_id);if(!proposalId)return NextResponse.json({error:'Proposal is required.'},{status:400});const p=(await rest<any[]>(actor,`coach_agent_proposals?id=eq.${proposalId}&coach_person_id=eq.${actor.personId}&status=eq.pending_review&select=*&limit=1`))[0];if(!p||p.agent_type!=='communication')return NextResponse.json({error:'Pending communication proposal not found.'},{status:404});const proposal=p.proposal||{};if(Number(proposal?.safeguarding?.blocked_minor_records||0)>0)return NextResponse.json({error:'Cannot approve: one or more minor athlete records lack required guardian linkage.'},{status:409});const thread=(await rest<any[]>(actor,'communication_threads',{method:'POST',body:JSON.stringify({tenant_id:actor.tenantId,organization_id:organizationId,team_id:teamId,thread_type:'team',title:txt(proposal.title,180)||'Coach team update',minor_safe_mode:Number(proposal?.safeguarding?.minors||0)>0,status:'active',created_by:actor.personId})}))[0];const message=(await rest<any[]>(actor,'communication_messages',{method:'POST',body:JSON.stringify({thread_id:thread.id,sender_person_id:actor.personId,sent_at:new Date().toISOString(),body:txt(proposal.body,8000),message_type:'coach_update',delivery_status:'queued',moderated:Number(proposal?.safeguarding?.minors||0)>0,metadata:{source:'coach_communication_agent',proposal_id:proposalId}})}))[0];const ids:Array<string>=Array.isArray(proposal.recipient_person_ids)?proposal.recipient_person_ids:[];if(ids.length)await rest(actor,'communication_message_recipients',{method:'POST',body:JSON.stringify(ids.map(id=>({message_id:message.id,recipient_person_id:id,delivery_status:'queued',metadata:{source:'coach_communication_agent'}})))});await rest(actor,`coach_agent_proposals?id=eq.${proposalId}`,{method:'PATCH',body:JSON.stringify({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by_person_id:actor.personId,decision_note:'Coach approved canonical communication for delivery queue.'})});return NextResponse.json({thread,message,recipient_count:ids.length,status:'queued'});}
return NextResponse.json({error:'Unsupported communication action.'},{status:400});
}catch(e){const a=authError(e);if(a)return a;return NextResponse.json({error:e instanceof Error?e.message:'Communication action failed.'},{status:500});}}
