import { NextRequest,NextResponse } from 'next/server';
import { requireAdmin,AdminAuthError,type AdminIdentity } from '@/lib/server/requireAdmin';
import { adminRest } from '@/lib/server/adminRest';
import { writeAdminAuditEvent } from '@/lib/server/writeAdminAuditEvent';
export const dynamic='force-dynamic'; export const revalidate=0; type Row=Record<string,any>;
function canCase(actor:AdminIdentity){return actor.isSuperUser||actor.roles.some(r=>['org_admin','operations','registrar'].includes(r))}
function canFinancialDecision(actor:AdminIdentity){return actor.isSuperUser||actor.roles.some(r=>['org_admin','treasurer'].includes(r))}
function scopedOrg(actor:AdminIdentity,id:string){if(actor.isSuperUser)return true;return actor.organizationIds.includes(id)}
async function snapshot(actor:AdminIdentity){const cases=await adminRest<Row[]>(actor,'urws_cases?select=id,organization_id,case_type_code,subject_type,subject_id,status,priority,policy_outcome,public_summary,financial_impact,currency,opened_at,resolved_at,updated_at&order=opened_at.desc&limit=300').catch(()=>[]);const ids=cases.map(x=>x.id);if(!ids.length)return {cases:[],evidence:[],packets:[],decisions:[],obligations:[],remedies:[],history:[],canCase:canCase(actor),canFinancialDecision:canFinancialDecision(actor)};const q=ids.map(encodeURIComponent).join(',');const [evidence,packets,decisions,obligations,remedies,history]=await Promise.all([adminRest<Row[]>(actor,`urws_evidence_items?select=id,case_id,evidence_type,source_type,occurred_at,sensitivity,summary,created_at&case_id=in.(${q})&sensitivity=eq.standard&order=occurred_at.desc`).catch(()=>[]),adminRest<Row[]>(actor,`urws_decision_packets?select=id,case_id,packet_version,status,public_facts,financial_summary,evidence_summary,authority_summary,missing_evidence,recommendation,recommendation_rationale,prepared_at&case_id=in.(${q})&order=prepared_at.desc`).catch(()=>[]),adminRest<Row[]>(actor,`urws_decisions?select=id,case_id,decision_type,policy_outcome,human_outcome,policy_overridden,decided_by_person_id,rationale,financial_impact,currency,decided_at&case_id=in.(${q})&order=decided_at.desc`).catch(()=>[]),adminRest<Row[]>(actor,`urws_obligations?select=id,case_id,obligation_type,obligated_party_type,description,due_at,status,satisfied_at&case_id=in.(${q})&order=due_at.asc`).catch(()=>[]),adminRest<Row[]>(actor,`urws_remedies?select=id,case_id,decision_id,remedy_type,status,amount,currency,effective_at,completed_at,description&case_id=in.(${q})&order=created_at.desc`).catch(()=>[]),adminRest<Row[]>(actor,`urws_case_status_history?select=id,case_id,from_status,to_status,reason,changed_at&case_id=in.(${q})&order=changed_at.desc`).catch(()=>[])]);return {cases,evidence,packets,decisions,obligations,remedies,history,canCase:canCase(actor),canFinancialDecision:canFinancialDecision(actor)} }
export async function GET(request:NextRequest){try{const actor=await requireAdmin(request);return NextResponse.json(await snapshot(actor))}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'URWS unavailable.'},{status:e instanceof AdminAuthError?e.status:500})}}
export async function POST(request:NextRequest){try{const actor=await requireAdmin(request);const body=await request.json() as Row;const action=String(body.action||'');
 if(action==='create-case'){if(!canCase(actor))throw new AdminAuthError('Your Admin role cannot open URWS cases.',403);const organization_id=String(body.organization_id||'');if(!organization_id||!scopedOrg(actor,organization_id))throw new AdminAuthError('Organization scope denied.',403);const rows=await adminRest<Row[]>(actor,'urws_cases',{method:'POST',body:JSON.stringify({organization_id,case_type_code:String(body.case_type_code||'service_failure'),subject_type:String(body.subject_type||'membership'),subject_id:body.subject_id||null,opened_by_person_id:actor.personId,owner_person_id:actor.personId,status:'open',priority:String(body.priority||'normal'),public_summary:String(body.public_summary||'').trim()||'URWS case opened for review.',financial_impact:Number(body.financial_impact||0),currency:String(body.currency||'CAD')})});await writeAdminAuditEvent(actor,{action:'URWS_CASE_OPENED',entityType:'urws_case',entityId:rows?.[0]?.id,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
 if(action==='add-evidence'){if(!canCase(actor)&&!canFinancialDecision(actor))throw new AdminAuthError('Your Admin role cannot add URWS evidence.',403);const case_id=String(body.case_id||'');const c=(await adminRest<Row[]>(actor,`urws_cases?select=id,organization_id,tenant_id&id=eq.${encodeURIComponent(case_id)}&limit=1`))?.[0];if(!c)throw new Error('Case not found.');const rows=await adminRest<Row[]>(actor,'urws_evidence_items',{method:'POST',body:JSON.stringify({tenant_id:c.tenant_id,organization_id:c.organization_id,case_id,evidence_type:String(body.evidence_type||'admin_note'),source_type:'admin',occurred_at:new Date().toISOString(),recorded_by_person_id:actor.personId,sensitivity:'standard',summary:String(body.summary||'').trim(),facts:{source:'admin_workspace'}})});await writeAdminAuditEvent(actor,{action:'URWS_EVIDENCE_ADDED',entityType:'urws_case',entityId:case_id,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
 if(action==='build-packet'){const case_id=String(body.case_id||'');const rows=await adminRest<Row[]>(actor,'rpc/urws_build_decision_packet',{method:'POST',body:JSON.stringify({p_case_id:case_id,p_prepared_by_person_id:actor.personId})});await writeAdminAuditEvent(actor,{action:'URWS_DECISION_PACKET_BUILT',entityType:'urws_case',entityId:case_id});return NextResponse.json({ok:true,packetId:rows})}
 if(action==='set-status'){if(!canCase(actor))throw new AdminAuthError('Your Admin role cannot change URWS case status.',403);const case_id=String(body.case_id||'');const status=String(body.status||'');if(!['open','under_review','escalated','resolved','closed','cancelled'].includes(status))throw new Error('Unsupported case status.');const rows=await adminRest<Row[]>(actor,`urws_cases?id=eq.${encodeURIComponent(case_id)}`,{method:'PATCH',body:JSON.stringify({status,resolved_at:['resolved','closed'].includes(status)?new Date().toISOString():null})});await writeAdminAuditEvent(actor,{action:'URWS_CASE_STATUS_CHANGED',entityType:'urws_case',entityId:case_id,afterData:rows?.[0],reason:String(body.reason||'')});return NextResponse.json({ok:true,record:rows?.[0]})}
 throw new Error('Unsupported URWS action.');
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'URWS action failed.'},{status:e instanceof AdminAuthError?e.status:400})}}
