import {NextRequest,NextResponse} from'next/server';
import{hasPermission,resolveAccess,serviceHeaders}from'@/lib/server/accessControl';
import{supabaseServerConfig}from'@/lib/server/superuserAuth';

export const dynamic='force-dynamic';export const revalidate=0;const noStore={'Cache-Control':'no-store'};
type Config={table:string;read:string;write:string;fields:string[];required:string[];scope:'organization'|'tenant'|'global';status?:boolean};
const RESOURCES:Record<string,Config>={
 organizations:{table:'organizations',read:'organizations.read',write:'organizations.update',fields:['code','name','legal_name','organization_type','status','parent_organization_id'],required:['code','name'],scope:'tenant',status:true},
 programs:{table:'programs',read:'record.read',write:'record.update',fields:['organization_id','sport_id','code','name','program_type','status'],required:['organization_id','code','name'],scope:'organization',status:true},
 seasons:{table:'seasons',read:'record.read',write:'record.update',fields:['organization_id','sport_id','code','name','starts_on','ends_on','status'],required:['organization_id','code','name'],scope:'organization',status:true},
 teams:{table:'teams',read:'teams.read',write:'teams.update',fields:['organization_id','sport_id','program_id','season_id','code','name','competitive_level','status'],required:['organization_id','code','name'],scope:'organization',status:true},
 memberships:{table:'memberships',read:'record.read',write:'record.update',fields:['organization_id','person_id','sport_id','membership_number','membership_type','starts_on','ends_on','status','governing_body_id'],required:['organization_id','person_id'],scope:'organization',status:true},
 sites:{table:'sites',read:'record.read',write:'record.update',fields:['organization_id','code','name','address_line1','city','region','postal_code','country_code','timezone','status'],required:['organization_id','code','name'],scope:'organization',status:true},
 invoices:{table:'invoices',read:'finance.read',write:'record.update',fields:['invoice_number','invoice_date','due_date','currency','subtotal','tax_total','total','balance_due','status'],required:[],scope:'global',status:true},
 payments:{table:'payments',read:'finance.read',write:'record.update',fields:['invoice_id','payment_date','amount','currency','method','processor_reference','status'],required:[],scope:'global',status:true},
 payroll:{table:'payroll_runs',read:'record.read',write:'record.update',fields:['period_start','period_end','pay_date','status','gross_total','net_total'],required:[],scope:'global',status:true},
 compliance:{table:'compliance_requirements',read:'record.read',write:'record.update',fields:['code','name','applies_to_role','applies_to_minor','severity','validity_days','rule_definition'],required:['code','name'],scope:'global'}
};
const clean=(v:unknown)=>typeof v==='string'?v.trim():v;const enc=(v:string)=>encodeURIComponent(v);
async function tenantOrganizations(url:string,headers:Record<string,string>,tenant:string){const r=await fetch(`${url}/rest/v1/organizations?select=id&tenant_id=eq.${enc(tenant)}`,{headers,cache:'no-store'});if(!r.ok)throw new Error('Unable to resolve tenant organization scope.');return(await r.json() as Array<{id:string}>).map(x=>x.id)}
function scopeQuery(c:Config,tenant:string|null,orgs:string[]){if(c.scope==='tenant'&&tenant)return`&tenant_id=eq.${enc(tenant)}`;if(c.scope==='organization'&&!orgs.length)return'&id=is.null';if(c.scope==='organization')return`&organization_id=in.(${orgs.join(',')})`;return''}
async function context(request:NextRequest,resource:string,write=false){const c=RESOURCES[resource];if(!c)return{error:NextResponse.json({error:'Unsupported Admin resource.'},{status:404,headers:noStore})};const ctx=await resolveAccess(request);if(!ctx)return{error:NextResponse.json({error:'Authentication required.'},{status:401,headers:noStore})};if(!ctx.isPlatformSuperUser&&!ctx.person)return{error:NextResponse.json({error:'Canonical client identity is required.'},{status:403,headers:noStore})};const permission=write?c.write:c.read;if(!hasPermission(ctx,permission)&&!(write&&hasPermission(ctx,write?'record.update':'record.read')))return{error:NextResponse.json({error:`${permission} is required.`},{status:403,headers:noStore})};const{url}=supabaseServerConfig();const headers=serviceHeaders();if(!headers)return{error:NextResponse.json({error:'Server authorization is not configured.'},{status:500,headers:noStore})};const tenant=ctx.person?.tenant_id||null;const orgs=tenant?await tenantOrganizations(url,headers,tenant):[];return{c,ctx,url,headers,tenant,orgs}}
export async function GET(request:NextRequest){try{const resource=request.nextUrl.searchParams.get('resource')||'';const x=await context(request,resource);if(x.error)return x.error;const{c,url,headers,tenant,orgs}=x as any;const q=scopeQuery(c,tenant,orgs);const r=await fetch(`${url}/rest/v1/${c.table}?select=*&order=id.desc&limit=250${q}`,{headers,cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(`Canonical ${resource} read failed (${r.status}).`);return NextResponse.json({resource,rows:text?JSON.parse(text):[],fields:c.fields,required:c.required,canWrite:true,generatedAt:new Date().toISOString()},{headers:noStore})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Admin resource read failed.'},{status:500,headers:noStore})}}
export async function POST(request:NextRequest){try{const body=await request.json() as any,resource=String(body.resource||'');const x=await context(request,resource,true);if(x.error)return x.error;const{c,url,headers,tenant,orgs,ctx}=x as any;const row:Record<string,unknown>={};for(const f of c.fields)if(body.row?.[f]!==undefined)row[f]=clean(body.row[f]);if(c.scope==='tenant'&&tenant)row.tenant_id=tenant;if(c.scope==='organization'){if(!row.organization_id&&orgs.length===1)row.organization_id=orgs[0];if(!orgs.includes(String(row.organization_id||'')))return NextResponse.json({error:'Organization scope is outside your client boundary.'},{status:403,headers:noStore})}for(const f of c.required)if(row[f]===undefined||row[f]===null||row[f]==='')return NextResponse.json({error:`${f} is required.`},{status:400,headers:noStore});const r=await fetch(`${url}/rest/v1/${c.table}`,{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify(row),cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(text.slice(0,300)||'Create failed.');return NextResponse.json({ok:true,row:text?JSON.parse(text)[0]:null,actor:ctx.user.id},{headers:noStore})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Create failed.'},{status:400,headers:noStore})}}
export async function PATCH(request:NextRequest){try{const body=await request.json() as any,resource=String(body.resource||''),id=String(body.id||'');if(!id)return NextResponse.json({error:'id is required.'},{status:400,headers:noStore});const x=await context(request,resource,true);if(x.error)return x.error;const{c,url,headers,tenant,orgs}=x as any;const scope=scopeQuery(c,tenant,orgs);const beforeR=await fetch(`${url}/rest/v1/${c.table}?select=*&id=eq.${enc(id)}${scope}&limit=1`,{headers,cache:'no-store'});const before=beforeR.ok?(await beforeR.json() as any[])[0]:null;if(!before)return NextResponse.json({error:'Record not found in your authorized scope.'},{status:404,headers:noStore});const row:Record<string,unknown>={};for(const f of c.fields)if(body.row?.[f]!==undefined)row[f]=clean(body.row[f]);if('organization_id'in row&&!orgs.includes(String(row.organization_id||''))&&!((x as any).ctx.isPlatformSuperUser))return NextResponse.json({error:'Organization scope is outside your client boundary.'},{status:403,headers:noStore});const r=await fetch(`${url}/rest/v1/${c.table}?id=eq.${enc(id)}`,{method:'PATCH',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify(row),cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(text.slice(0,300)||'Update failed.');return NextResponse.json({ok:true,row:text?JSON.parse(text)[0]:null},{headers:noStore})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Update failed.'},{status:400,headers:noStore})}}
export async function DELETE(request:NextRequest){try{const resource=request.nextUrl.searchParams.get('resource')||'',id=request.nextUrl.searchParams.get('id')||'';if(!id)return NextResponse.json({error:'id is required.'},{status:400,headers:noStore});const x=await context(request,resource,true);if(x.error)return x.error;const{c,url,headers,tenant,orgs}=x as any;const scope=scopeQuery(c,tenant,orgs);const check=await fetch(`${url}/rest/v1/${c.table}?select=id&id=eq.${enc(id)}${scope}&limit=1`,{headers,cache:'no-store'});if(!check.ok||(await check.json() as any[]).length===0)return NextResponse.json({error:'Record not found in your authorized scope.'},{status:404,headers:noStore});if(!c.status||!c.fields.includes('status'))return NextResponse.json({error:'This resource requires a domain-specific lifecycle action; physical delete is disabled.'},{status:409,headers:noStore});const r=await fetch(`${url}/rest/v1/${c.table}?id=eq.${enc(id)}`,{method:'PATCH',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({status:'inactive'}),cache:'no-store'});if(!r.ok)throw new Error('Archive/deactivate failed.');return NextResponse.json({ok:true,row:(await r.json())[0]||null},{headers:noStore})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Lifecycle action failed.'},{status:400,headers:noStore})}}
