import {NextRequest,NextResponse} from 'next/server';
import {CoachAuthError,requireCoach,type CoachIdentity} from '@/lib/server/requireCoach';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_ANON_KEY;
export const dynamic='force-dynamic';
export const revalidate=0;

function headers(actor:CoachIdentity,extra:HeadersInit={}){if(!KEY)throw new Error('Supabase access is not configured.');const h=new Headers(extra);h.set('apikey',KEY);h.set('Authorization',`Bearer ${actor.accessToken}`);h.set('Accept','application/json');if(!h.has('Content-Type'))h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');return h;}
async function rest<T>(actor:CoachIdentity,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:headers(actor,init.headers),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Coach workout operation failed (${r.status}) ${t.slice(0,260)}`);return(t?JSON.parse(t):null)as T;}
function authError(e:unknown){if(e instanceof CoachAuthError)return NextResponse.json({error:e.message},{status:e.status});return null;}
function csv(ids:string[]){return ids.map(id=>`\"${id}\"`).join(',')}
function uniq<T>(items:T[]){return Array.from(new Set(items));}
function text(v:unknown,max=4000){return String(v??'').trim().slice(0,max)}
function uuid(v:unknown){const s=text(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null;}
function numberOrNull(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
async function teamsFor(actor:CoachIdentity){const assigned=uniq(actor.assignments.map(a=>a.team_id).filter(Boolean)as string[]);if(actor.isSuperUser)return rest<any[]>(actor,'teams?select=id,organization_id,sport_id,season_id,name,status&status=eq.active&order=name.asc&limit=200');if(!assigned.length)return[];return rest<any[]>(actor,`teams?select=id,organization_id,sport_id,season_id,name,status&id=in.(${csv(assigned)})&status=eq.active&order=name.asc`);}
function canUse(actor:CoachIdentity,team:any){return actor.isSuperUser||actor.assignments.some(a=>a.team_id===team.id||(!a.team_id&&a.organization_id===team.organization_id));}
async function audit(actor:CoachIdentity,team:any,action:string,entityType:string,entityId:string|null,after:unknown){await rest(actor,'coach_decision_log',{method:'POST',body:JSON.stringify({organization_id:team.organization_id,coach_person_id:actor.personId,action,entity_type:entityType,entity_id:entityId,decision:'coach_authored',after_data:after,source:'coach_workout'})});}

export async function GET(request:NextRequest){
 try{
  const actor=await requireCoach(request),teams=await teamsFor(actor),requested=request.nextUrl.searchParams.get('team_id'),teamId=requested&&teams.some(t=>t.id===requested)?requested:(teams[0]?.id||null),team=teams.find(t=>t.id===teamId)||null;
  if(!team)return NextResponse.json({generatedAt:new Date().toISOString(),teams,selectedTeamId:null,plans:[],sessions:[],blocks:[],modifications:[],athletes:[],attendanceSessions:[],source:'LS1 canonical training data'});
  const memberships=await rest<any[]>(actor,`team_memberships?select=athlete_id&team_id=eq.${team.id}&status=eq.active&limit=1000`),athleteIds=uniq(memberships.map(m=>m.athlete_id).filter(Boolean));
  const athletes=athleteIds.length?await rest<any[]>(actor,`athletes?select=id,person_id,athlete_number&id=in.(${csv(athleteIds)})&limit=1000`):[],personIds=uniq(athletes.map(a=>a.person_id).filter(Boolean));
  const people=personIds.length?await rest<any[]>(actor,`people?select=id,first_name,preferred_name,last_name&id=in.(${csv(personIds)})&limit=1000`):[],pmap=new Map<string,any>(people.map(p=>[String(p.id),p] as [string,any]));
  const athleteRows=athletes.map(a=>{const p=pmap.get(String(a.person_id));return{id:a.id,name:p?[p.preferred_name||p.first_name,p.last_name].filter(Boolean).join(' '):'Athlete',athleteNumber:a.athlete_number};});
  const plans=await rest<any[]>(actor,`training_plans?select=id,team_id,season_id,name,plan_type,starts_on,ends_on,status,created_by&team_id=eq.${team.id}&order=starts_on.desc.nullslast&limit=200`),planIds=plans.map(p=>p.id);
  const sessions=planIds.length?await rest<any[]>(actor,`training_sessions?select=id,training_plan_id,attendance_session_id,title,session_type,total_load,total_distance,distance_unit,workout_definition&training_plan_id=in.(${csv(planIds)})&limit=1000`):[],sessionIds=sessions.map(s=>s.id);
  const blocks=sessionIds.length?await rest<any[]>(actor,`coach_session_blocks?select=*&training_session_id=in.(${csv(sessionIds)})&order=training_session_id.asc,sort_order.asc&limit=5000`):[];
  const modifications=sessionIds.length?await rest<any[]>(actor,`coach_athlete_session_modifications?select=*&training_session_id=in.(${csv(sessionIds)})&status=eq.active&order=created_at.asc&limit=5000`):[];
  const attendanceSessions=await rest<any[]>(actor,`attendance_sessions?select=id,session_date,start_time,end_time,session_type,status&team_id=eq.${team.id}&session_date=gte.${new Date().toISOString().slice(0,10)}&order=session_date.asc,start_time.asc&limit=200`);
  return NextResponse.json({generatedAt:new Date().toISOString(),source:'Canonical training plans/sessions + Coach-authored structured blocks and athlete modifications',teams,selectedTeamId:team.id,plans,sessions,blocks,modifications,athletes:athleteRows,attendanceSessions},{headers:{'Cache-Control':'no-store, max-age=0'}});
 }catch(e){const auth=authError(e);if(auth)return auth;return NextResponse.json({error:e instanceof Error?e.message:'Coach workout data unavailable.'},{status:500});}
}

export async function POST(request:NextRequest){
 try{
  const actor=await requireCoach(request);if(!actor.personId)return NextResponse.json({error:'A canonical Coach identity is required.'},{status:409});const body=await request.json(),action=text(body.action,80),teamId=uuid(body.team_id);if(!teamId)return NextResponse.json({error:'Team is required.'},{status:400});const teams=await teamsFor(actor),team=teams.find(t=>t.id===teamId);if(!team||!canUse(actor,team))return NextResponse.json({error:'Coach is not authorized for this team.'},{status:403});
  if(action==='create-plan'){
   const name=text(body.name,180),starts=text(body.starts_on,10),ends=text(body.ends_on,10);if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(starts)||!/^\d{4}-\d{2}-\d{2}$/.test(ends)||ends<starts)return NextResponse.json({error:'Plan name and valid dates are required.'},{status:400});const row=(await rest<any[]>(actor,'training_plans',{method:'POST',body:JSON.stringify({team_id:team.id,season_id:uuid(body.season_id)||team.season_id||null,name,plan_type:text(body.plan_type,80)||'coach_program',starts_on:starts,ends_on:ends,status:'active',created_by:actor.personId})}))[0];await audit(actor,team,'COACH_TRAINING_PLAN_CREATED','training_plans',row.id,row);return NextResponse.json(row,{status:201});
  }
  if(action==='create-session'){
   const planId=uuid(body.training_plan_id),title=text(body.title,180);if(!planId||!title)return NextResponse.json({error:'Training plan and session title are required.'},{status:400});const plan=(await rest<any[]>(actor,`training_plans?select=id,team_id&id=eq.${planId}&team_id=eq.${team.id}&limit=1`))[0];if(!plan)return NextResponse.json({error:'Training plan is outside this Coach scope.'},{status:403});const row=(await rest<any[]>(actor,'training_sessions',{method:'POST',body:JSON.stringify({training_plan_id:planId,attendance_session_id:uuid(body.attendance_session_id),title,session_type:text(body.session_type,80)||'practice',total_load:numberOrNull(body.total_load),total_distance:numberOrNull(body.total_distance),distance_unit:text(body.distance_unit,24)||null,workout_definition:{objective:text(body.objective,2000)||null,coaching_cues:Array.isArray(body.coaching_cues)?body.coaching_cues:[],authored_by:'coach',approval_status:'official'}})}))[0];await audit(actor,team,'COACH_TRAINING_SESSION_CREATED','training_sessions',row.id,row);return NextResponse.json(row,{status:201});
  }
  if(action==='add-block'){
   const sessionId=uuid(body.training_session_id),title=text(body.title,180);if(!sessionId||!title)return NextResponse.json({error:'Session and block title are required.'},{status:400});const session=(await rest<any[]>(actor,`training_sessions?select=id,training_plan_id&id=eq.${sessionId}&limit=1`))[0],plan=session?(await rest<any[]>(actor,`training_plans?select=id,team_id&id=eq.${session.training_plan_id}&team_id=eq.${team.id}&limit=1`))[0]:null;if(!plan)return NextResponse.json({error:'Training session is outside this Coach scope.'},{status:403});const row=(await rest<any[]>(actor,'coach_session_blocks',{method:'POST',body:JSON.stringify({training_session_id:sessionId,parent_block_id:uuid(body.parent_block_id),block_type:text(body.block_type,80)||'set',title,objective:text(body.objective,2000)||null,duration_minutes:numberOrNull(body.duration_minutes),distance:numberOrNull(body.distance),distance_unit:text(body.distance_unit,24)||null,intensity:text(body.intensity,80)||null,interval_definition:body.interval_definition||{},equipment:Array.isArray(body.equipment)?body.equipment:[],drill_definition:body.drill_definition||{},sort_order:Number.isInteger(Number(body.sort_order))?Number(body.sort_order):0})}))[0];await audit(actor,team,'COACH_SESSION_BLOCK_ADDED','coach_session_blocks',row.id,row);return NextResponse.json(row,{status:201});
  }
  if(action==='add-athlete-modification'){
   const sessionId=uuid(body.training_session_id),athleteId=uuid(body.athlete_id),reason=text(body.reason,3000);if(!sessionId||!athleteId||!reason)return NextResponse.json({error:'Session, athlete and reason are required.'},{status:400});const session=(await rest<any[]>(actor,`training_sessions?select=id,training_plan_id&id=eq.${sessionId}&limit=1`))[0],plan=session?(await rest<any[]>(actor,`training_plans?select=id,team_id&id=eq.${session.training_plan_id}&team_id=eq.${team.id}&limit=1`))[0]:null;if(!plan)return NextResponse.json({error:'Training session is outside this Coach scope.'},{status:403});const member=(await rest<any[]>(actor,`team_memberships?select=id&team_id=eq.${team.id}&athlete_id=eq.${athleteId}&status=eq.active&limit=1`))[0];if(!member)return NextResponse.json({error:'Athlete is outside this team.'},{status:403});const visibility=text(body.visibility,32)||'coach_staff';if(!['private','coach_staff','athlete','parent'].includes(visibility))return NextResponse.json({error:'Invalid modification visibility.'},{status:400});const row=(await rest<any[]>(actor,'coach_athlete_session_modifications',{method:'POST',body:JSON.stringify({training_session_id:sessionId,athlete_id:athleteId,coach_person_id:actor.personId,modification_type:text(body.modification_type,80)||'individualization',reason,definition:body.definition||{},visibility,status:'active',updated_at:new Date().toISOString()})}))[0];await audit(actor,team,'COACH_ATHLETE_SESSION_MODIFICATION_ADDED','coach_athlete_session_modifications',row.id,{...row,reason:'[recorded]'});return NextResponse.json(row,{status:201});
  }
  return NextResponse.json({error:'Unsupported workout action.'},{status:400});
 }catch(e){const auth=authError(e);if(auth)return auth;return NextResponse.json({error:e instanceof Error?e.message:'Coach workout action failed.'},{status:500});}
}
