import {NextRequest,NextResponse} from 'next/server';
import {AthleteAuthError,requireAthlete} from '@/lib/server/requireAthlete';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const enc=(v:string)=>encodeURIComponent(v);
const headers=(prefer='return=representation')=>({apikey:KEY!,Authorization:`Bearer ${KEY!}`,'Content-Type':'application/json',Accept:'application/json',Prefer:prefer});
async function rest(path:string,init:RequestInit={}){if(!KEY)throw new Error('Supabase server credentials are not configured.');const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Athlete participation request returned ${r.status}: ${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function capabilityEvidence(eventType:string,athleteId:string,competitionId:string){for(const unitKey of ['athlete_goals_and_actions_writeback','athlete_progressive_experience','team_competition_engine_bridge']){try{const rows=await rest(`platform_milestone_units?unit_key=eq.${enc(unitKey)}&select=id,evidence`);const row=rows?.[0];if(!row?.id)continue;const evidence={...(row.evidence||{}),competitionParticipationEvidence:{lastObservedAt:new Date().toISOString(),lastEventType:eventType,athleteId,competitionId}};await rest(`platform_milestone_units?id=eq.${enc(row.id)}`,{method:'PATCH',body:JSON.stringify({evidence,evidence_source:'Runtime Athlete Competition Experience',evidence_ref:eventType,verified_at:new Date().toISOString()})})}catch(error){console.error(`Athlete participation evidence failed for ${unitKey}`,error)}}}

export async function GET(request:NextRequest){try{const actor=await requireAthlete(request);const requested=String(request.nextUrl.searchParams.get('athleteId')||'');const athleteId=actor.isSuperUser?requested:actor.athleteId||'';if(!athleteId)throw new AthleteAuthError('Athlete identity is required.',400);const rows=await rest(`competition_participation_responses?athlete_id=eq.${enc(athleteId)}&select=id,tenant_id,organization_id,competition_id,eligibility_decision_id,recipient_person_id,invitation_status,response_status,notified_at,responded_at,metadata,created_at,updated_at&order=created_at.desc`);const competitionIds=[...new Set((rows||[]).map((r:any)=>String(r.competition_id)).filter(Boolean))];const competitions=competitionIds.length?await rest(`competitions?id=in.(${competitionIds.join(',')})&select=id,name,starts_at,ends_at,city,region,status`):[];const map=new Map((competitions||[]).map((c:any)=>[String(c.id),c]));const responses=(rows||[]).map((r:any)=>({...r,competition:map.get(String(r.competition_id))??null,canRespond:actor.isSuperUser||actor.ageBand==='18+'||Boolean(actor.personId&&r.recipient_person_id===actor.personId),authorityReason:actor.isSuperUser?'superuser':actor.ageBand==='18+'?'adult-athlete':actor.personId&&r.recipient_person_id===actor.personId?'explicit-athlete-recipient':'guardian-or-organization-authority-required'}));return NextResponse.json({responses,generatedAt:new Date().toISOString(),source:'competition_participation_responses'});}catch(error){const status=error instanceof AthleteAuthError?error.status:500;return NextResponse.json({responses:[],error:error instanceof Error?error.message:'Unable to load participation requests'},{status})}}

export async function POST(request:NextRequest){try{const actor=await requireAthlete(request);const body=await request.json();const responseId=String(body.responseId||''),responseStatus=String(body.responseStatus||'');if(!responseId)throw new AthleteAuthError('Participation response is required.',400);if(!['going','not_going'].includes(responseStatus))throw new AthleteAuthError('Participation response must be going or not going.',400);const row=(await rest(`competition_participation_responses?id=eq.${enc(responseId)}&select=id,tenant_id,competition_id,athlete_id,recipient_person_id,response_status,metadata&limit=1`))?.[0];if(!row?.id)throw new AthleteAuthError('Participation request was not found.',404);if(!actor.isSuperUser&&actor.athleteId!==row.athlete_id)throw new AthleteAuthError('Athletes may only respond for their own Athlete record.',403);const canRespond=actor.isSuperUser||actor.ageBand==='18+'||Boolean(actor.personId&&row.recipient_person_id===actor.personId);if(!canRespond)throw new AthleteAuthError('This competition response requires guardian or organization authority.',403);const now=new Date().toISOString();const metadata={...(row.metadata||{}),lastResponseSource:'athlete_hub',lastResponseActorUserId:actor.userId,lastResponseActorPersonId:actor.personId};const saved=await rest(`competition_participation_responses?id=eq.${enc(responseId)}`,{method:'PATCH',body:JSON.stringify({response_status:responseStatus,responded_at:now,metadata})});await rest('platform_events',{method:'POST',body:JSON.stringify({tenant_id:row.tenant_id,event_type:'competition.athlete_participation_response',aggregate_type:'competition',aggregate_id:row.competition_id,payload:{athleteId:row.athlete_id,responseId,responseStatus,actorUserId:actor.userId,source:'athlete_hub'},processing_status:'pending'})});await capabilityEvidence('competition.athlete_participation_response',String(row.athlete_id),String(row.competition_id));return NextResponse.json({ok:true,row:saved?.[0]??saved,respondedAt:now})}catch(error){const status=error instanceof AthleteAuthError?error.status:500;return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Unable to save participation response'},{status})}}
