import { NextRequest, NextResponse } from 'next/server';
import { requireSuperUser, SuperUserAuthError } from '@/lib/server/requireSuperUser';
import { superUserRest } from '@/lib/server/superUserRest';
import { writeAuditEvent } from '@/lib/server/writeAuditEvent';

export const dynamic='force-dynamic';export const revalidate=0;
type Row=Record<string,unknown>;
function req(value:unknown,label:string,max=500){const s=String(value||'').trim();if(!s)throw new Error(`${label} is required.`);if(s.length>max)throw new Error(`${label} is too long.`);return s}
function opt(value:unknown,max=2000){const s=String(value||'').trim();if(!s)return null;if(s.length>max)throw new Error('Value is too long.');return s}
function json(value:unknown,label:string,fallback:unknown={}){if(value===undefined||value===null||value==='')return fallback;if(typeof value==='object')return value;try{return JSON.parse(String(value))}catch{throw new Error(`${label} must be valid JSON.`)}}
function safeFilter(value:unknown){const s=String(value||'').trim();return s.replace(/[(),]/g,'').slice(0,160)}

export async function GET(request:NextRequest){try{const actor=await requireSuperUser(request);const rest=(path:string,init:RequestInit={})=>superUserRest<any>(actor,path,init);const type=request.nextUrl.searchParams.get('type')||'audit';const limit=Math.max(1,Math.min(100,Number(request.nextUrl.searchParams.get('limit')||50)));if(type==='audit'){const action=safeFilter(request.nextUrl.searchParams.get('action')),entityType=safeFilter(request.nextUrl.searchParams.get('entity_type')),entityId=safeFilter(request.nextUrl.searchParams.get('entity_id')),actorId=safeFilter(request.nextUrl.searchParams.get('actor_user_id'));let path=`audit_events?select=*&order=occurred_at.desc&limit=${limit}`;if(action)path+=`&action=ilike.*${encodeURIComponent(action)}*`;if(entityType)path+=`&entity_type=ilike.*${encodeURIComponent(entityType)}*`;if(entityId)path+=`&entity_id=eq.${encodeURIComponent(entityId)}`;if(actorId)path+=`&actor_user_id=eq.${encodeURIComponent(actorId)}`;return NextResponse.json({type,rows:await rest(path)});}if(type==='security'){const eventType=safeFilter(request.nextUrl.searchParams.get('event_type')),severity=safeFilter(request.nextUrl.searchParams.get('severity'));let path=`security_events?select=*&order=occurred_at.desc&limit=${limit}`;if(eventType)path+=`&event_type=ilike.*${encodeURIComponent(eventType)}*`;if(severity)path+=`&severity=eq.${encodeURIComponent(severity)}`;return NextResponse.json({type,rows:await rest(path)});}if(type==='health'){const [metrics,snapshots,tickets]=await Promise.all([rest('platform_metrics?select=*&order=calculated_at.desc&limit=100'),rest('platform_metric_snapshots?select=*&order=observed_at.desc&limit=100'),rest('support_tickets?select=*&order=updated_at.desc&limit=100')]);return NextResponse.json({type,metrics,snapshots,tickets});}return NextResponse.json({error:'Unknown operations view.'},{status:400});}catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Unable to load operations data.'},{status:500})}}

export async function POST(request:NextRequest){try{const actor=await requireSuperUser(request);if(!actor.canManagePlatformSettings)throw new SuperUserAuthError('Platform-management permission required.',403);const rest=(path:string,init:RequestInit={})=>superUserRest<any>(actor,path,init);const one=async(table:string,id:string)=>(await rest(`${table}?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0]||null;const tenant=async()=>(await rest('tenants?select=id&limit=1'))?.[0]?.id||null;const body=await request.json() as Row;const action=String(body.action||'');const tenantId=await tenant();
if(action==='create-metric-snapshot'){const metric=await one('platform_metrics',req(body.metric_id,'Metric ID',80));if(!metric)return NextResponse.json({error:'Metric not found.'},{status:404});const item=(await rest('platform_metric_snapshots',{method:'POST',body:JSON.stringify({metric_id:metric.id,tenant_id:body.tenant_id||tenantId,observed_at:new Date().toISOString(),value_numeric:body.value_numeric===''||body.value_numeric===undefined?metric.metric_value:Number(body.value_numeric),value_text:body.value_text||metric.metric_text||null,value_json:json(body.value_json,'Metric JSON',metric.basis||{}),source_timestamp:body.source_timestamp||metric.calculated_at||null,calculation_version:opt(body.calculation_version,100)})}))?.[0];await writeAuditEvent(actor,{action:'PLATFORM_METRIC_SNAPSHOT_CREATED',entityType:'platform_metric_snapshots',entityId:item?.id||null,tenantId,afterData:item||body,reason:'Super User captured system-health evidence'});return NextResponse.json(item)}
if(action==='create-operations-ticket'){const max=await rest('support_tickets?select=ticket_number&order=ticket_number.desc&limit=1');const ticketNumber=Number(max?.[0]?.ticket_number||0)+1;const item=(await rest('support_tickets',{method:'POST',body:JSON.stringify({tenant_id:tenantId,ticket_number:ticketNumber,title:req(body.title,'Ticket title',300),description:opt(body.description,4000),category:req(body.category||'platform','Category',80),severity:req(body.severity||'normal','Severity',50),status:'open',requester_person_id:actor.personId,owner_person_id:body.owner_person_id||actor.personId||null,related_entity_type:opt(body.related_entity_type,100),related_entity_id:body.related_entity_id||null})}))?.[0];await writeAuditEvent(actor,{action:'OPERATIONS_TICKET_CREATED',entityType:'support_tickets',entityId:item?.id||null,tenantId,afterData:item||body,reason:'Super User created operations issue from control plane'});return NextResponse.json(item)}
if(action==='set-ticket-status'){const id=req(body.id,'Ticket ID',80),before=await one('support_tickets',id);if(!before)return NextResponse.json({error:'Ticket not found.'},{status:404});const status=req(body.status,'Ticket status',50).toLowerCase();const after=(await rest(`support_tickets?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status,owner_person_id:body.owner_person_id||before.owner_person_id||actor.personId||null,updated_at:new Date().toISOString(),resolved_at:['resolved','closed'].includes(status)?new Date().toISOString():null})}))?.[0];await writeAuditEvent(actor,{action:'OPERATIONS_TICKET_STATUS_CHANGED',entityType:'support_tickets',entityId:id,tenantId,beforeData:before,afterData:after,reason:'Super User changed operations issue lifecycle'});return NextResponse.json(after)}
return NextResponse.json({error:'Unsupported operations action.'},{status:400});}catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Operations action failed.'},{status:400})}}
