import { NextRequest, NextResponse } from 'next/server';
import { requireSuperUser, SuperUserAuthError } from '@/lib/server/requireSuperUser';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL;const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
export const dynamic='force-dynamic';export const revalidate=0;
const HUBS=['superuser','admin','athlete','parent','official','scout','coach'] as const;
function headers(){if(!KEY)throw new Error('Supabase service credentials are not configured.');return{apikey:KEY,Authorization:`Bearer ${KEY}`}}
async function rest(path:string){if(!URL||!KEY)throw new Error('Supabase service credentials are not configured.');const response=await fetch(`${URL}/rest/v1/${path}`,{headers:headers(),cache:'no-store'});const text=await response.text();if(!response.ok)throw new Error(`Supabase ${path} returned ${response.status}: ${text.slice(0,300)}`);return text?JSON.parse(text):[]}
export async function GET(request:NextRequest){try{await requireSuperUser(request);const result:Record<string,{allowed:boolean;units:number;reason:string}>={};for(const hub of HUBS){const rows=await rest(`platform_milestone_units?unit_key=like.${encodeURIComponent(`${hub}_%`)}&select=implementation_percent,operational_percent,validation_percent`);const units=Array.isArray(rows)?rows:[];const allowed=units.length>0&&units.every((row:{implementation_percent?:number|string;operational_percent?:number|string;validation_percent?:number|string})=>Number(row.implementation_percent)===100&&Number(row.operational_percent)===100&&Number(row.validation_percent)===100);result[hub]={allowed,units:units.length,reason:allowed?'Hub release is certified 100/100/100.':units.length?'Hub remains below release certification.':'Hub has no release-certification inventory.'};}return NextResponse.json({hubs:result},{headers:{'Cache-Control':'no-store'}})}catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Unable to determine hub access.'},{status:500})}}
