import {NextRequest,NextResponse} from 'next/server';
import {AthleteAuthError,requireAthlete} from '@/lib/server/requireAthlete';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
type Row=Record<string,any>;
const enc=(v:string)=>encodeURIComponent(v);const h=()=>({apikey:KEY!,Authorization:`Bearer ${KEY!}`,Accept:'application/json'});
async function rest(path:string){if(!KEY)throw new Error('Supabase server credentials are not configured.');const r=await fetch(`${URL}/rest/v1/${path}`,{headers:h(),cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(`Supabase standards query returned ${r.status}: ${text.slice(0,400)}`);return text?JSON.parse(text):[]}
export const dynamic='force-dynamic';export const revalidate=0;

export async function GET(request:NextRequest){try{const actor=await requireAthlete(request);let athleteId=actor.athleteId,personId=actor.personId;if(actor.isSuperUser){const age=request.nextUrl.searchParams.get('age')||'15-17';const rpc=await fetch(`${URL}/rest/v1/rpc/get_athlete_hub`,{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({p_age_band:age,p_athlete_number:null}),cache:'no-store'});const payload=await rpc.json();athleteId=payload?.athlete?.id??null;if(athleteId){const a=await rest(`athletes?id=eq.${enc(athleteId)}&select=person_id`);personId=a?.[0]?.person_id??null}}if(!athleteId||!personId)throw new AthleteAuthError('Athlete identity is unavailable.',403);const people=await rest(`people?id=eq.${enc(personId)}&select=birth_date,sex&limit=1`);const person=people?.[0];if(!person?.birth_date)return NextResponse.json({connected:false,reason:'birth_date_missing',standards:[]});const birth=new Date(person.birth_date),now=new Date();let age=now.getUTCFullYear()-birth.getUTCFullYear();const beforeBirthday=now.getUTCMonth()<birth.getUTCMonth()||(now.getUTCMonth()===birth.getUTCMonth()&&now.getUTCDate()<birth.getUTCDate());if(beforeBirthday)age--;const entries:Row[]=await rest(`competition_entries?athlete_id=eq.${enc(athleteId)}&select=competition_event_id`);const ids=[...new Set(entries.map(e=>String(e.competition_event_id)).filter(Boolean))];const events:Row[]=ids.length?await rest(`competition_events?id=in.(${ids.join(',')})&select=code,name,event_definition`):[];const codes=new Set(events.map(e=>String(e.code||'')).filter(Boolean));const rows:Row[]=await rest(`swim_time_standards?age_low=lte.${age}&age_high=gte.${age}&select=id,course_code,event_code,age_low,age_high,gender,standard_name,standard_time_ms,effective_from,effective_to`);const sex=String(person.sex||'').toLowerCase();const today=now.toISOString().slice(0,10);const standards=rows.filter(r=>codes.has(String(r.event_code||''))).filter(r=>{const g=String(r.gender||'').toLowerCase();return !g||g==='open'||g==='all'||!sex||g===sex}).filter(r=>!r.effective_from||String(r.effective_from)<=today).filter(r=>!r.effective_to||String(r.effective_to)>=today).map(r=>({id:r.id,eventCode:r.event_code,courseCode:r.course_code,name:r.standard_name,timeMs:r.standard_time_ms,ageLow:r.age_low,ageHigh:r.age_high,gender:r.gender,effectiveFrom:r.effective_from,effectiveTo:r.effective_to}));return NextResponse.json({connected:standards.length>0,reason:standards.length?'verified_standards_available':'no_verified_standards_loaded_for_athlete_events',standards,events:events.map(e=>({code:e.code,name:e.name})),generatedAt:new Date().toISOString(),source:'swim_time_standards'});}catch(error){const status=error instanceof AthleteAuthError?error.status:500;return NextResponse.json({connected:false,standards:[],error:error instanceof Error?error.message:'Standards unavailable'},{status})}}
