'use client';

import {FormEvent,useCallback,useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {BookOpen,CheckCircle2,Flag,MessageSquareHeart,Send,ShieldAlert} from 'lucide-react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
function label(value:unknown){const text=String(value||'');return text?text.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):'Not recorded'}
function date(value:unknown){if(!value)return'Date TBD';const d=new Date(String(value));return Number.isNaN(d.getTime())?'Date TBD':d.toLocaleDateString('en-CA',{weekday:'short',month:'short',day:'numeric',year:'numeric'})}

export default function AthleteCompletionActions({age}:{age:string}){
 const pathname=usePathname();
 const [athleteId,setAthleteId]=useState('');
 const [responses,setResponses]=useState<Row[]>([]);
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState('');
 const [reflectionTitle,setReflectionTitle]=useState('');
 const [reflectionBody,setReflectionBody]=useState('');
 const [feedback,setFeedback]=useState('');
 const [rating,setRating]=useState(5);
 const [category,setCategory]=useState('experience');
 const load=useCallback(async()=>{try{const hubResponse=await authenticatedFetch(`/api/athlete?age=${encodeURIComponent(age)}`,{cache:'no-store'});const hub=await hubResponse.json();const id=String(hub?.athlete?.id||'');setAthleteId(id);if(id&&pathname.includes('/competitions')){const r=await authenticatedFetch(`/api/athlete/participation?athleteId=${encodeURIComponent(id)}`,{cache:'no-store'});const j=await r.json();if(r.ok)setResponses(j.responses||[])}}catch{}},[age,pathname]);
 useEffect(()=>{void load()},[load]);

 const saveReflection=async(event:FormEvent)=>{event.preventDefault();if(!athleteId)return;setBusy(true);setMessage('');try{const r=await authenticatedFetch('/api/athlete/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create_reflection',athleteId,reflectionType:'training',title:reflectionTitle,body:reflectionBody,occurredOn:new Date().toISOString().slice(0,10)})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to save reflection');setReflectionTitle('');setReflectionBody('');setMessage('Reflection saved to your Athlete Logbook.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to save reflection')}finally{setBusy(false)}};
 const submitFeedback=async(event:FormEvent)=>{event.preventDefault();if(!athleteId)return;setBusy(true);setMessage('');try{const r=await authenticatedFetch('/api/athlete/engagement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submit_feedback',athleteId,category,message:feedback,rating,route:pathname})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to submit feedback');setFeedback('');setMessage('Thanks — your feedback is recorded in LS1.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to submit feedback')}finally{setBusy(false)}};
 const respond=async(responseId:string,responseStatus:'going'|'not_going')=>{setBusy(true);setMessage('');try{const r=await authenticatedFetch('/api/athlete/participation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({responseId,responseStatus})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to save competition response');setMessage(responseStatus==='going'?'Competition response saved: I’m going.':'Competition response saved: I’m not going.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Unable to save competition response')}finally{setBusy(false)}};

 if(pathname.includes('/logbook'))return <section className="rounded-[1.75rem] border border-violet-300/20 bg-violet-400/[.06] p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-violet-300/10 p-3 text-violet-100"><BookOpen className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-violet-100/60">Canonical Athlete Logbook</div><h3 className="mt-1 text-xl font-black text-white">Capture what you learned today.</h3><p className="mt-1 text-sm text-white/55">Training and race reflections are saved to your Athlete record. This is not a private diary.</p></div></div><form onSubmit={saveReflection} className="mt-5 grid gap-3"><input value={reflectionTitle} onChange={e=>setReflectionTitle(e.target.value)} required maxLength={120} placeholder="What was today about?" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none placeholder:text-white/30"/><textarea value={reflectionBody} onChange={e=>setReflectionBody(e.target.value)} maxLength={2000} rows={5} placeholder="What went well? What did you learn? What will you do next?" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none placeholder:text-white/30"/><button disabled={busy||!athleteId} className="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-black disabled:opacity-40"><Send className="h-4 w-4"/>{busy?'Saving…':'Save Reflection'}</button></form>{message&&<div className="mt-3 text-xs text-white/65">{message}</div>}</section>;

 if(pathname.includes('/feedback'))return <section className="rounded-[1.75rem] border border-cyan-300/20 bg-cyan-400/[.06] p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-cyan-300/10 p-3 text-cyan-100"><MessageSquareHeart className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-100/60">Help Build LS1</div><h3 className="mt-1 text-xl font-black text-white">Tell us what would make your Athlete Experience better.</h3><p className="mt-1 text-sm text-white/55">This submits real product feedback to the LS1 engineering evidence stream.</p></div></div><form onSubmit={submitFeedback} className="mt-5 grid gap-3"><div className="flex flex-wrap gap-2"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs font-black text-white"><option value="experience">Experience</option><option value="competition">Competition</option><option value="performance">Performance</option><option value="training">Training</option><option value="recruiting">Recruiting</option><option value="idea">New idea</option></select><select value={rating} onChange={e=>setRating(Number(e.target.value))} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs font-black text-white">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} required minLength={5} maxLength={2000} rows={6} placeholder="What should LS1 improve, add, or make easier?" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none placeholder:text-white/30"/><button disabled={busy||!athleteId} className="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-black disabled:opacity-40"><Send className="h-4 w-4"/>{busy?'Submitting…':'Send Feedback'}</button></form>{message&&<div className="mt-3 text-xs text-white/65">{message}</div>}</section>;

 if(pathname.includes('/competitions')&&responses.length)return <section className="rounded-[1.75rem] border border-orange-300/20 bg-orange-400/[.05] p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-orange-300/10 p-3 text-orange-100"><Flag className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-orange-100/60">Competition participation</div><h3 className="mt-1 text-xl font-black text-white">Your meet invitations and declarations.</h3><p className="mt-1 text-sm text-white/55">Competition Engine owns eligibility and the final competition record. Athlete can respond only where authority allows it.</p></div></div><div className="mt-5 grid gap-3">{responses.map(row=><div key={row.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-black text-white">{row.competition?.name||'Competition'}</div><div className="mt-1 text-xs text-white/45">{date(row.competition?.starts_at)} · Invitation: {label(row.invitation_status)} · Response: {label(row.response_status)}</div></div><div className="flex items-center gap-2">{row.canRespond?<><button type="button" disabled={busy} onClick={()=>void respond(String(row.id),'going')} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400/15 px-3 py-2 text-xs font-black text-emerald-100 disabled:opacity-40"><CheckCircle2 className="h-4 w-4"/>I’m Going</button><button type="button" disabled={busy} onClick={()=>void respond(String(row.id),'not_going')} className="rounded-xl border border-white/10 bg-white/[.05] px-3 py-2 text-xs font-black text-white/70 disabled:opacity-40">I’m Not Going</button></>:<span className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs font-black text-white/55"><ShieldAlert className="h-4 w-4"/>Guardian / organization authority</span>}</div></div></div>)}</div>{message&&<div className="mt-3 text-xs text-white/65">{message}</div>}</section>;
 return null;
}
