'use client';

import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,Award,CalendarDays,CheckCircle2,ChevronRight,FileText,Flag,RefreshCw,ShieldCheck,Sparkles,Star,Target,Trophy,Upload,Users,X}from'lucide-react';
import{useSearchParams}from'next/navigation';

type Row=Record<string,any>;
type Payload={athlete:Row|null;availableBands:Row[];sports:Row[];teams:Row[];results:Row[];goals:Row[];development:Row[];schedule:Row[];badges:Row[];challenges:Row[];recruiting:{cycles?:Row[];outreachCount?:number};documents:Row[];metrics:Record<string,number>;reconciliation:Record<string,number>;generatedAt:string;source:string;projection:string;error?:string};
type Stage={label:string;short:string;tone:string;intro:string};
const STAGES:Record<string,Stage>={
 '5-8':{label:'Ages 5–8',short:'Foundation',tone:'Play · learn · belong',intro:'Your sports world should feel fun, simple and exciting.'},
 '9-11':{label:'Ages 9–11',short:'Development',tone:'Explore · practice · improve',intro:'See what happened, what is next and how you are growing.'},
 '12-14':{label:'Ages 12–14',short:'Growth',tone:'Own · understand · progress',intro:'Results, goals, training and preparation become part of your own sports story.'},
 '15-17':{label:'Ages 15–17',short:'Performance',tone:'Prepare · perform · learn',intro:'Performance, rankings, standards, recruiting and planning come together in one athlete workspace.'},
 '18+':{label:'18+ / Advanced',short:'Advanced',tone:'Analyze · decide · lead',intro:'The full longitudinal Athlete Passport with performance, planning, documents and career context.'}
};

function time(v:any){const n=Number(v);if(!Number.isFinite(n))return'—';const m=Math.floor(n/60),s=n-m*60;return m?`${m}:${s.toFixed(2).padStart(5,'0')}`:s.toFixed(2)}
function Card({eyebrow,title,value,detail,icon:Icon=Star,onClick,accent=false,children}:{eyebrow:string;title:string;value?:React.ReactNode;detail?:string;icon?:React.ElementType;onClick:()=>void;accent?:boolean;children?:React.ReactNode}){return <button onClick={onClick} className={`group w-full rounded-2xl border p-5 text-left transition ${accent?'border-[#FA4616]/50 bg-[#FA4616]/8':'border-neutral-800 bg-[#090b0b] hover:border-neutral-600'}`}><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-[#FA4616]">{eyebrow}</div><h3 className="mt-1 text-lg font-black text-white">{title}</h3></div><Icon className={`h-5 w-5 ${accent?'text-[#FA4616]':'text-neutral-600 group-hover:text-[#FA4616]'}`}/></div>{value!==undefined&&<div className="mt-4 text-3xl font-black text-white">{value}</div>}{detail&&<div className="mt-2 text-xs leading-5 text-neutral-500">{detail}</div>}{children}<div className="mt-4 flex items-center gap-1 text-[10px] font-bold text-[#FA4616]">Open <ChevronRight className="h-3 w-3"/></div></button>}
function Empty({children}:{children:React.ReactNode}){return <div className="rounded-xl border border-dashed border-neutral-800 bg-black/20 p-5 text-xs leading-5 text-neutral-500">{children}</div>}
function CalendarStrip({entries,onOpen}:{entries:Row[];onOpen:(row:Row)=>void}){const start=new Date();start.setHours(0,0,0,0);return <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const hits=entries.filter(e=>{const raw=e.competition?.startsAt||e.startsAt||e.start;return raw&&new Date(raw).toDateString()===d.toDateString()});return <button key={d.toISOString()} onClick={()=>onOpen({kind:'calendar-day',date:d.toISOString(),entries:hits})} className="min-h-24 rounded-xl border border-neutral-800 bg-[#0d1010] p-3 text-left hover:border-neutral-600"><div className="text-[9px] font-black uppercase tracking-[.15em] text-neutral-600">{d.toLocaleDateString(undefined,{weekday:'short'})}</div><div className="mt-1 text-lg font-black text-white">{d.getDate()}</div><div className="mt-2 space-y-1">{hits.slice(0,2).map((e:any,n:number)=><div key={n} className="truncate rounded bg-[#FA4616]/10 px-2 py-1 text-[9px] font-bold text-[#FA4616]">{e.competition?.name||e.title||'Event'}</div>)}</div></button>})}</div>}

function GoalForm({initial,saving,onSave,onCancel}:{initial:Row;saving:boolean;onSave:(v:Row)=>void;onCancel:()=>void}){const[v,setV]=useState<Row>(initial);return <form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();onSave(v)}}><label className="block text-xs text-neutral-400">Goal title<input autoFocus value={v.title||''} onChange={e=>setV({...v,title:e.target.value})} className="mt-1 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label><label className="block text-xs text-neutral-400">Why this matters<textarea value={v.description||''} onChange={e=>setV({...v,description:e.target.value})} className="mt-1 min-h-28 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs text-neutral-400">Target<input value={v.targetValue??''} onChange={e=>setV({...v,targetValue:e.target.value})} className="mt-1 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label><label className="text-xs text-neutral-400">Unit<input value={v.targetUnit||''} onChange={e=>setV({...v,targetUnit:e.target.value})} className="mt-1 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label></div><label className="block text-xs text-neutral-400">Due date<input type="date" value={v.dueOn||''} onChange={e=>setV({...v,dueOn:e.target.value})} className="mt-1 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label><div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg border border-neutral-700 px-4 py-2 text-sm text-white">Cancel</button><button disabled={saving} className="rounded-lg bg-[#FA4616] px-4 py-2 text-sm font-black text-black">{saving?'Saving…':'Save Goal'}</button></div></form>}
function DocumentUpload({athleteId,saving,setSaving,onDone,onError}:{athleteId:string;saving:boolean;setSaving:(v:boolean)=>void;onDone:()=>void;onError:(s:string)=>void}){const[file,setFile]=useState<File|null>(null);const[title,setTitle]=useState('');return <form className="mt-6 space-y-4" onSubmit={async e=>{e.preventDefault();if(!file){onError('Choose a file.');return}setSaving(true);try{const fd=new FormData();fd.set('athleteId',athleteId);fd.set('title',title||file.name);fd.set('file',file);fd.set('classification','restricted');const r=await fetch('/api/documents',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Upload failed');onDone()}catch(e){onError(e instanceof Error?e.message:'Upload failed')}finally{setSaving(false)}}}><label className="block text-xs text-neutral-400">Document title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-700 bg-black p-3 text-white"/></label><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full text-sm text-neutral-300"/><button disabled={saving} className="w-full rounded-lg bg-[#FA4616] px-4 py-3 text-sm font-black text-black">{saving?'Uploading…':'Upload & Save'}</button></form>}

export default function AthleteWorkspace(){
 const params=useSearchParams();const ageBand=STAGES[params.get('age')||'5-8']?params.get('age')||'5-8':'5-8';const stage=STAGES[ageBand];
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState<Row|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/athlete?age=${encodeURIComponent(ageBand)}`,{cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Athlete data unavailable');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Athlete data unavailable')}finally{setLoading(false)}},[ageBand]);
 useEffect(()=>{void load()},[load]);
 const athlete=data?.athlete,metrics=data?.metrics||{},results=data?.results||[],goals=data?.goals||[],schedule=data?.schedule||[],badges=data?.badges||[],challenges=data?.challenges||[];
 const latest=results[0];const records=useMemo(()=>{const m=new Map<string,Row>();for(const r of results){const k=String(r.event?.code||r.event?.name||r.id),n=Number(r.resultValue),old=m.get(k);if(Number.isFinite(n)&&(!old||n<Number(old.resultValue)))m.set(k,r)}return[...m.values()]},[results]);const activeGoal=goals.find(g=>String(g.status).toLowerCase()!=='completed')||goals[0];const next=schedule[0];
 async function saveGoal(v:Row){if(!athlete?.id)return;setSaving(true);try{const r=await fetch('/api/athlete/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:v.id?'update_goal':'create_goal',athleteId:athlete.id,goalId:v.id,title:v.title,description:v.description,goalType:v.goalType||v.type||'development',targetValue:v.targetValue,targetUnit:v.targetUnit,dueOn:v.dueOn,status:v.status||'open'})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to save goal');setDrawer(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save goal')}finally{setSaving(false)}}
 async function advanceChallenge(ch:Row){if(!athlete?.id)return;setSaving(true);try{const progress=Number(ch.progress||0)+1;const r=await fetch('/api/athlete/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_challenge',athleteId:athlete.id,challengeId:ch.id,progressValue:progress,status:'active'})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to save mission progress');setDrawer(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save mission')}finally{setSaving(false)}}
 const open=(kind:string,payload:Row={})=>setDrawer({kind,...payload});
 if(!data&&loading)return <main className="p-8 text-neutral-500">Loading Athlete World…</main>;
 if(!data)return <main className="p-8 text-red-300">{error||'Athlete data unavailable'}</main>;
 const young=ageBand==='5-8',developing=ageBand==='9-11',growth=ageBand==='12-14',performance=ageBand==='15-17'||ageBand==='18+';
 return <main className="mx-auto max-w-[1600px] space-y-6 p-5 lg:p-8">
  <section className={`overflow-hidden rounded-3xl border p-6 lg:p-8 ${young?'border-[#FA4616]/40 bg-gradient-to-br from-[#FA4616]/15 via-[#090b0b] to-[#090b0b]':'border-neutral-800 bg-[#090b0b]'}`}><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.25em] text-[#FA4616]">{young?'MY LS1 ADVENTURE':'ATHLETE WORLD'} · {stage.label}</div><h1 className="mt-2 text-3xl font-black text-white lg:text-4xl">{young?'Ready for your next adventure?':`Welcome back, ${athlete?.name||'Athlete'}`}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-neutral-400">{stage.intro}</p></div><button onClick={()=>void load()} className="self-start rounded-xl border border-neutral-700 bg-black/30 p-3 text-neutral-400"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/></button></div></section>

  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-200">{error}</div>}

  {young&&<>
   <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card eyebrow="My mission" title={challenges[0]?.name||'Try something brave today'} detail={challenges[0]?.description||'Your coach and LS1 will give you simple missions to explore.'} icon={Target} accent onClick={()=>open('challenge',challenges[0]||{})}><div className="mt-4 h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full bg-[#FA4616]" style={{width:`${Math.min(100,Number(challenges[0]?.progress||0)*20)}%`}}/></div></Card><Card eyebrow="What’s next" title={next?.competition?.name||'Your next swim adventure'} detail={next?`${next.event?.name||next.event?.code||'Event'} · ${new Date(next.competition?.startsAt).toLocaleString()}`:'Your schedule will appear here as soon as it is assigned.'} icon={CalendarDays} onClick={()=>open('schedule',{items:schedule})}/></div>
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card eyebrow="My wins" title={badges[0]?.name||'Your wins live here'} detail={badges[0]?'Earned from real evidence.':'Effort, courage, teamwork and improvement all count as wins.'} icon={Award} onClick={()=>open('badges',{items:badges})}/><Card eyebrow="My goal" title={activeGoal?.title||'Choose my next mission'} detail={activeGoal?.description||'Create a simple goal with help from your parent or coach.'} icon={Star} onClick={()=>open('goal-editor',activeGoal||{})}/><Card eyebrow="My team" title={data.teams[0]?.name||'My Team'} detail={data.teams[0]?.organization||'Your people and team belong here.'} icon={Users} onClick={()=>open('team',data.teams[0]||{})}/><Card eyebrow="My latest swim" title={latest?String(latest.event?.name||latest.event?.code||'Latest result'):'When I race'} value={latest?time(latest.resultValue):'—'} detail={latest?'A real recorded swim — tap to see what happened.':'Results appear here when you compete. No fake times.'} icon={Trophy} onClick={()=>open('result',latest||{})}/></div>
   <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-[#FA4616]"/><h2 className="text-lg font-black text-white">My Adventure Trail</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(challenges.length?challenges:[{name:'First Practice'},{name:'Try a New Skill'},{name:'Help a Teammate'},{name:'My First Race'}]).slice(0,4).map((c:any,i:number)=><button key={c.id||i} onClick={()=>open('challenge',c)} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-left"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#FA4616]/10 text-[#FA4616]"><Star className="h-4 w-4"/></div><div className="mt-3 font-bold text-white">{c.name}</div><div className="mt-1 text-xs text-neutral-500">{Number(c.progress||0)>0?'Adventure in progress':'Ready when you are'}</div></button>)}</div></section>
  </>}

  {!young&&<>
   <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card eyebrow="Front page news" title={latest?String(latest.event?.name||latest.event?.code||'Latest result'):'Latest result'} value={latest?time(latest.resultValue):'—'} detail={latest?`${latest.competition||'Competition'}${latest.rank?` · placed #${latest.rank}`:''}`:'No canonical result is connected yet.'} icon={Trophy} accent onClick={()=>open('result',latest||{})}/><Card eyebrow="Personal best" title={records[0]?String(records[0].event?.name||records[0].event?.code||'Best event'):'Personal records'} value={records[0]?time(records[0].resultValue):'—'} detail={records.length?`${records.length} event bests from canonical results`:'PBs will calculate automatically from verified results.'} icon={Award} onClick={()=>open('records',{items:records})}/><Card eyebrow="My goal" title={activeGoal?.title||'Set my next goal'} detail={activeGoal?.description||'Create and update your own development goal.'} icon={Target} onClick={()=>open('goal-editor',activeGoal||{})}/><Card eyebrow="Up next" title={next?.competition?.name||'Schedule'} detail={next?new Date(next.competition?.startsAt).toLocaleString():'No athlete-specific upcoming event is connected yet.'} icon={CalendarDays} onClick={()=>open('schedule',{items:schedule})}/></div>
   <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-[#FA4616]">My calendar</div><h2 className="mt-1 text-lg font-black text-white">The week ahead</h2></div><CalendarDays className="h-5 w-5 text-neutral-600"/></div><div className="mt-5"><CalendarStrip entries={schedule} onOpen={setDrawer}/></div></section>
   <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card eyebrow="How I’m progressing" title="Performance & development" value={`${metrics.officialResults||0} results`} detail={`${metrics.trainingSessions||0} training records · ${metrics.assessments||0} assessments`} icon={Activity} onClick={()=>open('performance',{results,development:data.development,metrics})}/><Card eyebrow="Achievements" title={badges[0]?.name||'Milestones & badges'} value={badges.length||0} detail="Achievements only appear when supported by recorded evidence." icon={Sparkles} onClick={()=>open('badges',{items:badges})}/><Card eyebrow="My team" title={data.teams[0]?.name||'Current team'} detail={data.teams[0]?.organization||'No active team context'} icon={Users} onClick={()=>open('team',data.teams[0]||{})}/></div>
  </>}

  {(growth||performance)&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card eyebrow="Standards" title="Qualification status" value="—" detail="Time-standard data exists in LS1; athlete comparison remains unverified until event/course matching is completed." icon={Flag} onClick={()=>open('standards',{status:'not-yet-verified'})}/><Card eyebrow="Rankings" title="Where do I stand?" value={latest?.rank?`#${latest.rank}`:'—'} detail={latest?.rank?'This is latest recorded competition placing, not a regional ranking.':'Ranking engine data is not connected yet; LS1 will not invent it.'} icon={Trophy} onClick={()=>open('rankings',{latest})}/><Card eyebrow="Training" title="My training evidence" value={metrics.trainingSessions||0} detail={`${metrics.attendanceRecords||0} attendance records`} icon={Activity} onClick={()=>open('training',{metrics})}/><Card eyebrow="Documents" title="My Vault" value={data.documents.length} detail="Private, versioned athlete documents." icon={ShieldCheck} onClick={()=>open('documents',{items:data.documents})}/></div>}

  {performance&&<div className="grid gap-4 md:grid-cols-2"><Card eyebrow="Recruiting" title={data.recruiting?.cycles?.[0]?.name||'Recruiting Passport'} detail={`${data.recruiting?.outreachCount||0} recorded outreach actions · verified evidence only`} icon={Flag} onClick={()=>open('recruiting',{...data.recruiting})}/><Card eyebrow="Athlete Passport" title="My complete record" detail="Identity, teams, sports, results, goals, development, documents and history stay attached to one athlete asset." icon={ShieldCheck} onClick={()=>open('passport',{athlete,sports:data.sports,teams:data.teams})}/></div>}

  {drawer&&<div className="fixed inset-0 z-50 bg-black/75" onClick={()=>setDrawer(null)}><aside className="absolute right-0 top-0 h-full w-full max-w-xl overflow-y-auto border-l border-neutral-800 bg-[#080909] p-6" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-[#FA4616]">Athlete action drawer</div><h2 className="mt-2 text-xl font-black capitalize text-white">{String(drawer.kind||'Details').replaceAll('-',' ')}</h2></div><button onClick={()=>setDrawer(null)} className="rounded-lg border border-neutral-800 p-2"><X className="h-4 w-4 text-neutral-400"/></button></div>
   {drawer.kind==='goal-editor'?<GoalForm initial={drawer} saving={saving} onSave={saveGoal} onCancel={()=>setDrawer(null)}/>:drawer.kind==='challenge'?<div className="mt-6"><div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-5"><div className="text-lg font-black text-white">{drawer.name||'My Mission'}</div><p className="mt-2 text-sm text-neutral-500">{drawer.description||'Take one small step and save your progress.'}</p><div className="mt-4 text-sm font-bold text-white">Progress: {Number(drawer.progress||0)}</div></div>{drawer.id&&<button disabled={saving} onClick={()=>void advanceChallenge(drawer)} className="mt-4 w-full rounded-lg bg-[#FA4616] px-4 py-3 text-sm font-black text-black">{saving?'Saving…':'I made progress +1'}</button>}</div>:drawer.kind==='documents'?<div className="mt-6 space-y-3">{drawer.items?.length?drawer.items.map((d:Row)=><div key={d.id} className="rounded-xl border border-neutral-800 p-4"><div className="font-bold text-white">{d.title}</div><div className="mt-1 text-xs text-neutral-500">{d.verificationStatus||'unverified'} · {d.classification||'restricted'}</div></div>):<Empty>No documents yet.</Empty>}<button onClick={()=>setDrawer({kind:'document-upload'})} className="w-full rounded-lg bg-[#FA4616] px-4 py-3 text-sm font-black text-black">Upload Document</button></div>:drawer.kind==='document-upload'?<DocumentUpload athleteId={String(athlete?.id||'')} saving={saving} setSaving={setSaving} onDone={async()=>{setDrawer(null);await load()}} onError={setError}/>:<div className="mt-6 space-y-3">{drawer.items&&Array.isArray(drawer.items)?drawer.items.map((item:Row,i:number)=><button key={item.id||i} className="w-full rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-left"><div className="font-bold text-white">{item.title||item.name||item.event?.name||item.competition?.name||`Record ${i+1}`}</div><div className="mt-1 text-xs text-neutral-500">{item.description||item.status||item.entryStatus||item.verificationStatus||''}</div></button>):<pre className="whitespace-pre-wrap rounded-xl border border-neutral-800 bg-black p-4 text-xs leading-5 text-neutral-400">{JSON.stringify(Object.fromEntries(Object.entries(drawer).filter(([k])=>k!=='kind')),null,2)}</pre>}</div>}
  </aside></div>}
 </main>;
}
