'use client';

import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState,type ElementType,type ReactNode} from 'react';
import {usePathname,useSearchParams} from 'next/navigation';
import {
 Activity,Award,BarChart3,BookOpen,CalendarDays,CheckCircle2,ChevronRight,ClipboardCheck,
 FileText,Flag,Gauge,HeartPulse,Medal,MessageCircle,NotebookPen,RefreshCw,Settings,
 ShieldCheck,Sparkles,Star,Target,Trophy,TrendingUp,UserCheck,Users,Waves,X,Zap
} from 'lucide-react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={athlete:Row|null;sports?:Row[];teams?:Row[];results?:Row[];goals?:Row[];development?:Row[];schedule?:Row[];badges?:Row[];challenges?:Row[];recruiting?:{cycles?:Row[];outreachCount?:number};documents?:Row[];metrics?:Record<string,number>;error?:string};
type Age='9-11'|'12-14'|'15-17'|'18+';
type Stage={name:string;age:string;tag:string;headline:string;subline:string;hero:string;accent:string;soft:string;ring:string;emoji:string};

const STAGES:Record<Age,Stage>={
 '9-11':{name:'Development',age:'9–11',tag:'Explore · practice · improve',headline:'Level up your sport.',subline:'Build skills, collect wins, chase PBs and see what is coming next.',hero:'from-cyan-400/35 via-blue-500/25 to-violet-600/25',accent:'text-cyan-200',soft:'bg-cyan-400/12',ring:'border-cyan-300/30',emoji:'⚡'},
 '12-14':{name:'Growth',age:'12–14',tag:'Own · understand · progress',headline:'Build your athlete identity.',subline:'Own your PBs, goals, meet choices and the story of how you are improving.',hero:'from-violet-500/40 via-fuchsia-500/25 to-pink-500/20',accent:'text-violet-200',soft:'bg-violet-400/12',ring:'border-violet-300/30',emoji:'🚀'},
 '15-17':{name:'Performance',age:'15–17',tag:'Prepare · perform · be seen',headline:'Turn performance into opportunity.',subline:'Qualify, compete, understand your performance and keep recruiting visible.',hero:'from-orange-500/40 via-rose-500/30 to-fuchsia-500/20',accent:'text-orange-200',soft:'bg-orange-400/12',ring:'border-orange-300/30',emoji:'🔥'},
 '18+':{name:'Advanced',age:'18+',tag:'Analyze · optimize · lead',headline:'Run your performance career.',subline:'Manage the season, competition strategy, performance evidence and your Athlete Passport.',hero:'from-emerald-500/35 via-teal-500/25 to-cyan-500/20',accent:'text-emerald-200',soft:'bg-emerald-400/12',ring:'border-emerald-300/30',emoji:'🏁'},
};

const NAV=[
 ['overview','Home',Sparkles],['calendar','Calendar',CalendarDays],['competitions','Meets & Entries',Flag],['performance','PBs & Performance',TrendingUp],
 ['goals','Goals',Target],['logbook','Logbook',NotebookPen],['achievements','Achievements',Award],['documents','Documents',FileText],['recruiting','Recruiting',UserCheck],
] as const;

const TONES=[
 'from-cyan-500/25 via-blue-500/10 to-transparent border-cyan-300/20',
 'from-violet-500/25 via-fuchsia-500/10 to-transparent border-violet-300/20',
 'from-orange-500/25 via-rose-500/10 to-transparent border-orange-300/20',
 'from-emerald-500/25 via-teal-500/10 to-transparent border-emerald-300/20',
 'from-pink-500/25 via-purple-500/10 to-transparent border-pink-300/20',
];

function swimTime(v:unknown){const n=Number(v);if(!Number.isFinite(n))return'—';const m=Math.floor(n/60),s=n-m*60;return m?`${m}:${s.toFixed(2).padStart(5,'0')}`:s.toFixed(2)}
function dateLabel(v:unknown,short=false){if(!v)return'Date TBD';const d=new Date(String(v));if(Number.isNaN(d.getTime()))return'Date TBD';return d.toLocaleDateString('en-CA',short?{month:'short',day:'numeric'}:{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function clamp(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0}
function titleCase(v:string){return v.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}

function ColorCard({icon:Icon,eyebrow,title,value,detail,tone=TONES[0],onClick,children}:{icon:ElementType;eyebrow:string;title:string;value?:ReactNode;detail?:string;tone?:string;onClick?:()=>void;children?:ReactNode}){
 const inner=<><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/50">{eyebrow}</div><div className="mt-1 text-lg font-black text-white">{title}</div></div><div className="rounded-2xl border border-white/10 bg-white/10 p-3 text-white shadow-lg"><Icon className="h-5 w-5"/></div></div>{value!==undefined&&<div className="mt-5 text-3xl font-black tracking-tight text-white">{value}</div>}{detail&&<div className="mt-2 text-sm leading-6 text-white/60">{detail}</div>}{children}{onClick&&<div className="mt-5 flex items-center gap-1 text-xs font-black text-white/80">Open <ChevronRight className="h-3.5 w-3.5"/></div>}</>;
 const cls=`rounded-[1.75rem] border bg-gradient-to-br p-5 text-left shadow-[0_24px_70px_rgba(0,0,0,.20)] transition ${tone} ${onClick?'hover:-translate-y-1 hover:scale-[1.01] hover:border-white/35':''}`;
 return onClick?<button type="button" onClick={onClick} className={`w-full ${cls}`}>{inner}</button>:<section className={cls}>{inner}</section>
}

function Empty({title,detail}:{title:string;detail:string}){return <div className="rounded-[1.5rem] border border-dashed border-white/15 bg-white/[.025] p-7 text-center"><div className="font-black text-white">{title}</div><div className="mt-2 text-sm leading-6 text-white/45">{detail}</div></div>}

export default function AthleteCapitalHub(){
 const pathname=usePathname();const params=useSearchParams();const requested=params.get('age')||'9-11';const age=(requested in STAGES?requested:'9-11') as Age;const stage=STAGES[age];const view=pathname.split('/').filter(Boolean)[1]||'overview';
 const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[drawer,setDrawer]=useState<Row|null>(null);const[sport,setSport]=useState('');const[logbookEnabled,setLogbookEnabled]=useState(true);const[diaryEnabled,setDiaryEnabled]=useState(false);const[entrySelections,setEntrySelections]=useState<Set<string>>(new Set());const[theme,setTheme]=useState('electric');
 const load=useCallback(async()=>{setLoading(true);try{const r=await authenticatedFetch(`/api/athlete?age=${encodeURIComponent(age)}`,{cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Athlete data unavailable');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Athlete data unavailable')}finally{setLoading(false)}},[age]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{try{const l=localStorage.getItem('ls1-athlete-logbook'),d=localStorage.getItem('ls1-athlete-diary'),t=localStorage.getItem('ls1-athlete-theme');if(l!==null)setLogbookEnabled(l==='true');if(d!==null)setDiaryEnabled(d==='true');if(t)setTheme(t)}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('ls1-athlete-logbook',String(logbookEnabled));localStorage.setItem('ls1-athlete-diary',String(diaryEnabled));localStorage.setItem('ls1-athlete-theme',theme)}catch{}},[logbookEnabled,diaryEnabled,theme]);
 const results=data?.results||[],schedule=data?.schedule||[],goals=data?.goals||[],badges=data?.badges||[],challenges=data?.challenges||[],sports=data?.sports||[],teams=data?.teams||[],documents=data?.documents||[],metrics=data?.metrics||{};
 const pbs=useMemo(()=>{const map=new Map<string,Row>();for(const r of results){const key=String(r.event?.code||r.event?.name||r.id);const n=Number(r.resultValue),old=map.get(key);if(Number.isFinite(n)&&(!old||n<Number(old.resultValue)))map.set(key,r)}return[...map.values()]},[results]);
 const recentByEvent=useMemo(()=>{const map=new Map<string,Row[]>();for(const r of results){const key=String(r.event?.code||r.event?.name||'event');const list=map.get(key)||[];list.push(r);map.set(key,list)}return map},[results]);
 useEffect(()=>{if(!sport&&sports.length)setSport(String(sports[0].id||sports[0].code||sports[0].name||'sport'))},[sport,sports]);
 if(!data&&loading)return <main className="min-h-[60vh] p-8 text-white/55">Loading Athlete World…</main>;
 if(!data)return <main className="p-8 text-red-300">{error||'Athlete data unavailable'}</main>;
 const snapshot=data;const athlete=snapshot.athlete||{};const latest=results[0];const next=schedule[0];const activeGoal=goals.find(g=>String(g.status||'').toLowerCase()!=='completed')||goals[0];const recruiting=snapshot.recruiting||{};const open=(kind:string,payload:Row={})=>setDrawer({kind,...payload});
 const ageQuery=`?age=${encodeURIComponent(age)}`;
 const visibleNav=NAV.filter(([key])=>!(key==='recruiting'&&age==='9-11'));
 const toggleEntry=(id:string)=>setEntrySelections(current=>{const nextSet=new Set(current);nextSet.has(id)?nextSet.delete(id):nextSet.add(id);return nextSet});

 const coachBanner=<button type="button" onClick={()=>open('coach-message')} className="group w-full overflow-hidden rounded-[1.8rem] border border-sky-300/25 bg-[linear-gradient(110deg,rgba(14,165,233,.28),rgba(99,102,241,.24),rgba(217,70,239,.20))] p-5 text-left shadow-[0_25px_80px_rgba(30,64,175,.16)] transition hover:border-sky-200/45"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-sky-300/15 text-sky-100"><MessageCircle className="h-7 w-7"/></div><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase tracking-[.18em] text-sky-100">Coach connection</div><div className="mt-1 text-lg font-black text-white">No direct coach message is connected yet.</div><div className="mt-1 text-xs leading-5 text-white/60">When coach-to-athlete communication is connected, the newest message will take priority here.</div></div><ChevronRight className="h-5 w-5 text-white/40 transition group-hover:translate-x-1"/></div></button>;

 function Overview(){
  if(age==='9-11')return <div className="space-y-5">{coachBanner}<div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><ColorCard icon={Zap} eyebrow="Level-up mission" title={challenges[0]?.name||'Your next challenge'} detail={challenges[0]?.description||'No coach challenge is connected yet.'} tone={TONES[0]} onClick={()=>open('challenge',challenges[0]||{})}><div className="mt-5 flex gap-2">{[1,2,3,4,5].map((n)=><Star key={n} className={`h-6 w-6 ${n<=Math.min(5,Math.ceil(clamp(challenges[0]?.progress)*5/100))?'fill-yellow-300 text-yellow-300':'text-white/15'}`}/>)}</div></ColorCard><ColorCard icon={CalendarDays} eyebrow="Next adventure" title={next?.competition?.name||'No meet scheduled'} detail={next?`${next.event?.name||next.event?.code||'Event'} · ${dateLabel(next.competition?.startsAt)}`:'Your next meet will show here when connected.'} tone={TONES[1]} onClick={()=>open('schedule',{items:schedule})}/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ColorCard icon={Medal} eyebrow="Wins" title="My collection" value={badges.length} detail="Real achievements recorded in LS1." tone={TONES[2]} onClick={()=>open('badges',{items:badges})}/><ColorCard icon={Trophy} eyebrow="PB hunt" title={pbs[0]?.event?.name||'Personal bests'} value={pbs[0]?swimTime(pbs[0].resultValue):'—'} detail={`${pbs.length} event bests`} tone={TONES[0]} onClick={()=>open('pbs',{items:pbs})}/><ColorCard icon={Target} eyebrow="My goal" title={activeGoal?.title||'No goal yet'} detail={activeGoal?.description||'A goal can be connected here.'} tone={TONES[3]} onClick={()=>open('goal',activeGoal||{})}/><ColorCard icon={Users} eyebrow="My team" title={teams[0]?.name||'Team'} detail={teams[0]?.organization||'No active team connected'} tone={TONES[4]} onClick={()=>open('team',teams[0]||{})}/></div></div>;
  if(age==='12-14')return <div className="space-y-5">{coachBanner}<div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><ColorCard icon={TrendingUp} eyebrow="My performance story" title={pbs[0]?.event?.name||'Build your PB board'} value={pbs[0]?swimTime(pbs[0].resultValue):'—'} detail={`${results.length} recorded swims · ${pbs.length} event bests`} tone={TONES[1]} onClick={()=>open('performance',{items:results})}><div className="mt-5 flex h-20 items-end gap-2">{results.slice(0,8).reverse().map((r,i)=>{const n=Number(r.resultValue);const base=Number(pbs[0]?.resultValue)||n||1;const h=Number.isFinite(n)?Math.max(20,Math.min(100,(base/n)*75)):20;return <div key={r.id||i} className="flex-1 rounded-t-xl bg-gradient-to-t from-violet-500 to-fuchsia-300/80" style={{height:`${h}%`}}/>})}</div></ColorCard><ColorCard icon={Flag} eyebrow="Qualification chase" title="Standards & targets" value="—" detail="Verified standards are not connected yet. LS1 will not invent a qualifying gap." tone={TONES[2]} onClick={()=>open('standards')}/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ColorCard icon={ClipboardCheck} eyebrow="Meet ownership" title={`${schedule.length} upcoming`} detail="Explore your entries and choose what you want to discuss with your coach." tone={TONES[0]} onClick={()=>open('entry-planner',{items:schedule})}/><ColorCard icon={Target} eyebrow="Goal ownership" title={activeGoal?.title||'No active goal'} detail={activeGoal?.description||'Own the next target.'} tone={TONES[3]} onClick={()=>open('goal',activeGoal||{})}/><ColorCard icon={NotebookPen} eyebrow="My logbook" title={logbookEnabled?'Logbook on':'Logbook off'} detail="Training and race reflections." tone={TONES[1]} onClick={()=>setLogbookEnabled(v=>!v)}/><ColorCard icon={Award} eyebrow="Progress markers" title={`${badges.length} achievements`} detail="Evidence-backed wins, milestones and badges." tone={TONES[4]} onClick={()=>open('badges',{items:badges})}/></div></div>;
  if(age==='15-17')return <div className="space-y-5">{coachBanner}<div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><ColorCard icon={Gauge} eyebrow="Performance cockpit" title={pbs[0]?.event?.name||'Performance board'} value={pbs[0]?swimTime(pbs[0].resultValue):'—'} detail={`${results.length} verified result records · ${pbs.length} PB events`} tone={TONES[2]} onClick={()=>open('performance',{items:results})}/><ColorCard icon={UserCheck} eyebrow="Recruitment" title={recruiting.cycles?.[0]?.name||'Recruiting Passport'} value={`${recruiting.outreachCount||0} outreach`} detail="Recruitment is deliberately visible on your Overview at this stage." tone={TONES[4]} onClick={()=>open('recruiting',{...recruiting})}/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ColorCard icon={Flag} eyebrow="Qualification" title="Standards & eligibility" value="—" detail="Eligibility and standard matching will surface here when verified." tone={TONES[0]} onClick={()=>open('standards')}/><ColorCard icon={Trophy} eyebrow="Rankings" title="Where I stand" value={latest?.rank?`#${latest.rank}`:'—'} detail={latest?.rank?'Latest recorded placing; not presented as a governing-body ranking.':'Ranking feed not connected yet.'} tone={TONES[1]} onClick={()=>open('rankings')}/><ColorCard icon={CalendarDays} eyebrow="Race planning" title={next?.competition?.name||'No meet'} detail={next?dateLabel(next.competition?.startsAt):'Nothing scheduled'} tone={TONES[2]} onClick={()=>open('entry-planner',{items:schedule})}/><ColorCard icon={Activity} eyebrow="Training evidence" title={`${metrics.trainingSessions||0} sessions`} detail={`${metrics.attendanceRecords||0} attendance records`} tone={TONES[3]} onClick={()=>open('training',{metrics})}/></div></div>;
  return <div className="space-y-5">{coachBanner}<div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><ColorCard icon={BarChart3} eyebrow="Season performance" title="Performance trajectory" value={pbs[0]?swimTime(pbs[0].resultValue):'—'} detail={`${pbs.length} PB events · ${results.length} recorded results`} tone={TONES[3]} onClick={()=>open('performance',{items:results})}/><ColorCard icon={ShieldCheck} eyebrow="Capital asset" title="My Athlete Passport" value={`${teams.length} team${teams.length===1?'':'s'}`} detail="One canonical athlete identity across sport, team, performance and career." tone={TONES[0]} onClick={()=>open('passport',{athlete,sports,teams})}/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ColorCard icon={Flag} eyebrow="Competition strategy" title={next?.competition?.name||'Season calendar'} detail={next?dateLabel(next.competition?.startsAt):'No upcoming meet'} tone={TONES[1]} onClick={()=>open('entry-planner',{items:schedule})}/><ColorCard icon={Gauge} eyebrow="Optimization" title="Standards & targets" value="—" detail="Verified comparison not connected yet." tone={TONES[2]} onClick={()=>open('standards')}/><ColorCard icon={Activity} eyebrow="Training system" title={`${metrics.trainingSessions||0} sessions`} detail={`${metrics.assessments||0} assessments · ${metrics.attendanceRecords||0} attendance`} tone={TONES[3]} onClick={()=>open('training',{metrics})}/><ColorCard icon={UserCheck} eyebrow="Career" title={recruiting.cycles?.[0]?.name||'Career record'} detail={`${recruiting.outreachCount||0} outreach actions`} tone={TONES[4]} onClick={()=>open('recruiting',{...recruiting})}/></div></div>
 }

 function CalendarView(){const days=Array.from({length:21},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+i);const items=schedule.filter(x=>x.competition?.startsAt&&new Date(x.competition.startsAt).toDateString()===d.toDateString());return{d,items}});return <div className="space-y-5"><ColorCard icon={CalendarDays} eyebrow="Athlete calendar" title="Your next 21 days" detail="Meets and athlete-specific events from connected LS1 records." tone={TONES[0]}><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-7">{days.map(({d,items})=><button key={d.toISOString()} onClick={()=>open('calendar-day',{date:d.toISOString(),items})} className={`min-h-24 rounded-2xl border p-3 text-left transition ${items.length?'border-cyan-300/35 bg-cyan-400/15 hover:bg-cyan-400/25':'border-white/10 bg-black/15 hover:bg-white/5'}`}><div className="text-[9px] font-black uppercase text-white/40">{d.toLocaleDateString('en-CA',{weekday:'short'})}</div><div className="mt-1 text-xl font-black text-white">{d.getDate()}</div><div className="mt-2 text-[10px] font-bold text-cyan-100">{items.length?`${items.length} event${items.length===1?'':'s'}`:'Open'}</div></button>)}</div></ColorCard></div>}

 function CompetitionView(){return <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-3"><ColorCard icon={ClipboardCheck} eyebrow="Upcoming" title="Connected entries" value={schedule.length} detail="Events already connected to this athlete." tone={TONES[0]}/><ColorCard icon={CheckCircle2} eyebrow="Eligibility" title="Eligibility engine" value="—" detail="Not yet connected; LS1 will not label an athlete eligible without rules evidence." tone={TONES[3]}/><ColorCard icon={Flag} eyebrow="Entry planner" title="My shortlist" value={entrySelections.size} detail="Explore and shortlist connected events. Submission remains locked until authority and eligibility are connected." tone={TONES[2]}/></div><section className="rounded-[1.8rem] border border-white/10 bg-gradient-to-br from-indigo-500/15 via-black/20 to-fuchsia-500/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-200">Meet explorer</div><h2 className="mt-1 text-2xl font-black text-white">What do you want to race?</h2></div><div className="rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-1 text-[10px] font-black text-amber-100">PREVIEW SELECTION · NOT SUBMITTED</div></div><div className="mt-5 space-y-3">{schedule.length?schedule.map((x,i)=>{const id=String(x.entryId||x.id||i);const selected=entrySelections.has(id);return <button key={id} onClick={()=>toggleEntry(id)} className={`grid w-full gap-4 rounded-2xl border p-4 text-left transition sm:grid-cols-[1fr_auto] ${selected?'border-fuchsia-300/40 bg-fuchsia-400/15':'border-white/10 bg-white/[.035] hover:border-white/25'}`}><div><div className="font-black text-white">{x.competition?.name||'Competition'}</div><div className="mt-1 text-sm text-white/55">{x.event?.name||x.event?.code||'Event'} · {dateLabel(x.competition?.startsAt)}</div>{x.resultValue&&<div className="mt-2 text-xs font-bold text-cyan-200">Recorded value {swimTime(x.resultValue)}</div>}</div><div className={`self-center rounded-full border px-3 py-2 text-xs font-black ${selected?'border-fuchsia-300/40 text-fuchsia-100':'border-white/15 text-white/45'}`}>{selected?'Shortlisted':'Add to shortlist'}</div></button>}):<Empty title="No connected meet entries" detail="When entries or eligible event opportunities exist, they will appear here."/>}</div></section></div>}

 function PerformanceView(){return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ColorCard icon={Trophy} eyebrow="PB events" title="Personal best board" value={pbs.length} tone={TONES[2]}/><ColorCard icon={Waves} eyebrow="Results" title="Recorded swims" value={results.length} tone={TONES[0]}/><ColorCard icon={TrendingUp} eyebrow="Latest" title={latest?.event?.name||'Latest result'} value={latest?swimTime(latest.resultValue):'—'} tone={TONES[1]}/><ColorCard icon={Flag} eyebrow="Standards" title="Verified targets" value="—" detail="Not connected yet." tone={TONES[3]}/></div><section className="rounded-[1.8rem] border border-white/10 bg-gradient-to-br from-slate-900 via-violet-950/40 to-slate-900 p-5"><div className="flex items-center gap-3"><BarChart3 className="h-6 w-6 text-violet-200"/><h2 className="text-2xl font-black text-white">My PB board</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{pbs.length?pbs.map((pb,i)=>{const key=String(pb.event?.code||pb.event?.name||'event'),history=recentByEvent.get(key)||[];return <button key={pb.id||i} onClick={()=>open('pb-detail',{...pb,history})} className={`rounded-2xl border bg-gradient-to-br p-4 text-left transition hover:-translate-y-1 ${TONES[i%TONES.length]}`}><div className="text-[10px] font-black uppercase text-white/45">{pb.event?.code||'Event'}</div><div className="mt-1 font-black text-white">{pb.event?.name||'Event'}</div><div className="mt-3 text-3xl font-black text-white">{swimTime(pb.resultValue)}</div><div className="mt-2 text-xs text-white/50">{history.length} recorded result{history.length===1?'':'s'}</div></button>}):<div className="md:col-span-2 xl:col-span-3"><Empty title="No verified result history yet" detail="PBs will be calculated from canonical result evidence when available."/></div>}</div></section></div>}

 function GoalsView(){return <div className="space-y-5"><ColorCard icon={Target} eyebrow="My direction" title={activeGoal?.title||'No active goal'} detail={activeGoal?.description||'Goals will appear here when connected.'} tone={TONES[3]} onClick={()=>open('goal',activeGoal||{})}/><div className="grid gap-4 md:grid-cols-2">{goals.length?goals.map((g,i)=><ColorCard key={g.id||i} icon={Target} eyebrow={String(g.status||'goal')} title={g.title||'Goal'} detail={g.description||'No description'} tone={TONES[i%TONES.length]} onClick={()=>open('goal',g)}/>):<Empty title="No goals connected" detail="Athlete goal writeback exists behind the authorization boundary but still requires final RLS and athlete browser validation."/>}</div></div>}

 function LogbookView(){return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><button onClick={()=>setLogbookEnabled(v=>!v)} className={`rounded-[1.8rem] border p-6 text-left transition ${logbookEnabled?'border-cyan-300/30 bg-gradient-to-br from-cyan-500/25 to-blue-500/10':'border-white/10 bg-white/[.03]'}`}><NotebookPen className="h-7 w-7 text-cyan-200"/><div className="mt-4 text-2xl font-black text-white">Athlete Logbook</div><div className="mt-2 text-sm text-white/55">{logbookEnabled?'On · training and race reflections can be part of your athlete experience.':'Off · turn it on whenever you want this tool visible.'}</div></button><button onClick={()=>setDiaryEnabled(v=>!v)} className={`rounded-[1.8rem] border p-6 text-left transition ${diaryEnabled?'border-fuchsia-300/30 bg-gradient-to-br from-fuchsia-500/25 to-violet-500/10':'border-white/10 bg-white/[.03]'}`}><BookOpen className="h-7 w-7 text-fuchsia-200"/><div className="mt-4 text-2xl font-black text-white">Personal Diary</div><div className="mt-2 text-sm text-white/55">{diaryEnabled?'On in your local preference only. Private storage is intentionally not connected until visibility rules are defined.':'Off by default. Privacy rules must be explicit before diary entries are persisted.'}</div></button></div>{logbookEnabled?<section className="rounded-[1.8rem] border border-white/10 bg-gradient-to-br from-cyan-500/10 via-black/20 to-violet-500/10 p-5"><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-200">Reflection workspace</div><h2 className="mt-2 text-2xl font-black text-white">How did today feel?</h2><div className="mt-5 grid grid-cols-5 gap-2">{['😴','😐','🙂','💪','🔥'].map(x=><button key={x} onClick={()=>open('reflection-preview',{mood:x})} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-2xl transition hover:scale-105 hover:bg-white/10">{x}</button>)}</div><div className="mt-4 rounded-2xl border border-dashed border-white/15 p-4 text-sm text-white/45">Reflection persistence will activate only after athlete self-service RLS and visibility rules are verified.</div></section>:null}</div>}

 function RecruitingView(){if(age==='9-11')return <Empty title="Recruiting is not part of this stage" detail="Development athletes stay focused on learning, progress and enjoying the sport."/>;return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><ColorCard icon={UserCheck} eyebrow="Recruiting profile" title={recruiting.cycles?.[0]?.name||'Athlete recruiting profile'} value={`${recruiting.outreachCount||0}`} detail="Recorded outreach actions" tone={TONES[4]}/><ColorCard icon={Trophy} eyebrow="Performance evidence" title="PB events" value={pbs.length} detail="Canonical performance evidence available for athlete storytelling." tone={TONES[2]}/><ColorCard icon={FileText} eyebrow="Documents" title="Profile evidence" value={documents.length} detail="Connected athlete documents." tone={TONES[0]}/></div><ColorCard icon={ShieldCheck} eyebrow="Recruiting principle" title="Verified athlete story" detail="LS1 should make the athlete easy to understand without fabricating rankings, standards, interest or outreach." tone={TONES[1]}/></div>}

 function AchievementsView(){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{badges.length?badges.map((b,i)=><ColorCard key={b.id||i} icon={Award} eyebrow="Achievement" title={b.name||'Achievement'} detail={b.description||'Recorded achievement evidence.'} tone={TONES[i%TONES.length]} onClick={()=>open('achievement',b)}/>):<div className="sm:col-span-2 xl:col-span-3"><Empty title="No achievements recorded yet" detail="This screen stays honest until an achievement is earned or recorded."/></div>}</div>}

 function DocumentsView(){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{documents.length?documents.map((d,i)=><ColorCard key={d.id||i} icon={FileText} eyebrow="Document" title={d.name||d.title||'Athlete document'} detail={d.status||d.document_type||'Connected document'} tone={TONES[i%TONES.length]} onClick={()=>open('document',d)}/>):<div className="md:col-span-2 xl:col-span-3"><Empty title="No athlete documents connected" detail="Documents will appear here from the canonical document system."/></div>}</div>}

 function SettingsView(){return <div className="space-y-5"><section className="rounded-[1.8rem] border border-white/10 bg-gradient-to-br from-violet-500/15 via-black/20 to-cyan-500/10 p-5"><div className="text-[10px] font-black uppercase tracking-[.18em] text-violet-200">Make LS1 yours</div><h2 className="mt-2 text-2xl font-black text-white">Color & experience</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['electric','Electric','from-cyan-500 to-violet-500'],['sunset','Sunset','from-orange-500 to-fuchsia-500'],['race','Race Day','from-emerald-500 to-cyan-500']].map(([id,label,gradient])=><button key={id} onClick={()=>setTheme(id)} className={`rounded-2xl border p-4 text-left ${theme===id?'border-white/45 bg-white/10':'border-white/10 bg-black/15'}`}><div className={`h-10 rounded-xl bg-gradient-to-r ${gradient}`}/><div className="mt-3 font-black text-white">{label}</div></button>)}</div></section><div className="grid gap-4 md:grid-cols-2"><ColorCard icon={NotebookPen} eyebrow="Feature toggle" title={`Logbook ${logbookEnabled?'on':'off'}`} detail="Show or hide the athlete logbook experience." tone={TONES[0]} onClick={()=>setLogbookEnabled(v=>!v)}/><ColorCard icon={BookOpen} eyebrow="Privacy-sensitive toggle" title={`Diary ${diaryEnabled?'on':'off'}`} detail="Preference only until guardian/privacy visibility rules are implemented." tone={TONES[4]} onClick={()=>setDiaryEnabled(v=>!v)}/></div></div>}

 function FeedbackView(){return <section className="rounded-[2rem] border border-emerald-300/20 bg-[radial-gradient(circle_at_15%_15%,rgba(34,211,238,.22),transparent_25%),radial-gradient(circle_at_85%_20%,rgba(217,70,239,.22),transparent_25%),linear-gradient(135deg,rgba(16,185,129,.20),rgba(15,23,42,.8))] p-6"><MessageCircle className="h-8 w-8 text-emerald-200"/><h2 className="mt-4 text-3xl font-black text-white">Help build the Athlete Hub.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Athlete feedback should shape LS1 by stage and by sport. The feedback storage workflow is not connected yet, so this interaction is preview-only.</p><div className="mt-6 grid max-w-xl grid-cols-4 gap-3">{['😍','🔥','🙂','🤔'].map(x=><button key={x} onClick={()=>open('feedback-preview',{reaction:x})} className="rounded-2xl border border-white/10 bg-white/8 p-5 text-3xl transition hover:-translate-y-1 hover:bg-white/15">{x}</button>)}</div></section>}

 let body:ReactNode;if(view==='calendar')body=<CalendarView/>;else if(view==='competitions')body=<CompetitionView/>;else if(view==='performance')body=<PerformanceView/>;else if(view==='goals')body=<GoalsView/>;else if(view==='logbook')body=<LogbookView/>;else if(view==='achievements')body=<AchievementsView/>;else if(view==='documents')body=<DocumentsView/>;else if(view==='recruiting')body=<RecruitingView/>;else if(view==='settings')body=<SettingsView/>;else if(view==='feedback')body=<FeedbackView/>;else body=<Overview/>;

 return <main className="min-h-screen bg-[radial-gradient(circle_at_20%_0%,rgba(59,130,246,.10),transparent_26%),radial-gradient(circle_at_90%_10%,rgba(217,70,239,.08),transparent_24%),#05070b] text-white"><div className="mx-auto grid max-w-[1680px] gap-5 p-4 lg:grid-cols-[250px_1fr] lg:p-6">
  <aside className="hidden min-h-[calc(100vh-3rem)] flex-col rounded-[2rem] border border-white/10 bg-white/[.035] p-4 backdrop-blur-xl lg:flex"><div className={`rounded-[1.5rem] border bg-gradient-to-br p-4 ${stage.hero} ${stage.ring}`}><div className="text-3xl">{stage.emoji}</div><div className="mt-3 text-[10px] font-black uppercase tracking-[.18em] text-white/55">Athlete stage</div><div className="mt-1 text-xl font-black text-white">{stage.name}</div><div className="text-xs font-bold text-white/55">{stage.age}</div></div><div className="mt-4"><label className="text-[9px] font-black uppercase tracking-[.16em] text-white/35">Sport</label><select value={sport} onChange={e=>setSport(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0a0d13] px-3 py-2 text-sm font-bold text-white"><option value="">Swimming</option>{sports.map((s,i)=><option key={s.id||i} value={String(s.id||s.code||s.name)}>{s.name||s.code||'Sport'}</option>)}</select></div><nav className="mt-4 space-y-1">{visibleNav.map(([key,label,Icon])=><Link key={key} href={`${key==='overview'?'/athlete':`/athlete/${key}`}${ageQuery}`} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition ${view===key||(key==='overview'&&view==='overview')?'bg-white/12 text-white shadow-lg':'text-white/45 hover:bg-white/7 hover:text-white'}`}><Icon className="h-4 w-4"/><span>{label}</span></Link>)}</nav><div className="mt-auto space-y-1 border-t border-white/10 pt-4"><Link href={`/athlete/settings${ageQuery}`} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-white/50 hover:bg-white/7 hover:text-white"><Settings className="h-4 w-4"/>Settings & Customize</Link><Link href={`/athlete/feedback${ageQuery}`} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-emerald-200 hover:bg-emerald-400/10"><MessageCircle className="h-4 w-4"/>Send feedback</Link></div></aside>
  <section className="min-w-0 space-y-5"><header className={`relative overflow-hidden rounded-[2.2rem] border bg-gradient-to-br p-6 shadow-[0_30px_100px_rgba(0,0,0,.28)] lg:p-8 ${stage.hero} ${stage.ring}`}><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-white/8 blur-2xl"/><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className={`text-[10px] font-black uppercase tracking-[.22em] ${stage.accent}`}>{stage.name} · {stage.age} · {stage.tag}</div><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] text-white lg:text-6xl">{view==='overview'?stage.headline:titleCase(view)}</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-white/65">{view==='overview'?stage.subline:'Your athlete tools stay connected to the same canonical LS1 Athlete record.'}</p></div><div className="flex flex-wrap items-center gap-3"><div className="rounded-2xl border border-white/15 bg-black/15 px-4 py-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-white/35">PB events</div><div className="mt-1 text-2xl font-black text-white">{pbs.length}</div></div><div className="rounded-2xl border border-white/15 bg-black/15 px-4 py-3"><div className="text-[9px] font-black uppercase tracking-[.16em] text-white/35">Upcoming</div><div className="mt-1 text-2xl font-black text-white">{schedule.length}</div></div><button onClick={()=>void load()} className="rounded-2xl border border-white/15 bg-black/15 p-4 text-white/70 hover:bg-white/10" aria-label="Refresh athlete data"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button></div></div></header>
  <div className="flex gap-2 overflow-x-auto pb-1 lg:hidden">{visibleNav.map(([key,label,Icon])=><Link key={key} href={`${key==='overview'?'/athlete':`/athlete/${key}`}${ageQuery}`} className={`flex shrink-0 items-center gap-2 rounded-full border px-3 py-2 text-xs font-black ${view===key?'border-white/30 bg-white/12 text-white':'border-white/10 text-white/45'}`}><Icon className="h-3.5 w-3.5"/>{label}</Link>)}</div>
  {error&&<div className="rounded-2xl border border-red-300/20 bg-red-500/10 p-4 text-sm text-red-100">{error}</div>}{body}
  </section></div>
  {drawer&&<div className="fixed inset-0 z-[90] bg-black/75 backdrop-blur-sm" onClick={()=>setDrawer(null)}><aside className="absolute right-0 top-0 h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[#080b11] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><div className={`text-[10px] font-black uppercase tracking-[.18em] ${stage.accent}`}>Athlete detail</div><h2 className="mt-2 text-3xl font-black text-white">{titleCase(String(drawer.kind||'details'))}</h2></div><button onClick={()=>setDrawer(null)} className="rounded-xl border border-white/10 p-2 text-white/60 hover:text-white"><X className="h-5 w-5"/></button></div><div className="mt-6 space-y-3">{Array.isArray(drawer.items)?(drawer.items.length?drawer.items.map((x:Row,i:number)=><div key={x.id||x.entryId||i} className={`rounded-2xl border bg-gradient-to-br p-4 ${TONES[i%TONES.length]}`}><div className="font-black text-white">{x.competition?.name||x.event?.name||x.name||x.title||`Item ${i+1}`}</div><div className="mt-1 text-sm text-white/55">{x.event?.name||x.event?.code||x.description||x.status||''}</div>{x.competition?.startsAt&&<div className="mt-2 text-xs font-bold text-cyan-200">{dateLabel(x.competition.startsAt)}</div>}</div>):<Empty title="Nothing connected yet" detail="This drawer stays empty until LS1 has canonical evidence to show."/>):drawer.history&&Array.isArray(drawer.history)?<div className="space-y-3">{drawer.history.map((x:Row,i:number)=><div key={x.id||i} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center justify-between"><div className="font-black text-white">{dateLabel(x.occurredAt||x.date||x.created_at,true)}</div><div className="text-xl font-black text-cyan-200">{swimTime(x.resultValue)}</div></div></div>)}</div>:<div className="rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/10 to-cyan-500/5 p-5"><div className="text-xl font-black text-white">{drawer.competition?.name||drawer.event?.name||drawer.name||drawer.title||drawer.reaction||drawer.mood||'Details'}</div><div className="mt-2 text-sm leading-6 text-white/55">{drawer.event?.name||drawer.event?.code||drawer.description||drawer.status||'This interaction is connected to the Athlete Hub experience.'}</div></div>}</div></aside></div>}
 </main>
}
