'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, Award, CalendarDays, ChevronRight, Clock3, Flag, Medal, RefreshCw, Route, ShieldCheck, Target, Trophy, Users } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';

type Row = Record<string, any>;
type AthletePayload = { availableAthletes:Row[]; athlete:Row|null; sports:Row[]; teams:Row[]; results:Row[]; goals:Row[]; development:Row[]; metrics:Record<string,number>; generatedAt:string; source:string; projection:string; error?:string };

const viewMeta:Record<string,[string,string]> = {
 overview:['Overview','What am I doing, how am I progressing, and what is next?'], passport:['Athlete Passport','One longitudinal athlete identity across sports, teams and organizations.'], chronometer:['Chronometer','A chronological lens across membership, development and performance.'], journey:['Athlete Journey','The athlete story built only from recorded evidence.'], development:['Development','Goals, assessments and longitudinal development evidence.'], stage:['Development Stage','Progressive experience context without creating a second athlete record.'], skills:['Skills','Skill evidence and development signals.'], goals:['Goals','Recorded development goals and their current status.'], trajectory:['Trajectory','Performance and development direction over time.'], performance:['Performance','Measured performance records from canonical sources.'], records:['Personal Records','Best known performances by event and course.'], standards:['Time Standards','Qualification and standard comparisons when standard data is connected.'], rankings:['Rankings','Rank and comparison evidence when ranking data is connected.'], analysis:['Competition Analysis','Competition-level performance evidence and context.'], 'training-history':['Training History','Recorded athlete training activity.'], habits:['Training Habits','Patterns derived from recorded training evidence.'], readiness:['Readiness','Readiness and recovery signals when recorded.'], schedule:['Schedule','Upcoming athlete competition and calendar obligations.'], preparation:['Meet Preparation','Entries, preparation and decisions for upcoming competition.'], results:['Results','Canonical result history and source evidence.']
};
const stages=['Foundation','Development','Performance','Elite'];

function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 ${className}`}>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-neutral-800 bg-[#0b0d0d] p-5 text-xs leading-5 text-neutral-500">{text}</div>}
function Metric({label,value,detail}:{label:string;value:React.ReactNode;detail:string}){return <div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-500">{label}</div><div className="mt-2 text-2xl font-black text-white">{value}</div><div className="mt-1 text-[10px] text-neutral-500">{detail}</div></div>}
function timeLabel(value:unknown){const n=Number(value);if(!Number.isFinite(n))return '—';const m=Math.floor(n/60),s=n-m*60;return m?`${m}:${s.toFixed(2).padStart(5,'0')}`:s.toFixed(2)}

export default function AthleteWorkspace(){
 const router=useRouter(); const params=useSearchParams(); const view=params.get('view')??'overview'; const athleteParam=params.get('athlete');
 const [data,setData]=useState<AthletePayload|null>(null); const [loading,setLoading]=useState(false); const [experience,setExperience]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const qs=athleteParam?`?athlete=${encodeURIComponent(athleteParam)}`:'';const r=await fetch(`/api/athlete${qs}`,{cache:'no-store'});setData(await r.json())}finally{setLoading(false)}},[athleteParam]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),20000);return()=>window.clearInterval(t)},[load]);
 useEffect(()=>{if(data?.athlete?.stage&&!experience)setExperience(data.athlete.stage)},[data?.athlete?.stage,experience]);
 const athlete=data?.athlete; const meta=viewMeta[view]??['Athlete','Living athlete passport']; const metrics=data?.metrics??{};
 const records=useMemo(()=>{const best=new Map<string,Row>();for(const r of data?.results??[]){const key=`${r.event_code}|${r.course_code??''}`;const prev=best.get(key);if(!prev||Number(r.result_value)<Number(prev.result_value))best.set(key,r)}return [...best.values()]},[data?.results]);
 const selectAthlete=(number:string)=>{const next=new URLSearchParams(params.toString());next.set('athlete',number);next.set('view',view);router.push(`/athlete?${next.toString()}`,{scroll:false})};
 const identity=<Panel><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="text-[9px] font-black uppercase tracking-[.25em] text-[#FA4616]">ATHLETE IDENTITY</div><h1 className="mt-2 text-3xl font-black text-white">{athlete?.name??'Athlete Passport'}</h1><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-neutral-400"><span>{athlete?.athleteNumber??'—'}</span><span>{athlete?`${athlete.age} years`:'—'}</span><span>{data?.sports?.map(s=>s.name).join(', ')||'No sport context'}</span><span>{data?.teams?.map(t=>t.name).join(', ')||'No team context'}</span></div></div><div className="flex flex-wrap gap-2"><select value={athlete?.athleteNumber??''} onChange={e=>selectAthlete(e.target.value)} className="rounded-xl border border-neutral-800 bg-[#0d1010] px-3 py-2 text-xs text-white outline-none">{(data?.availableAthletes??[]).map(a=><option key={a.athlete_number} value={a.athlete_number}>{a.name} · {a.athlete_number}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-neutral-800 p-3 text-neutral-400 hover:text-white" aria-label="Refresh"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div><div className="mt-5 flex flex-wrap gap-2">{stages.map(stage=><button key={stage} onClick={()=>setExperience(stage)} className={`rounded-full border px-3 py-1.5 text-[10px] font-bold ${experience===stage?'border-[#FA4616] bg-[#FA4616]/10 text-white':'border-neutral-800 text-neutral-500'}`}>{stage}</button>)}</div><div className="mt-3 text-[10px] text-neutral-600">Experience preview: {experience||athlete?.stage||'—'} · canonical stage: {athlete?.stage??'—'} · projection: {data?.projection??'—'}</div></Panel>;
 const resultRows=<div className="space-y-2">{(data?.results??[]).length?(data?.results??[]).map(r=><div key={r.id} className="grid gap-2 rounded-xl border border-neutral-800 bg-[#0d1010] p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="text-sm font-bold text-white">{r.context?.distance??''}{r.course_code??''} {r.context?.stroke??r.event_code}</div><div className="mt-1 text-[10px] text-neutral-500">{r.competition??r.context?.meet_name??'Competition source'} · {r.is_official?'official':'unverified'}</div></div><div className="text-xl font-black text-white">{timeLabel(r.result_value)}</div></div>):<Empty text="No canonical performance records are connected for this athlete yet."/>}</div>;
 const body=(()=>{
  if(view==='overview')return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Teams" value={metrics.teams??0} detail="Active canonical memberships"/><Metric label="Official results" value={metrics.officialResults??0} detail="Validated performance records"/><Metric label="Goals" value={metrics.goals??0} detail="Recorded development goals"/><Metric label="Quality issues" value={metrics.dataQualityIssues??0} detail="Open identity/data exceptions"/></div><div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel><div className="flex items-center gap-2"><Trophy className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Recent results</h2></div><div className="mt-4">{resultRows}</div></Panel><Panel><div className="flex items-center gap-2"><Users className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Current context</h2></div><div className="mt-4 space-y-3">{(data?.teams??[]).map(t=><div key={t.id} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="font-bold text-white">{t.name}</div><div className="mt-1 text-xs text-neutral-500">{t.organization} · {t.program} · {t.season}</div></div>)}</div></Panel></>;
  if(view==='passport')return <div className="grid gap-6 lg:grid-cols-2"><Panel><h2 className="font-black text-white">Canonical identity</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Athlete ID" value={athlete?.athleteNumber??'—'} detail="Stable athlete-facing identifier"/><Metric label="Status" value={athlete?.status??'—'} detail="Canonical athlete status"/><Metric label="Stage" value={athlete?.stage??'—'} detail="Derived experience stage"/><Metric label="Sports" value={data?.sports?.length??0} detail={data?.sports?.map(s=>s.name).join(', ')||'None'}/></div></Panel><Panel><h2 className="font-black text-white">Associations</h2><div className="mt-4 space-y-3">{(data?.teams??[]).map(t=><div key={t.id} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-sm"><div className="font-bold text-white">{t.name}</div><div className="mt-1 text-neutral-500">{t.organization} · {t.program} · {t.season}</div></div>)}</div></Panel></div>;
  if(view==='chronometer'||view==='journey')return <Panel><div className="flex items-center gap-2"><Route className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Recorded timeline</h2></div><div className="mt-5 space-y-3">{(data?.teams??[]).map(t=><div key={`team-${t.id}`} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[9px] uppercase text-neutral-500">Membership</div><div className="mt-1 font-bold text-white">Joined {t.name}</div></div>)}{(data?.results??[]).map(r=><div key={`result-${r.id}`} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[9px] uppercase text-neutral-500">Performance</div><div className="mt-1 font-bold text-white">{r.context?.distance}{r.course_code} {r.context?.stroke} · {timeLabel(r.result_value)}</div><div className="mt-1 text-xs text-neutral-500">{r.competition??r.context?.meet_name}</div></div>)}</div></Panel>;
  if(['development','goals'].includes(view))return <div className="grid gap-6 lg:grid-cols-2"><Panel><div className="flex items-center gap-2"><Target className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Goals</h2></div><div className="mt-4 space-y-2">{(data?.goals??[]).length?(data?.goals??[]).map(g=><div key={g.id} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="font-bold text-white">{g.title}</div><div className="mt-1 text-xs text-neutral-500">{g.status} · due {g.due_on??'not set'}</div></div>):<Empty text="No development goals have been recorded for this athlete."/>}</div></Panel><Panel><h2 className="font-black text-white">Assessments</h2><div className="mt-4 space-y-2">{(data?.development??[]).length?(data?.development??[]).map(d=><div key={d.id} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="font-bold text-white">{d.assessment_type}</div><div className="mt-1 text-xs text-neutral-500">{d.assessed_at}</div></div>):<Empty text="No development assessment has been recorded yet."/>}</div></Panel></div>;
  if(view==='stage')return <Panel><div className="grid gap-3 md:grid-cols-4">{stages.map(stage=><div key={stage} className={`rounded-xl border p-5 ${athlete?.stage===stage?'border-[#FA4616] bg-[#FA4616]/10':'border-neutral-800 bg-[#0d1010]'}`}><div className="text-sm font-black text-white">{stage}</div><div className="mt-2 text-xs leading-5 text-neutral-500">{stage==='Foundation'?'5–8 · basic, fun, gamey':stage==='Development'?'9–13 · development and emerging skills':stage==='Performance'?'14–17 · competitive, technical, recruiting':'18+ · advanced, technical, career'}</div></div>)}</div></Panel>;
  if(view==='skills')return <Panel><h2 className="font-black text-white">Skills evidence</h2><div className="mt-4"><Empty text="Skill-specific evidence has not yet been recorded for this athlete. The workspace does not manufacture skill scores."/></div></Panel>;
  if(view==='trajectory')return <Panel><h2 className="font-black text-white">Performance trajectory</h2><div className="mt-4">{resultRows}</div></Panel>;
  if(view==='performance'||view==='results'||view==='analysis')return <Panel><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Canonical performance evidence</h2></div><div className="mt-4">{resultRows}</div></Panel>;
  if(view==='records')return <Panel><div className="flex items-center gap-2"><Award className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">Personal records</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{records.length?records.map(r=><Metric key={`${r.event_code}-${r.course_code}`} label={r.event_code} value={timeLabel(r.result_value)} detail={`${r.course_code??''} · ${r.competition??r.context?.meet_name??'source record'}`}/>):<Empty text="No personal-record evidence is available yet."/>}</div></Panel>;
  if(view==='standards'||view==='rankings')return <Panel><h2 className="font-black text-white">{meta[0]}</h2><div className="mt-4"><Empty text={`${meta[0]} data is not yet connected for this athlete. This surface will remain blank rather than invent rankings or qualification status.`}/></div></Panel>;
  if(['training-history','habits','readiness'].includes(view))return <Panel><h2 className="font-black text-white">{meta[0]}</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Metric label="Training records" value={metrics.trainingSessions??0} detail="Canonical athlete training logs"/><Metric label="Readiness records" value="—" detail="No readiness evidence connected"/><Metric label="Derived habits" value="—" detail="Requires sufficient training history"/></div></Panel>;
  if(['schedule','preparation'].includes(view))return <Panel><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#FA4616]"/><h2 className="font-black text-white">{meta[0]}</h2></div><div className="mt-4"><Empty text="No athlete-specific upcoming competition/entry records are connected yet. Historical source ingestion does not create future entries."/></div></Panel>;
  return <Panel><Empty text="This athlete workspace is available but has no recorded domain evidence yet."/></Panel>;
 })();
 return <div className="min-h-full w-full bg-[#050707] p-6 lg:p-8">{identity}{data?.error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-amber-900/60 bg-amber-950/20 px-4 py-3 text-xs text-amber-300"><AlertTriangle className="h-4 w-4"/>{data.error}</div>}<div className="mt-6"><div className="mb-4"><div className="text-[9px] font-black uppercase tracking-[.25em] text-neutral-600">{view.toUpperCase().replaceAll('-',' ')}</div><h2 className="mt-1 text-2xl font-black text-white">{meta[0]}</h2><p className="mt-1 text-xs text-neutral-500">{meta[1]}</p></div><div className="space-y-6">{body}</div></div><div className="mt-6 text-[9px] text-neutral-700">Last refreshed {data?new Date(data.generatedAt).toLocaleString():'—'} · {data?.source??'LS1SportsEAM Supabase'} · adult-only public test projection</div></div>;
}
