'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {CalendarDays,CheckCircle2,ChevronRight,Flag,MessageCircle,NotebookPen,Sparkles,Target,Trophy,Zap} from 'lucide-react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={athlete?:Row|null;schedule?:Row[];results?:Row[];goals?:Row[];error?:string};
type Moment='race-day'|'meet-prep'|'post-race'|'training-day';

function parseDate(value:unknown){if(!value)return null;const d=new Date(String(value));return Number.isNaN(d.getTime())?null:d}
function dateLabel(value:unknown){const d=parseDate(value);return d?d.toLocaleString('en-CA',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Date TBD'}
function swimTime(value:unknown){const n=Number(value);if(!Number.isFinite(n))return'—';const m=Math.floor(n/60),s=n-m*60;return m?`${m}:${s.toFixed(2).padStart(5,'0')}`:s.toFixed(2)}

export default function AthleteExperienceLayer(){
 const params=useSearchParams();const age=params.get('age')||'5-8';
 const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[goalOpen,setGoalOpen]=useState(false);const[reflectionOpen,setReflectionOpen]=useState(false);
 const[goalTitle,setGoalTitle]=useState('');const[reflection,setReflection]=useState('');
 const load=useCallback(async()=>{try{const r=await authenticatedFetch(`/api/athlete?age=${encodeURIComponent(age)}`,{cache:'no-store'});const j=await r.json();if(r.ok&&!j.error)setData(j)}catch{}},[age]);
 useEffect(()=>{void load()},[load]);
 const schedule=data?.schedule||[],results=data?.results||[],goals=data?.goals||[];const athlete=data?.athlete||null;
 const next=useMemo(()=>schedule.map(item=>({item,date:parseDate(item.competition?.startsAt||item.startsAt||item.start_at)})).filter(x=>x.date&&x.date.getTime()>=Date.now()-6*60*60*1000).sort((a,b)=>a.date!.getTime()-b.date!.getTime())[0], [schedule]);
 const latest=useMemo(()=>results.map(item=>({item,date:parseDate(item.occurredAt||item.resultDate||item.competition?.startsAt||item.created_at)})).filter(x=>x.date).sort((a,b)=>b.date!.getTime()-a.date!.getTime())[0],[results]);
 const moment:Moment=useMemo(()=>{const now=Date.now();if(next?.date){const hours=(next.date.getTime()-now)/36e5;if(hours<=24)return'race-day';if(hours<=24*14)return'meet-prep'}if(latest?.date&&now-latest.date.getTime()<=72*36e5)return'post-race';return'training-day'},[next,latest]);
 const config={
  'race-day':{eyebrow:'Race Day',title:next?.item?.competition?.name||'Competition day',detail:next?`${next.item.event?.name||next.item.event?.code||'Your event'} · ${dateLabel(next.date)}`:'Your competition timeline is active.',icon:Flag,cta:'Open my meet',tone:'from-orange-500/35 via-rose-500/25 to-fuchsia-500/20 border-orange-300/30'},
  'meet-prep':{eyebrow:'Meet Prep',title:next?.item?.competition?.name||'Your next competition',detail:next?`Next up ${dateLabel(next.date)}. Entries and authoritative competition status stay connected to Competition Engine.`:'Prepare for the next competition.',icon:CalendarDays,cta:'Review meet plan',tone:'from-cyan-500/30 via-blue-500/25 to-violet-500/20 border-cyan-300/30'},
  'post-race':{eyebrow:'Post-Race',title:latest?.item?.event?.name||'Your latest performance',detail:latest?`${swimTime(latest.item.resultValue)} · turn the result into learning while it is fresh.`:'Capture what you learned.',icon:Trophy,cta:'Reflect on the race',tone:'from-emerald-500/30 via-teal-500/20 to-cyan-500/20 border-emerald-300/30'},
  'training-day':{eyebrow:'Today in LS1',title:goals[0]?.title||'What moves you forward today?',detail:goals[0]?.description||'Your coach, goals, training evidence and next competition should converge here into one meaningful next action.',icon:Zap,cta:goals.length?'Open my goal':'Set my next goal',tone:'from-violet-500/30 via-fuchsia-500/20 to-cyan-500/20 border-violet-300/30'}
 }[moment];
 const Icon=config.icon;
 async function save(action:string,body:Record<string,unknown>){if(!athlete?.id)return setNotice('A canonical athlete identity is required before this can be saved.');setBusy(true);setNotice('');try{const r=await authenticatedFetch('/api/athlete/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,athleteId:athlete.id,...body})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to save');setNotice('Saved to your LS1 athlete record.');setGoalOpen(false);setReflectionOpen(false);setGoalTitle('');setReflection('');await load()}catch(e){setNotice(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const primary=()=>{if(moment==='post-race')return setReflectionOpen(true);if(moment==='training-day'&&!goals.length)return setGoalOpen(true);const target=moment==='race-day'||moment==='meet-prep'?'/athlete/competitions':'/athlete/goals';window.location.assign(`${target}?age=${encodeURIComponent(age)}`)};
 return <section className="px-4 pt-4 sm:px-6 lg:px-8">
  <div className={`relative overflow-hidden rounded-[2rem] border bg-gradient-to-r p-5 shadow-[0_30px_100px_rgba(0,0,0,.20)] sm:p-6 ${config.tone}`}>
   <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/10 blur-3xl"/>
   <div className="relative flex flex-col gap-5 xl:flex-row xl:items-center">
    <div className="flex min-w-0 flex-1 items-start gap-4"><div className="rounded-2xl border border-white/15 bg-white/10 p-3 text-white"><Icon className="h-7 w-7"/></div><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-white/60">{config.eyebrow} · Athlete Experience</div><h2 className="mt-1 text-xl font-black text-white sm:text-2xl">{config.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">{config.detail}</p></div></div>
    <div className="flex flex-wrap gap-2"><button type="button" onClick={primary} className="inline-flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-black text-neutral-950 shadow-lg">{config.cta}<ChevronRight className="h-4 w-4"/></button><button type="button" onClick={()=>setGoalOpen(true)} className="inline-flex items-center gap-2 rounded-2xl border border-white/20 bg-black/15 px-4 py-3 text-sm font-black text-white"><Target className="h-4 w-4"/>Goal</button><button type="button" onClick={()=>setReflectionOpen(true)} className="inline-flex items-center gap-2 rounded-2xl border border-white/20 bg-black/15 px-4 py-3 text-sm font-black text-white"><NotebookPen className="h-4 w-4"/>Reflect</button></div>
   </div>
   <div className="relative mt-5 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/15 p-3"><div className="text-[10px] font-black uppercase tracking-widest text-white/45">Next competition</div><div className="mt-1 text-sm font-black text-white">{next?.item?.competition?.name||'Not scheduled'}</div></div><div className="rounded-2xl border border-white/10 bg-black/15 p-3"><div className="text-[10px] font-black uppercase tracking-widest text-white/45">Active goals</div><div className="mt-1 text-sm font-black text-white">{goals.filter(g=>String(g.status||'').toLowerCase()!=='completed').length}</div></div><div className="rounded-2xl border border-white/10 bg-black/15 p-3"><div className="text-[10px] font-black uppercase tracking-widest text-white/45">Latest recorded result</div><div className="mt-1 text-sm font-black text-white">{latest?swimTime(latest.item.resultValue):'No result connected'}</div></div></div>
  </div>
  {notice&&<div className="mx-1 mt-3 flex items-center gap-2 text-sm text-white/70"><CheckCircle2 className="h-4 w-4"/>{notice}</div>}
  {(goalOpen||reflectionOpen)&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-4 backdrop-blur-sm sm:items-center"><div className="w-full max-w-lg rounded-[2rem] border border-white/15 bg-[#10131b] p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="rounded-2xl bg-white/10 p-3 text-white">{goalOpen?<Target className="h-5 w-5"/>:<MessageCircle className="h-5 w-5"/>}</div><div><div className="text-xs font-black uppercase tracking-widest text-white/45">{goalOpen?'Athlete goal':'Race / training reflection'}</div><div className="text-xl font-black text-white">{goalOpen?'What do you want to chase?':'What did you learn?'}</div></div></div>{goalOpen?<input autoFocus value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="My next goal…" className="mt-5 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none placeholder:text-white/30"/>:<textarea autoFocus value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="What felt good? What changes next time?" rows={5} className="mt-5 w-full resize-none rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none placeholder:text-white/30"/>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>{setGoalOpen(false);setReflectionOpen(false)}} className="rounded-xl px-4 py-2 text-sm font-bold text-white/60">Cancel</button><button disabled={busy||(goalOpen?!goalTitle.trim():!reflection.trim())} type="button" onClick={()=>goalOpen?save('create_goal',{title:goalTitle,goalType:'development'}):save('create_reflection',{title:moment==='post-race'?'Race reflection':'Athlete reflection',body:reflection,reflectionType:moment==='post-race'?'race':'training'})} className="rounded-xl bg-white px-4 py-2 text-sm font-black text-neutral-950 disabled:opacity-40">{busy?'Saving…':'Save to LS1'}</button></div></div></div>}
 </section>
}
