import {NextRequest,NextResponse} from 'next/server';
import {AthleteAuthError,requireAthlete} from '@/lib/server/requireAthlete';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const enc=(v:string)=>encodeURIComponent(v);const headers=(prefer='return=representation')=>({apikey:KEY!,Authorization:`Bearer ${KEY!}`,'Content-Type':'application/json',Accept:'application/json',Prefer:prefer});
async function rest(path:string,init:RequestInit={}){if(!KEY)throw new Error('Supabase server credentials are not configured.');const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Competition action returned ${r.status}: ${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function evidence(eventType:string,entryId:string){try{const rows=await rest(`platform_milestone_units?unit_key=eq.athlete_goals_and_actions_writeback&select=id,evidence`);const row=rows?.[0];if(!row?.id)return;const evidence={...(row.evidence||{}),competitionRuntimeEvidence:{lastObservedAt:new Date().toISOString(),lastEventType:eventType,entryId}};await rest(`platform_milestone_units?id=eq.${enc(row.id)}`,{method:'PATCH',body:JSON.stringify({evidence,evidence_source:'Runtime Athlete Competition Experience',evidence_ref:eventType,verified_at:new Date().toISOString()})})}catch(error){console.error('Athlete competition capability evidence failed',error)}}
export async function POST(request:NextRequest){try{const actor=await requireAthlete(request);const body=await request.json();const action=String(body.action||''),entryId=String(body.entryId||'');if(action!=='positive_checkin')throw new AthleteAuthError('Unsupported competition action.',400);if(!entryId)throw new AthleteAuthError('Competition entry is required.',400);const entry=(await rest(`competition_entries?id=eq.${enc(entryId)}&select=id,athlete_id,competition_event_id,entry_status,eligibility_status,scratch_status&limit=1`))?.[0];if(!entry?.id)throw new AthleteAuthError('Competition entry was not found.',404);if(!actor.isSuperUser&&actor.athleteId!==entry.athlete_id)throw new AthleteAuthError('Athletes may only act on their own competition entry.',403);if(!actor.isSuperUser&&actor.ageBand!=='18+')throw new AthleteAuthError('Minor positive check-in requires an explicit guardian/organization authority rule before Athlete self-confirmation can be enabled.',403);const event=(await rest(`competition_events?id=eq.${enc(entry.competition_event_id)}&select=id,competition_id,session_id&limit=1`))?.[0];if(!event?.competition_id)throw new Error('Competition context is unavailable.');const existing=(await rest(`competition_checkins?entry_id=eq.${enc(entryId)}&athlete_id=eq.${enc(String(entry.athlete_id))}&select=id,status,checkin_type&limit=1`))?.[0];if(!existing?.id)return NextResponse.json({ok:false,error:'Positive check-in is not open for this entry. Competition Engine must create the check-in requirement/window first.'},{status:409});const now=new Date().toISOString();const saved=await rest(`competition_checkins?id=eq.${enc(existing.id)}`,{method:'PATCH',body:JSON.stringify({status:'confirmed',checked_in_at:now,checked_in_by:actor.personId,source:'athlete_hub'})});await rest('platform_events',{method:'POST',body:JSON.stringify({event_type:'competition.athlete_positive_checkin_confirmed',aggregate_type:'competition_entry',aggregate_id:entryId,payload:{athleteId:entry.athlete_id,competitionId:event.competition_id,sessionId:event.session_id,checkinId:existing.id,actorUserId:actor.userId,source:'athlete_hub'},processing_status:'pending'})});await evidence('competition.athlete_positive_checkin_confirmed',entryId);return NextResponse.json({ok:true,row:saved?.[0]??saved,confirmedAt:now})}catch(error){const status=error instanceof AthleteAuthError?error.status:500;return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Unable to complete competition action'},{status})}}
