import { NextRequest, NextResponse } from 'next/server';
import { requireSuperUser, SuperUserAuthError } from '@/lib/server/requireSuperUser';
import { writeAuditEvent } from '@/lib/server/writeAuditEvent';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL; const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
export const dynamic='force-dynamic'; export const revalidate=0;
function headers(){if(!KEY)throw new Error('Supabase service credentials are not configured.');return{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',Prefer:'return=representation'};}
async function rest(path:string,init:RequestInit={}){if(!URL||!KEY)throw new Error('Supabase service credentials are not configured.');const response=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});const body=await response.text();if(!response.ok)throw new Error(`Supabase ${path} returned ${response.status}: ${body.slice(0,500)}`);return body?JSON.parse(body):null;}
function text(value:unknown,label:string,max=160){const result=String(value||'').trim();if(!result)throw new Error(`${label} is required.`);if(result.length>max)throw new Error(`${label} must be ${max} characters or fewer.`);return result;}
function optionalText(value:unknown,max=500){const result=String(value||'').trim();if(!result)return null;if(result.length>max)throw new Error(`Text must be ${max} characters or fewer.`);return result;}
function jsonObject(value:unknown,label:string){if(value===null||value===undefined||value==='')return{};if(typeof value==='object'&&!Array.isArray(value))return value as Record<string,unknown>;try{const parsed=JSON.parse(String(value));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();return parsed as Record<string,unknown>;}catch{throw new Error(`${label} must be a JSON object.`);}}
function rejectSecrets(value:Record<string,unknown>){const forbidden=/pass(word)?|secret|token|api[_-]?key|private[_-]?key|client[_-]?secret/i;const scan=(o:Record<string,unknown>):boolean=>Object.entries(o).some(([k,v])=>forbidden.test(k)||Boolean(v&&typeof v==='object'&&!Array.isArray(v)&&scan(v as Record<string,unknown>)));if(scan(value))throw new Error('Secrets and credentials cannot be stored in generic configuration. Use the approved secret-management path.');}
async function defaultTenantId(){return(await rest('tenants?select=id&limit=1'))?.[0]?.id||null;} async function row(table:string,id:string){return(await rest(`${table}?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0]||null;}
async function create(actor:any,table:string,payload:Record<string,unknown>,auditAction:string,tenantId:string|null){const created=await rest(table,{method:'POST',body:JSON.stringify(payload)});const item=created?.[0];await writeAuditEvent(actor,{action:auditAction,entityType:table,entityId:item?.id||null,tenantId,afterData:item||payload,reason:`Super User ${auditAction.toLowerCase().replaceAll('_',' ')}`});return item;}
async function patch(actor:any,table:string,id:string,payload:Record<string,unknown>,auditAction:string,tenantId:string|null){const before=await row(table,id);if(!before)throw new Error(`${table} record not found.`);const updated=await rest(`${table}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(payload)});const after=updated?.[0]||await row(table,id);await writeAuditEvent(actor,{action:auditAction,entityType:table,entityId:id,tenantId:before.tenant_id||tenantId,beforeData:before,afterData:after,reason:`Super User ${auditAction.toLowerCase().replaceAll('_',' ')}`});return after;}

export async function POST(request:NextRequest){try{const actor=await requireSuperUser(request);if(!actor.canManagePlatformSettings)throw new SuperUserAuthError('Platform-management permission required.',403);const body=await request.json();const action=String(body.action||'');const tenantId=await defaultTenantId();
 if(action==='create-business-rule')return NextResponse.json(await create(actor,'business_rule_definitions',{tenant_id:tenantId,code:text(body.code,'Code',80).toUpperCase(),name:text(body.name,'Name'),domain:text(body.domain,'Domain',80),trigger_event:optionalText(body.trigger_event,120),rule_definition:jsonObject(body.rule_definition,'Rule definition'),priority:Number(body.priority)||100,is_active:true},'BUSINESS_RULE_CREATED',tenantId));
 if(action==='create-validation-rule')return NextResponse.json(await create(actor,'validation_rule_definitions',{tenant_id:tenantId,code:text(body.code,'Code',80).toUpperCase(),name:text(body.name,'Name'),entity_type:optionalText(body.entity_type,120),field_name:optionalText(body.field_name,120),severity:String(body.severity||'error'),rule_type:text(body.rule_type,'Rule type',80),rule_definition:jsonObject(body.rule_definition,'Rule definition'),message_template:optionalText(body.message_template),is_active:true},'VALIDATION_RULE_CREATED',tenantId));
 if(action==='create-data-quality-rule')return NextResponse.json(await create(actor,'data_quality_rules',{tenant_id:tenantId,entity_type:text(body.entity_type,'Entity type',120),rule_code:text(body.rule_code,'Rule code',80).toUpperCase(),description:text(body.description,'Description',500),expression:jsonObject(body.expression,'Expression'),severity:String(body.severity||'error'),active:true},'DATA_QUALITY_RULE_CREATED',tenantId));
 if(action==='set-business-rule-active')return NextResponse.json(await patch(actor,'business_rule_definitions',text(body.id,'Rule ID',80),{is_active:Boolean(body.active),updated_at:new Date().toISOString()},'BUSINESS_RULE_LIFECYCLE_CHANGED',tenantId));

 if(action==='create-integration-definition'){const contract=jsonObject(body.contract_definition,'Contract definition');rejectSecrets(contract);return NextResponse.json(await create(actor,'integration_definitions',{tenant_id:tenantId,code:text(body.code,'Code',80).toUpperCase(),name:text(body.name,'Name'),integration_type:String(body.integration_type||'api'),direction:String(body.direction||'inbound'),transport:optionalText(body.transport,80),source_system:optionalText(body.source_system,120),contract_definition:contract,auth_definition:{},is_active:true},'INTEGRATION_DEFINITION_CREATED',tenantId));}
 if(action==='create-integration-connection'){const configuration=jsonObject(body.configuration,'Configuration');rejectSecrets(configuration);return NextResponse.json(await create(actor,'integration_connections',{tenant_id:tenantId,system_code:text(body.system_code,'System code',80).toUpperCase(),name:text(body.name,'Name'),provider:optionalText(body.provider,120),status:String(body.status||'configured'),auth_method:optionalText(body.auth_method,80),configuration},'INTEGRATION_CONNECTION_CREATED',tenantId));}
 if(action==='create-integration-mapping'){const transform=jsonObject(body.transform_definition,'Transform definition');rejectSecrets(transform);return NextResponse.json(await create(actor,'integration_mappings',{connection_id:body.connection_id||null,entity_type:text(body.entity_type,'Entity type',120),source_field:text(body.source_field,'Source field'),target_field:text(body.target_field,'Target field'),transform_definition:transform},'INTEGRATION_MAPPING_CREATED',tenantId));}
 if(action==='set-integration-connection-status')return NextResponse.json(await patch(actor,'integration_connections',text(body.id,'Connection ID',80),{status:text(body.status,'Status',60).toLowerCase()},'INTEGRATION_CONNECTION_STATUS_CHANGED',tenantId));
 if(action==='set-dead-letter-status')return NextResponse.json(await patch(actor,'integration_dead_letters',text(body.id,'Dead-letter ID',80),{status:text(body.status,'Status',60).toLowerCase()},'INTEGRATION_DEAD_LETTER_STATUS_CHANGED',tenantId));

 if(action==='create-ai-agent'){const configuration=jsonObject(body.configuration,'Configuration');rejectSecrets(configuration);return NextResponse.json(await create(actor,'ai_agents',{tenant_id:tenantId,code:text(body.code,'Code',80).toUpperCase(),name:text(body.name,'Name'),description:optionalText(body.description),agent_type:text(body.agent_type,'Agent type',80),configuration,is_active:false},'AI_AGENT_CREATED',tenantId));}
 if(action==='set-ai-agent-active')return NextResponse.json(await patch(actor,'ai_agents',text(body.id,'Agent ID',80),{is_active:Boolean(body.active),updated_at:new Date().toISOString()},Boolean(body.active)?'AI_AGENT_ACTIVATED':'AI_AGENT_DISABLED',tenantId));
 if(action==='create-ai-agent-policy'){const policy=jsonObject(body.policy_definition,'Policy definition');rejectSecrets(policy);const agentId=text(body.record_id,'Agent ID',80);if(!await row('ai_agents',agentId))throw new Error('AI agent not found.');return NextResponse.json(await create(actor,'ai_agent_policies',{agent_id:agentId,name:text(body.name,'Name'),policy_definition:policy,is_active:true},'AI_AGENT_POLICY_CREATED',tenantId));}
 if(action==='create-ai-agent-tool'){const tool=jsonObject(body.tool_definition,'Tool definition');rejectSecrets(tool);const agentId=text(body.record_id,'Agent ID',80);if(!await row('ai_agents',agentId))throw new Error('AI agent not found.');return NextResponse.json(await create(actor,'ai_agent_tools',{agent_id:agentId,name:text(body.name,'Name'),tool_definition:tool,is_active:true},'AI_AGENT_TOOL_CREATED',tenantId));}
 if(action==='create-automation-definition'){const definition=jsonObject(body.automation_definition,'Automation definition');rejectSecrets(definition);return NextResponse.json(await create(actor,'automation_definitions',{tenant_id:tenantId,code:text(body.code,'Code',80).toUpperCase(),name:text(body.name,'Name'),description:optionalText(body.description),trigger_type:text(body.trigger_type,'Trigger type',80),definition,is_active:false},'AUTOMATION_DEFINITION_CREATED',tenantId));}
 return NextResponse.json({error:'Unsupported domain action.'},{status:400});
 }catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Domain action failed.'},{status:400});}}
