import { NextRequest,NextResponse } from 'next/server';
import { resolveAccess,serviceHeaders } from '@/lib/server/accessControl';
import { supabaseServerConfig } from '@/lib/server/superuserAuth';

const noStore={'Cache-Control':'no-store'};
type Ctx={athleteId:string;tenantId:string|null;personId:string|null;url:string;headers:Record<string,string>};
async function rest(x:Pick<Ctx,'url'|'headers'>,path:string,init:RequestInit={}){const r=await fetch(`${x.url}/rest/v1/${path}`,{...init,headers:{...x.headers,...(init.headers||{})},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(t.slice(0,500)||`Canonical request failed (${r.status}).`);return t?JSON.parse(t):[]}
async function context(request:NextRequest,requestedAthleteId:string):Promise<Ctx|NextResponse>{
 const access=await resolveAccess(request);if(!access)return NextResponse.json({ok:false,error:'Authentication required.'},{status:401,headers:noStore});
 if(!access.isPlatformSuperUser&&!access.person)return NextResponse.json({ok:false,error:'Canonical LS1 identity required.'},{status:403,headers:noStore});
 if(!access.isPlatformSuperUser&&!access.allowedHubs.includes('athlete'))return NextResponse.json({ok:false,error:'Athlete Hub authority required.'},{status:403,headers:noStore});
 const {url}=supabaseServerConfig(),headers=serviceHeaders();if(!headers)return NextResponse.json({ok:false,error:'Server authorization unavailable.'},{status:500,headers:noStore});
 if(access.isPlatformSuperUser){if(!requestedAthleteId)return NextResponse.json({ok:false,error:'Athlete identity is required for Platform SuperUser inspection.'},{status:400,headers:noStore});const rows=await rest({url,headers},`athletes?select=id,person_id&id=eq.${encodeURIComponent(requestedAthleteId)}&limit=1`);if(!rows.length)return NextResponse.json({ok:false,error:'Canonical athlete identity was not found.'},{status:404,headers:noStore});return{athleteId:rows[0].id,tenantId:access.person?.tenant_id||null,personId:rows[0].person_id||null,url,headers}}
 const rows=await rest({url,headers},`athletes?select=id,person_id&person_id=eq.${encodeURIComponent(access.person!.id)}&limit=1`);if(!rows.length)return NextResponse.json({ok:false,error:'Authenticated person is not linked to a canonical athlete.'},{status:403,headers:noStore});
 const athleteId=String(rows[0].id);if(requestedAthleteId&&requestedAthleteId!==athleteId)return NextResponse.json({ok:false,error:'Athlete action is outside the authenticated athlete scope.'},{status:403,headers:noStore});
 return{athleteId,tenantId:access.person!.tenant_id,personId:access.person!.id,url,headers};
}
async function audit(x:Ctx,eventType:string,payload:Record<string,unknown>){await rest(x,'platform_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({tenant_id:x.tenantId,event_type:eventType,aggregate_type:'athlete',aggregate_id:x.athleteId,payload,processing_status:'pending'})})}
export async function POST(request:NextRequest){try{const body=await request.json();const action=String(body.action||''),requested=String(body.athleteId||'');const q=await context(request,requested);if(q instanceof NextResponse)return q;const x=q,athleteId=x.athleteId;
 if(action==='create_goal'){const row={athlete_id:athleteId,goal_type:String(body.goalType||'development'),title:String(body.title||'').trim(),description:body.description?String(body.description):null,target_value:body.targetValue===null||body.targetValue===undefined||body.targetValue===''?null:Number(body.targetValue),target_unit:body.targetUnit?String(body.targetUnit):null,due_on:body.dueOn||null,status:'open'};if(!row.title)throw new Error('Goal title is required.');const saved=await rest(x,'development_goals',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(x,'athlete.goal.created',{goalId:saved?.[0]?.id,title:row.title});return NextResponse.json({ok:true,row:saved},{headers:noStore})}
 if(action==='update_goal'){const goalId=String(body.goalId||'');if(!goalId)throw new Error('Goal ID is required.');const owned=await rest(x,`development_goals?select=id&athlete_id=eq.${encodeURIComponent(athleteId)}&id=eq.${encodeURIComponent(goalId)}&limit=1`);if(!owned.length)return NextResponse.json({ok:false,error:'Goal is outside the authenticated athlete scope.'},{status:403,headers:noStore});const patch={title:String(body.title||'').trim(),description:body.description?String(body.description):null,target_value:body.targetValue===null||body.targetValue===undefined||body.targetValue===''?null:Number(body.targetValue),target_unit:body.targetUnit?String(body.targetUnit):null,due_on:body.dueOn||null,status:String(body.status||'open')};if(!patch.title)throw new Error('Goal title is required.');const saved=await rest(x,`development_goals?id=eq.${encodeURIComponent(goalId)}&athlete_id=eq.${encodeURIComponent(athleteId)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(x,'athlete.goal.updated',{goalId,title:patch.title,status:patch.status});return NextResponse.json({ok:true,row:saved},{headers:noStore})}
 if(action==='create_reflection'){const row={athlete_id:athleteId,reflection_type:String(body.reflectionType||'general'),title:String(body.title||'').trim(),body:body.body?String(body.body):null,occurred_on:body.occurredOn||new Date().toISOString().slice(0,10),visibility:'athlete'};if(!row.title)throw new Error('Reflection title is required.');const saved=await rest(x,'athlete_reflections',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await audit(x,'athlete.reflection.created',{reflectionId:saved?.[0]?.id,title:row.title});return NextResponse.json({ok:true,row:saved},{headers:noStore})}
 if(action==='update_challenge'){const challengeId=String(body.challengeId||'');if(!challengeId)throw new Error('Challenge ID is required.');if(!x.tenantId)throw new Error('Athlete tenant context is required.');const row={tenant_id:x.tenantId,athlete_id:athleteId,challenge_id:challengeId,progress_value:Number(body.progressValue||0),status:String(body.status||'active')};const saved=await rest(x,'athlete_challenge_progress?on_conflict=athlete_id,challenge_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});await audit(x,'athlete.challenge.updated',{challengeId,progressValue:row.progress_value,status:row.status});return NextResponse.json({ok:true,row:saved},{headers:noStore})}
 return NextResponse.json({ok:false,error:'Unsupported athlete action.'},{status:400,headers:noStore});
}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Unable to save athlete data'},{status:400,headers:noStore})}}
