import {NextRequest,NextResponse} from 'next/server';
import {CoachAuthError,requireCoach,type CoachIdentity} from '@/lib/server/requireCoach';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_ANON_KEY;
function headers(actor:CoachIdentity,extra:HeadersInit={}){if(!KEY)throw new Error('Supabase access is not configured.');const h=new Headers(extra);h.set('apikey',KEY);h.set('Authorization',`Bearer ${actor.accessToken}`);h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');return h;}
async function rest<T>(actor:CoachIdentity,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:headers(actor,init.headers),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Championship action failed (${r.status}) ${t.slice(0,260)}`);return(t?JSON.parse(t):null)as T;}
function authError(e:unknown){if(e instanceof CoachAuthError)return NextResponse.json({error:e.message},{status:e.status});return null;}
function text(v:unknown,max=2000){return String(v??'').trim().slice(0,max)}
function uuid(v:unknown){const s=text(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null;}
function integer(v:unknown){const n=Number(v);return Number.isInteger(n)&&n>=0?n:null;}
async function context(actor:CoachIdentity,teamId:string){const team=(await rest<any[]>(actor,`teams?select=id,organization_id,sport_id&id=eq.${teamId}&status=eq.active&limit=1`))[0];if(!team)throw new Error('Team is not available.');if(!actor.isSuperUser&&!actor.assignments.some(a=>a.team_id===teamId||(!a.team_id&&a.organization_id===team.organization_id)))throw new CoachAuthError('Coach is not authorized for this team.',403);const org=(await rest<any[]>(actor,`organizations?select=id,tenant_id&id=eq.${team.organization_id}&limit=1`))[0];return{team,org};}
async function audit(actor:CoachIdentity,organizationId:string,action:string,entityType:string,entityId:string|null,decision:string,after:unknown){await rest(actor,'coach_decision_log',{method:'POST',body:JSON.stringify({organization_id:organizationId,coach_person_id:actor.personId,action,entity_type:entityType,entity_id:entityId,decision,after_data:after,source:'coach_championship'})});}

export async function POST(request:NextRequest){
 try{
  const actor=await requireCoach(request);if(!actor.personId)return NextResponse.json({error:'A canonical Coach identity is required.'},{status:409});const body=await request.json(),action=text(body.action,80),teamId=uuid(body.team_id);if(!teamId)return NextResponse.json({error:'Team is required.'},{status:400});const {team,org}=await context(actor,teamId);if(!org?.tenant_id)return NextResponse.json({error:'Team organization has no canonical tenant.'},{status:409});
  if(action==='save-target'){
   const athleteId=uuid(body.athlete_id),competitionId=uuid(body.competition_id),eventCode=text(body.event_code,120),priority=text(body.priority,32)||'secondary',targetType=text(body.target_type,32)||'qualification';if(!athleteId||!competitionId||!eventCode)return NextResponse.json({error:'Athlete, competition and event are required.'},{status:400});if(!['primary','secondary','developmental'].includes(priority)||!['qualification','final','podium','placement','development'].includes(targetType))return NextResponse.json({error:'Invalid target classification.'},{status:400});
   const payload={tenant_id:org.tenant_id,organization_id:team.organization_id,team_id:team.id,coach_person_id:actor.personId,athlete_id:athleteId,competition_id:competitionId,event_code:eventCode,priority,target_type:targetType,target_standard_name:text(body.target_standard_name,160)||null,target_time_ms:integer(body.target_time_ms),source_standard_id:uuid(body.source_standard_id),status:'active',coach_note:text(body.coach_note,4000)||null,updated_at:new Date().toISOString()};
   const existing=(await rest<any[]>(actor,`coach_championship_targets?select=id&coach_person_id=eq.${actor.personId}&athlete_id=eq.${athleteId}&competition_id=eq.${competitionId}&event_code=eq.${encodeURIComponent(eventCode)}&target_type=eq.${targetType}&limit=1`))[0];const row=existing?(await rest<any[]>(actor,`coach_championship_targets?id=eq.${existing.id}`,{method:'PATCH',body:JSON.stringify(payload)}))[0]:(await rest<any[]>(actor,'coach_championship_targets',{method:'POST',body:JSON.stringify(payload)}))[0];await audit(actor,team.organization_id,'COACH_CHAMPIONSHIP_TARGET_SAVED','coach_championship_targets',row?.id||null,'active',row);return NextResponse.json(row,{status:existing?200:201});
  }
  if(action==='save-relay-scenario'){
   const competitionId=uuid(body.competition_id),name=text(body.name,180),scenarioType=text(body.scenario_type,32)||'candidate';if(!competitionId||!name)return NextResponse.json({error:'Competition and scenario name are required.'},{status:400});if(!['candidate','preferred','alternate','final'].includes(scenarioType))return NextResponse.json({error:'Invalid relay scenario type.'},{status:400});const legs=Array.isArray(body.legs)?body.legs:[];if(legs.length<2||legs.length>8)return NextResponse.json({error:'Relay scenario requires 2–8 athletes.'},{status:400});const seen=new Set<string>();const normalized:any[]=[];for(let i=0;i<legs.length;i++){const athleteId=uuid(legs[i]?.athlete_id);if(!athleteId||seen.has(athleteId))return NextResponse.json({error:'Relay legs require unique canonical athletes.'},{status:400});seen.add(athleteId);normalized.push({leg_no:i+1,athlete_id:athleteId,stroke_code:text(legs[i]?.stroke_code,40)||null,projected_split_ms:integer(legs[i]?.projected_split_ms),source_result_id:uuid(legs[i]?.source_result_id),rationale:legs[i]?.rationale||{}});}
   const projected=normalized.every(l=>l.projected_split_ms!==null)?normalized.reduce((sum,l)=>sum+Number(l.projected_split_ms),0):integer(body.projected_time_ms);const scenario=(await rest<any[]>(actor,'coach_relay_scenarios',{method:'POST',body:JSON.stringify({tenant_id:org.tenant_id,organization_id:team.organization_id,team_id:team.id,coach_person_id:actor.personId,competition_id:competitionId,competition_event_id:uuid(body.competition_event_id),name,relay_type:text(body.relay_type,80)||null,scenario_type:scenarioType,projected_time_ms:projected,objective:text(body.objective,2000)||null,rationale:body.rationale||{},status:'draft'})}))[0];const legRows=normalized.map(l=>({...l,relay_scenario_id:scenario.id}));await rest(actor,'coach_relay_scenario_legs',{method:'POST',body:JSON.stringify(legRows)});await audit(actor,team.organization_id,'COACH_RELAY_SCENARIO_CREATED','coach_relay_scenarios',scenario.id,'draft',{...scenario,legs:legRows});return NextResponse.json({...scenario,legs:legRows},{status:201});
  }
  if(action==='approve-relay-scenario'){
   const id=uuid(body.id);if(!id)return NextResponse.json({error:'Relay scenario is required.'},{status:400});const before=(await rest<any[]>(actor,`coach_relay_scenarios?select=*&id=eq.${id}&team_id=eq.${team.id}&limit=1`))[0];if(!before)return NextResponse.json({error:'Relay scenario not found.'},{status:404});const row=(await rest<any[]>(actor,`coach_relay_scenarios?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({scenario_type:'final',status:'approved',approved_at:new Date().toISOString(),updated_at:new Date().toISOString()})}))[0];await audit(actor,team.organization_id,'COACH_RELAY_SCENARIO_APPROVED','coach_relay_scenarios',id,'approved',row);return NextResponse.json(row);
  }
  return NextResponse.json({error:'Unsupported championship action.'},{status:400});
 }catch(e){const auth=authError(e);if(auth)return auth;return NextResponse.json({error:e instanceof Error?e.message:'Championship action failed.'},{status:500});}
}
