'use client';

import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{AlertTriangle,CheckCircle2,Clock3,RefreshCw,Target,XCircle}from'lucide-react';
import{useSearchParams}from'next/navigation';
import{authenticatedFetch}from'@/lib/client/authenticatedFetch';
import SuperUserVisualCommand from './SuperUserVisualCommand';

type Milestone={id:string;code:string;name:string;domain:string;status:string;sort_order:number};
type Task={id:string;parent_task_id?:string|null;milestone_id:string|null;code:string;name:string;description?:string|null;status:string;percent_complete:number|string;start_date?:string|null;target_date?:string|null;sort_order?:number;blocker?:string|null;evidence?:Record<string,unknown>|null};
type Unit={id:string;milestone_id:string|null;unit_key:string;unit_type:string;status:string;implementation_percent:number|string;operational_percent:number|string;validation_percent:number|string;evidence_source?:string|null;evidence_ref?:string|null;verified_at?:string|null;evidence?:Record<string,unknown>|null};
type Inventory={id:string;area:string;artifact_key:string;artifact_type:string;status:string;repository_path?:string|null;commit_sha?:string|null;implementation_percent:number|string;operational_percent:number|string;validation_percent:number|string;verified_at?:string|null};
type Payload={project:{id:string;name:string;status:string;target_date:string|null;description:string|null}|null;milestones:Milestone[];tasks?:Task[];units?:Unit[];inventory?:Inventory[];counts:Record<string,number|null>;generatedAt:string;source?:string;error?:string};
type ScopePayload={scope:{id:string;scope_key:string;name:string;description:string|null;status:string};requiredMilestoneIds:string[];roadmapMilestoneIds:string[];excludedUnitIds:string[];error?:string};
type MilestoneRow=Milestone&{units:Unit[];implementation:number;operational:number;validation:number;readiness:number;failures:number;required:boolean};

const clamp=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const avg=(v:number[])=>v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0;
const ready=(u:Unit)=>clamp(u.implementation_percent)===100&&clamp(u.operational_percent)===100&&clamp(u.validation_percent)===100;
const humanize=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#090b0b] ${className}`}>{children}</section>}
function Progress({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-emerald-400 transition-[width]" style={{width:`${clamp(value)}%`}}/></div>}
function Metric({label,value}:{label:string;value:number}){return <div><div className="flex items-center justify-between text-[9px] uppercase tracking-[.14em] text-neutral-500"><span>{label}</span><span className="font-black text-white">{Math.round(value)}%</span></div><div className="mt-1"><Progress value={value}/></div></div>}

export default function ProjectCommand(){
 const searchParams=useSearchParams(),view=searchParams.get('view')||'command-center';
 const[data,setData]=useState<Payload|null>(null),[scope,setScope]=useState<ScopePayload|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const pollingAllowedRef=useRef(true);
 const load=useCallback(async()=>{setLoading(true);try{const[commandResponse,scopeResponse]=await Promise.all([authenticatedFetch('/api/superuser-command',{cache:'no-store',credentials:'same-origin'}),authenticatedFetch('/api/superuser-delivery-scope',{cache:'no-store',credentials:'same-origin'})]);const command=await commandResponse.json() as Payload,scopeJson=await scopeResponse.json() as ScopePayload;if(commandResponse.status===401||scopeResponse.status===401){pollingAllowedRef.current=false;throw new Error('Your Super User session expired. Sign in again to resume live command updates.')}if(!commandResponse.ok||command.error)throw new Error(command.error||'Command data unavailable');if(!scopeResponse.ok||scopeJson.error)throw new Error(scopeJson.error||'Delivery scope unavailable');pollingAllowedRef.current=true;setData(command);setScope(scopeJson);setError('')}catch(e){const message=e instanceof Error?e.message:'Command data unavailable';if(/session is missing or expired|sign in again/i.test(message))pollingAllowedRef.current=false;setError(message)}finally{setLoading(false)}},[]);
 useEffect(()=>{pollingAllowedRef.current=true;void load();const tick=()=>{if(document.visibilityState==='visible'&&pollingAllowedRef.current)void load()};const timer=window.setInterval(tick,15000);document.addEventListener('visibilitychange',tick);return()=>{pollingAllowedRef.current=false;window.clearInterval(timer);document.removeEventListener('visibilitychange',tick)}},[load]);
 const requiredSet=useMemo(()=>new Set(scope?.requiredMilestoneIds??[]),[scope]);
 const excludedUnitSet=useMemo(()=>new Set(scope?.excludedUnitIds??[]),[scope]);
 const rows=useMemo<MilestoneRow[]>(()=>{const milestones=data?.milestones??[],all=data?.units??[];return milestones.slice().sort((a,b)=>a.sort_order-b.sort_order).map(m=>{const own=all.filter(u=>u.milestone_id===m.id&&!excludedUnitSet.has(u.id)),implementation=avg(own.map(u=>clamp(u.implementation_percent))),operational=avg(own.map(u=>clamp(u.operational_percent))),validation=avg(own.map(u=>clamp(u.validation_percent))),readiness=own.length?avg(own.map(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent)))):0;return{...m,units:own,implementation,operational,validation,readiness,failures:own.filter(u=>!ready(u)).length,required:requiredSet.has(m.id)}})},[data,requiredSet,excludedUnitSet]);
 const allUnits=data?.units??[],units=allUnits.filter(u=>u.milestone_id&&requiredSet.has(u.milestone_id)&&!excludedUnitSet.has(u.id)),implementation=avg(units.map(u=>clamp(u.implementation_percent))),operational=avg(units.map(u=>clamp(u.operational_percent))),validation=avg(units.map(u=>clamp(u.validation_percent))),scopeReadiness=units.length?avg(units.map(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent)))):0,completeUnits=units.filter(ready).length;
 const outstanding=units.filter(u=>!ready(u)).sort((a,b)=>Math.min(clamp(a.implementation_percent),clamp(a.operational_percent),clamp(a.validation_percent))-Math.min(clamp(b.implementation_percent),clamp(b.operational_percent),clamp(b.validation_percent)));
 const title=view==='project-map'?'Team Engine Project Map':view==='milestones'?'Team Engine Milestones':view==='metrics'?'Live Core Metrics':'Team Engine Super User Command Center';
 const generated=data?.generatedAt?new Date(data.generatedAt).toLocaleTimeString():null;
 return <section className="rounded-2xl border border-neutral-800 bg-[#070909] p-5 lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-5"><div><div className="text-[9px] font-black uppercase tracking-[.26em] text-emerald-400">SUPERUSER · TEAM ENGINE · LIVE OPERATIONAL CONTROL</div><h1 className="mt-2 text-3xl font-black text-white">{title}</h1><p className="mt-2 max-w-4xl text-xs leading-5 text-neutral-500">{scope?.scope?.description||'Current completion scope is loading.'} The full roadmap remains visible, but roadmap-only milestones and explicitly excluded future-domain units do not dilute or block this release.</p></div><button onClick={()=>{pollingAllowedRef.current=true;void load()}} disabled={loading} className="rounded-xl border border-neutral-800 p-3 text-neutral-400 hover:text-white" aria-label="Refresh live project state"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
  {error&&<div className="mt-5 flex items-center gap-2 rounded-xl border border-red-900/60 bg-red-950/20 px-4 py-3 text-xs text-red-300"><AlertTriangle className="h-4 w-4"/>{error}</div>}
  <SuperUserVisualCommand data={data} requiredMilestoneIds={scope?.requiredMilestoneIds??[]} excludedUnitIds={scope?.excludedUnitIds??[]} onRefresh={load}/>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
   {[['Current scope readiness',scopeReadiness],['Implemented',implementation],['Operational',operational],['Validated',validation]].map(([label,value])=><Panel key={String(label)} className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">{label}</div><div className="mt-2 text-3xl font-black text-white">{value}%</div><div className="mt-3"><Progress value={Number(value)}/></div></Panel>)}
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">100% ready units</div><div className="mt-2 text-3xl font-black text-white">{completeUnits}<span className="text-base text-neutral-600"> / {units.length}</span></div><div className="mt-2 text-[10px] text-neutral-600">Current scope only</div></Panel>
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Last live read</div><div className="mt-2 text-lg font-black text-white">{generated||'—'}</div><div className="mt-2 flex items-center gap-1 text-[10px] text-neutral-500"><Clock3 className="h-3 w-3"/>Visible-tab refresh every 15s while authenticated</div></Panel>
  </div>
  <Panel className="mt-5 overflow-hidden"><div className="border-b border-neutral-800 p-5"><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">Milestone operational matrix</div><p className="mt-2 text-xs text-neutral-500">ACTIVE milestones count toward the current Team Engine finish line. ROADMAP milestones remain visible for sequence awareness only.</p></div><div className="overflow-x-auto"><div className="min-w-[980px]"><div className="grid grid-cols-[270px_90px_1fr_1fr_1fr_1fr_100px] gap-4 border-b border-neutral-800 px-5 py-3 text-[8px] font-black uppercase tracking-[.12em] text-neutral-600"><span>Milestone</span><span>Scope</span><span>Implemented</span><span>Operational</span><span>Validated</span><span>Readiness</span><span>Outstanding</span></div>{rows.map(r=><div key={r.id} className={`grid grid-cols-[270px_90px_1fr_1fr_1fr_1fr_100px] items-center gap-4 border-b border-neutral-900 px-5 py-4 last:border-b-0 ${r.required?'':'opacity-45'}`}><div><div className="text-[9px] font-black text-emerald-400">{r.code}</div><div className="mt-1 text-xs font-bold text-white">{r.name}</div><div className="mt-1 text-[9px] text-neutral-600">{r.units.length} tracked units</div></div><div className={`rounded-full border px-2 py-1 text-center text-[8px] font-black ${r.required?'border-emerald-900/60 text-emerald-300':'border-neutral-800 text-neutral-600'}`}>{r.required?'ACTIVE':'ROADMAP'}</div><Metric label="" value={r.implementation}/><Metric label="" value={r.operational}/><Metric label="" value={r.validation}/><Metric label="" value={r.readiness}/><div className={`text-center text-lg font-black ${r.failures?'text-amber-300':'text-emerald-300'}`}>{r.failures}</div></div>)}</div></div></Panel>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel className="p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><Target className="h-4 w-4"/>Current action plan — every incomplete scoped unit</div><div className="mt-4 space-y-2">{outstanding.map((u,index)=>{const milestone=rows.find(r=>r.id===u.milestone_id),score=Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent));return <div key={u.id} className="grid gap-3 rounded-xl border border-neutral-800 bg-[#0b0e0e] p-4 sm:grid-cols-[34px_1fr_190px]"><div className="flex h-7 w-7 items-center justify-center rounded-full border border-neutral-700 text-[10px] font-black text-neutral-300">{index+1}</div><div><div className="text-sm font-black text-white">{milestone?.code||'—'} · {humanize(u.unit_key)}</div><div className="mt-1 text-[10px] uppercase tracking-[.14em] text-neutral-600">{humanize(u.unit_type)} · {u.status}</div>{u.evidence_ref&&<div className="mt-2 text-[10px] text-neutral-500">Evidence: {u.evidence_ref}</div>}</div><div className="space-y-2"><Metric label="Built" value={clamp(u.implementation_percent)}/><Metric label="Operational" value={clamp(u.operational_percent)}/><Metric label="Validated" value={clamp(u.validation_percent)}/><div className="text-right text-[9px] font-black text-amber-300">READINESS {score}%</div></div></div>})}{!outstanding.length&&units.length>0&&<div className="flex items-center gap-2 rounded-xl border border-emerald-900/60 bg-emerald-950/20 p-4 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4"/>All current-scope units are 100% implemented, operational and validated.</div>}</div></Panel>
   <Panel className="p-5"><div className="text-[9px] font-black uppercase tracking-[.2em] text-neutral-500">Control rules</div><div className="mt-4 space-y-4 text-xs leading-5 text-neutral-400"><p><b className="text-white">100% is the finish line.</b> Built but not operational is unfinished. Operational but unvalidated is unfinished.</p><p><b className="text-white">Scope is database-driven.</b> Competition and future hubs remain visible but cannot block Team Engine completion unless deliberately promoted into the active scope.</p><p><b className="text-white">Unit overrides are explicit.</b> Future-domain units stored under shared milestones can be excluded without deleting their historical evidence.</p><p><b className="text-white">Every visual resolves to evidence.</b> Timeline bars, milestone charts and completion dimensions open the same evidence model.</p><p><b className="text-white">No invented dates or metrics.</b> The Gantt is generated only from canonical project-task dates.</p><p><b className="text-white">Inventory:</b> {data?.inventory?.length||0} artifacts · {allUnits.length} total units · {units.length} active-scope units.</p><p className="flex items-center gap-2 text-amber-300"><XCircle className="h-4 w-4"/>Anything incomplete in the active scope stays visible until corrected and validated.</p></div></Panel></div>
 </section>;
}
