'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw, ShieldCheck, Target, XCircle } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

type Gate = { code:string; name:string; passed:boolean; status:string; evidence_source?:string|null; evidence_ref?:string|null; verified_at?:string|null; evidence?:Record<string,unknown> };
type Task = { id:string; code:string; name:string; description:string|null; status:string; percent_complete:number|string; blocker:string|null; evidence:Record<string,unknown>|null; milestone_id:string|null; target_date:string|null };
type Milestone = { id:string; code:string; name:string; domain:string; status:string; sort_order:number; metric_definition:Record<string,unknown>|null };
type Payload = { project:{id:string;name:string;status:string;target_date:string|null;description:string|null}|null; milestones:Milestone[]; tasks:Task[]; counts:Record<string,number|null>; generatedAt:string; source?:string; progressModel?:string; error?:string };
type Row = Milestone & { task:Task|null; progress:number; gates:Gate[]; passed:number; total:number; nextGate:Gate|null };

const clamp=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const gateOrder=['DB','API','UI','LIFECYCLE','AUTHORIZATION','AUDIT','INTEGRATION','VALIDATION'];
const gateLabel:Record<string,string>={DB:'Database',API:'API',UI:'User interface',LIFECYCLE:'Lifecycle writes',AUTHORIZATION:'Authorization',AUDIT:'Audit trail',INTEGRATION:'Integration',VALIDATION:'Tests / validation'};

function Panel({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#090b0b] ${className}`}>{children}</section>}
function Progress({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-emerald-400 transition-[width]" style={{width:`${clamp(value)}%`}}/></div>}
function GatePill({gate}:{gate:Gate|undefined}){if(!gate)return <span className="rounded-md border border-neutral-800 px-2 py-1 text-[9px] text-neutral-600">—</span>;return <span title={gate.evidence_source||gate.status} className={`inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[9px] font-black ${gate.passed?'border-emerald-900/70 bg-emerald-950/30 text-emerald-300':'border-neutral-800 bg-[#0d1010] text-neutral-500'}`}>{gate.passed?<CheckCircle2 className="h-3 w-3"/>:<XCircle className="h-3 w-3"/>}{gate.code}</span>}

export default function ProjectCommand(){
 const searchParams=useSearchParams();
 const view=searchParams.get('view')||'command-center';
 const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/superuser-command',{cache:'no-store'});const v=await r.json() as Payload;if(!r.ok||v.error)throw new Error(v.error||'Command data unavailable');setData(v);setError('')}catch(e){setError(e instanceof Error?e.message:'Command data unavailable')}finally{setLoading(false)}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(timer)},[]);
 const rows=useMemo<Row[]>(()=>{const milestones=data?.milestones??[],tasks=data?.tasks??[];return milestones.slice().sort((a,b)=>a.sort_order-b.sort_order).map(m=>{const task=tasks.find(t=>t.milestone_id===m.id)||null;const md=m.metric_definition||{};const gates=Array.isArray(md.gates)?(md.gates as Gate[]):[];const ordered=gateOrder.map(code=>gates.find(g=>g.code===code)).filter((g):g is Gate=>!!g);const passed=ordered.filter(g=>g.passed).length;const total=ordered.length||Number(md.gate_count)||8;const progress=task?clamp(task.percent_complete):(total?Math.round(passed/total*100):0);return {...m,task,progress,gates:ordered,passed,total,nextGate:ordered.find(g=>!g.passed)||null}})},[data]);
 const portfolio=rows.length?Math.round(rows.reduce((s,r)=>s+r.progress,0)/rows.length):0;
 const passedGates=rows.reduce((s,r)=>s+r.passed,0),totalGates=rows.reduce((s,r)=>s+r.total,0);
 const complete=rows.filter(r=>r.progress===100).length,blocked=rows.filter(r=>!!r.task?.blocker).length;
 const actions=rows.filter(r=>r.progress<100).slice().sort((a,b)=>a.progress-b.progress||a.sort_order-b.sort_order);
 const title=view==='project-map'?'Master EAM / ERP Project Map':view==='milestones'?'14 Platform Milestones':view==='metrics'?'Live Core Metrics':'EAM Platform Command Center';
 const generated=data?.generatedAt?new Date(data.generatedAt).toLocaleTimeString():null;
 return <section className="rounded-2xl border border-neutral-800 bg-[#070909] p-5 lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-5"><div><div className="text-[9px] font-black uppercase tracking-[.26em] text-emerald-400">SUPERUSER · LIVE IMPLEMENTATION CONTROL</div><h1 className="mt-2 text-3xl font-black text-white">{title}</h1><p className="mt-2 max-w-4xl text-xs leading-5 text-neutral-500">The percentage is calculated from verified implementation gates in Supabase: database → API → UI → lifecycle writes → authorization → audit → integration → tests/validation. Unverified work does not count as complete.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-neutral-800 p-3 text-neutral-400 hover:text-white" aria-label="Refresh live project state"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
  {error&&<div className="mt-5 flex items-center gap-2 rounded-xl border border-red-900/60 bg-red-950/20 px-4 py-3 text-xs text-red-300"><AlertTriangle className="h-4 w-4"/>{error}</div>}
  <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Platform completion</div><div className="mt-2 text-4xl font-black text-white">{portfolio}%</div><div className="mt-4"><Progress value={portfolio}/></div></Panel>
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Verified gates</div><div className="mt-2 text-3xl font-black text-white">{passedGates}<span className="text-base text-neutral-600"> / {totalGates}</span></div><div className="mt-2 text-[10px] text-neutral-500">Evidence-backed only</div></Panel>
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Milestones complete</div><div className="mt-2 text-3xl font-black text-white">{complete}<span className="text-base text-neutral-600"> / {rows.length||14}</span></div><div className="mt-2 text-[10px] text-neutral-500">All 8 gates required</div></Panel>
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Explicit blockers</div><div className="mt-2 text-3xl font-black text-white">{blocked}</div><div className="mt-2 text-[10px] text-neutral-500">From live project tasks</div></Panel>
   <Panel className="p-5"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-500">Last database read</div><div className="mt-2 text-lg font-black text-white">{generated||'—'}</div><div className="mt-2 flex items-center gap-1 text-[10px] text-neutral-500"><Clock3 className="h-3 w-3"/>Auto-refresh every 10s</div></Panel>
  </div>

  <Panel className="mt-5 overflow-hidden"><div className="border-b border-neutral-800 p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><ShieldCheck className="h-4 w-4"/>Live milestone evidence matrix</div><p className="mt-2 text-xs text-neutral-500">This is the build truth. A green gate has evidence; a grey gate is work still to prove.</p></div><div className="overflow-x-auto"><div className="min-w-[1120px]"><div className="grid grid-cols-[260px_80px_repeat(8,1fr)] gap-2 border-b border-neutral-800 px-5 py-3 text-[8px] font-black uppercase tracking-[.12em] text-neutral-600"><span>Milestone</span><span>Progress</span>{gateOrder.map(g=><span key={g}>{gateLabel[g]}</span>)}</div>{rows.map(r=><div key={r.id} className="grid grid-cols-[260px_80px_repeat(8,1fr)] items-center gap-2 border-b border-neutral-900 px-5 py-3 last:border-b-0"><div><div className="text-[9px] font-black text-emerald-400">{r.code}</div><div className="mt-1 text-xs font-bold text-white">{r.name}</div></div><div><div className="text-sm font-black text-white">{Math.round(r.progress)}%</div><div className="mt-1"><Progress value={r.progress}/></div></div>{gateOrder.map(code=><div key={code}><GatePill gate={r.gates.find(g=>g.code===code)}/></div>)}</div>)}</div></div></Panel>

  <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
   <Panel className="p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><Target className="h-4 w-4"/>Action plan — what gets us back on track</div><p className="mt-2 text-xs text-neutral-500">Ordered by least-complete milestone. The next action is the first unverified gate, so the plan changes automatically as evidence is verified.</p><div className="mt-4 space-y-2">{actions.map((r,index)=><div key={r.id} className="grid gap-3 rounded-xl border border-neutral-800 bg-[#0b0e0e] p-4 sm:grid-cols-[34px_1fr_auto]"><div className="flex h-7 w-7 items-center justify-center rounded-full border border-neutral-700 text-[10px] font-black text-neutral-300">{index+1}</div><div><div className="text-sm font-black text-white">{r.code} · {r.name}</div><div className="mt-1 text-xs text-neutral-400">Next proof: <span className="font-bold text-amber-300">{r.nextGate?gateLabel[r.nextGate.code]||r.nextGate.name:'Review milestone evidence'}</span></div>{r.task?.blocker&&<div className="mt-2 text-[10px] text-red-300">Blocker: {r.task.blocker}</div>}</div><div className="text-right"><div className="text-lg font-black text-white">{Math.round(r.progress)}%</div><div className="text-[9px] text-neutral-600">{r.passed}/{r.total} gates</div></div></div>)}{!actions.length&&<div className="rounded-xl border border-emerald-900/60 bg-emerald-950/20 p-4 text-sm text-emerald-300">All milestones have all required evidence gates.</div>}</div></Panel>
   <Panel className="p-5"><div className="text-[9px] font-black uppercase tracking-[.2em] text-neutral-500">How to read this</div><div className="mt-4 space-y-4 text-xs leading-5 text-neutral-400"><p><b className="text-white">Implementation is not a guess.</b> A milestone advances only when its required gates are marked passed with evidence in the production database.</p><p><b className="text-white">13% means one of eight gates.</b> The UI rounds 12.5% to 13%. It is not a marketing or planning estimate.</p><p><b className="text-white">The action plan is derived from the same evidence.</b> As API, UI, lifecycle, security, audit, integration and validation proof is added, the next required gate moves forward automatically.</p><p><b className="text-white">Source:</b> {data?.source||'LS1SportsEAM Supabase'} · {data?.progressModel||'8-gate evidence denominator'}.</p></div></Panel>
  </div>
 </section>;
}
