'use client';

import { FormEvent, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Wrench } from 'lucide-react';

const EAM = new Set(['facilities','assets','maintenance','resources']);
const PROCUREMENT = new Set(['procurement']);
const PAYROLL = new Set(['payroll']);
const WORKFLOW = new Set(['workflow']);
const GOVERNANCE = new Set(['compliance','data-governance','privacy','retention','audit']);
const AI = new Set(['agents','automation','alerts','insights']);
const PLATFORM = new Set(['platform','settings','role-customization','product','deployments','system-health','knowledge']);

type Group = 'eam'|'procurement'|'payroll'|'workflow'|'governance'|'ai'|'platform';

function Input({name,label,required=false,type='text',placeholder=''}:{name:string;label:string;required?:boolean;type?:string;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<input name={name} required={required} type={type} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
function Json({name,label,placeholder='{}'}:{name:string;label:string;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<textarea name={name} rows={4} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 font-mono text-[11px] normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}

export default function SuperUserEnterpriseActions({view}:{view:string}){
  const group=useMemo<Group|null>(()=>EAM.has(view)?'eam':PROCUREMENT.has(view)?'procurement':PAYROLL.has(view)?'payroll':WORKFLOW.has(view)?'workflow':GOVERNANCE.has(view)?'governance':AI.has(view)?'ai':PLATFORM.has(view)?'platform':null,[view]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  if(!group)return null;
  async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setError('');setMessage('');try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch('/api/superuser-enterprise-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Enterprise action failed.');setMessage(`${action.replaceAll('-',' ')} completed and audited.`);event.currentTarget.reset();window.dispatchEvent(new CustomEvent('ls1sports:data-changed'));}catch(cause){setError(cause instanceof Error?cause.message:'Enterprise action failed.');}finally{setBusy(false)}}
  const card='rounded-xl border border-neutral-800 bg-[#0d1010] p-4';const primary='mt-4 w-full rounded-lg bg-emerald-400 px-3 py-2.5 text-xs font-black text-black disabled:opacity-50';const secondary='mt-4 w-full rounded-lg border border-neutral-700 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50';
  return <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6"><div className="flex items-start gap-3"><Wrench className="mt-0.5 h-5 w-5 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">ENTERPRISE OPERATING CONTROLS</div><h2 className="mt-1 text-xl font-black text-white">{group.toUpperCase()} lifecycle</h2><p className="mt-2 text-xs leading-5 text-neutral-500">Controlled enterprise mutations with canonical state transitions and privileged audit evidence.</p></div></div>{error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}{message&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-4 py-3 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
  <div className="mt-6 grid gap-5 xl:grid-cols-3">
  {group==='eam'&&<>
    <form onSubmit={e=>void submit(e,'create-facility')} className={card}><div className="mb-4 text-sm font-black text-white">Facility</div><div className="space-y-3"><Input name="site_id" label="Site ID" required/><Input name="code" label="Facility code" required/><Input name="name" label="Facility name" required/><Input name="facility_type" label="Facility type"/><Input name="capacity" label="Capacity" type="number"/><Input name="timezone" label="Timezone"/></div><button disabled={busy} className={primary}>Create facility</button></form>
    <form onSubmit={e=>void submit(e,'create-asset')} className={card}><div className="mb-4 text-sm font-black text-white">Managed asset</div><div className="space-y-3"><Input name="organization_id" label="Organization ID"/><Input name="facility_id" label="Facility ID"/><Input name="asset_number" label="Asset number" required/><Input name="name" label="Asset name" required/><Input name="asset_type" label="Asset type"/><Input name="manufacturer" label="Manufacturer"/><Input name="model" label="Model"/><Input name="serial_number" label="Serial number"/><Input name="parent_asset_id" label="Parent asset ID"/></div><button disabled={busy} className={primary}>Create asset</button></form>
    <form onSubmit={e=>void submit(e,'create-work-order')} className={card}><div className="mb-4 text-sm font-black text-white">Maintenance work order</div><div className="space-y-3"><Input name="asset_id" label="Asset ID"/><Input name="facility_id" label="Facility ID"/><Input name="work_order_number" label="Work order number" required/><Input name="description" label="Description"/><Input name="priority" label="Priority" placeholder="normal"/><Input name="scheduled_start" label="Scheduled start"/><Input name="scheduled_end" label="Scheduled end"/></div><button disabled={busy} className={primary}>Create work order</button></form>
    <form onSubmit={e=>void submit(e,'set-asset-status')} className={card}><div className="mb-4 text-sm font-black text-white">Asset lifecycle</div><Input name="id" label="Asset ID" required/><Input name="status" label="Status" required/><button disabled={busy} className={secondary}>Apply asset status</button></form>
    <form onSubmit={e=>void submit(e,'set-work-order-status')} className={card}><div className="mb-4 text-sm font-black text-white">Work-order lifecycle</div><Input name="id" label="Work order ID" required/><Input name="status" label="Status" required placeholder="open, in_progress, completed"/><button disabled={busy} className={secondary}>Apply work-order status</button></form>
  </>}
  {group==='procurement'&&<>
    <form onSubmit={e=>void submit(e,'create-purchase-request')} className={card}><div className="mb-4 text-sm font-black text-white">Purchase requisition</div><div className="space-y-3"><Input name="organization_id" label="Organization ID"/><Input name="requested_by" label="Requested by person ID"/><Input name="vendor_id" label="Preferred vendor ID"/><Input name="currency" label="Currency" placeholder="CAD"/><Input name="purpose" label="Purpose"/><Json name="lines" label="Requisition lines JSON" placeholder='[{"description":"Timing pads","quantity":2,"unit_price":1000}]'/></div><button disabled={busy} className={primary}>Create requisition</button></form>
    <form onSubmit={e=>void submit(e,'set-purchase-request-status')} className={card}><div className="mb-4 text-sm font-black text-white">Requisition approval state</div><Input name="id" label="Purchase request ID" required/><Input name="status" label="Status" required placeholder="approved"/><button disabled={busy} className={secondary}>Apply request status</button></form>
    <form onSubmit={e=>void submit(e,'convert-purchase-order')} className={card}><div className="mb-4 text-sm font-black text-white">Convert approved request to PO</div><Input name="purchase_request_id" label="Purchase request ID" required/><Input name="vendor_id" label="Vendor ID"/><Input name="po_number" label="PO number" required/><Input name="currency" label="Currency" placeholder="CAD"/><button disabled={busy} className={primary}>Issue purchase order</button></form>
    <form onSubmit={e=>void submit(e,'receive-purchase-order-line')} className={card}><div className="mb-4 text-sm font-black text-white">Receive PO line</div><Input name="id" label="PO line ID" required/><Input name="received_quantity" label="Received quantity" required type="number"/><button disabled={busy} className={secondary}>Record receipt</button></form>
  </>}
  {group==='payroll'&&<>
    <form onSubmit={e=>void submit(e,'create-payroll-run')} className={`${card} xl:col-span-2`}><div className="mb-4 text-sm font-black text-white">Payroll run</div><div className="grid gap-3 sm:grid-cols-2"><Input name="legal_entity_id" label="Legal entity ID"/><Input name="period_start" label="Period start" required type="date"/><Input name="period_end" label="Period end" required type="date"/><Input name="pay_date" label="Pay date" type="date"/></div><div className="mt-3"><Json name="lines" label="Payroll lines JSON" placeholder='[{"person_id":"...","earnings":2500,"deductions":500}]'/></div><button disabled={busy} className={primary}>Create calculated payroll run</button></form>
    <form onSubmit={e=>void submit(e,'set-payroll-status')} className={card}><div className="mb-4 text-sm font-black text-white">Payroll lifecycle</div><Input name="id" label="Payroll run ID" required/><Input name="status" label="Status" required placeholder="review, approved, posted, paid"/><button disabled={busy} className={secondary}>Apply payroll status</button></form>
  </>}
  {group==='workflow'&&<>
    <form onSubmit={e=>void submit(e,'create-workflow-definition')} className={card}><div className="mb-4 text-sm font-black text-white">Workflow definition</div><Input name="code" label="Code" required/><Input name="name" label="Name" required/><Input name="version" label="Version" type="number"/><Json name="definition" label="Definition JSON"/><button disabled={busy} className={primary}>Create workflow</button></form>
    <form onSubmit={e=>void submit(e,'set-workflow-definition-status')} className={card}><div className="mb-4 text-sm font-black text-white">Workflow lifecycle</div><Input name="id" label="Workflow definition ID" required/><Input name="status" label="Status" required placeholder="active"/><button disabled={busy} className={secondary}>Apply workflow status</button></form>
    <form onSubmit={e=>void submit(e,'start-workflow')} className={card}><div className="mb-4 text-sm font-black text-white">Start workflow instance</div><Input name="workflow_definition_id" label="Definition ID"/><Input name="entity_type" label="Entity type"/><Input name="entity_id" label="Entity ID"/><Json name="context" label="Context JSON"/><button disabled={busy} className={primary}>Start workflow</button></form>
    <form onSubmit={e=>void submit(e,'complete-workflow-task')} className={card}><div className="mb-4 text-sm font-black text-white">Complete workflow task</div><Input name="id" label="Task ID" required/><Input name="decision" label="Decision"/><Json name="metadata" label="Task metadata JSON"/><button disabled={busy} className={secondary}>Complete task</button></form>
  </>}
  {group==='governance'&&<>
    <form onSubmit={e=>void submit(e,'create-compliance-requirement')} className={card}><div className="mb-4 text-sm font-black text-white">Compliance requirement</div><Input name="code" label="Code" required/><Input name="name" label="Name" required/><Input name="applies_to_role" label="Applies to role"/><Input name="severity" label="Severity" placeholder="required"/><Input name="validity_days" label="Validity days" type="number"/><Json name="rule_definition" label="Rule JSON"/><button disabled={busy} className={primary}>Create requirement</button></form>
    <form onSubmit={e=>void submit(e,'create-retention-policy')} className={card}><div className="mb-4 text-sm font-black text-white">Retention policy</div><Input name="data_classification" label="Data classification" required/><Input name="jurisdiction" label="Jurisdiction" placeholder="CA"/><Input name="retention_days" label="Retention days" required type="number"/><Input name="legal_hold_allowed" label="Legal hold allowed" placeholder="true"/><button disabled={busy} className={primary}>Create retention policy</button></form>
    <form onSubmit={e=>void submit(e,'resolve-privacy-request')} className={card}><div className="mb-4 text-sm font-black text-white">Privacy request resolution</div><Input name="id" label="Privacy request ID" required/><Input name="status" label="Status" placeholder="completed"/><Json name="resolution" label="Resolution JSON"/><button disabled={busy} className={secondary}>Resolve privacy request</button></form>
  </>}
  {group==='ai'&&<>
    <form onSubmit={e=>void submit(e,'create-ai-agent')} className={card}><div className="mb-4 text-sm font-black text-white">Governed AI agent</div><Input name="code" label="Code" required/><Input name="name" label="Name" required/><Input name="purpose" label="Purpose"/><Input name="risk_level" label="Risk level" placeholder="low"/><Input name="requires_human_approval" label="Human approval required" placeholder="true"/><Json name="configuration" label="Configuration JSON"/><button disabled={busy} className={primary}>Register AI agent</button></form>
    <form onSubmit={e=>void submit(e,'queue-ai-agent-run')} className={card}><div className="mb-4 text-sm font-black text-white">Queue AI run</div><Input name="agent_id" label="Agent ID" required/><Input name="trigger_type" label="Trigger type" placeholder="manual"/><Json name="trigger_ref" label="Trigger reference JSON"/><Json name="input" label="Input JSON"/><button disabled={busy} className={primary}>Queue governed run</button></form>
    <form onSubmit={e=>void submit(e,'set-ai-agent-status')} className={card}><div className="mb-4 text-sm font-black text-white">AI-agent lifecycle</div><Input name="id" label="Agent ID" required/><Input name="status" label="Status" required/><button disabled={busy} className={secondary}>Apply agent status</button></form>
    <form onSubmit={e=>void submit(e,'create-automation')} className={`${card} xl:col-span-2`}><div className="mb-4 text-sm font-black text-white">Automation definition</div><div className="grid gap-3 sm:grid-cols-2"><Input name="code" label="Code" required/><Input name="name" label="Name" required/><Input name="description" label="Description"/><Input name="version" label="Version" type="number"/></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Json name="trigger_definition" label="Trigger JSON"/><Json name="condition_definition" label="Condition JSON"/><Json name="action_definition" label="Action JSON"/><Json name="retry_policy" label="Retry policy JSON"/></div><button disabled={busy} className={primary}>Create automation</button></form>
    <form onSubmit={e=>void submit(e,'set-automation-enabled')} className={card}><div className="mb-4 text-sm font-black text-white">Automation lifecycle</div><Input name="id" label="Automation ID" required/><Input name="enabled" label="Enabled" required placeholder="true / false"/><button disabled={busy} className={secondary}>Apply automation state</button></form>
  </>}
  {group==='platform'&&<>
    <form onSubmit={e=>void submit(e,'set-system-configuration')} className={card}><div className="mb-4 text-sm font-black text-white">Versioned system configuration</div><Input name="config_namespace" label="Namespace" required/><Input name="config_key" label="Key" required/><Json name="config_value" label="Value JSON"/><button disabled={busy} className={primary}>Set configuration</button></form>
    <form onSubmit={e=>void submit(e,'set-platform-preference')} className={card}><div className="mb-4 text-sm font-black text-white">Platform preference</div><Input name="scope_type" label="Scope type" required/><Input name="scope_id" label="Scope ID"/><Input name="preference_namespace" label="Preference namespace" required/><Input name="preference_key" label="Preference key" required/><Json name="preference_value" label="Preference JSON"/><button disabled={busy} className={primary}>Set preference</button></form>
  </>}
  </div></section>;
}
