'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, RefreshCw, Users } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

const TEAM_ENGINE_VIEWS = new Set(['team-engine','registrar','rosters','memberships','programs','teams','seasons']);
type Group='overview'|'registrar'|'rosters'|'memberships'|'programs'|'teams'|'seasons';
type Option={id:string;label:string;detail?:string|null};
type OptionsPayload={organizations:Option[];sports:Option[];programs:Option[];seasons:Option[];teams:Option[];people:Option[];athletes:Option[];memberships:Option[];rosterMemberships:Option[];generatedAt?:string;source?:string;error?:string};

function Input({name,label,required=false,type='text',placeholder=''}:{name:string;label:string;required?:boolean;type?:string;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<input name={name} required={required} type={type} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
function Select({name,label,options,required=false,placeholder='Select…'}:{name:string;label:string;options:Option[];required?:boolean;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<select name={name} required={required} defaultValue="" className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"><option value="">{placeholder}</option>{options.map(option=><option key={option.id} value={option.id}>{option.label}{option.detail?` — ${option.detail}`:''}</option>)}</select></label>}
function StatusSelect({name='status',label='Status',defaultValue='active'}:{name?:string;label?:string;defaultValue?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<select name={name} defaultValue={defaultValue} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs text-white"><option value="planned">Planned</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="completed">Completed</option><option value="archived">Archived</option></select></label>}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-sm font-black text-white">{title}</div>{description&&<p className="mt-1 text-[10px] leading-4 text-neutral-600">{description}</p>}<div className="mt-4">{children}</div></div>}

const EMPTY:OptionsPayload={organizations:[],sports:[],programs:[],seasons:[],teams:[],people:[],athletes:[],memberships:[],rosterMemberships:[]};

export default function SuperUserTeamEngineActions({view}:{view:string}){
 const group=useMemo<Group|null>(()=>{if(!TEAM_ENGINE_VIEWS.has(view))return null;if(view==='team-engine')return'overview';return view as Group},[view]);
 const[busy,setBusy]=useState(false),[loadingOptions,setLoadingOptions]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[options,setOptions]=useState<OptionsPayload>(EMPTY);
 const loadOptions=useCallback(async()=>{if(!group)return;setLoadingOptions(true);try{const response=await authenticatedFetch('/api/superuser-team-engine-options',{cache:'no-store',credentials:'same-origin'});const json=await response.json() as OptionsPayload;if(!response.ok||json.error)throw new Error(json.error||'Unable to load Team Engine choices.');setOptions(json)}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load Team Engine choices.')}finally{setLoadingOptions(false)}},[group]);
 useEffect(()=>{void loadOptions()},[loadOptions]);
 if(!group)return null;
 async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setError('');setMessage('');try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await authenticatedFetch('/api/superuser-team-engine-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Team Engine action failed.');setMessage(`${action.replaceAll('-',' ')} completed and audited.`);event.currentTarget.reset();await loadOptions();window.dispatchEvent(new CustomEvent('ls1sports:data-changed'))}catch(cause){setError(cause instanceof Error?cause.message:'Team Engine action failed.')}finally{setBusy(false)}}
 const showPrograms=group==='overview'||group==='programs',showSeasons=group==='overview'||group==='seasons',showTeams=group==='overview'||group==='teams',showMemberships=group==='overview'||group==='registrar'||group==='memberships',showRosters=group==='overview'||group==='registrar'||group==='rosters';
 const primary='mt-4 w-full rounded-lg bg-emerald-400 px-3 py-2.5 text-xs font-black text-black disabled:opacity-50',secondary='mt-4 w-full rounded-lg border border-neutral-700 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50';
 return <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><Users className="mt-0.5 h-5 w-5 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">TEAM ENGINE CONTROL</div><h2 className="mt-1 text-xl font-black text-white">Guided operating actions</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-neutral-500">Choose people and operating records by name. LS1Sports keeps the canonical IDs underneath the workflow and audits every mutation.</p></div></div><button onClick={()=>void loadOptions()} disabled={loadingOptions} className="rounded-lg border border-neutral-800 p-2 text-neutral-500 hover:text-white" aria-label="Refresh Team Engine choices"><RefreshCw className={`h-4 w-4 ${loadingOptions?'animate-spin':''}`}/></button></div>{error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}{message&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-4 py-3 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
 <div className="mt-6 grid gap-5 xl:grid-cols-3">
 {showPrograms&&<><Section title="Create program" description="Attach a named program to an organization and sport."><form onSubmit={e=>void submit(e,'create-program')} className="space-y-3"><Select name="organization_id" label="Organization" options={options.organizations} required/><Select name="sport_id" label="Sport" options={options.sports}/><Input name="code" label="Program code" required placeholder="HPAC-HPP"/><Input name="name" label="Program name" required/><Input name="program_type" label="Program type"/><StatusSelect/><button disabled={busy} className={primary}>Create program</button></form></Section><Section title="Program lifecycle" description="Change the state of an existing program."><form onSubmit={e=>void submit(e,'set-program-status')} className="space-y-3"><Select name="id" label="Program" options={options.programs} required/><StatusSelect/><button disabled={busy} className={secondary}>Apply program status</button></form></Section></>}
 {showSeasons&&<><Section title="Create season" description="Create the operating period used by teams and programs."><form onSubmit={e=>void submit(e,'create-season')} className="space-y-3"><Select name="organization_id" label="Organization" options={options.organizations} required/><Select name="sport_id" label="Sport" options={options.sports}/><Input name="code" label="Season code" required/><Input name="name" label="Season name" required/><Input name="starts_on" label="Starts on" type="date"/><Input name="ends_on" label="Ends on" type="date"/><StatusSelect defaultValue="planned"/><button disabled={busy} className={primary}>Create season</button></form></Section><Section title="Season lifecycle"><form onSubmit={e=>void submit(e,'set-season-status')} className="space-y-3"><Select name="id" label="Season" options={options.seasons} required/><StatusSelect defaultValue="active"/><button disabled={busy} className={secondary}>Apply season status</button></form></Section></>}
 {showTeams&&<><Section title="Create team" description="Connect organization, sport, program and season without exposing IDs."><form onSubmit={e=>void submit(e,'create-team')} className="space-y-3"><Select name="organization_id" label="Organization" options={options.organizations} required/><Select name="sport_id" label="Sport" options={options.sports}/><Select name="program_id" label="Program" options={options.programs}/><Select name="season_id" label="Season" options={options.seasons}/><Input name="code" label="Team code" required/><Input name="name" label="Team name" required/><Input name="competitive_level" label="Competitive level"/><StatusSelect/><button disabled={busy} className={primary}>Create team</button></form></Section><Section title="Team lifecycle"><form onSubmit={e=>void submit(e,'set-team-status')} className="space-y-3"><Select name="id" label="Team" options={options.teams} required/><StatusSelect/><button disabled={busy} className={secondary}>Apply team status</button></form></Section></>}
 {showMemberships&&<><Section title="Create organization membership" description="Choose the person and organization by name."><form onSubmit={e=>void submit(e,'create-membership')} className="space-y-3"><Select name="organization_id" label="Organization" options={options.organizations} required/><Select name="person_id" label="Person" options={options.people} required/><Select name="sport_id" label="Sport" options={options.sports}/><Input name="membership_number" label="Membership number"/><Input name="membership_type" label="Membership type"/><Input name="starts_on" label="Starts on" type="date"/><Input name="ends_on" label="Ends on" type="date"/><StatusSelect/><button disabled={busy} className={primary}>Create membership</button></form></Section><Section title="Membership lifecycle"><form onSubmit={e=>void submit(e,'set-membership-status')} className="space-y-3"><Select name="id" label="Membership" options={options.memberships} required/><StatusSelect/><button disabled={busy} className={secondary}>Apply membership status</button></form></Section></>}
 {showRosters&&<><Section title="Add athlete to roster" description="Choose the team and athlete by name; LS1Sports records the canonical relationship."><form onSubmit={e=>void submit(e,'add-roster-member')} className="space-y-3"><Select name="team_id" label="Team" options={options.teams} required/><Select name="athlete_id" label="Athlete" options={options.athletes} required/><input type="hidden" name="membership_type" value="athlete"/><Input name="starts_on" label="Starts on" type="date"/><Input name="ends_on" label="Ends on" type="date"/><Input name="jersey_number" label="Roster number"/><Input name="notes" label="Notes"/><StatusSelect/><button disabled={busy} className={primary}>Add athlete to roster</button></form></Section><Section title="Add staff / person to roster" description="Use for coaches, managers and other rostered people."><form onSubmit={e=>void submit(e,'add-roster-member')} className="space-y-3"><Select name="team_id" label="Team" options={options.teams} required/><Select name="person_id" label="Person" options={options.people} required/><Input name="membership_type" label="Role / membership type" required placeholder="coach, manager, staff"/><Input name="starts_on" label="Starts on" type="date"/><Input name="ends_on" label="Ends on" type="date"/><Input name="notes" label="Notes"/><StatusSelect/><button disabled={busy} className={primary}>Add person to roster</button></form></Section><Section title="Roster lifecycle"><form onSubmit={e=>void submit(e,'set-roster-status')} className="space-y-3"><Select name="id" label="Roster member" options={options.rosterMemberships} required/><StatusSelect/><button disabled={busy} className={secondary}>Apply roster status</button></form></Section></>}
 </div><div className="mt-4 text-[9px] text-neutral-700">Reference source: {options.source||'LS1SportsEAM'}{options.generatedAt?` · ${new Date(options.generatedAt).toLocaleTimeString()}`:''}</div></section>
}
