'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Search } from 'lucide-react';

type Row=Record<string,unknown>;
function Input({name,label,placeholder=''}:{name:string;label:string;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<input name={name} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
function Json({name,label}:{name:string;label:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<textarea name={name} rows={4} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 font-mono text-[11px] normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
function fmt(value:unknown){if(value===null||value===undefined)return '—';if(typeof value==='object')return JSON.stringify(value);return String(value)}
export default function SuperUserOperationsActions({view}:{view:string}){const relevant=view==='audit'||view==='system-health'||view==='deployments';const[rows,setRows]=useState<Row[]>([]),[health,setHealth]=useState<{metrics?:Row[];snapshots?:Row[];tickets?:Row[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
async function loadHealth(){if(view!=='system-health'&&view!=='deployments')return;try{const r=await fetch('/api/superuser-operations-action?type=health',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load health data.');setHealth(j)}catch(c){setError(c instanceof Error?c.message:'Unable to load health data.')}}
useEffect(()=>{if(relevant)void loadHealth()},[view]);if(!relevant)return null;
async function searchAudit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const data=new FormData(event.currentTarget);const params=new URLSearchParams({type:String(data.get('type')||'audit')});for(const key of ['action','entity_type','entity_id','actor_user_id','event_type','severity']){const v=String(data.get(key)||'').trim();if(v)params.set(key,v)}const r=await fetch(`/api/superuser-operations-action?${params.toString()}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Investigation search failed.');setRows(Array.isArray(j.rows)?j.rows:[])}catch(c){setError(c instanceof Error?c.message:'Investigation search failed.')}finally{setBusy(false)}}
async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setError('');setMessage('');try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const r=await fetch('/api/superuser-operations-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Operations action failed.');setMessage(`${action.replaceAll('-',' ')} completed and audited.`);event.currentTarget.reset();await loadHealth()}catch(c){setError(c instanceof Error?c.message:'Operations action failed.')}finally{setBusy(false)}}
const card='rounded-xl border border-neutral-800 bg-[#0d1010] p-4';const btn='mt-4 w-full rounded-lg border border-neutral-700 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50';
return <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6"><div className="flex items-start gap-3"><Activity className="mt-0.5 h-5 w-5 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">OPERATIONS CONTROL</div><h2 className="mt-1 text-xl font-black text-white">{view==='audit'?'Audit & security investigation':'System health & release readiness'}</h2></div></div>{error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}{message&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-4 py-3 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
{view==='audit'&&<><form onSubmit={searchAudit} className={`${card} mt-6`}><div className="mb-4 flex items-center gap-2 text-sm font-black text-white"><Search className="h-4 w-4 text-emerald-400"/>Investigate canonical evidence</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">Evidence source<select name="type" className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs text-white"><option value="audit">Audit events</option><option value="security">Security events</option></select></label><Input name="action" label="Audit action contains"/><Input name="entity_type" label="Entity type"/><Input name="entity_id" label="Entity ID"/><Input name="actor_user_id" label="Actor user ID"/><Input name="event_type" label="Security event type"/><Input name="severity" label="Security severity"/></div><button disabled={busy} className={btn}>Search evidence</button></form><div className="mt-5 overflow-x-auto rounded-xl border border-neutral-800"><table className="min-w-full text-left text-xs"><thead className="bg-[#111515] text-[9px] uppercase tracking-[.12em] text-neutral-500"><tr><th className="px-3 py-3">When</th><th className="px-3 py-3">Action / Event</th><th className="px-3 py-3">Entity</th><th className="px-3 py-3">Reason / Details</th></tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id||index)} className="border-t border-neutral-900 align-top"><td className="px-3 py-3 text-neutral-400">{fmt(row.occurred_at)}</td><td className="px-3 py-3 font-bold text-white">{fmt(row.action||row.event_type)}</td><td className="px-3 py-3 font-mono text-[10px] text-neutral-400">{fmt(row.entity_type)} {fmt(row.entity_id)}</td><td className="max-w-xl px-3 py-3 text-neutral-400">{fmt(row.reason||row.details)}</td></tr>)}</tbody></table></div></>}
{view!=='audit'&&<div className="mt-6 grid gap-5 xl:grid-cols-3"><div className={card}><div className="text-[9px] uppercase tracking-[.14em] text-neutral-500">Metrics</div><div className="mt-2 text-3xl font-black text-white">{health?.metrics?.length||0}</div></div><div className={card}><div className="text-[9px] uppercase tracking-[.14em] text-neutral-500">Metric snapshots</div><div className="mt-2 text-3xl font-black text-white">{health?.snapshots?.length||0}</div></div><div className={card}><div className="text-[9px] uppercase tracking-[.14em] text-neutral-500">Operations tickets</div><div className="mt-2 text-3xl font-black text-white">{health?.tickets?.length||0}</div></div><form onSubmit={e=>void submit(e,'create-metric-snapshot')} className={card}><div className="mb-4 text-sm font-black text-white">Capture health evidence</div><Input name="metric_id" label="Metric ID"/><Input name="value_numeric" label="Numeric value"/><Input name="value_text" label="Text value"/><Input name="calculation_version" label="Calculation version"/><Json name="value_json" label="Evidence JSON"/><button disabled={busy} className={btn}>Capture snapshot</button></form><form onSubmit={e=>void submit(e,'create-operations-ticket')} className={card}><div className="mb-4 text-sm font-black text-white">Open operations issue</div><Input name="title" label="Title"/><Input name="description" label="Description"/><Input name="category" label="Category" placeholder="platform"/><Input name="severity" label="Severity" placeholder="normal"/><Input name="related_entity_type" label="Related entity type"/><Input name="related_entity_id" label="Related entity ID"/><button disabled={busy} className={btn}>Create tracked issue</button></form><form onSubmit={e=>void submit(e,'set-ticket-status')} className={card}><div className="mb-4 text-sm font-black text-white">Operations issue lifecycle</div><Input name="id" label="Ticket ID"/><Input name="status" label="Status" placeholder="resolved"/><Input name="owner_person_id" label="Owner person ID"/><button disabled={busy} className={btn}>Apply issue status</button></form><div className={`${card} xl:col-span-3`}><div className="text-sm font-black text-white">Recent health evidence</div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{(health?.snapshots||[]).slice(0,12).map((row,index)=><div key={String(row.id||index)} className="rounded-lg border border-neutral-800 p-3"><div className="font-mono text-[10px] text-neutral-400">{fmt(row.metric_id)}</div><div className="mt-1 text-xs text-white">{fmt(row.value_numeric||row.value_text||row.value_json)}</div><div className="mt-1 text-[9px] text-neutral-600">{fmt(row.observed_at)}</div></div>)}</div></div></div>}
</section>}
