'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, CalendarRange, CheckCircle2, Clock3, Sparkles, X } from 'lucide-react';

type Milestone={id:string;code:string;name:string;domain:string;status:string;sort_order:number};
type Task={id:string;milestone_id:string|null;code:string;name:string;description?:string|null;status:string;percent_complete:number|string;start_date?:string|null;target_date?:string|null;blocker?:string|null;evidence?:Record<string,unknown>|null};
type Unit={id:string;milestone_id:string|null;unit_key:string;unit_type:string;status:string;implementation_percent:number|string;operational_percent:number|string;validation_percent:number|string;evidence_source?:string|null;evidence_ref?:string|null;verified_at?:string|null;evidence?:Record<string,unknown>|null};
type Payload={project?:{id:string;name:string;status:string;target_date:string|null;description:string|null}|null;milestones:Milestone[];tasks?:Task[];units?:Unit[];generatedAt:string;source?:string};
type Drawer={kind:'overview'|'milestone'|'task'|'dimension';title:string;subtitle?:string;milestone?:Milestone;task?:Task;dimension?:'implementation'|'operational'|'validation'};
const clamp=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const avg=(values:number[])=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0;
const humanize=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmtDate=(value?:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not scheduled';
function DetailRow({label,value}:{label:string;value:React.ReactNode}){return <div className="grid grid-cols-[130px_1fr] gap-4 border-b border-neutral-900 py-3 last:border-0"><div className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-600">{label}</div><div className="text-xs leading-5 text-neutral-300">{value}</div></div>}

export default function SuperUserVisualCommand({data,requiredMilestoneIds,excludedUnitIds}:{data:Payload|null;requiredMilestoneIds:string[];excludedUnitIds:string[]}){
 const[drawer,setDrawer]=useState<Drawer|null>(null);
 const milestones=data?.milestones??[],tasks=data?.tasks??[],allUnits=data?.units??[],requiredSet=useMemo(()=>new Set(requiredMilestoneIds),[requiredMilestoneIds]),excludedSet=useMemo(()=>new Set(excludedUnitIds),[excludedUnitIds]);
 const scopedAllUnits=useMemo(()=>allUnits.filter(u=>!excludedSet.has(u.id)),[allUnits,excludedSet]);
 const units=useMemo(()=>scopedAllUnits.filter(u=>u.milestone_id&&requiredSet.has(u.milestone_id)),[scopedAllUnits,requiredSet]);
 const dimension=useMemo(()=>({implementation:avg(units.map(u=>clamp(u.implementation_percent))),operational:avg(units.map(u=>clamp(u.operational_percent))),validation:avg(units.map(u=>clamp(u.validation_percent)))}),[units]);
 const scheduled=useMemo(()=>tasks.filter(t=>t.start_date||t.target_date),[tasks]);
 const bounds=useMemo(()=>{const dates=scheduled.flatMap(t=>[t.start_date,t.target_date].filter(Boolean) as string[]).map(v=>new Date(`${v}T12:00:00`).getTime()).filter(Number.isFinite);if(!dates.length)return null;const min=Math.min(...dates),max=Math.max(...dates);return{min,max:max===min?min+86400000:max}},[scheduled]);
 const milestoneRows=useMemo(()=>milestones.slice().sort((a,b)=>a.sort_order-b.sort_order).map(m=>{const own=scopedAllUnits.filter(u=>u.milestone_id===m.id);return{...m,required:requiredSet.has(m.id),readiness:own.length?avg(own.map(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent)))):0,outstanding:own.filter(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent))<100).length}}),[milestones,scopedAllUnits,requiredSet]);
 const openDimension=(key:'implementation'|'operational'|'validation')=>setDrawer({kind:'dimension',title:humanize(key),subtitle:'Current Team Engine completion dimension',dimension:key});
 return <>
  <section className="mt-6 grid gap-5 2xl:grid-cols-[1.35fr_.65fr]">
   <div className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><CalendarRange className="h-4 w-4"/>Interactive delivery timeline</div><h2 className="mt-2 text-xl font-black text-white">Team Engine Super User Gantt</h2><p className="mt-2 text-xs leading-5 text-neutral-500">Every bar uses live task dates. Active-scope tasks are emphasized; future-hub and Competition roadmap tasks remain visible but muted.</p></div><button onClick={()=>setDrawer({kind:'overview',title:data?.project?.name||'Team Engine delivery',subtitle:'Project delivery evidence'})} className="rounded-xl border border-neutral-800 px-3 py-2 text-[10px] font-black text-neutral-300 hover:border-emerald-500/40 hover:text-white">Open project detail</button></div>
   {scheduled.length&&bounds?<div className="mt-5 overflow-x-auto"><div className="min-w-[920px] space-y-2">{scheduled.slice().sort((a,b)=>String(a.start_date||a.target_date).localeCompare(String(b.start_date||b.target_date))).map(task=>{const start=new Date(`${task.start_date||task.target_date}T12:00:00`).getTime(),end=new Date(`${task.target_date||task.start_date}T12:00:00`).getTime(),left=Math.max(0,((start-bounds.min)/(bounds.max-bounds.min))*100),width=Math.max(2,((Math.max(end,start)-start+86400000)/(bounds.max-bounds.min))*100),milestone=milestones.find(m=>m.id===task.milestone_id),active=Boolean(task.milestone_id&&requiredSet.has(task.milestone_id));return <button key={task.id} onClick={()=>setDrawer({kind:'task',title:task.name,subtitle:milestone?`${milestone.code} · ${milestone.name}`:'Project task',task})} className={`grid w-full grid-cols-[250px_1fr_85px] items-center gap-4 rounded-xl border border-neutral-900 bg-[#0b0e0e] px-4 py-3 text-left hover:border-emerald-500/30 ${active?'':'opacity-40'}`}><div className="min-w-0"><div className="truncate text-xs font-black text-white">{task.name}</div><div className="mt-1 text-[9px] text-neutral-600">{fmtDate(task.start_date)} → {fmtDate(task.target_date)} · {active?'ACTIVE':'ROADMAP'}</div></div><div className="relative h-8 overflow-hidden rounded-lg bg-neutral-950"><div className="absolute inset-y-1 rounded-md border border-emerald-500/30 bg-emerald-500/10" style={{left:`${left}%`,width:`${Math.min(width,100-left)}%`}}><div className="h-full rounded-md bg-emerald-400/35" style={{width:`${clamp(task.percent_complete)}%`}}/></div></div><div className="text-right"><div className="text-sm font-black text-white">{Math.round(clamp(task.percent_complete))}%</div>{task.blocker&&<AlertTriangle className="ml-auto mt-1 h-3.5 w-3.5 text-amber-300"/>}</div></button>})}</div></div>:<div className="mt-5 rounded-xl border border-dashed border-neutral-800 p-6 text-xs leading-5 text-neutral-500">No project tasks currently have start/target dates.</div>}</div>
   <div className="space-y-5"><div className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><BarChart3 className="h-4 w-4"/>Current-scope completion</div><div className="mt-5 space-y-4">{(['implementation','operational','validation'] as const).map(key=><button key={key} onClick={()=>openDimension(key)} className="block w-full text-left"><div className="flex items-center justify-between text-[10px] font-bold text-neutral-400"><span>{humanize(key)}</span><span className="text-white">{dimension[key]}%</span></div><div className="mt-2 h-4 overflow-hidden rounded-full bg-neutral-900"><div className="h-full rounded-full bg-emerald-400 transition-[width]" style={{width:`${dimension[key]}%`}}/></div></button>)}</div></div>
   <div className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><Sparkles className="h-4 w-4"/>Milestone readiness</div><div className="mt-4 space-y-2">{milestoneRows.map(m=><button key={m.id} onClick={()=>setDrawer({kind:'milestone',title:m.name,subtitle:`${m.code} · ${m.required?'ACTIVE':'ROADMAP'}`,milestone:m})} className={`grid w-full grid-cols-[1fr_90px_28px] items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-neutral-900 ${m.required?'':'opacity-40'}`}><div><div className="text-[10px] font-bold text-white">{m.name}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-neutral-900"><div className="h-full rounded-full bg-emerald-400" style={{width:`${m.readiness}%`}}/></div></div><div className="text-right text-[10px] font-black text-white">{m.readiness}%</div><div className={`text-center text-[10px] font-black ${m.outstanding?'text-amber-300':'text-emerald-300'}`}>{m.outstanding}</div></button>)}</div></div></div>
  </section>
  {drawer&&<div className="fixed inset-0 z-[90] flex justify-end bg-black/70 backdrop-blur-sm" onClick={()=>setDrawer(null)}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-neutral-800 bg-[#080a0a] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-emerald-400">SUPERUSER EVIDENCE DRAWER</div><h2 className="mt-2 text-2xl font-black text-white">{drawer.title}</h2>{drawer.subtitle&&<p className="mt-1 text-xs text-neutral-500">{drawer.subtitle}</p>}</div><button onClick={()=>setDrawer(null)} className="rounded-lg border border-neutral-800 p-2 text-neutral-500 hover:text-white"><X className="h-4 w-4"/></button></div><div className="mt-6 rounded-xl border border-neutral-800 bg-[#0c0f0f] p-4">
   {drawer.kind==='overview'&&<><DetailRow label="Status" value={data?.project?.status||'—'}/><DetailRow label="Target" value={data?.project?.target_date?fmtDate(data.project.target_date):'No target date'}/><DetailRow label="Description" value={data?.project?.description||'No description recorded.'}/><DetailRow label="Milestones" value={milestones.length}/><DetailRow label="Active scope" value={requiredSet.size}/><DetailRow label="Tasks" value={tasks.length}/><DetailRow label="Operational units" value={scopedAllUnits.length}/><DetailRow label="Excluded units" value={excludedSet.size}/><DetailRow label="Source" value={data?.source||'LS1SportsEAM Supabase'}/></>}
   {drawer.kind==='task'&&drawer.task&&<><DetailRow label="Code" value={drawer.task.code}/><DetailRow label="Scope" value={drawer.task.milestone_id&&requiredSet.has(drawer.task.milestone_id)?'ACTIVE':'ROADMAP'}/><DetailRow label="Status" value={drawer.task.status}/><DetailRow label="Complete" value={`${Math.round(clamp(drawer.task.percent_complete))}%`}/><DetailRow label="Window" value={`${fmtDate(drawer.task.start_date)} → ${fmtDate(drawer.task.target_date)}`}/><DetailRow label="Description" value={drawer.task.description||'No task description recorded.'}/><DetailRow label="Blocker" value={drawer.task.blocker||<span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 className="h-3.5 w-3.5"/>No blocker recorded</span>}/><DetailRow label="Evidence" value={<pre className="whitespace-pre-wrap break-words text-[10px] text-neutral-400">{JSON.stringify(drawer.task.evidence||{},null,2)}</pre>}/></>}
   {drawer.kind==='milestone'&&drawer.milestone&&(()=>{const own=scopedAllUnits.filter(u=>u.milestone_id===drawer.milestone!.id),ownTasks=tasks.filter(t=>t.milestone_id===drawer.milestone!.id),incomplete=own.filter(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent))<100);return <><DetailRow label="Scope" value={requiredSet.has(drawer.milestone.id)?'ACTIVE':'ROADMAP'}/><DetailRow label="Domain" value={drawer.milestone.domain}/><DetailRow label="Status" value={drawer.milestone.status}/><DetailRow label="Tasks" value={ownTasks.length}/><DetailRow label="Units" value={own.length}/><DetailRow label="Outstanding" value={incomplete.length}/><div className="mt-4 space-y-2">{incomplete.map(u=><div key={u.id} className="rounded-lg border border-neutral-800 bg-black/20 p-3"><div className="text-xs font-bold text-white">{humanize(u.unit_key)}</div><div className="mt-1 text-[10px] text-neutral-500">Built {clamp(u.implementation_percent)}% · Operational {clamp(u.operational_percent)}% · Validated {clamp(u.validation_percent)}%</div>{u.evidence_ref&&<div className="mt-1 text-[9px] text-neutral-600">Evidence: {u.evidence_ref}</div>}</div>)}</div></>})()}
   {drawer.kind==='dimension'&&drawer.dimension&&<><DetailRow label="Current-scope score" value={`${dimension[drawer.dimension]}%`}/><DetailRow label="Measures" value={drawer.dimension==='implementation'?'Whether the tracked capability is built.':drawer.dimension==='operational'?'Whether the capability works end-to-end in its intended workflow.':'Whether evidence has proven the capability behaves correctly.'}/><DetailRow label="Tracked units" value={units.length}/><div className="mt-4 space-y-2">{units.filter(u=>clamp(u[`${drawer.dimension}_percent` as keyof Unit])<100).slice(0,30).map(u=><div key={u.id} className="rounded-lg border border-neutral-800 p-3"><div className="text-xs font-bold text-white">{humanize(u.unit_key)}</div><div className="mt-1 text-[10px] text-neutral-500">{clamp(u[`${drawer.dimension}_percent` as keyof Unit])}% · {u.status}</div></div>)}</div></>}
   </div><div className="mt-4 flex items-center gap-2 text-[10px] text-neutral-600"><Clock3 className="h-3.5 w-3.5"/>Live project evidence from the same Super User command source.</div></aside></div>}
 </>;
}
