'use client';

import { useMemo, useState, type ReactNode } from 'react';
import { AlertTriangle, CalendarRange, CheckCircle2, ChevronDown, ChevronRight, Clipboard, LockKeyhole, Plus, RefreshCw, X } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Milestone={id:string;code:string;name:string;domain:string;status:string;sort_order:number};
type Task={id:string;parent_task_id?:string|null;milestone_id:string|null;code:string;name:string;description?:string|null;status:string;percent_complete:number|string;start_date?:string|null;target_date?:string|null;sort_order?:number;blocker?:string|null;evidence?:Record<string,unknown>|null};
type Unit={id:string;milestone_id:string|null;unit_key:string;unit_type:string;status:string;implementation_percent:number|string;operational_percent:number|string;validation_percent:number|string;evidence_source?:string|null;evidence_ref?:string|null;verified_at?:string|null;evidence?:Record<string,unknown>|null};
type Payload={project?:{id:string;name:string;status:string;start_date?:string|null;target_date:string|null;description:string|null}|null;milestones:Milestone[];tasks?:Task[];units?:Unit[];generatedAt:string;source?:string};
type Row={id:string;kind:'task'|'unit';depth:number;task?:Task;unit?:Unit;milestone?:Milestone;parentTask?:Task;name:string;code:string;status:string;readiness:number;start_date?:string|null;target_date?:string|null;blocker?:string|null;locked:boolean;hasChildren:boolean};
type Drawer={row?:Row;kind:'row'|'overview'|'create'};

const clamp=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const avg=(values:number[])=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0;
const humanize=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmtDate=(value?:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';
function DetailRow({label,value}:{label:string;value:ReactNode}){return <div className="grid grid-cols-[130px_1fr] gap-4 border-b border-neutral-900 py-3 last:border-0"><div className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-600">{label}</div><div className="text-xs leading-5 text-neutral-300">{value}</div></div>}

export default function SuperUserVisualCommand({data,requiredMilestoneIds,excludedUnitIds,onRefresh}:{data:Payload|null;requiredMilestoneIds:string[];excludedUnitIds:string[];onRefresh?:()=>void|Promise<void>}){
 const[drawer,setDrawer]=useState<Drawer|null>(null),[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[creating,setCreating]=useState(false),[createError,setCreateError]=useState(''),[copied,setCopied]=useState(false);
 const milestones=data?.milestones??[],tasks=data?.tasks??[],allUnits=data?.units??[];
 const requiredSet=useMemo(()=>new Set(requiredMilestoneIds),[requiredMilestoneIds]),excludedSet=useMemo(()=>new Set(excludedUnitIds),[excludedUnitIds]);
 const scopedUnits=useMemo(()=>allUnits.filter(u=>!excludedSet.has(u.id)),[allUnits,excludedSet]);
 const milestoneById=useMemo(()=>new Map(milestones.map(m=>[m.id,m])),[milestones]);
 const childrenByParent=useMemo(()=>{const map=new Map<string,Task[]>();for(const task of tasks){const key=task.parent_task_id||'ROOT';const list=map.get(key)||[];list.push(task);map.set(key,list)}for(const list of map.values())list.sort((a,b)=>(a.sort_order??999)-(b.sort_order??999)||a.name.localeCompare(b.name));return map},[tasks]);
 const unitsByMilestone=useMemo(()=>{const map=new Map<string,Unit[]>();for(const unit of scopedUnits){if(!unit.milestone_id)continue;const list=map.get(unit.milestone_id)||[];list.push(unit);map.set(unit.milestone_id,list)}for(const list of map.values())list.sort((a,b)=>a.unit_key.localeCompare(b.unit_key));return map},[scopedUnits]);
 const taskRollup=useMemo(()=>{const memo=new Map<string,number>();const calc=(task:Task):number=>{if(memo.has(task.id))return memo.get(task.id)!;const children=childrenByParent.get(task.id)||[];const ownUnits=task.milestone_id?(unitsByMilestone.get(task.milestone_id)||[]):[];const unitScores=ownUnits.map(u=>Math.min(clamp(u.implementation_percent),clamp(u.operational_percent),clamp(u.validation_percent)));const childScores=children.map(calc);const score=childScores.length||unitScores.length?avg([...childScores,...unitScores]):clamp(task.percent_complete);memo.set(task.id,score);return score};for(const task of tasks)calc(task);return memo},[tasks,childrenByParent,unitsByMilestone]);
 const rows=useMemo(()=>{const out:Row[]=[];const seenUnits=new Set<string>();const walk=(task:Task,depth:number)=>{const children=childrenByParent.get(task.id)||[];const ownUnits=task.milestone_id?(unitsByMilestone.get(task.milestone_id)||[]):[];out.push({id:task.id,kind:'task',depth,task,milestone:task.milestone_id?milestoneById.get(task.milestone_id):undefined,name:task.name,code:task.code,status:task.status,readiness:taskRollup.get(task.id)??clamp(task.percent_complete),start_date:task.start_date,target_date:task.target_date,blocker:task.blocker,locked:Boolean(task.evidence?.locked)||String(task.status).toLowerCase()==='locked',hasChildren:children.length>0||ownUnits.length>0});if(collapsed.has(task.id))return;for(const child of children)walk(child,depth+1);if(children.length===0)for(const unit of ownUnits){if(seenUnits.has(unit.id))continue;seenUnits.add(unit.id);out.push({id:unit.id,kind:'unit',depth:depth+1,unit,milestone:task.milestone_id?milestoneById.get(task.milestone_id):undefined,parentTask:task,name:humanize(unit.unit_key),code:unit.unit_type,status:unit.status,readiness:Math.min(clamp(unit.implementation_percent),clamp(unit.operational_percent),clamp(unit.validation_percent)),start_date:task.start_date,target_date:task.target_date,locked:clamp(unit.implementation_percent)===100&&clamp(unit.operational_percent)===100&&clamp(unit.validation_percent)===100,hasChildren:false})}};for(const root of childrenByParent.get('ROOT')||[])walk(root,0);return out},[childrenByParent,unitsByMilestone,milestoneById,taskRollup,collapsed]);
 const scheduled=rows.filter(r=>r.start_date||r.target_date);
 const bounds=useMemo(()=>{const dates=scheduled.flatMap(r=>[r.start_date,r.target_date].filter(Boolean) as string[]).map(v=>new Date(`${v}T12:00:00`).getTime()).filter(Number.isFinite);if(!dates.length)return null;const min=Math.min(...dates),max=Math.max(...dates);return{min,max:max===min?min+86400000:max}},[scheduled]);
 const overall=useMemo(()=>{const engines=(childrenByParent.get('ROOT')||[]).filter(t=>String(t.evidence?.work_order_type)==='engine');return engines.length?avg(engines.map(t=>taskRollup.get(t.id)??0)):avg(rows.filter(r=>r.depth===0).map(r=>r.readiness))},[childrenByParent,taskRollup,rows]);
 const activeRow=drawer?.row;
 const outstanding=activeRow?.kind==='task'&&activeRow.task?rows.filter(r=>{let cursor=r.task?.parent_task_id||r.parentTask?.id||null;while(cursor){if(cursor===activeRow.task!.id)return r.readiness<100;cursor=tasks.find(t=>t.id===cursor)?.parent_task_id||null}return false}):[];
 const executionPrompt=activeRow?`Execute LS1Sports Team Engine work order ${activeRow.code} — ${activeRow.name} to 100%.\n\nScope ID: ${activeRow.id}\nCurrent readiness: ${activeRow.readiness}%\nStatus: ${activeRow.status}\n${activeRow.milestone?`Milestone: ${activeRow.milestone.code} — ${activeRow.milestone.name}\n`:''}${activeRow.blocker?`Blocker: ${activeRow.blocker}\n`:''}\n100% is non-negotiable. Complete implementation, operational behavior, permissions/authorization, lifecycle writes, auditability, integration behavior, validation/tests, deployment/runtime verification, and regression protection. Do not mark complete until every acceptance criterion has evidence. Preserve all previously locked behavior. Competition remains placeholder-only and must not disrupt Team Engine.\n\n${outstanding.length?`Outstanding subordinate work:\n${outstanding.slice(0,40).map(r=>`- ${r.code}: ${r.name} (${r.readiness}%)`).join('\n')}\n\n`:''}When complete, update the canonical LS1Sports project evidence so implementation = 100%, operational = 100%, validation = 100%, status = locked/complete, and the Command Center turns this work item green.`:'';
 async function copyPrompt(){if(!executionPrompt)return;await navigator.clipboard.writeText(executionPrompt);setCopied(true);window.setTimeout(()=>setCopied(false),1500)}
 function toggle(id:string){setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 async function createWorkOrder(form:FormData){setCreating(true);setCreateError('');try{const response=await authenticatedFetch('/api/superuser-command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create-work-order',parent_task_id:String(form.get('parent_task_id')||''),name:String(form.get('name')||''),description:String(form.get('description')||''),start_date:String(form.get('start_date')||''),target_date:String(form.get('target_date')||'')})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to create work order');setDrawer(null);await onRefresh?.()}catch(e){setCreateError(e instanceof Error?e.message:'Unable to create work order')}finally{setCreating(false)}}
 return <>
  <section className="mt-6 rounded-2xl border border-neutral-800 bg-[#090b0b]">
   <div className="flex flex-wrap items-start justify-between gap-4 border-b border-neutral-800 p-5 lg:p-6"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-emerald-400"><CalendarRange className="h-4 w-4"/>Interactive delivery timeline</div><h2 className="mt-2 text-xl font-black text-white">Team Engine Super User Gantt</h2><p className="mt-2 max-w-4xl text-xs leading-5 text-neutral-500">Permanent EAM execution scheduler. Every row resolves to canonical project work, operational evidence, a build work order, and an executable AI prompt.</p></div><div className="flex gap-2"><button onClick={()=>setDrawer({kind:'create'})} className="inline-flex items-center gap-2 rounded-xl border border-neutral-800 px-3 py-2 text-[10px] font-black text-neutral-300 hover:border-emerald-500/40 hover:text-white"><Plus className="h-3.5 w-3.5"/>New work order</button><button onClick={()=>setDrawer({kind:'overview'})} className="rounded-xl border border-neutral-800 px-3 py-2 text-[10px] font-black text-neutral-300 hover:border-emerald-500/40 hover:text-white">Platform detail</button></div></div>
   <div className="grid grid-cols-4 gap-px border-b border-neutral-800 bg-neutral-800 sm:grid-cols-8"><div className="col-span-2 bg-[#0b0e0e] p-3 sm:col-span-3"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-600">Platform implementation</div><div className="mt-1 flex items-end gap-2"><span className="text-2xl font-black text-white">{overall}%</span><span className="pb-1 text-[9px] text-neutral-500">complete</span></div></div><div className="bg-[#0b0e0e] p-3"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-600">Rows</div><div className="mt-1 text-lg font-black text-white">{rows.length}</div></div><div className="bg-[#0b0e0e] p-3"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-600">Locked</div><div className="mt-1 text-lg font-black text-emerald-300">{rows.filter(r=>r.locked).length}</div></div><div className="bg-[#0b0e0e] p-3"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-600">Open</div><div className="mt-1 text-lg font-black text-amber-300">{rows.filter(r=>r.readiness<100).length}</div></div><div className="col-span-2 bg-[#0b0e0e] p-3 sm:col-span-2"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-600">Last source read</div><div className="mt-1 text-xs font-black text-white">{data?.generatedAt?new Date(data.generatedAt).toLocaleTimeString():'—'}</div></div></div>
   {bounds?<div className="overflow-auto"><div className="min-w-[1180px]"><div className="sticky top-0 z-10 grid grid-cols-[430px_110px_1fr_70px] border-b border-neutral-800 bg-[#0b0d0d]"><div className="px-4 py-3 text-[8px] font-black uppercase tracking-[.14em] text-neutral-500">Work order / capability</div><div className="px-3 py-3 text-[8px] font-black uppercase tracking-[.14em] text-neutral-500">Window</div><div className="grid grid-cols-5 border-x border-neutral-800 text-center text-[8px] font-black uppercase tracking-[.12em] text-neutral-500">{[0,.25,.5,.75,1].map((pct,i)=><div key={i} className="border-r border-neutral-800 px-2 py-3 last:border-r-0">{new Date(bounds.min+(bounds.max-bounds.min)*pct).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div>)}</div><div className="px-2 py-3 text-center text-[8px] font-black uppercase tracking-[.14em] text-neutral-500">Ready</div></div>
    {rows.map(row=>{const start=new Date(`${row.start_date||row.target_date}T12:00:00`).getTime(),end=new Date(`${row.target_date||row.start_date}T12:00:00`).getTime(),left=Math.max(0,((start-bounds.min)/(bounds.max-bounds.min))*100),width=Math.max(1.5,((Math.max(end,start)-start+86400000)/(bounds.max-bounds.min))*100);return <div key={`${row.kind}-${row.id}`} className={`grid grid-cols-[430px_110px_1fr_70px] border-b border-neutral-900 ${row.depth===0?'bg-[#0d1110]':'bg-[#090b0b]'} hover:bg-[#101413]`}><div className="flex min-w-0 items-center gap-1 px-3 py-2.5" style={{paddingLeft:12+row.depth*22}}>{row.kind==='task'&&row.hasChildren?<button onClick={()=>toggle(row.id)} className="rounded p-0.5 text-neutral-500 hover:text-white">{collapsed.has(row.id)?<ChevronRight className="h-3.5 w-3.5"/>:<ChevronDown className="h-3.5 w-3.5"/>}</button>:<span className="w-4"/>}<button onClick={()=>setDrawer({kind:'row',row})} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><span className={`truncate text-[11px] font-black ${row.depth===0?'text-white':'text-neutral-200'}`}>{row.name}</span>{row.locked&&<LockKeyhole className="h-3.5 w-3.5 shrink-0 text-emerald-300"/>}{row.blocker&&<AlertTriangle className="h-3.5 w-3.5 shrink-0 text-amber-300"/>}</div><div className="mt-0.5 truncate text-[8px] uppercase tracking-[.12em] text-neutral-600">{row.code} · {row.kind==='unit'?'CAPABILITY':'WORK ORDER'} · {row.status}</div></button></div><button onClick={()=>setDrawer({kind:'row',row})} className="px-2 text-left text-[9px] text-neutral-500">{fmtDate(row.start_date)}<br/>{fmtDate(row.target_date)}</button><button onClick={()=>setDrawer({kind:'row',row})} className="relative m-2 min-h-7 overflow-hidden rounded border border-neutral-900 bg-neutral-950"><div className={`absolute inset-y-1 rounded ${row.locked?'bg-emerald-400/35':'bg-sky-400/25'} border border-white/10`} style={{left:`${left}%`,width:`${Math.min(width,100-left)}%`}}><div className={`h-full ${row.locked?'bg-emerald-400/55':'bg-sky-400/45'}`} style={{width:`${row.readiness}%`}}/></div></button><button onClick={()=>setDrawer({kind:'row',row})} className={`text-center text-[11px] font-black ${row.locked?'text-emerald-300':row.readiness<100?'text-amber-300':'text-white'}`}>{row.readiness}%</button></div>})}
   </div></div>:<div className="p-6 text-xs text-neutral-500">No scheduled work rows are available from canonical project dates.</div>}
  </section>
  {drawer&&<div className="fixed inset-0 z-[90] flex justify-end bg-black/70 backdrop-blur-sm" onClick={()=>setDrawer(null)}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-neutral-800 bg-[#080a0a] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-emerald-400">SUPERUSER EVIDENCE DRAWER</div><h2 className="mt-2 text-2xl font-black text-white">{drawer.kind==='create'?'Create build work order':drawer.kind==='overview'?(data?.project?.name||'LS1Sports implementation'):activeRow?.name}</h2>{activeRow&&<p className="mt-1 text-xs text-neutral-500">{activeRow.code} · {activeRow.kind==='task'?'Work order':'Capability'}</p>}</div><button onClick={()=>setDrawer(null)} className="rounded-lg border border-neutral-800 p-2 text-neutral-500 hover:text-white"><X className="h-4 w-4"/></button></div>
    {drawer.kind==='overview'&&<div className="mt-6 rounded-xl border border-neutral-800 bg-[#0c0f0f] p-4"><DetailRow label="Status" value={data?.project?.status||'—'}/><DetailRow label="Completion" value={`${overall}%`}/><DetailRow label="Work rows" value={rows.length}/><DetailRow label="Locked" value={rows.filter(r=>r.locked).length}/><DetailRow label="Outstanding" value={rows.filter(r=>r.readiness<100).length}/><DetailRow label="Source" value={data?.source||'LS1SportsEAM Supabase'}/></div>}
    {drawer.kind==='row'&&activeRow&&<><div className="mt-6 rounded-xl border border-neutral-800 bg-[#0c0f0f] p-4"><DetailRow label="Status" value={<span className="inline-flex items-center gap-2">{activeRow.status}{activeRow.locked&&<LockKeyhole className="h-3.5 w-3.5 text-emerald-300"/>}</span>}/><DetailRow label="Readiness" value={`${activeRow.readiness}%`}/><DetailRow label="Window" value={`${fmtDate(activeRow.start_date)} → ${fmtDate(activeRow.target_date)}`}/><DetailRow label="Purpose" value={activeRow.task?.description||activeRow.unit?.evidence_ref||'Canonical LS1Sports implementation capability.'}/>{activeRow.milestone&&<DetailRow label="Milestone" value={`${activeRow.milestone.code} · ${activeRow.milestone.name}`}/>}<DetailRow label="Blocker" value={activeRow.blocker||<span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 className="h-3.5 w-3.5"/>None recorded</span>}/>{activeRow.unit&&<><DetailRow label="Implemented" value={`${clamp(activeRow.unit.implementation_percent)}%`}/><DetailRow label="Operational" value={`${clamp(activeRow.unit.operational_percent)}%`}/><DetailRow label="Validated" value={`${clamp(activeRow.unit.validation_percent)}%`}/></>}<DetailRow label="Evidence" value={<pre className="max-h-56 overflow-auto whitespace-pre-wrap break-words text-[10px] text-neutral-400">{JSON.stringify(activeRow.task?.evidence||activeRow.unit?.evidence||{},null,2)}</pre>}/></div>{outstanding.length>0&&<div className="mt-4 rounded-xl border border-neutral-800 p-4"><div className="text-[9px] font-black uppercase tracking-[.16em] text-neutral-500">Outstanding subordinate work</div><div className="mt-3 space-y-2">{outstanding.slice(0,30).map(r=><button key={r.id} onClick={()=>setDrawer({kind:'row',row:r})} className="flex w-full items-center justify-between rounded-lg border border-neutral-900 px-3 py-2 text-left hover:border-emerald-500/30"><span className="text-[11px] font-bold text-white">{r.name}</span><span className="text-[10px] font-black text-amber-300">{r.readiness}%</span></button>)}</div></div>}<div className="mt-4 rounded-xl border border-emerald-900/50 bg-emerald-950/10 p-4"><div className="flex items-center justify-between gap-3"><div className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-300">AI execution prompt</div><button onClick={copyPrompt} className="inline-flex items-center gap-2 rounded-lg border border-emerald-900/60 px-3 py-2 text-[9px] font-black text-emerald-200 hover:bg-emerald-950/40"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy prompt'}</button></div><pre className="mt-3 whitespace-pre-wrap break-words text-[11px] leading-5 text-neutral-300">{executionPrompt}</pre></div></>}
    {drawer.kind==='create'&&<form action={createWorkOrder} className="mt-6 space-y-4"><div><label className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">Engine / parent work order</label><select name="parent_task_id" required className="mt-2 w-full rounded-xl border border-neutral-800 bg-[#0c0f0f] px-3 py-3 text-sm text-white">{(childrenByParent.get('ROOT')||[]).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">Feature / work order</label><input name="name" required className="mt-2 w-full rounded-xl border border-neutral-800 bg-[#0c0f0f] px-3 py-3 text-sm text-white" placeholder="Feature or change request"/></div><div><label className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">Execution plan / acceptance intent</label><textarea name="description" required rows={6} className="mt-2 w-full rounded-xl border border-neutral-800 bg-[#0c0f0f] px-3 py-3 text-sm text-white" placeholder="Describe what must exist and work at 100%."/></div><div className="grid grid-cols-2 gap-3"><div><label className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">Start</label><input name="start_date" type="date" className="mt-2 w-full rounded-xl border border-neutral-800 bg-[#0c0f0f] px-3 py-3 text-sm text-white"/></div><div><label className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">Target</label><input name="target_date" type="date" className="mt-2 w-full rounded-xl border border-neutral-800 bg-[#0c0f0f] px-3 py-3 text-sm text-white"/></div></div>{createError&&<div className="rounded-lg border border-red-900/50 bg-red-950/20 p-3 text-xs text-red-300">{createError}</div>}<button disabled={creating} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 text-xs font-black text-black disabled:opacity-50">{creating?<RefreshCw className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}{creating?'Creating':'Create work order'}</button></form>}
   </aside></div>}
 </>;
}
