'use client';

import { useCallback,useEffect,useState } from 'react';
import { AlertTriangle,RefreshCw,ShieldCheck,WalletCards } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={metrics:Row;capabilities:Row[];generatedAt:string;source?:string;error?:string};
const money=(v:unknown)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number.isFinite(Number(v))?Number(v):0);
function Stat({label,value,detail,alert=false}:{label:string;value:string|number;detail:string;alert?:boolean}){return <div className={`rounded-xl border p-4 ${alert?'border-amber-500/35 bg-amber-500/10':'border-neutral-800 bg-[#0b0e0e]'}`}><div className="text-[10px] font-black uppercase tracking-[.14em] text-neutral-400">{label}</div><div className="mt-2 text-2xl font-black text-white">{value}</div><div className="mt-1 text-xs leading-5 text-neutral-500">{detail}</div></div>}
export default function SuperUserURWSCommand(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await authenticatedFetch('/api/superuser-urws',{cache:'no-store',credentials:'same-origin'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'URWS command data unavailable.');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'URWS command data unavailable.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>window.clearInterval(timer)},[load]);
 const m=data?.metrics||{};const attention=Number(m.urgent_or_critical_cases||0)+Number(m.overdue_expected_transitions||0)+Number(m.failed_financial_executions||0)+Number(m.approved_refund_requests_not_executed||0);
 return <section className="rounded-2xl border border-neutral-800 bg-[#070909] p-5 lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-[#FA4616]"><AlertTriangle className="h-4 w-4"/>URWS · LIVE PLATFORM CONTROL</div><h2 className="mt-2 text-2xl font-black text-white">Ugly Real-World Scenarios</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-neutral-400">Live exception, policy, financial-consequence and execution evidence. These numbers come from canonical URWS records; zero means zero, not demo data.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-neutral-800 p-3 text-neutral-300"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
  {error&&<div className="mt-4 rounded-xl border border-red-900/50 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Open cases" value={Number(m.open_cases||0)} detail={`${Number(m.urgent_or_critical_cases||0)} urgent / critical`} alert={Number(m.urgent_or_critical_cases||0)>0}/><Stat label="Open case exposure" value={money(m.open_case_financial_impact)} detail={`${Number(m.open_financial_commitments||0)} open commitments`}/><Stat label="Awaiting execution" value={Number(m.approved_remedies_awaiting_execution||0)} detail={`${money(m.financial_amount_awaiting_completion)} authorized / executing`} alert={Number(m.approved_remedies_awaiting_execution||0)>0}/><Stat label="Execution failures" value={Number(m.failed_financial_executions||0)} detail={`${Number(m.financial_executions_in_progress||0)} currently executing`} alert={Number(m.failed_financial_executions||0)>0}/><Stat label="Approved refunds not executed" value={Number(m.approved_refund_requests_not_executed||0)} detail="Approval is deliberately separate from processed refund" alert={Number(m.approved_refund_requests_not_executed||0)>0}/></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.8fr]"><div className="rounded-xl border border-neutral-800 bg-[#0b0e0e] p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-neutral-300"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Detection & evidence</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label="Active scenario types" value={Number(m.active_case_types||0)} detail="Configured case taxonomy"/><Stat label="Detection rules" value={Number(m.enabled_detection_rules||0)} detail="Enabled event rules"/><Stat label="Evidence / decisions" value={`${Number(m.evidence_items||0)} / ${Number(m.decisions||0)}`} detail="Recorded canonical evidence / decisions"/></div><div className="mt-4 text-sm text-neutral-400">Overdue expected transitions: <b className="text-white">{Number(m.overdue_expected_transitions||0)}</b> · Policy overrides: <b className="text-white">{Number(m.policy_override_decisions||0)}</b> · Third-party recoveries: <b className="text-white">{Number(m.financial_recoveries||0)}</b></div></div>
   <div className="rounded-xl border border-neutral-800 bg-[#0b0e0e] p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-neutral-300"><WalletCards className="h-4 w-4 text-[#FA4616]"/>Capability evidence</div><div className="mt-4 space-y-3">{(data?.capabilities||[]).map(c=><div key={c.capability_key} className="rounded-lg border border-neutral-800 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm text-white">{c.capability_name}</b><span className="text-[10px] font-black uppercase tracking-wide text-neutral-400">{String(c.status||'unknown').replaceAll('_',' ')}</span></div><div className="mt-1 text-xs leading-5 text-neutral-500">{c.description||'No capability description recorded.'}</div></div>)}{!(data?.capabilities||[]).length&&!loading&&<div className="text-sm text-neutral-500">No URWS capability registry rows returned.</div>}</div></div></div>
  <div className={`mt-4 text-xs ${attention?'text-amber-300':'text-neutral-500'}`}>{attention?`${attention} URWS item(s) currently require attention.`:'No URWS exception/execution alerts are currently recorded.'} {data?.generatedAt?`Live read ${new Date(data.generatedAt).toLocaleTimeString()}.`:''}</div>
 </section>
}
