'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, ChevronRight, Database, LayoutDashboard, RefreshCw, Search, ShieldCheck, X } from 'lucide-react';

type Row = Record<string, any>;
type Command = { project: Row|null; milestones: Row[]; tasks: Row[]; raci: Row[]; units: Row[]; counts: Record<string,number|null>; generatedAt:string; source:string; error?:string };
type Milestone = Row & { id: string; code: string; name: string; status?: string };
type ComputedMilestone = Milestone & { implementation: number|null; operational: number|null; validation: number|null; tasks: Row[]; units: Row[] };

const descriptions:Record<string,string>={
 M01:'Tenant, organization, membership and core platform boundaries.',M02:'Person, user identity and authentication mapping.',M03:'Roles, permissions, assignments, scopes and hub access.',M04:'Staging, validation, identity resolution and controlled ingestion.',M05:'Organizations, teams, rosters, membership, programs, seasons, staff and communications.',M06:'Athlete master, development, performance, goals, records and trajectory.',M07:'Training plans, workouts, attendance, development and communication.',M08:'Family, approvals, registration, documents, payments and communication.',M09:'Organization administration, registrar, reporting, SafeSport and privacy.',M10:'Billing, invoices, payments, expenses, accounting and reporting.',M11:'Competition lifecycle, entries, results, officials, rules and publication.',M12:'Agent registry, permissions, recommendations, approvals, automation and execution.',M13:'Sport-neutral framework, adapters and cross-sport capability.',M14:'Security, observability, recovery, testing, deployment and release gates.'
};
function Panel({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#090b0b] p-6 ${className}`}>{children}</section>}
function Evidence({label,value,detail}:{label:string;value:React.ReactNode;detail:string}){return <div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[8px] font-black uppercase tracking-[.18em] text-neutral-500">{label}</div><div className="mt-2 text-xl font-black text-white">{value}</div><div className="mt-1 text-[10px] leading-4 text-neutral-400">{detail}</div></div>}
function Drawer({title,eyebrow,children,onClose}:{title:string;eyebrow:string;children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50"><button aria-label="Close drawer" className="absolute inset-0 bg-black/70" onClick={onClose}/><aside className="absolute right-0 top-0 h-full w-full max-w-[620px] overflow-y-auto border-l border-neutral-800 bg-[#080a0a] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-neutral-800 bg-[#080a0a]/95 px-6 py-5 backdrop-blur"><div><div className="text-[8px] font-black uppercase tracking-[.22em] text-emerald-400">{eyebrow}</div><h2 className="mt-1 text-xl font-black text-white">{title}</h2></div><button aria-label="Close" onClick={onClose} className="rounded-lg border border-neutral-800 p-2 text-neutral-400 hover:text-white"><X className="h-4 w-4"/></button></div><div className="space-y-5 p-6">{children}</div></aside></div>}

export default function SuperUserWorkspace(){
 const [data,setData]=useState<Command|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[view,setView]=useState('command-center'),[query,setQuery]=useState(''),[drawer,setDrawer]=useState<ComputedMilestone|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/superuser-command',{cache:'no-store'});const j=await r.json();setData(j);setError(j.error||'')}catch(e){setError(e instanceof Error?e.message:'SuperUser command unavailable')}finally{setLoading(false)}},[]);
 useEffect(()=>{const sync=()=>setView(new URLSearchParams(window.location.search).get('view')||'command-center');sync();window.addEventListener('popstate',sync);const t=setInterval(load,15000);void load();return()=>{window.removeEventListener('popstate',sync);clearInterval(t)}},[load]);
 const tasks=data?.tasks??[],units=data?.units??[],milestones=(data?.milestones??[]) as Milestone[];
 const computed=useMemo<ComputedMilestone[]>(()=>milestones.map((m)=>{const ts=tasks.filter(t=>t.milestone_id===m.id),us=units.filter(u=>u.milestone_id===m.id);const implementation=ts.length?Math.round(ts.reduce((s,t)=>s+Number(t.percent_complete||0),0)/ts.length):null;const operationalEvidence=ts.filter(t=>Number(t.evidence?.operational_percent)>=0);const validationEvidence=ts.filter(t=>Number(t.evidence?.validation_percent)>=0);const operational=operationalEvidence.length?Math.round(operationalEvidence.reduce((s,t)=>s+Number(t.evidence?.operational_percent||0),0)/operationalEvidence.length):null;const validation=validationEvidence.length?Math.round(validationEvidence.reduce((s,t)=>s+Number(t.evidence?.validation_percent||0),0)/validationEvidence.length):null;return { ...m, implementation, operational, validation, tasks:ts, units:us };}),[milestones,tasks,units]);
 const measured=computed.filter(m=>m.implementation!==null),overall=measured.length?Math.round(measured.reduce((s,m)=>s+(m.implementation||0),0)/measured.length):0,filtered=computed.filter(m=>!query||`${m.code} ${m.name} ${descriptions[m.code]||''}`.toLowerCase().includes(query.toLowerCase()));
 const title=view==='project-map'?'Master EAM / ERP Project Map':view==='milestones'?'14 Milestones':view==='metrics'?'Live Core Metrics':'LS1Sports EAM / ERP Project Command';
 const open=(m:ComputedMilestone)=>setDrawer(m);
 const selected=drawer;
 return <div className="min-h-full w-full bg-[#050707] p-6 lg:p-8">
  <Panel><div className="flex flex-wrap items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.3em] text-emerald-400"><LayoutDashboard className="h-4 w-4"/>LS1Sports Platform Intelligence</div><h1 className="mt-4 text-3xl font-black tracking-tight text-white">{title}</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-neutral-400">Live implementation state from LS1SportsEAM Supabase. Implementation, operational readiness and validation are separate signals; unknown evidence is never turned into a guessed percentage.</p></div><div className="min-w-[230px] rounded-2xl border border-neutral-800 bg-[#0d1010] p-5"><div className="text-[8px] font-black uppercase tracking-[.2em] text-neutral-500">Portfolio implementation</div><div className="mt-2 text-4xl font-black text-white">{overall}%</div><div className="mt-2 text-[10px] text-neutral-400">{measured.length}/14 milestones measured</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-emerald-400" style={{width:`${overall}%`}}/></div></div></div></Panel>
  {error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-amber-900/50 bg-amber-950/20 px-4 py-3 text-xs text-amber-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}
  <div className="mt-6 space-y-6">
   {view==='command-center'&&<Panel><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-neutral-500">Master implementation control</div><h2 className="mt-1 text-xl font-black text-white">Project timeline</h2><p className="mt-2 text-xs text-neutral-400">Live project tasks mapped to the 14 milestones. Select any workstream for evidence.</p></div><button onClick={load} className="flex items-center gap-2 rounded-lg border border-neutral-800 px-3 py-2 text-xs text-neutral-300 hover:text-white"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div><div className="mt-6 space-y-3">{computed.map(m=><button key={m.id} onClick={()=>open(m)} className="grid w-full grid-cols-[190px_1fr_70px] items-center gap-4 rounded-xl border border-neutral-800 bg-[#0d1010] p-3 text-left hover:border-neutral-700"><div className="text-xs font-bold text-white">{m.code} · {m.name}</div><div className="h-3 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-emerald-400" style={{width:`${m.implementation??0}%`}}/></div><div className="text-right text-xs font-black text-white">{m.implementation===null?'—':`${m.implementation}%`}</div></button>)}</div></Panel>}
   {(view==='command-center'||view==='milestones')&&<Panel><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-neutral-500">Development</div><h2 className="mt-1 text-xl font-black text-white">14 Core Metrics</h2><p className="mt-2 text-xs text-neutral-400">Seven foundation + seven operations. Implementation is measured from live project tasks.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-neutral-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search milestones" className="w-64 rounded-lg border border-neutral-800 bg-[#0d1010] py-2 pl-9 pr-3 text-xs text-white outline-none placeholder:text-neutral-600"/></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{filtered.map(m=><button key={m.id} onClick={()=>open(m)} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-left hover:border-neutral-700"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-neutral-500">{m.status==='complete'?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:<Activity className="h-4 w-4 text-amber-400"/>}{m.status}</div><ChevronRight className="h-4 w-4 text-neutral-600"/></div><div className="mt-3 text-sm font-black text-white">{m.code} · {m.name}</div><div className="mt-3 grid grid-cols-3 gap-2"><Evidence label="Implemented" value={m.implementation===null?'—':`${m.implementation}%`} detail="Task evidence"/><Evidence label="Operational" value={m.operational===null?'—':`${m.operational}%`} detail="Executed workflow evidence"/><Evidence label="Validated" value={m.validation===null?'—':`${m.validation}%`} detail="Test/release evidence"/></div></button>)}</div></Panel>}
   {(view==='metrics'||view==='command-center')&&<Panel><div className="flex items-center gap-2"><Database className="h-4 w-4 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-neutral-500">Evidence</div><h2 className="text-xl font-black text-white">Live Core Metrics</h2></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{Object.entries(data?.counts||{}).map(([k,v])=><Evidence key={k} label={k.replaceAll('_',' ')} value={v??'—'} detail="Live Supabase record count"/>)}</div><div className="mt-4 text-[10px] text-neutral-500">Last refreshed {data?new Date(data.generatedAt).toLocaleString():'—'} · {data?.source||'LS1SportsEAM Supabase'}</div></Panel>}
   {view==='project-map'&&<Panel><div className="text-[9px] font-black uppercase tracking-[.22em] text-neutral-500">Architecture</div><h2 className="mt-1 text-xl font-black text-white">Master EAM / ERP Project Map</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[['MASTER DATA','Tenant · Organization · Person · Athlete · Teams · Programs · Seasons · Membership · Facilities'],['TRANSACTIONS','Registration · Scheduling · Competition · Finance · Documents · Compliance · Communications'],['PLATFORM SERVICES','Identity · Authorization · Security · Workflow · Rules · Audit · Search · Reporting · Data Quality'],['INTEGRATIONS','Hy-Tek · Payments · SSO · Timing Systems · Accounting · Storage · Governing Bodies'],['AI ORCHESTRATION','Agent Registry · Permissions · AI Actions · Recommendations · Human Approval · Execution Results'],['EAM / OPERATIONS','Facilities · Assets · Maintenance · Procurement · Payroll · Exceptions']].map(([a,b])=><div key={a} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-5"><div className="text-[9px] font-black tracking-[.2em] text-emerald-400">{a}</div><div className="mt-3 text-xs leading-6 text-neutral-300">{b}</div></div>)}</div></Panel>}
  </div>
  {selected&&<Drawer title={selected.name} eyebrow={`${selected.code} · live evidence`} onClose={()=>setDrawer(null)}><div className="grid grid-cols-3 gap-3"><Evidence label="Implemented" value={selected.implementation===null?'—':`${selected.implementation}%`} detail="Live project task evidence"/><Evidence label="Operational" value={selected.operational===null?'Not measured':`${selected.operational}%`} detail="Executed workflow evidence"/><Evidence label="Validated" value={selected.validation===null?'Not measured':`${selected.validation}%`} detail="Test/release evidence"/></div><Panel><div className="text-[9px] font-black uppercase tracking-[.18em] text-neutral-500">Scope</div><p className="mt-2 text-sm leading-6 text-neutral-300">{descriptions[selected.code]||'Milestone scope is defined by live project records.'}</p></Panel><Panel><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.18em] text-neutral-500"><ShieldCheck className="h-4 w-4"/>Implementation tasks</div><div className="mt-3 space-y-2">{selected.tasks.map((t:Row)=><div key={t.id} className="rounded-lg border border-neutral-800 bg-[#0d1010] p-3"><div className="flex justify-between gap-3"><span className="text-xs font-bold text-white">{t.code} · {t.name}</span><span className="text-xs font-black text-white">{t.percent_complete}%</span></div><div className="mt-1 text-[10px] text-neutral-400">{t.status} · {t.blocker||'No blocker recorded'}</div><pre className="mt-2 overflow-x-auto whitespace-pre-wrap text-[9px] text-neutral-400">{JSON.stringify(t.evidence||{},null,2)}</pre></div>)}</div></Panel><Panel><div className="text-[9px] font-black uppercase tracking-[.18em] text-neutral-500">RACI</div><div className="mt-3 space-y-2">{(data?.raci||[]).filter(r=>r.task_id&&selected.tasks.some((t:Row)=>t.id===r.task_id)).map((r:Row)=><div key={r.id} className="rounded-lg border border-neutral-800 p-3 text-xs text-neutral-300"><span className="font-black text-white">{r.responsibility}</span> · {r.notes||'Assigned in platform governance'}</div>)}</div></Panel></Drawer>}
 </div>
}
