'use client';

import { FormEvent, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Plus, Save, ShieldCheck } from 'lucide-react';

type Props = { view: string; onChanged?: () => void | Promise<void> };
type FormShape = Record<string, string>;

const RULE_VIEWS = new Set(['rules','business-rules','eligibility-rules','validation-rules','data-quality-rules']);
const INTEGRATION_VIEWS = new Set(['integrations','integration-connections','integration-mappings','integration-runs','integration-dead-letters']);
const AI_VIEWS = new Set(['agents','automation']);

function Field({ label, name, value, onChange, required = false, type = 'text', placeholder = '' }: { label: string; name: string; value: string; onChange: (name: string, value: string) => void; required?: boolean; type?: string; placeholder?: string }) {
  return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<input name={name} value={value} required={required} type={type} placeholder={placeholder} onChange={event => onChange(name, event.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60" /></label>;
}
function JsonField({ label, name, value, onChange }: { label: string; name: string; value: string; onChange: (name: string, value: string) => void }) {
  return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<textarea name={name} value={value} rows={5} onChange={event => onChange(name, event.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 font-mono text-[11px] normal-case tracking-normal text-white outline-none focus:border-emerald-500/60" /></label>;
}

export default function SuperUserDomainActions({ view, onChanged }: Props) {
  const kind = useMemo(() => RULE_VIEWS.has(view) ? 'rules' : INTEGRATION_VIEWS.has(view) ? 'integrations' : AI_VIEWS.has(view) ? 'ai' : null, [view]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [form, setForm] = useState<FormShape>({ code:'', name:'', domain:'', trigger_event:'', priority:'100', rule_definition:'{}', entity_type:'', field_name:'', severity:'error', rule_type:'expression', message_template:'', expression:'{}', integration_type:'api', direction:'inbound', transport:'https', source_system:'', contract_definition:'{}', system_code:'', provider:'', auth_method:'managed_secret', configuration:'{}', status:'configured', connection_id:'', source_field:'', target_field:'', transform_definition:'{}', record_id:'', lifecycle_status:'disabled', description:'', agent_type:'decision_support', policy_definition:'{}', tool_definition:'{}', automation_definition:'{}', trigger_type:'event' });
  if (!kind) return null;
  function change(name:string,value:string){setForm(current=>({...current,[name]:value}));}
  async function run(action:string,payload:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/superuser-domain-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Action failed.');setMessage(`${action.replaceAll('-',' ')} completed.`);await onChanged?.();return json;}catch(cause){setError(cause instanceof Error?cause.message:'Action failed.');return null;}finally{setBusy(false);}}
  function payloadFrom(event:FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget).entries());}
  const button='mt-4 w-full rounded-lg bg-emerald-400 px-3 py-2.5 text-xs font-black text-black disabled:opacity-50';
  const card='rounded-xl border border-neutral-800 bg-[#0d1010] p-4';

  return <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6">
    <div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">OPERATING CONTROLS</div><h2 className="mt-1 text-xl font-black text-white">{kind==='rules'?'Rules lifecycle':kind==='integrations'?'Integration lifecycle':'AI / Automation lifecycle'}</h2><p className="mt-2 text-xs leading-5 text-neutral-500">Authorized Super User mutations write canonical records and privileged audit evidence. Configuration payloads reject embedded credentials.</p></div></div>
    {error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}
    {message&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-4 py-3 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</div>}

    {kind==='ai'&&<div className="mt-6 grid gap-5 xl:grid-cols-3">
      <form onSubmit={e=>void run('create-ai-agent',payloadFrom(e))} className={card}><div className="mb-4 flex items-center gap-2 text-sm font-black text-white"><Plus className="h-4 w-4 text-emerald-400"/>Agent</div><div className="space-y-3"><Field label="Code" name="code" value={form.code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Agent type" name="agent_type" value={form.agent_type} onChange={change} required/><Field label="Description" name="description" value={form.description} onChange={change}/><JsonField label="Configuration JSON" name="configuration" value={form.configuration} onChange={change}/></div><button disabled={busy} className={button}>Create agent</button></form>
      <form onSubmit={e=>void run('create-ai-agent-policy',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Agent policy</div><div className="space-y-3"><Field label="Agent ID" name="record_id" value={form.record_id} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><JsonField label="Policy JSON" name="policy_definition" value={form.policy_definition} onChange={change}/></div><button disabled={busy} className={button}>Create policy</button></form>
      <form onSubmit={e=>void run('create-ai-agent-tool',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Agent tool</div><div className="space-y-3"><Field label="Agent ID" name="record_id" value={form.record_id} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><JsonField label="Tool JSON" name="tool_definition" value={form.tool_definition} onChange={change}/></div><button disabled={busy} className={button}>Create tool</button></form>
      <form onSubmit={e=>{const p=payloadFrom(e);void run('set-ai-agent-active',{id:p.record_id,active:p.lifecycle_status==='active'});}} className={`${card} xl:col-span-3`}><div className="text-sm font-black text-white">Agent lifecycle</div><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_220px_auto]"><Field label="Agent ID" name="record_id" value={form.record_id} onChange={change} required/><label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">State<select name="lifecycle_status" value={form.lifecycle_status} onChange={e=>change('lifecycle_status',e.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs text-white"><option value="active">Active</option><option value="disabled">Disabled</option></select></label><button disabled={busy} className="self-end rounded-lg border border-neutral-700 px-4 py-2.5 text-xs font-black text-white">Apply state</button></div></form>
      {view==='automation'&&<form onSubmit={e=>void run('create-automation-definition',payloadFrom(e))} className={`${card} xl:col-span-2`}><div className="mb-4 text-sm font-black text-white">Automation definition</div><div className="grid gap-3 md:grid-cols-2"><Field label="Code" name="code" value={form.code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Trigger type" name="trigger_type" value={form.trigger_type} onChange={change} required/><Field label="Description" name="description" value={form.description} onChange={change}/></div><div className="mt-3"><JsonField label="Definition JSON" name="automation_definition" value={form.automation_definition} onChange={change}/></div><button disabled={busy} className={button}>Create automation</button></form>}
    </div>}

    {kind==='rules'&&<div className="mt-6 grid gap-5 xl:grid-cols-3"><form onSubmit={e=>void run('create-business-rule',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Business rule</div><div className="space-y-3"><Field label="Code" name="code" value={form.code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Domain" name="domain" value={form.domain} onChange={change} required/><JsonField label="Rule JSON" name="rule_definition" value={form.rule_definition} onChange={change}/></div><button disabled={busy} className={button}>Create business rule</button></form><form onSubmit={e=>void run('create-validation-rule',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Validation rule</div><div className="space-y-3"><Field label="Code" name="code" value={form.code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Rule type" name="rule_type" value={form.rule_type} onChange={change} required/><JsonField label="Rule JSON" name="rule_definition" value={form.rule_definition} onChange={change}/></div><button disabled={busy} className={button}>Create validation rule</button></form><form onSubmit={e=>void run('create-data-quality-rule',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Data-quality rule</div><div className="space-y-3"><Field label="Rule code" name="rule_code" value={form.code} onChange={(_n,v)=>change('code',v)} required/><Field label="Entity type" name="entity_type" value={form.entity_type} onChange={change} required/><Field label="Description" name="description" value={form.message_template} onChange={(_n,v)=>change('message_template',v)} required/><JsonField label="Expression JSON" name="expression" value={form.expression} onChange={change}/></div><button disabled={busy} className={button}>Create data-quality rule</button></form></div>}

    {kind==='integrations'&&<div className="mt-6 grid gap-5 xl:grid-cols-3"><form onSubmit={e=>void run('create-integration-definition',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Integration definition</div><div className="space-y-3"><Field label="Code" name="code" value={form.code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Type" name="integration_type" value={form.integration_type} onChange={change}/><JsonField label="Contract JSON" name="contract_definition" value={form.contract_definition} onChange={change}/></div><button disabled={busy} className={button}>Create definition</button></form><form onSubmit={e=>void run('create-integration-connection',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Connection</div><div className="space-y-3"><Field label="System code" name="system_code" value={form.system_code} onChange={change} required/><Field label="Name" name="name" value={form.name} onChange={change} required/><Field label="Status" name="status" value={form.status} onChange={change}/><JsonField label="Configuration JSON" name="configuration" value={form.configuration} onChange={change}/></div><button disabled={busy} className={button}>Create connection</button></form><form onSubmit={e=>void run('create-integration-mapping',payloadFrom(e))} className={card}><div className="mb-4 text-sm font-black text-white">Mapping</div><div className="space-y-3"><Field label="Connection ID" name="connection_id" value={form.connection_id} onChange={change}/><Field label="Entity type" name="entity_type" value={form.entity_type} onChange={change} required/><Field label="Source field" name="source_field" value={form.source_field} onChange={change} required/><Field label="Target field" name="target_field" value={form.target_field} onChange={change} required/><JsonField label="Transform JSON" name="transform_definition" value={form.transform_definition} onChange={change}/></div><button disabled={busy} className={button}>Create mapping</button></form></div>}
  </section>;
}
