'use client';

import { useCallback,useEffect,useState } from 'react';
import { AlertTriangle,RefreshCw,ShieldCheck,WalletCards } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={metrics:Row;capabilities:Row[];generatedAt:string;source?:string;error?:string};
const money=(v:unknown)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number.isFinite(Number(v))?Number(v):0);
function Stat({label,value,detail,alert=false}:{label:string;value:string|number;detail:string;alert?:boolean}){return <div className={`rounded-xl border p-4 ${alert?'border-amber-500/35 bg-amber-500/10':'border-neutral-800 bg-[#0b0e0e]'}`}><div className="text-[10px] font-black uppercase tracking-[.14em] text-neutral-400">{label}</div><div className="mt-2 text-2xl font-black text-white">{value}</div><div className="mt-1 text-xs leading-5 text-neutral-500">{detail}</div></div>}
export default function SuperUserURWSCommand(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await authenticatedFetch('/api/superuser-urws',{cache:'no-store',credentials:'same-origin'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'URWS command data unavailable.');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'URWS command data unavailable.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>window.clearInterval(timer)},[load]);
 const m=data?.metrics||{};const attention=Number(m.urgent_or_critical_cases||0)+Number(m.overdue_expected_transitions||0)+Number(m.failed_financial_executions||0)+Number(m.approved_refund_requests_not_executed||0)+Number(m.pending_decision_second_approvals||0)+Number(m.open_travel_cases||0)+Number(m.open_facility_cases||0)+Number(m.open_workforce_cases||0)+Number(m.open_registration_cases||0)+Number(m.open_family_authority_cases||0)+Number(m.open_finance_cases||0)+Number(m.open_asset_cases||0)+Number(m.open_record_correction_cases||0)+Number(m.open_safeguarding_urws_cases||0)+Number(m.open_service_failure_cases||0);
 return <section className="rounded-2xl border border-neutral-800 bg-[#070909] p-5 lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-[#FA4616]"><AlertTriangle className="h-4 w-4"/>URWS · LIVE PLATFORM CONTROL</div><h2 className="mt-2 text-2xl font-black text-white">Ugly Real-World Scenarios</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-neutral-400">Live exception, policy, authority, financial-consequence and execution evidence. These are canonical database counts; zero means zero, not demo data, and no completion percentage is manufactured here.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-neutral-800 p-3 text-neutral-300"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
  {error&&<div className="mt-4 rounded-xl border border-red-900/50 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Open cases" value={Number(m.open_cases||0)} detail={`${Number(m.urgent_or_critical_cases||0)} urgent / critical`} alert={Number(m.urgent_or_critical_cases||0)>0}/><Stat label="Open case exposure" value={money(m.open_case_financial_impact)} detail={`${Number(m.open_financial_commitments||0)} open commitments`}/><Stat label="Awaiting execution" value={Number(m.approved_remedies_awaiting_execution||0)} detail={`${money(m.financial_amount_awaiting_completion)} authorized / executing`} alert={Number(m.approved_remedies_awaiting_execution||0)>0}/><Stat label="Execution failures" value={Number(m.failed_financial_executions||0)} detail={`${Number(m.financial_executions_in_progress||0)} currently executing`} alert={Number(m.failed_financial_executions||0)>0}/><Stat label="Approved refunds not executed" value={Number(m.approved_refund_requests_not_executed||0)} detail="Approval is deliberately separate from processed refund" alert={Number(m.approved_refund_requests_not_executed||0)>0}/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Second approvals pending" value={Number(m.pending_decision_second_approvals||0)} detail={`${Number(m.ready_decision_proposals||0)} governed proposal(s) ready to execute`} alert={Number(m.pending_decision_second_approvals||0)>0}/><Stat label="Open competition cases" value={Number(m.open_competition_cases||0)} detail="Entry exceptions and fee disputes" alert={Number(m.open_competition_cases||0)>0}/><Stat label="Competition fee commitments" value={Number(m.competition_financial_commitments||0)} detail="Canonical competition-entry fee commitments"/><Stat label="Competition unrecovered" value={money(m.competition_unrecovered_amount)} detail="Committed competition fees not yet recovered" alert={Number(m.competition_unrecovered_amount||0)>0}/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-3"><Stat label="Open travel cases" value={Number(m.open_travel_cases||0)} detail="Travel commitment exceptions currently open" alert={Number(m.open_travel_cases||0)>0}/><Stat label="Travel plans" value={Number(m.travel_plan_count||0)} detail="Canonical travel plans in the platform"/><Stat label="Guardian-required travelers" value={Number(m.guardian_required_travel_participants||0)} detail="Recorded participant requirement, not an inferred compliance failure"/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-3"><Stat label="Open facility cases" value={Number(m.open_facility_cases||0)} detail="Canonical facility disruption cases currently open" alert={Number(m.open_facility_cases||0)>0}/><Stat label="Active facility closures" value={Number(m.active_facility_closures||0)} detail="Recorded source closures not marked resolved/cancelled" alert={Number(m.active_facility_closures||0)>0}/><Stat label="Affected facility bookings" value={Number(m.facility_affected_bookings||0)} detail="Canonical bookings overlapping active closures; no inferred cancellations" alert={Number(m.facility_affected_bookings||0)>0}/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-3"><Stat label="Open workforce cases" value={Number(m.open_workforce_cases||0)} detail="Credential compliance cases currently open" alert={Number(m.open_workforce_cases||0)>0}/><Stat label="Lapsed staff credentials" value={Number(m.lapsed_staff_credentials||0)} detail="Canonical expired/lapsed credentials tied to staff assignments" alert={Number(m.lapsed_staff_credentials||0)>0}/><Stat label="Active staff assignments" value={Number(m.active_staff_assignments||0)} detail="Current canonical team staff assignments"/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Registration exceptions" value={Number(m.open_registration_cases||0)} detail="Open governed registration exceptions" alert={Number(m.open_registration_cases||0)>0}/><Stat label="Guardian authority cases" value={Number(m.open_family_authority_cases||0)} detail={`${Number(m.family_authority_restrictions_or_disputes||0)} canonical restricted/disputed/revoked assignments`} alert={Number(m.open_family_authority_cases||0)>0}/><Stat label="Finance disputes" value={Number(m.open_finance_cases||0)} detail="Billing, payment, hardship, chargeback and refund cases" alert={Number(m.open_finance_cases||0)>0}/><Stat label="Membership cases" value={Number(m.open_membership_cases||0)} detail="Pause, cancellation, exception and refund disputes" alert={Number(m.open_membership_cases||0)>0}/></div>
  <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Asset incidents" value={Number(m.open_asset_cases||0)} detail={`${Number(m.assets_requiring_attention||0)} canonical assets currently lost/damaged/missing/stolen/out of service`} alert={Number(m.open_asset_cases||0)>0}/><Stat label="Record corrections" value={Number(m.open_record_correction_cases||0)} detail={`${Number(m.pending_record_corrections||0)} requested/reviewing/approved corrections not yet fully applied`} alert={Number(m.open_record_correction_cases||0)>0}/><Stat label="Safeguarding URWS" value={Number(m.open_safeguarding_urws_cases||0)} detail={`${Number(m.open_restricted_urws_cases||0)} open restricted URWS case(s); restricted details are not rendered here`} alert={Number(m.open_safeguarding_urws_cases||0)>0}/><Stat label="Service failures" value={Number(m.open_service_failure_cases||0)} detail="Attendance and expected-service exception cases" alert={Number(m.open_service_failure_cases||0)>0}/></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.8fr]"><div className="rounded-xl border border-neutral-800 bg-[#0b0e0e] p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-neutral-300"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Detection & evidence</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label="Active scenario types" value={Number(m.active_case_types||0)} detail="Configured case taxonomy"/><Stat label="Detection rules" value={Number(m.enabled_detection_rules||0)} detail="Enabled event rules"/><Stat label="Evidence / decisions" value={`${Number(m.evidence_items||0)} / ${Number(m.decisions||0)}`} detail="Recorded canonical evidence / decisions"/></div><div className="mt-4 text-sm text-neutral-400">Overdue expected transitions: <b className="text-white">{Number(m.overdue_expected_transitions||0)}</b> · Policy overrides: <b className="text-white">{Number(m.policy_override_decisions||0)}</b> · Third-party recoveries: <b className="text-white">{Number(m.financial_recoveries||0)}</b></div></div>
   <div className="rounded-xl border border-neutral-800 bg-[#0b0e0e] p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-neutral-300"><WalletCards className="h-4 w-4 text-[#FA4616]"/>Capability evidence</div><div className="mt-4 space-y-3">{(data?.capabilities||[]).map(c=><div key={c.capability_key} className="rounded-lg border border-neutral-800 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm text-white">{c.capability_name}</b><span className="text-[10px] font-black uppercase tracking-wide text-neutral-400">{String(c.status||'unknown').replaceAll('_',' ')}</span></div><div className="mt-1 text-xs leading-5 text-neutral-500">{c.description||'No capability description recorded.'}</div></div>)}{!(data?.capabilities||[]).length&&!loading&&<div className="text-sm text-neutral-500">No URWS capability registry rows returned.</div>}</div></div></div>
  <div className={`mt-4 text-xs ${attention?'text-amber-300':'text-neutral-500'}`}>{attention?`${attention} URWS item(s) currently require attention.`:'No URWS exception/execution alerts are currently recorded.'} {data?.generatedAt?`Live read ${new Date(data.generatedAt).toLocaleTimeString()}.`:''}</div>
 </section>
}