'use client';

import { FormEvent, useState } from 'react';
import { AlertTriangle, CheckCircle2, Trophy } from 'lucide-react';

const VIEWS=new Set(['competition','competition-events','competition-entries','competition-results','competition-officials','competition-seeding','competition-timing','competition-rules','competition-reconciliation','competition-publication','competition-records','competition-imports']);
function Input({name,label,required=false,placeholder='',type='text'}:{name:string;label:string;required?:boolean;placeholder?:string;type?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<input name={name} required={required} placeholder={placeholder} type={type} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 text-xs normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
function Json({name,label,placeholder='{}'}:{name:string;label:string;placeholder?:string}){return <label className="block text-[10px] font-bold uppercase tracking-[.12em] text-neutral-500">{label}<textarea name={name} rows={4} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black px-3 py-2.5 font-mono text-[11px] normal-case tracking-normal text-white outline-none focus:border-emerald-500/60"/></label>}
export default function SuperUserCompetitionActions({view}:{view:string}){const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');if(!VIEWS.has(view))return null;async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setError('');setMessage('');try{const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch('/api/superuser-competition-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Competition action failed.');setMessage(`${action.replaceAll('-',' ')} completed and audited.`);event.currentTarget.reset();window.dispatchEvent(new CustomEvent('ls1sports:data-changed'));}catch(cause){setError(cause instanceof Error?cause.message:'Competition action failed.');}finally{setBusy(false)}}const card='rounded-xl border border-neutral-800 bg-[#0d1010] p-4';const primary='mt-4 w-full rounded-lg bg-emerald-400 px-3 py-2.5 text-xs font-black text-black disabled:opacity-50';const secondary='mt-4 w-full rounded-lg border border-neutral-700 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50';return <section className="rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 lg:p-6"><div className="flex items-start gap-3"><Trophy className="mt-0.5 h-5 w-5 text-emerald-400"/><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">COMPETITION TRUTH CONTROLS</div><h2 className="mt-1 text-xl font-black text-white">LS1Sports canonical competition chain</h2><p className="mt-2 text-xs leading-5 text-neutral-500">External systems verify LS1Sports; they do not define truth. Canonical promotion and publication remain gated by LS1 validation and resolved reconciliation evidence.</p></div></div>{error&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4"/>{error}</div>}{message&&<div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-4 py-3 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</div>}<div className="mt-6 grid gap-5 xl:grid-cols-3">
<form onSubmit={e=>void submit(e,'create-competition')} className={card}><div className="mb-4 text-sm font-black text-white">Competition</div><Input name="organization_id" label="Organization ID"/><Input name="sport_id" label="Sport ID"/><Input name="name" label="Name" required/><Input name="competition_type" label="Type"/><Input name="starts_at" label="Starts at"/><Input name="ends_at" label="Ends at"/><Input name="timezone" label="Timezone"/><Input name="city" label="City"/><Input name="region" label="Region"/><Input name="sanction_number" label="Sanction number"/><Input name="venue_facility_id" label="Venue facility ID"/><button disabled={busy} className={primary}>Create competition</button></form>
<form onSubmit={e=>void submit(e,'create-session')} className={card}><div className="mb-4 text-sm font-black text-white">Session</div><Input name="competition_id" label="Competition ID" required/><Input name="name" label="Session name" required/><Input name="session_no" label="Session number" type="number"/><Input name="starts_at" label="Starts at"/><Input name="ends_at" label="Ends at"/><button disabled={busy} className={primary}>Create session</button></form>
<form onSubmit={e=>void submit(e,'create-event')} className={card}><div className="mb-4 text-sm font-black text-white">Event</div><Input name="competition_id" label="Competition ID" required/><Input name="session_id" label="Session ID"/><Input name="code" label="Event code" required/><Input name="name" label="Event name" required/><Input name="sequence_no" label="Sequence" type="number"/><Json name="event_definition" label="Event definition JSON"/><button disabled={busy} className={primary}>Create event</button></form>
<form onSubmit={e=>void submit(e,'create-entry')} className={card}><div className="mb-4 text-sm font-black text-white">Entry</div><Input name="competition_event_id" label="Competition event ID" required/><Input name="athlete_id" label="Athlete ID"/><Input name="team_id" label="Team ID"/><Input name="seed_value" label="Seed value" type="number"/><Input name="seed_unit" label="Seed unit"/><button disabled={busy} className={primary}>Create pending entry</button></form>
<form onSubmit={e=>void submit(e,'record-eligibility-decision')} className={card}><div className="mb-4 text-sm font-black text-white">Eligibility decision</div><Input name="competition_id" label="Competition ID" required/><Input name="competition_entry_id" label="Entry ID"/><Input name="athlete_id" label="Athlete ID"/><Input name="rule_code" label="Rule code"/><Input name="decision" label="Decision" required/><Input name="severity" label="Severity"/><Input name="ruleset_id" label="Ruleset ID"/><Json name="evidence" label="Evidence JSON"/><button disabled={busy} className={primary}>Record eligibility evidence</button></form>
<form onSubmit={e=>void submit(e,'create-seeding-run')} className={card}><div className="mb-4 text-sm font-black text-white">Seeding run</div><Input name="competition_id" label="Competition ID" required/><Input name="competition_event_id" label="Event ID"/><Input name="run_no" label="Run number" type="number"/><Input name="algorithm_code" label="Algorithm code" required/><Json name="parameters" label="Parameters JSON"/><button disabled={busy} className={primary}>Create LS1 seeding run</button></form>
<form onSubmit={e=>void submit(e,'add-seeding-assignment')} className={card}><div className="mb-4 text-sm font-black text-white">Seeding assignment</div><Input name="seeding_run_id" label="Seeding run ID" required/><Input name="competition_entry_id" label="Entry ID" required/><Input name="heat_no" label="Heat" type="number"/><Input name="lane_no" label="Lane" type="number"/><Input name="seed_rank" label="Seed rank" type="number"/><Input name="seed_value" label="Seed value" type="number"/><Input name="seed_unit" label="Seed unit"/><Json name="rationale" label="Rationale JSON"/><button disabled={busy} className={primary}>Add assignment</button></form>
<form onSubmit={e=>void submit(e,'approve-seeding-run')} className={card}><div className="mb-4 text-sm font-black text-white">Approve seeding</div><Input name="id" label="Seeding run ID" required/><button disabled={busy} className={secondary}>Approve populated seeding run</button></form>
<form onSubmit={e=>void submit(e,'record-scratch')} className={card}><div className="mb-4 text-sm font-black text-white">Scratch request</div><Input name="competition_id" label="Competition ID" required/><Input name="competition_entry_id" label="Entry ID"/><Input name="athlete_id" label="Athlete ID"/><Input name="reason_code" label="Reason code"/><Input name="reason_text" label="Reason"/><Json name="audit_context" label="Audit context JSON"/><button disabled={busy} className={primary}>Record scratch</button></form>
<form onSubmit={e=>void submit(e,'approve-scratch')} className={card}><div className="mb-4 text-sm font-black text-white">Approve scratch</div><Input name="id" label="Scratch ID" required/><button disabled={busy} className={secondary}>Approve & sync entry</button></form>
<form onSubmit={e=>void submit(e,'record-checkin')} className={card}><div className="mb-4 text-sm font-black text-white">Check-in</div><Input name="competition_id" label="Competition ID" required/><Input name="session_id" label="Session ID"/><Input name="entry_id" label="Entry ID"/><Input name="athlete_id" label="Athlete ID"/><Input name="team_id" label="Team ID"/><Input name="checkin_type" label="Check-in type" placeholder="positive"/><Input name="notes" label="Notes"/><button disabled={busy} className={primary}>Record LS1 check-in</button></form>
<form onSubmit={e=>void submit(e,'record-result')} className={card}><div className="mb-4 text-sm font-black text-white">Independent LS1 result</div><Input name="competition_entry_id" label="Entry ID"/><Input name="athlete_id" label="Athlete ID"/><Input name="team_id" label="Team ID"/><Input name="result_value" label="Result value" type="number"/><Input name="result_unit" label="Unit"/><Input name="rank" label="Rank" type="number"/><Input name="status" label="Status" placeholder="provisional"/><button disabled={busy} className={primary}>Record non-canonical result</button></form>
<form onSubmit={e=>void submit(e,'revise-result')} className={card}><div className="mb-4 text-sm font-black text-white">Version result</div><Input name="id" label="Result ID" required/><Input name="result_value" label="Result value" type="number"/><Input name="result_unit" label="Unit"/><Input name="rank" label="Rank" type="number"/><Input name="status" label="Status"/><Input name="change_reason" label="Change reason" required/><button disabled={busy} className={secondary}>Create new result version</button></form>
<form onSubmit={e=>void submit(e,'set-result-validation')} className={card}><div className="mb-4 text-sm font-black text-white">LS1 validation state</div><Input name="id" label="Result ID" required/><Input name="validation_status" label="Validation status" required placeholder="validated"/><button disabled={busy} className={secondary}>Set validation state</button></form>
<form onSubmit={e=>void submit(e,'promote-canonical-result')} className={card}><div className="mb-4 text-sm font-black text-white">Canonical promotion</div><Input name="id" label="Result ID" required/><button disabled={busy} className={primary}>Promote only if proof gates pass</button></form>
<form onSubmit={e=>void submit(e,'start-reconciliation')} className={card}><div className="mb-4 text-sm font-black text-white">Parallel verification run</div><Input name="competition_id" label="Competition ID"/><Input name="source_system_id" label="External source system ID"/><Input name="source_artifact_id" label="Source artifact ID"/><Input name="reconciliation_type" label="Type" placeholder="parallel_verification"/><button disabled={busy} className={primary}>Start verification</button></form>
<form onSubmit={e=>void submit(e,'add-reconciliation-item')} className={card}><div className="mb-4 text-sm font-black text-white">Verification comparison</div><Input name="reconciliation_id" label="Reconciliation ID" required/><Input name="entity_type" label="Entity type" required/><Input name="source_record_key" label="External record key"/><Input name="canonical_entity_id" label="LS1 canonical entity ID"/><Input name="comparison_status" label="Comparison status" required/><Json name="source_payload" label="External payload"/><Json name="canonical_payload" label="LS1 payload"/><Json name="differences" label="Differences"/><button disabled={busy} className={primary}>Record comparison evidence</button></form>
<form onSubmit={e=>void submit(e,'resolve-reconciliation-item')} className={card}><div className="mb-4 text-sm font-black text-white">Resolve verification difference</div><Input name="id" label="Reconciliation item ID" required/><Json name="differences" label="Resolved evidence JSON"/><button disabled={busy} className={secondary}>Resolve with evidence</button></form>
<form onSubmit={e=>void submit(e,'approve-reconciliation')} className={card}><div className="mb-4 text-sm font-black text-white">Approve verification run</div><Input name="id" label="Reconciliation ID" required/><button disabled={busy} className={secondary}>Approve only when zero open differences</button></form>
<form onSubmit={e=>void submit(e,'create-judicial-case')} className={card}><div className="mb-4 text-sm font-black text-white">Judicial case</div><Input name="competition_id" label="Competition ID" required/><Input name="case_type" label="Case type" required/><Input name="entity_type" label="Entity type" required/><Input name="entity_id" label="Entity ID"/><Input name="summary" label="Summary"/><Input name="rule_reference" label="Rule reference"/><Json name="evidence" label="Evidence JSON"/><button disabled={busy} className={primary}>Open judicial case</button></form>
<form onSubmit={e=>void submit(e,'decide-judicial-case')} className={card}><div className="mb-4 text-sm font-black text-white">Judicial decision</div><Input name="id" label="Judicial case ID" required/><Input name="decision" label="Decision" required/><button disabled={busy} className={secondary}>Record decision</button></form>
<form onSubmit={e=>void submit(e,'publish-competition')} className={`${card} xl:col-span-2`}><div className="mb-4 text-sm font-black text-white">Publish verified competition output</div><div className="grid gap-3 sm:grid-cols-2"><Input name="competition_id" label="Competition ID" required/><Input name="publication_type" label="Publication type" required/><Input name="version_no" label="Version" type="number"/><Input name="content_ref" label="Content reference"/><Input name="checksum_sha256" label="Checksum SHA-256"/><Input name="supersedes_id" label="Supersedes publication ID"/></div><div className="mt-3"><Json name="payload" label="Publication payload JSON"/></div><button disabled={busy} className={primary}>Publish only after reconciliation gates pass</button></form>
</div></section>}
