'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, GitCommitHorizontal, RefreshCw, Rocket, ShieldCheck, X } from 'lucide-react';

type Row = Record<string, any>;
type Summary = { required:number; pass:number; fail:number; blocked:number; notRun:number; openDefects:number; certificationReady:boolean };
type Payload = { candidate:Row|null; verifications:Row[]; defects:Row[]; summary:Summary; runtime:{commitSha:string|null;branchName:string|null;deploymentId:string|null;environment:string|null}; error?:string };

function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#090b0b] p-5 ${className}`}>{children}</section>}
function shortSha(value:unknown){const s=String(value||'');return s?s.slice(0,12):'—'}
function tone(status:string){if(status==='CERTIFIED'||status==='PASS'||status==='CLOSED')return 'text-emerald-300';if(status==='FAIL'||status==='REJECTED'||status==='OPEN')return 'text-red-300';if(status==='BLOCKED'||status==='BUILD_FAILED'||status==='RETEST_REQUIRED')return 'text-amber-300';return 'text-neutral-300'}

export default function SuperUserReleaseCertification({full=false}:{full?:boolean}){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState<'checks'|'defects'|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/superuser-release',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Release ledger unavailable');setData(j)}catch(e){setError(e instanceof Error?e.message:'Release ledger unavailable')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const action=async(body:Record<string,unknown>)=>{setSaving(true);setError('');try{const r=await fetch('/api/superuser-release',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Release action failed');setData(j);return true}catch(e){setError(e instanceof Error?e.message:'Release action failed');return false}finally{setSaving(false)}};
 const candidate=data?.candidate,summary=data?.summary;
 const deploymentRecorded=Boolean(candidate?.deployment_id);
 const canCreate=Boolean(data?.runtime?.commitSha)&&!candidate;
 const certificationReady=Boolean(summary?.certificationReady&&deploymentRecorded);
 const blockers=useMemo(()=>{if(!summary)return[];const rows:string[]=[];if(!deploymentRecorded)rows.push('Deployment evidence not recorded');if(summary.notRun)rows.push(`${summary.notRun} required verification(s) not run`);if(summary.fail)rows.push(`${summary.fail} required verification(s) failed`);if(summary.blocked)rows.push(`${summary.blocked} required verification(s) blocked`);if(summary.openDefects)rows.push(`${summary.openDefects} unresolved defect(s)`);if(summary.required===0)rows.push('Required verification matrix has not been populated');return rows},[summary,deploymentRecorded]);
 return <>
  <Panel className="border-emerald-950/70">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.22em] text-emerald-400"><ShieldCheck className="h-4 w-4"/>Release certification</div><h2 className="mt-2 text-xl font-black text-white">Super User exact-SHA truth</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-neutral-500">Build/deployment status, required verification evidence and unresolved defects are kept separate. The database will reject certification until its gate is satisfied.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-lg border border-neutral-800 p-2 text-neutral-400 hover:text-white"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
   {error&&<div className="mt-4 flex items-start gap-2 rounded-xl border border-red-900/50 bg-red-950/20 p-3 text-xs text-red-200"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>{error}</div>}
   {!candidate&&!loading&&<div className="mt-5 rounded-xl border border-dashed border-neutral-800 p-5"><div className="text-sm font-bold text-white">No active Super User release candidate</div><div className="mt-1 text-xs text-neutral-500">{data?.runtime?.commitSha?`Deployed SHA ${shortSha(data.runtime.commitSha)} can be registered as the next candidate.`:'The next deliberate deployment will provide the exact Vercel commit SHA.'}</div>{canCreate&&<button disabled={saving} onClick={()=>void action({action:'create-candidate'})} className="mt-4 rounded-lg bg-emerald-400 px-4 py-2 text-xs font-black text-black">Create candidate from deployed SHA</button>}</div>}
   {candidate&&<><div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-600">Commit</div><div className="mt-2 flex items-center gap-2 font-mono text-sm font-bold text-white"><GitCommitHorizontal className="h-4 w-4 text-emerald-400"/>{shortSha(candidate.commit_sha)}</div><div className="mt-1 text-[10px] text-neutral-600">{candidate.branch_name}</div></div><div className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-600">State</div><div className={`mt-2 text-sm font-black ${tone(String(candidate.status))}`}>{candidate.status}</div><div className="mt-1 text-[10px] text-neutral-600">{candidate.deployment_id?'Deployment recorded':'No deployment evidence'}</div></div><button onClick={()=>setDrawer('checks')} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-left hover:border-neutral-600"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-600">Required checks</div><div className="mt-2 text-2xl font-black text-white">{summary?.pass||0}/{summary?.required||0}</div><div className="mt-1 flex items-center gap-1 text-[10px] text-emerald-400">Open evidence <ChevronRight className="h-3 w-3"/></div></button><button onClick={()=>setDrawer('defects')} className="rounded-xl border border-neutral-800 bg-[#0d1010] p-4 text-left hover:border-neutral-600"><div className="text-[9px] uppercase tracking-[.18em] text-neutral-600">Open defects</div><div className="mt-2 text-2xl font-black text-white">{summary?.openDefects||0}</div><div className="mt-1 flex items-center gap-1 text-[10px] text-emerald-400">Open ledger <ChevronRight className="h-3 w-3"/></div></button></div>
   {blockers.length>0&&<div className="mt-4 rounded-xl border border-amber-900/40 bg-amber-950/10 p-4"><div className="text-[9px] font-black uppercase tracking-[.18em] text-amber-300">Outstanding before certification</div><div className="mt-2 flex flex-wrap gap-2">{blockers.map(b=><span key={b} className="rounded-full border border-amber-900/50 px-2.5 py-1 text-[10px] text-amber-200">{b}</span>)}</div></div>}
   {full&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={saving||!certificationReady||candidate.status==='CERTIFIED'} onClick={()=>void action({action:'certify',candidateId:candidate.id,reason:'All required Super User release gates satisfied.'})} className="inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-4 py-2 text-xs font-black text-black disabled:cursor-not-allowed disabled:opacity-30"><Rocket className="h-4 w-4"/>{candidate.status==='CERTIFIED'?'Certified':'Certify exact SHA'}</button><div className="self-center text-[10px] text-neutral-600">Certification is database-gated; this button cannot override failed evidence.</div></div>}</>}
  </Panel>
  {drawer&&<div className="fixed inset-0 z-[120] bg-black/70" onMouseDown={()=>setDrawer(null)}><aside className="absolute right-0 top-0 h-full w-full max-w-3xl overflow-y-auto border-l border-neutral-800 bg-[#080a0a] p-6" onMouseDown={e=>e.stopPropagation()}><div className="mb-6 flex items-start justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-400">Release evidence</div><h2 className="mt-1 text-2xl font-black text-white">{drawer==='checks'?'Required verifications':'Defect ledger'}</h2></div><button onClick={()=>setDrawer(null)} className="rounded-lg border border-neutral-800 p-2 text-neutral-400"><X className="h-4 w-4"/></button></div>{drawer==='checks'?<div className="space-y-3">{(data?.verifications||[]).length?(data?.verifications||[]).map(v=><Panel key={v.id}><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-neutral-600">{v.category} · {v.test_key}</div><div className="mt-1 text-sm font-bold text-white">{v.route_path||v.workflow_key||'Platform control'}</div></div><span className={`text-xs font-black ${tone(String(v.result))}`}>{v.result}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2"><div><div className="text-[9px] uppercase text-neutral-600">Expected</div><div className="mt-1 text-xs text-neutral-300">{v.expected_result}</div></div><div><div className="text-[9px] uppercase text-neutral-600">Actual</div><div className="mt-1 text-xs text-neutral-300">{v.actual_result||'Not recorded'}</div></div></div><pre className="mt-3 overflow-auto whitespace-pre-wrap rounded-lg bg-black/30 p-3 text-[10px] text-neutral-500">{JSON.stringify(v.evidence||{},null,2)}</pre></Panel>):<div className="rounded-xl border border-dashed border-neutral-800 p-6 text-sm text-neutral-500">No verification matrix has been recorded for this candidate yet.</div>}</div>:<div className="space-y-3">{(data?.defects||[]).length?(data?.defects||[]).map(d=><Panel key={d.id}><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-neutral-600">{d.severity} · {d.defect_key}</div><div className="mt-1 text-sm font-bold text-white">{d.title}</div></div><span className={`text-xs font-black ${tone(String(d.status))}`}>{d.status}</span></div><p className="mt-3 text-xs leading-5 text-neutral-400">{d.description||'No description recorded.'}</p><div className="mt-3 text-[10px] text-neutral-600">Occurrences {d.occurrence_count} · resolution SHA {shortSha(d.resolution_commit_sha)}</div></Panel>):<div className="rounded-xl border border-dashed border-neutral-800 p-6 text-sm text-emerald-300"><CheckCircle2 className="mb-2 h-5 w-5"/>No defects recorded for this candidate.</div>}</div>}</aside></div>}
 </>
}
