import { NextRequest, NextResponse } from 'next/server';
import { requireSuperUser, SuperUserAuthError } from '@/lib/server/requireSuperUser';
import { superUserRest } from '@/lib/server/superUserRest';
import { writeAuditEvent } from '@/lib/server/writeAuditEvent';

export const dynamic='force-dynamic';export const revalidate=0;
type Row=Record<string,unknown>;
function req(value:unknown,label:string,max=500){const s=String(value||'').trim();if(!s)throw new Error(`${label} is required.`);if(s.length>max)throw new Error(`${label} is too long.`);return s}
function opt(value:unknown,max=4000){const s=String(value||'').trim();if(!s)return null;if(s.length>max)throw new Error('Value is too long.');return s}
function json(value:unknown,label:string,fallback:unknown={}){if(value===undefined||value===null||value==='')return fallback;if(typeof value==='object')return value;try{return JSON.parse(String(value))}catch{throw new Error(`${label} must be valid JSON.`)}}

export async function GET(request:NextRequest){try{const actor=await requireSuperUser(request);const rest=(path:string,init:RequestInit={})=>superUserRest<any>(actor,path,init);const operator=(await rest(`platform_superuser_operators?id=eq.${encodeURIComponent(actor.operatorId)}&select=id,email,display_name,person_id,profile&limit=1`))?.[0]||null;const canonicalProfile=actor.personId?(await rest(`people?id=eq.${encodeURIComponent(actor.personId)}&select=id,first_name,middle_name,last_name,preferred_name,email,phone,pronouns,status,privacy_classification&limit=1`))?.[0]||null:null;const operatorProfile=operator?.profile&&typeof operator.profile==='object'?operator.profile:{};const profile=canonicalProfile||{email:actor.email,...operatorProfile};const notifications=actor.personId?await rest(`notification_events?recipient_person_id=eq.${encodeURIComponent(actor.personId)}&select=*&order=created_at.desc&limit=100`):[];return NextResponse.json({operator:{id:actor.operatorId,email:actor.email,displayName:actor.displayName,personId:actor.personId,profileSource:canonicalProfile?'person':'operator'},profile,notifications:notifications||[]},{headers:{'Cache-Control':'no-store'}})}catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Unable to load account controls.'},{status:500})}}

export async function POST(request:NextRequest){try{const actor=await requireSuperUser(request);const rest=(path:string,init:RequestInit={})=>superUserRest<any>(actor,path,init);const tenant=async()=>(await rest('tenants?select=id&limit=1'))?.[0]?.id||null;const one=async(table:string,id:string)=>(await rest(`${table}?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0]||null;const body=await request.json() as Row;const action=String(body.action||'');const tenantId=await tenant();
if(action==='update-own-profile'){const fields=['first_name','middle_name','last_name','preferred_name','phone','pronouns'];if(actor.personId){const before=await one('people',actor.personId);if(!before)throw new Error('Linked person record not found.');const patch:Row={updated_at:new Date().toISOString()};for(const key of fields)if(body[key]!==undefined)patch[key]=String(body[key]||'').trim()||null;const after=(await rest(`people?id=eq.${encodeURIComponent(actor.personId)}`,{method:'PATCH',body:JSON.stringify(patch)}))?.[0];await writeAuditEvent(actor,{action:'SUPERUSER_PROFILE_UPDATED',entityType:'people',entityId:actor.personId,tenantId,beforeData:before,afterData:after,reason:'Super User updated own linked person profile'});return NextResponse.json({profile:after,profileSource:'person'})}const before=await one('platform_superuser_operators',actor.operatorId);if(!before)throw new Error('Operator record not found.');const current=(before.profile&&typeof before.profile==='object'?before.profile:{}) as Row;const profile:Row={...current};for(const key of fields)if(body[key]!==undefined)profile[key]=String(body[key]||'').trim()||null;const after=(await rest(`platform_superuser_operators?id=eq.${encodeURIComponent(actor.operatorId)}`,{method:'PATCH',body:JSON.stringify({profile,updated_at:new Date().toISOString()})}))?.[0];await writeAuditEvent(actor,{action:'SUPERUSER_OPERATOR_PROFILE_UPDATED',entityType:'platform_superuser_operators',entityId:actor.operatorId,tenantId,beforeData:{profile:before.profile||{}},afterData:{profile:after?.profile||profile},reason:'Platform-only Super User updated operator-local profile'});return NextResponse.json({profile:after?.profile||profile,profileSource:'operator'})}
if(action==='mark-notification-read'){if(!actor.personId)throw new Error('Notifications require a linked person record.');const id=req(body.id,'Notification ID',80),before=await one('notification_events',id);if(!before||String(before.recipient_person_id||'')!==actor.personId)return NextResponse.json({error:'Notification not found for this operator.'},{status:404});const after=(await rest(`notification_events?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()})}))?.[0];return NextResponse.json(after)}
if(action==='mark-all-notifications-read'){if(!actor.personId)throw new Error('Notifications require a linked person record.');const after=await rest(`notification_events?recipient_person_id=eq.${encodeURIComponent(actor.personId)}&read_at=is.null`,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()})});return NextResponse.json({updated:Array.isArray(after)?after.length:0})}
if(action==='create-knowledge-item'){const item=(await rest('knowledge_items',{method:'POST',body:JSON.stringify({tenant_id:tenantId,sport_id:body.sport_id||null,title:req(body.title,'Title',300),content:opt(body.content,20000),category:opt(body.category,100),sensitivity:req(body.sensitivity||'standard','Sensitivity',50),status:req(body.status||'published','Status',50),created_by:actor.personId})}))?.[0];await writeAuditEvent(actor,{action:'KNOWLEDGE_ITEM_CREATED',entityType:'knowledge_items',entityId:item?.id||null,tenantId,afterData:item||body,reason:'Super User authored knowledge/SOP content'});return NextResponse.json(item)}
if(action==='set-knowledge-status'){const id=req(body.id,'Knowledge item ID',80),before=await one('knowledge_items',id);if(!before)return NextResponse.json({error:'Knowledge item not found.'},{status:404});const after=(await rest(`knowledge_items?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:req(body.status,'Status',50)})}))?.[0];await writeAuditEvent(actor,{action:'KNOWLEDGE_STATUS_CHANGED',entityType:'knowledge_items',entityId:id,tenantId,beforeData:before,afterData:after,reason:'Super User changed knowledge/SOP lifecycle'});return NextResponse.json(after)}
if(action==='create-report-definition'){const item=(await rest('report_definitions',{method:'POST',body:JSON.stringify({tenant_id:tenantId,code:req(body.code,'Report code',80),name:req(body.name,'Report name',200),report_type:opt(body.report_type,100),query_definition:json(body.query_definition,'Query definition',{}),sensitivity:req(body.sensitivity||'standard','Sensitivity',50),status:'active'})}))?.[0];await writeAuditEvent(actor,{action:'REPORT_DEFINITION_CREATED',entityType:'report_definitions',entityId:item?.id||null,tenantId,afterData:item||body,reason:'Super User created report definition'});return NextResponse.json(item)}
if(action==='queue-report-run'){const report=await one('report_definitions',req(body.report_id,'Report ID',80));if(!report)return NextResponse.json({error:'Report definition not found.'},{status:404});if(String(report.status||'').toLowerCase()!=='active')throw new Error('Report definition must be active before execution.');const run=(await rest('report_runs',{method:'POST',body:JSON.stringify({report_id:report.id,requested_by:actor.personId,status:'running',started_at:new Date().toISOString(),row_count:0})}))?.[0];await writeAuditEvent(actor,{action:'REPORT_RUN_QUEUED',entityType:'report_runs',entityId:run?.id||null,tenantId,afterData:run||body,reason:'Super User queued report execution'});return NextResponse.json(run)}
if(action==='complete-report-run'){const id=req(body.id,'Report run ID',80),before=await one('report_runs',id);if(!before)return NextResponse.json({error:'Report run not found.'},{status:404});const after=(await rest(`report_runs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:req(body.status||'completed','Status',50),completed_at:new Date().toISOString(),output_location:opt(body.output_location,1000),row_count:Number(body.row_count||0)})}))?.[0];await writeAuditEvent(actor,{action:'REPORT_RUN_COMPLETED',entityType:'report_runs',entityId:id,tenantId,beforeData:before,afterData:after,reason:'Super User completed report run lifecycle'});return NextResponse.json(after)}
return NextResponse.json({error:'Unsupported support action.'},{status:400});}catch(error){if(error instanceof SuperUserAuthError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:'Support action failed.'},{status:400})}}
