import {NextRequest,NextResponse} from 'next/server';
import {AthleteAuthError,requireAthlete} from '@/lib/server/requireAthlete';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const enc=(v:string)=>encodeURIComponent(v);
const headers=(prefer='return=representation')=>({apikey:KEY!,Authorization:`Bearer ${KEY!}`,'Content-Type':'application/json',Accept:'application/json',Prefer:prefer});
async function rest(path:string,init:RequestInit={}){if(!KEY)throw new Error('Supabase server credentials are not configured.');const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Athlete engagement request returned ${r.status}: ${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function evidence(unitKeys:string[],eventType:string,payload:Record<string,unknown>){for(const unitKey of unitKeys){try{const rows=await rest(`platform_milestone_units?unit_key=eq.${enc(unitKey)}&select=id,evidence`);const row=rows?.[0];if(!row?.id)continue;const evidence={...(row.evidence||{}),runtimeEvidence:{lastObservedAt:new Date().toISOString(),lastEventType:eventType,...payload}};await rest(`platform_milestone_units?id=eq.${enc(row.id)}`,{method:'PATCH',body:JSON.stringify({evidence,evidence_source:'Runtime Athlete Experience',evidence_ref:eventType,verified_at:new Date().toISOString()})})}catch(error){console.error(`Athlete capability evidence failed for ${unitKey}`,error)}}}

export async function POST(request:NextRequest){try{const actor=await requireAthlete(request);const body=await request.json();const action=String(body.action||'');if(action!=='submit_feedback')throw new AthleteAuthError('Unsupported Athlete engagement action.',400);const athleteId=String(body.athleteId||actor.athleteId||'');if(!athleteId)throw new AthleteAuthError('Athlete identity is required.',400);if(!actor.isSuperUser&&actor.athleteId!==athleteId)throw new AthleteAuthError('Athletes may only submit feedback from their own Athlete record.',403);const category=String(body.category||'experience').trim().slice(0,80);const message=String(body.message||'').trim();const route=String(body.route||'/athlete').trim().slice(0,200);const rating=body.rating===null||body.rating===undefined||body.rating===''?null:Number(body.rating);if(message.length<5)throw new AthleteAuthError('Tell us a little more before submitting feedback.',400);if(message.length>2000)throw new AthleteAuthError('Feedback must be 2000 characters or less.',400);if(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))throw new AthleteAuthError('Rating must be between 1 and 5.',400);const athlete=(await rest(`athletes?id=eq.${enc(athleteId)}&select=id,person_id&limit=1`))?.[0];if(!athlete?.person_id)throw new AthleteAuthError('Canonical Athlete identity was not found.',404);const person=(await rest(`people?id=eq.${enc(String(athlete.person_id))}&select=tenant_id&limit=1`))?.[0];const saved=await rest('platform_events',{method:'POST',body:JSON.stringify({tenant_id:person?.tenant_id??null,event_type:'athlete.feedback.submitted',aggregate_type:'athlete',aggregate_id:athleteId,payload:{category,message,rating,route,actorUserId:actor.userId,personId:actor.personId,source:'athlete_hub'},processing_status:'pending'})});await evidence(['athlete_progressive_experience','team_athlete_experience_distribution'],'athlete.feedback.submitted',{athleteId,category,feedbackBackendVerified:true});return NextResponse.json({ok:true,id:saved?.[0]?.id??null,submittedAt:new Date().toISOString()})}catch(error){const status=error instanceof AthleteAuthError?error.status:500;return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Unable to submit Athlete feedback'},{status})}}
