import {NextRequest,NextResponse} from 'next/server';
import {CoachAuthError,requireCoach,type CoachIdentity} from '@/lib/server/requireCoach';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_ANON_KEY;
export const dynamic='force-dynamic';
export const revalidate=0;

function headers(actor:CoachIdentity,extra:HeadersInit={}){if(!KEY)throw new Error('Supabase access is not configured.');const h=new Headers(extra);h.set('apikey',KEY);h.set('Authorization',`Bearer ${actor.accessToken}`);h.set('Accept','application/json');if(!h.has('Content-Type'))h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');return h;}
async function rest<T>(actor:CoachIdentity,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:headers(actor,init.headers),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Coach load operation failed (${r.status}) ${t.slice(0,260)}`);return(t?JSON.parse(t):null)as T;}
function authError(e:unknown){if(e instanceof CoachAuthError)return NextResponse.json({error:e.message},{status:e.status});return null;}
function csv(ids:string[]){return ids.map(id=>`\"${id}\"`).join(',')}
function uniq<T>(items:T[]){return Array.from(new Set(items));}
function text(v:unknown,max=2000){return String(v??'').trim().slice(0,max)}
function uuid(v:unknown){const s=text(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null;}
async function teamsFor(actor:CoachIdentity){const assigned=uniq(actor.assignments.map(a=>a.team_id).filter(Boolean)as string[]);if(actor.isSuperUser)return rest<any[]>(actor,'teams?select=id,organization_id,name,status&status=eq.active&order=name.asc&limit=200');if(!assigned.length)return[];return rest<any[]>(actor,`teams?select=id,organization_id,name,status&id=in.(${csv(assigned)})&status=eq.active&order=name.asc`);}
function canUse(actor:CoachIdentity,team:any){return actor.isSuperUser||actor.assignments.some(a=>a.team_id===team.id||(!a.team_id&&a.organization_id===team.organization_id));}

export async function GET(request:NextRequest){
 try{
  const actor=await requireCoach(request),teams=await teamsFor(actor),requested=request.nextUrl.searchParams.get('team_id'),teamId=requested&&teams.some(t=>t.id===requested)?requested:(teams[0]?.id||null),team=teams.find(t=>t.id===teamId)||null;
  if(!team)return NextResponse.json({generatedAt:new Date().toISOString(),teams,selectedTeamId:null,policy:null,athletes:[],signals:[],dataQuality:{logs:0,datedLogs:0},source:'LS1 canonical training logs'});
  const policy=actor.personId?(await rest<any[]>(actor,`coach_training_load_policies?select=*&coach_person_id=eq.${encodeURIComponent(actor.personId)}&team_id=eq.${team.id}&limit=1`))[0]||null:null;
  const memberships=await rest<any[]>(actor,`team_memberships?select=athlete_id&team_id=eq.${team.id}&status=eq.active&limit=1000`),athleteIds=uniq(memberships.map(m=>m.athlete_id).filter(Boolean));
  const athletes=athleteIds.length?await rest<any[]>(actor,`athletes?select=id,person_id,athlete_number&id=in.(${csv(athleteIds)})&limit=1000`):[],personIds=uniq(athletes.map(a=>a.person_id).filter(Boolean));
  const people=personIds.length?await rest<any[]>(actor,`people?select=id,first_name,preferred_name,last_name&id=in.(${csv(personIds)})&limit=1000`):[],pmap=new Map<string,any>(people.map(p=>[String(p.id),p] as [string,any]));
  const athleteRows=athletes.map(a=>{const p=pmap.get(String(a.person_id));return{id:a.id,name:p?[p.preferred_name||p.first_name,p.last_name].filter(Boolean).join(' '):'Athlete',athleteNumber:a.athlete_number};});
  const plans=await rest<any[]>(actor,`training_plans?select=id&team_id=eq.${team.id}&limit=500`),planIds=plans.map(p=>p.id),sessions=planIds.length?await rest<any[]>(actor,`training_sessions?select=id,training_plan_id,attendance_session_id,title,total_load,total_distance,distance_unit&training_plan_id=in.(${csv(planIds)})&limit=3000`):[],sessionIds=sessions.map(s=>s.id),attendanceIds=uniq(sessions.map(s=>s.attendance_session_id).filter(Boolean));
  const attendance=attendanceIds.length?await rest<any[]>(actor,`attendance_sessions?select=id,session_date& id=in.(${csv(attendanceIds)})`.replace('& ', '&')):[],dateMap=new Map<string,string>(attendance.map(a=>[String(a.id),String(a.session_date)] as [string,string])),sessionDate=new Map<string,string>();for(const s of sessions){const d=s.attendance_session_id?dateMap.get(String(s.attendance_session_id)):undefined;if(d)sessionDate.set(String(s.id),d);}
  const logs=sessionIds.length&&athleteIds.length?await rest<any[]>(actor,`training_athlete_logs?select=id,training_session_id,athlete_id,participation_status,load,distance,rpe&training_session_id=in.(${csv(sessionIds)})&athlete_id=in.(${csv(athleteIds)})&limit=10000`):[];
  const today=new Date();today.setUTCHours(0,0,0,0);const shortDays=Number(policy?.short_window_days||7),longDays=Number(policy?.long_window_days||28),shortStart=new Date(today.getTime()-(shortDays-1)*86400000),longStart=new Date(today.getTime()-(longDays-1)*86400000);let datedLogs=0;
  const signals=athleteRows.map(athlete=>{const rows=logs.filter(l=>l.athlete_id===athlete.id).map(l=>({...l,date:sessionDate.get(String(l.training_session_id))||null})).filter(l=>l.date);datedLogs+=rows.length;const short=rows.filter(l=>new Date(`${l.date}T00:00:00Z`)>=shortStart),long=rows.filter(l=>new Date(`${l.date}T00:00:00Z`)>=longStart);const shortLoad=short.reduce((s,l)=>s+Number(l.load||0),0),longLoad=long.reduce((s,l)=>s+Number(l.load||0),0),shortAvg=shortLoad/shortDays,longAvg=longLoad/longDays,ratio=longAvg>0?shortAvg/longAvg:null;let signal='unconfigured';if(policy?.enabled){if(rows.length<Number(policy.min_logged_sessions||4)||ratio===null)signal='insufficient_data';else if(ratio>Number(policy.high_ratio))signal='higher_than_policy';else if(ratio<Number(policy.low_ratio))signal='lower_than_policy';else signal='within_policy';}return{athleteId:athlete.id,athleteName:athlete.name,shortWindowDays:shortDays,longWindowDays:longDays,shortSessions:short.length,longSessions:long.length,shortLoad,longLoad,shortAverage:Number(shortAvg.toFixed(2)),longAverage:Number(longAvg.toFixed(2)),ratio:ratio===null?null:Number(ratio.toFixed(3)),signal,lastLoggedOn:rows.map(r=>r.date).sort().at(-1)||null};});
  return NextResponse.json({generatedAt:new Date().toISOString(),source:'Canonical training_athlete_logs + dated training sessions; operational signal only, never medical diagnosis',teams,selectedTeamId:team.id,policy,athletes:athleteRows,signals,dataQuality:{logs:logs.length,datedLogs}},{headers:{'Cache-Control':'no-store, max-age=0'}});
 }catch(e){const auth=authError(e);if(auth)return auth;return NextResponse.json({error:e instanceof Error?e.message:'Training load intelligence unavailable.'},{status:500});}
}

export async function POST(request:NextRequest){
 try{
  const actor=await requireCoach(request);if(!actor.personId)return NextResponse.json({error:'A canonical Coach identity is required.'},{status:409});const body=await request.json(),teamId=uuid(body.team_id);if(!teamId)return NextResponse.json({error:'Team is required.'},{status:400});const teams=await teamsFor(actor),team=teams.find(t=>t.id===teamId);if(!team||!canUse(actor,team))return NextResponse.json({error:'Coach is not authorized for this team.'},{status:403});const shortWindow=Number(body.short_window_days),longWindow=Number(body.long_window_days),high=Number(body.high_ratio),low=Number(body.low_ratio),min=Number(body.min_logged_sessions);if(!Number.isInteger(shortWindow)||shortWindow<3||shortWindow>21||!Number.isInteger(longWindow)||longWindow<14||longWindow>90||longWindow<=shortWindow||!Number.isFinite(high)||high<=1||!Number.isFinite(low)||low<=0||low>=1||!Number.isInteger(min)||min<1||min>30)return NextResponse.json({error:'Invalid load monitoring policy.'},{status:400});const payload={organization_id:team.organization_id,team_id:team.id,coach_person_id:actor.personId,short_window_days:shortWindow,long_window_days:longWindow,high_ratio:high,low_ratio:low,min_logged_sessions:min,enabled:body.enabled!==false,rationale:text(body.rationale,3000)||null,updated_at:new Date().toISOString()};const existing=(await rest<any[]>(actor,`coach_training_load_policies?select=id&coach_person_id=eq.${actor.personId}&team_id=eq.${team.id}&limit=1`))[0];const row=existing?(await rest<any[]>(actor,`coach_training_load_policies?id=eq.${existing.id}`,{method:'PATCH',body:JSON.stringify(payload)}))[0]:(await rest<any[]>(actor,'coach_training_load_policies',{method:'POST',body:JSON.stringify(payload)}))[0];await rest(actor,'coach_decision_log',{method:'POST',body:JSON.stringify({organization_id:team.organization_id,coach_person_id:actor.personId,action:'COACH_TRAINING_LOAD_POLICY_SAVED',entity_type:'coach_training_load_policies',entity_id:row.id,decision:'active',after_data:row,reason:'Coach explicitly configured operational load-change thresholds',source:'coach_load'})});return NextResponse.json(row,{status:existing?200:201});
 }catch(e){const auth=authError(e);if(auth)return auth;return NextResponse.json({error:e instanceof Error?e.message:'Training load policy save failed.'},{status:500});}
}
