'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import { CheckCircle2,RefreshCw,WalletCards,XCircle } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
const money=(v:unknown,c='CAD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c||'CAD'}).format(Number.isFinite(Number(v))?Number(v):0);
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString('en-CA',{dateStyle:'medium',timeStyle:'short'}):'—';
export function AdminURWSExecutionWorkspace(){
 const[data,setData]=useState<{cases:Row[];remedies:Row[];decisions:Row[]}>({cases:[],remedies:[],decisions:[]});
 const[selectedCase,setSelectedCase]=useState(''); const[executions,setExecutions]=useState<Row[]>([]); const[refundRequests,setRefundRequests]=useState<Row[]>([]); const[payments,setPayments]=useState<Row[]>([]);
 const[working,setWorking]=useState(false); const[loading,setLoading]=useState(true); const[error,setError]=useState(''); const[notice,setNotice]=useState('');
 const[refundId,setRefundId]=useState(''); const[refundRequestId,setRefundRequestId]=useState(''); const[paymentId,setPaymentId]=useState(''); const[externalReference,setExternalReference]=useState(''); const[note,setNote]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await authenticatedFetch('/api/admin-urws',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load URWS execution context.');setData({cases:j.cases||[],remedies:j.remedies||[],decisions:j.decisions||[]});setSelectedCase(x=>x&&j.cases?.some((c:Row)=>c.id===x)?x:(j.cases?.[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Unable to load.')}finally{setLoading(false)}},[]);
 const loadExecutions=useCallback(async()=>{if(!selectedCase){setExecutions([]);setRefundRequests([]);setPayments([]);return}try{const r=await authenticatedFetch(`/api/admin-urws-execution?case_id=${encodeURIComponent(selectedCase)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load financial execution ledger.');setExecutions(j.dispositions||[]);setRefundRequests(j.refundRequests||[]);setPayments(j.payments||[]);setRefundRequestId(x=>x&&j.refundRequests?.some((rr:Row)=>rr.id===x)?x:(j.refundRequests?.find((rr:Row)=>!rr.resulting_refund_id)?.id||''));setPaymentId(x=>x&&j.payments?.some((p:Row)=>p.id===x)?x:(j.payments?.[0]?.id||''));const prepared=j.refundRequests?.find((rr:Row)=>rr.resulting_refund_id);if(prepared?.resulting_refund_id)setRefundId(String(prepared.resulting_refund_id));}catch(e){setError(e instanceof Error?e.message:'Unable to load financial execution ledger.')}},[selectedCase]);
 useEffect(()=>{void load()},[load]); useEffect(()=>{setRefundId('');setRefundRequestId('');setPaymentId('');void loadExecutions()},[loadExecutions]);
 const selected=data.cases.find(c=>c.id===selectedCase); const remedies=useMemo(()=>data.remedies.filter(r=>r.case_id===selectedCase),[data.remedies,selectedCase]);
 async function action(body:Row,ok:string){setWorking(true);setError('');setNotice('');try{const r=await authenticatedFetch('/api/admin-urws-execution',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Financial execution failed.');setNotice(ok);await Promise.all([load(),loadExecutions()]);return j}catch(e){setError(e instanceof Error?e.message:'Financial execution failed.');return null}finally{setWorking(false)}}
 async function prepareRefund(){const j=await action({action:'prepare-refund',refund_request_id:refundRequestId,payment_id:paymentId},'Canonical pending refund prepared. It is not processed yet.');if(j?.refundId)setRefundId(String(j.refundId));}
 return <main className="min-h-full bg-[#060707] p-5 text-white lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-sm font-black uppercase tracking-[.16em] text-[#FA4616]">URWS Financial Execution</div><h1 className="mt-2 text-3xl font-black">Approved is not processed.</h1><p className="mt-2 max-w-4xl text-neutral-300">This workspace separates authorized remedies from actual financial execution. A refund is first prepared against a real approved request and real source payment; it cannot be completed until the canonical refund record has actually been processed.</p></div><button onClick={()=>void Promise.all([load(),loadExecutions()])} className="inline-flex items-center gap-2 rounded-xl border border-neutral-700 px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
  {error&&<div className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-100">{error}</div>}{notice&&<div className="mt-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-100">{notice}</div>}
  <div className="mt-6 grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="rounded-2xl border border-neutral-800 bg-[#0b0d0d]"><div className="border-b border-neutral-800 p-4 font-black">URWS cases</div>{data.cases.map(c=><button key={c.id} onClick={()=>setSelectedCase(c.id)} className={`w-full border-b border-neutral-800 p-4 text-left ${selectedCase===c.id?'bg-[#FA4616]/10':''}`}><div className="font-black">{c.public_summary||c.case_type_code}</div><div className="mt-1 text-xs text-neutral-500">{String(c.status||'open').replaceAll('_',' ')} · {money(c.financial_impact,c.currency)}</div></button>)}</aside>
   <section className="space-y-5">{selected&&<div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="text-xs font-black uppercase tracking-wide text-neutral-500">Selected case</div><h2 className="mt-2 text-xl font-black">{selected.public_summary||selected.case_type_code}</h2><div className="mt-2 text-sm text-neutral-400">{selected.case_type_code?.replaceAll('_',' ')} · {selected.status}</div></div>}
    {selected?.subject_type==='membership'&&refundRequests.length>0&&<section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><h3 className="text-lg font-black">Prepare canonical refund</h3><p className="mt-2 text-sm text-neutral-400">Preparation creates a pending refund tied to an approved membership refund request and an invoice payment. It does not send money and does not mark the request processed.</p><div className="mt-4 grid gap-3 lg:grid-cols-2"><label className="text-xs font-black uppercase tracking-wide text-neutral-400">Approved refund request<select value={refundRequestId} onChange={e=>{setRefundRequestId(e.target.value);const rr=refundRequests.find(x=>x.id===e.target.value);setRefundId(String(rr?.resulting_refund_id||''))}} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black p-3 text-sm text-white"><option value="">Select approved request</option>{refundRequests.map(rr=><option key={rr.id} value={rr.id}>{money(rr.amount,rr.currency)} · {when(rr.requested_at)}{rr.resulting_refund_id?' · refund prepared':''}</option>)}</select></label><label className="text-xs font-black uppercase tracking-wide text-neutral-400">Source payment<select value={paymentId} onChange={e=>setPaymentId(e.target.value)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black p-3 text-sm text-white"><option value="">Select source payment</option>{payments.map(p=><option key={p.id} value={p.id}>{money(p.amount,p.currency)} · {p.payment_date||'date unavailable'} · {p.method||'method unavailable'} · {p.status||'unknown'}</option>)}</select></label></div><div className="mt-4 flex items-center gap-3"><button disabled={working||!refundRequestId||!paymentId||Boolean(refundRequests.find(x=>x.id===refundRequestId)?.resulting_refund_id)} onClick={()=>void prepareRefund()} className="rounded-lg bg-[#FA4616] px-4 py-2 text-sm font-black text-black disabled:opacity-40">Prepare pending refund</button>{refundId&&<span className="text-xs text-neutral-400">Canonical refund prepared: <span className="font-mono text-neutral-200">{refundId}</span></span>}</div></section>}
    <div className="grid gap-5 2xl:grid-cols-2"><section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><h3 className="text-lg font-black">Approved remedies</h3><div className="mt-4 space-y-3">{remedies.map(r=><div key={r.id} className="rounded-xl border border-neutral-800 p-4"><div className="flex justify-between gap-3"><div><b>{String(r.remedy_type||'remedy').replaceAll('_',' ')}</b><div className="mt-1 text-sm text-neutral-500">{money(r.amount,r.currency)} · {r.status}</div></div><WalletCards className="h-5 w-5 text-[#FA4616]"/></div><p className="mt-2 text-sm text-neutral-400">{r.description||'No description.'}</p>{r.status==='approved'&&<div className="mt-4 space-y-2">{r.remedy_type==='refund'&&<div className="rounded-lg border border-neutral-800 bg-black/40 p-3 text-xs text-neutral-400">{refundId?'Canonical pending refund is ready to enter execution.':'Prepare a canonical refund above before beginning execution.'}</div>}<input value={externalReference} onChange={e=>setExternalReference(e.target.value)} placeholder="Processor / accounting reference" className="w-full rounded-lg border border-neutral-700 bg-black p-2 text-sm"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Execution note" className="min-h-20 w-full rounded-lg border border-neutral-700 bg-black p-2 text-sm"/><button disabled={working||(r.remedy_type==='refund'&&!refundId.trim())} onClick={()=>void action({action:'begin',remedy_id:r.id,refund_id:refundId.trim()||null,payment_id:r.remedy_type==='refund'?paymentId||null:null,external_reference:externalReference.trim()||null,note:note.trim()||null},'Financial execution started.') } className="rounded-lg bg-[#FA4616] px-3 py-2 text-sm font-black text-black disabled:opacity-40">Begin execution</button></div>}</div>)}{!remedies.length&&<div className="text-sm text-neutral-500">No approved remedies for this case.</div>}</div></section>
     <section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><h3 className="text-lg font-black">Execution ledger</h3><div className="mt-4 space-y-3">{executions.map(d=><div key={d.id} className="rounded-xl border border-neutral-800 p-4"><div className="flex justify-between gap-3"><b>{String(d.disposition_type).replaceAll('_',' ')}</b><span className="text-xs font-black uppercase text-neutral-400">{d.status}</span></div><div className="mt-2 text-sm text-neutral-400">{money(d.amount,d.currency)} · started {when(d.execution_started_at||d.created_at)}</div>{d.refund_id&&<div className="mt-1 text-xs text-neutral-600">Refund {d.refund_id}</div>}{d.status==='executing'&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={working} onClick={()=>void action({action:'complete',disposition_id:d.id,success:true,external_reference:externalReference.trim()||null,note:note.trim()||null},'Financial execution completed.') } className="inline-flex items-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-sm font-black text-emerald-100"><CheckCircle2 className="h-4 w-4"/>Mark completed</button><button disabled={working} onClick={()=>void action({action:'complete',disposition_id:d.id,success:false,external_reference:externalReference.trim()||null,note:note.trim()||null},'Financial execution marked failed.') } className="inline-flex items-center gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm font-black text-red-100"><XCircle className="h-4 w-4"/>Mark failed</button></div>}</div>)}{!executions.length&&<div className="text-sm text-neutral-500">No execution records yet.</div>}</div></section></div>
   </section></div>
 </main>
}
export default AdminURWSExecutionWorkspace;
