'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import { AlertTriangle,ClipboardCheck,FileSearch,History,RefreshCw,ShieldCheck,WalletCards,X } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={cases:Row[];caseTypes:Row[];organizations:Row[];memberships:Row[];evidence:Row[];packets:Row[];decisions:Row[];obligations:Row[];remedies:Row[];history:Row[];canCase:boolean;canFinancialDecision:boolean;error?:string};
const empty:Payload={cases:[],caseTypes:[],organizations:[],memberships:[],evidence:[],packets:[],decisions:[],obligations:[],remedies:[],history:[],canCase:false,canFinancialDecision:false};
const money=(v:unknown,c='CAD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c||'CAD'}).format(Number.isFinite(Number(v))?Number(v):0);
const when=(v:unknown)=>{if(!v)return '—';const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-CA',{dateStyle:'medium',timeStyle:'short'})};
const date=(v:unknown)=>v?String(v).slice(0,10):'—';
function Pill({value}:{value:unknown}){const s=String(value||'unknown').toLowerCase();const cls=['resolved','closed','complete','completed','approved','eligible'].includes(s)?'border-emerald-500/30 bg-emerald-500/10 text-emerald-200':['escalated','overdue','declined','failed','outside_policy'].includes(s)?'border-red-500/30 bg-red-500/10 text-red-200':['under_review','pending','open','unassessed','requested'].includes(s)?'border-amber-500/30 bg-amber-500/10 text-amber-100':'border-neutral-700 bg-neutral-900 text-neutral-300';return <span className={`rounded-full border px-2.5 py-1 text-xs font-black uppercase tracking-wide ${cls}`}>{s.replaceAll('_',' ')}</span>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><h3 className="text-lg font-black">{title}</h3>{children}</section>}

export function AdminURWSWorkspace(){
 const[data,setData]=useState<Payload>(empty),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[evidenceText,setEvidenceText]=useState(''),[showNew,setShowNew]=useState(false),[membershipContext,setMembershipContext]=useState<Row|null>(null),[membershipLoading,setMembershipLoading]=useState(false);
 const[newCase,setNewCase]=useState({organization_id:'',case_type_code:'membership_refund_dispute',subject_type:'membership',subject_id:'',priority:'normal',public_summary:'',financial_impact:''});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await authenticatedFetch('/api/admin-urws',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load URWS.');setData({...empty,...j});setSelectedId(x=>x&&j.cases?.some((c:Row)=>c.id===x)?x:(j.cases?.[0]?.id||''));setNewCase(x=>({...x,organization_id:x.organization_id||j.organizations?.[0]?.id||'',case_type_code:j.caseTypes?.some((t:Row)=>t.code===x.case_type_code&&t.sensitivity==='standard')?x.case_type_code:(j.caseTypes?.find((t:Row)=>t.sensitivity==='standard')?.code||'service_failure')}));}catch(e){setError(e instanceof Error?e.message:'Unable to load URWS.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const selected=useMemo(()=>data.cases.find(c=>c.id===selectedId)||null,[data.cases,selectedId]);
 useEffect(()=>{let cancelled=false;async function go(){setMembershipContext(null);if(selected?.subject_type!=='membership'||!selected.subject_id)return;setMembershipLoading(true);try{const r=await authenticatedFetch(`/api/admin-urws?membership_id=${encodeURIComponent(selected.subject_id)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Membership context unavailable.');if(!cancelled)setMembershipContext(j.membership||null)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Membership context unavailable.')}finally{if(!cancelled)setMembershipLoading(false)}}void go();return()=>{cancelled=true}},[selected?.subject_id,selected?.subject_type]);
 const related=(arr:Row[])=>selected?arr.filter(r=>r.case_id===selected.id):[];const standardTypes=data.caseTypes.filter(t=>t.sensitivity==='standard');const membershipChoices=data.memberships.filter(m=>!newCase.organization_id||String(m.organization_id)===newCase.organization_id);
 async function act(body:Row,ok:string){setWorking(true);setError('');setMessage('');try{const r=await authenticatedFetch('/api/admin-urws',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'URWS action failed.');setMessage(ok);setEvidenceText('');await load();return j}catch(e){setError(e instanceof Error?e.message:'URWS action failed.');return null}finally{setWorking(false)}}
 async function submitCase(){if(!newCase.organization_id||!newCase.case_type_code||newCase.public_summary.trim().length<8){setError('Organization, scenario type, and a factual summary are required.');return}if(newCase.subject_type==='membership'&&!newCase.subject_id){setError('Select the membership this case concerns.');return}const j=await act({action:'create-case',...newCase,financial_impact:Number(newCase.financial_impact||0)},'URWS case opened.');if(j){setShowNew(false);if(j.record?.id)setSelectedId(j.record.id);setNewCase(x=>({...x,public_summary:'',financial_impact:''}))}}
 function selectMembership(id:string){const m=data.memberships.find(x=>x.id===id);setNewCase(x=>({...x,subject_id:id,organization_id:m?.organization_id||x.organization_id}))}
 const open=data.cases.filter(c=>!['resolved','closed','cancelled'].includes(String(c.status))).length,exposure=data.cases.reduce((s,c)=>s+Number(c.financial_impact||0),0),overdue=data.obligations.filter(o=>o.due_at&&new Date(o.due_at)<new Date()&&!['satisfied','cancelled'].includes(String(o.status))).length;
 return <main className="min-h-full bg-[#060707] p-5 text-white lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[.16em] text-[#FA4616]"><AlertTriangle className="h-5 w-5"/>Ugly Real-World Scenarios</div><h1 className="mt-2 text-3xl font-black">URWS Case Workspace</h1><p className="mt-2 max-w-4xl text-base leading-7 text-neutral-300">Policy → evidence → authority → exception → decision → consequence → automation → audit trail. No reconstructed memory, no fabricated evidence.</p></div><div className="flex gap-2">{data.canCase&&<button disabled={working} onClick={()=>setShowNew(true)} className="rounded-xl bg-[#FA4616] px-4 py-3 text-sm font-black">Open case</button>}<button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-neutral-700 px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>
  {showNew&&<section className="mt-5 rounded-2xl border border-[#FA4616]/35 bg-[#100c0a] p-5"><div className="flex justify-between gap-4"><div><div className="text-sm font-black uppercase tracking-[.12em] text-[#FA4616]">Open a canonical URWS case</div><p className="mt-1 text-sm text-neutral-400">Standard-sensitivity workflow only. Restricted scenarios route through dedicated controlled workflows.</p></div><button onClick={()=>setShowNew(false)} className="rounded-lg border border-neutral-700 p-2"><X className="h-4 w-4"/></button></div><div className="mt-5 grid gap-4 lg:grid-cols-2">
   <label className="text-sm font-bold">Organization<select value={newCase.organization_id} onChange={e=>setNewCase(x=>({...x,organization_id:e.target.value,subject_id:x.subject_type==='membership'?'':x.subject_id}))} className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3"><option value="">Select organization</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
   <label className="text-sm font-bold">Scenario type<select value={newCase.case_type_code} onChange={e=>setNewCase(x=>({...x,case_type_code:e.target.value}))} className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3">{standardTypes.map(t=><option key={t.code} value={t.code}>{t.name} · {t.domain}</option>)}</select></label>
   <label className="text-sm font-bold">Subject domain<select value={newCase.subject_type} onChange={e=>setNewCase(x=>({...x,subject_type:e.target.value,subject_id:''}))} className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3">{['membership','registration','finance','competition','travel','facility','workforce','record','organization'].map(v=><option key={v}>{v}</option>)}</select></label>
   <label className="text-sm font-bold">Priority<select value={newCase.priority} onChange={e=>setNewCase(x=>({...x,priority:e.target.value}))} className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3">{['low','normal','high','urgent'].map(v=><option key={v}>{v}</option>)}</select></label>
   {newCase.subject_type==='membership'&&<label className="text-sm font-bold lg:col-span-2">Membership<select value={newCase.subject_id} onChange={e=>selectMembership(e.target.value)} className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3"><option value="">Select membership</option>{membershipChoices.map(m=><option key={m.id} value={m.id}>{m.display_name}{m.membership_number?` · ${m.membership_number}`:''} · {String(m.status||'unknown').replaceAll('_',' ')}</option>)}</select></label>}
   <label className="text-sm font-bold lg:col-span-2">Public factual summary<textarea value={newCase.public_summary} onChange={e=>setNewCase(x=>({...x,public_summary:e.target.value}))} placeholder="What happened, without restricted medical/safeguarding details…" className="mt-2 min-h-24 w-full rounded-xl border border-neutral-700 bg-black p-3"/></label>
   <label className="text-sm font-bold">Known financial exposure<input value={newCase.financial_impact} onChange={e=>setNewCase(x=>({...x,financial_impact:e.target.value}))} inputMode="decimal" placeholder="0.00" className="mt-2 w-full rounded-xl border border-neutral-700 bg-black p-3"/></label>
  </div><div className="mt-5 flex justify-end"><button disabled={working||!newCase.organization_id||newCase.public_summary.trim().length<8||(newCase.subject_type==='membership'&&!newCase.subject_id)} onClick={()=>void submitCase()} className="rounded-xl bg-[#FA4616] px-5 py-3 text-sm font-black disabled:opacity-40">Create URWS case</button></div></section>}
  {error&&<div className="mt-5 rounded-xl border border-red-500/35 bg-red-500/10 p-4 text-red-100">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-500/35 bg-emerald-500/10 p-4 text-emerald-100">{message}</div>}
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><Panel title="Open cases"><div className="mt-2 text-3xl font-black">{open}</div></Panel><Panel title="Recorded exposure"><div className="mt-2 text-3xl font-black">{money(exposure)}</div></Panel><Panel title="Overdue obligations"><div className="mt-2 text-3xl font-black">{overdue}</div></Panel></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border border-neutral-800 bg-[#0b0d0d]"><div className="border-b border-neutral-800 p-4"><div className="font-black">Case queue</div><div className="mt-1 text-sm text-neutral-500">{data.cases.length} canonical case{data.cases.length===1?'':'s'}</div></div><div className="divide-y divide-neutral-800">{data.cases.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full p-4 text-left hover:bg-neutral-900 ${selectedId===c.id?'bg-[#FA4616]/10':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-black">{c.public_summary||c.case_type_code}</div><div className="mt-1 text-sm text-neutral-500">{c.case_type_code?.replaceAll('_',' ')} · {when(c.opened_at)}</div></div><Pill value={c.status}/></div></button>)}{!loading&&!data.cases.length&&<div className="p-6 text-neutral-400">No URWS cases exist. LS1 will not invent one.</div>}</div></aside>
   {selected?<section className="space-y-5"><Panel title={selected.public_summary||'URWS case'}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="text-xs font-black uppercase tracking-[.12em] text-neutral-500">{selected.subject_type} · {selected.case_type_code?.replaceAll('_',' ')}</div><Pill value={selected.status}/></div><div className="flex flex-wrap gap-4 text-sm text-neutral-400"><span>Opened {when(selected.opened_at)}</span><span>Financial impact {money(selected.financial_impact,selected.currency)}</span><span>Priority {selected.priority}</span><span>Policy <b className="text-neutral-200">{String(selected.policy_outcome||'unassessed').replaceAll('_',' ')}</b></span></div>{data.canCase&&<div className="mt-5 flex flex-wrap gap-2">{['under_review','escalated','resolved','closed'].map(s=><button key={s} disabled={working||selected.status===s} onClick={()=>void act({action:'set-status',case_id:selected.id,status:s},`Case moved to ${s.replaceAll('_',' ')}.`)} className="rounded-lg border border-neutral-700 px-3 py-2 text-sm font-bold disabled:opacity-40">{s.replaceAll('_',' ')}</button>)}</div>}</Panel>
    {selected.subject_type==='membership'&&<Panel title="Membership case history"><div className="mb-4 flex items-center gap-2 text-sm text-neutral-400"><History className="h-4 w-4 text-[#FA4616]"/>{membershipLoading?'Loading canonical membership history…':'Operational history only; restricted medical detail is intentionally excluded.'}</div>{membershipContext?<div className="grid gap-4 xl:grid-cols-2"><div className="rounded-xl border border-neutral-800 p-4"><div className="text-xs font-black uppercase tracking-wide text-neutral-500">Lifecycle / pauses</div><div className="mt-3 space-y-3">{(membershipContext.lifecycle_events||[]).map((e:Row)=><div key={e.id} className="border-b border-neutral-800 pb-3"><div className="flex justify-between gap-3"><b>{String(e.event_type||'event').replaceAll('_',' ')}</b><span className="text-xs text-neutral-500">{when(e.effective_at)}</span></div><p className="mt-1 text-sm text-neutral-400">{e.summary}</p></div>)}{(membershipContext.exceptions||[]).map((x:Row)=><div key={x.id} className="rounded-lg bg-neutral-900 p-3"><div className="flex justify-between gap-3"><b>{String(x.exception_type).replaceAll('_',' ')}</b><Pill value={x.status}/></div><div className="mt-2 text-xs text-neutral-400">Approved {date(x.approved_start_on)} → {date(x.approved_end_on)} · billing resumes {date(x.billing_resume_on)}</div></div>)}{!(membershipContext.lifecycle_events||[]).length&&!(membershipContext.exceptions||[]).length&&<div className="text-sm text-neutral-500">No lifecycle or exception evidence exists yet.</div>}</div></div><div className="rounded-xl border border-neutral-800 p-4"><div className="text-xs font-black uppercase tracking-wide text-neutral-500">Refund / policy evidence</div><div className="mt-3 space-y-3">{(membershipContext.refund_requests||[]).map((r:Row)=><div key={r.id} className="rounded-lg bg-neutral-900 p-3"><div className="flex justify-between gap-3"><b>{money(r.amount,r.currency)}</b><Pill value={r.status}/></div><div className="mt-2 text-xs text-neutral-400">Requested {when(r.requested_at)} · policy {String(r.policy_eligibility||'unassessed').replaceAll('_',' ')}</div></div>)}{(membershipContext.policy_acceptances||[]).map((a:Row)=><div key={a.id} className="border-b border-neutral-800 pb-3 text-sm"><b>Policy acceptance</b><div className="mt-1 text-neutral-500">Accepted {when(a.accepted_at)} · {String(a.acknowledgement_method||'electronic').replaceAll('_',' ')}</div></div>)}{!(membershipContext.refund_requests||[]).length&&!(membershipContext.policy_acceptances||[]).length&&<div className="text-sm text-neutral-500">No refund request or policy acceptance evidence exists yet.</div>}</div></div></div>:!membershipLoading&&<div className="text-sm text-neutral-500">No membership snapshot available.</div>}</Panel>}
    <div className="grid gap-5 2xl:grid-cols-2"><Panel title="Evidence"><div className="mt-4 space-y-3">{related(data.evidence).map(e=><div key={e.id} className="rounded-xl border border-neutral-800 p-4"><div className="flex justify-between gap-3"><b>{e.evidence_type?.replaceAll('_',' ')}</b><span className="text-xs text-neutral-500">{when(e.occurred_at)}</span></div><p className="mt-2 text-sm leading-6 text-neutral-300">{e.summary}</p></div>)}{!related(data.evidence).length&&<div className="text-neutral-500">No standard evidence recorded.</div>}</div>{(data.canCase||data.canFinancialDecision)&&<div className="mt-4"><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} placeholder="Record factual, non-sensitive evidence…" className="min-h-24 w-full rounded-xl border border-neutral-700 bg-black p-3 text-sm"/><button disabled={working||!evidenceText.trim()} onClick={()=>void act({action:'add-evidence',case_id:selected.id,summary:evidenceText,evidence_type:'admin_note'},'Evidence recorded.')} className="mt-2 rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-3 py-2 text-sm font-black text-cyan-100 disabled:opacity-40">Add evidence</button></div>}</Panel>
     <Panel title="Decision packet"><div className="mt-3 flex justify-end"><button disabled={working} onClick={()=>void act({action:'build-packet',case_id:selected.id},'Decision packet rebuilt from canonical records.')} className="rounded-lg border border-violet-500/30 bg-violet-500/10 px-3 py-2 text-sm font-black text-violet-100"><ClipboardCheck className="mr-2 inline h-4 w-4"/>Build packet</button></div>{related(data.packets)[0]?<div className="mt-4 space-y-3 text-sm"><div className="rounded-xl border border-neutral-800 p-4"><b>Recommendation</b><div className="mt-2 text-neutral-300">{related(data.packets)[0].recommendation||'No recommendation produced.'}</div><p className="mt-2 text-neutral-500">{related(data.packets)[0].recommendation_rationale}</p></div><div className="rounded-xl border border-neutral-800 p-4"><b>Missing evidence</b><pre className="mt-2 whitespace-pre-wrap text-neutral-400">{JSON.stringify(related(data.packets)[0].missing_evidence??[],null,2)}</pre></div></div>:<p className="mt-4 text-neutral-500">No packet has been generated yet.</p>}</Panel></div>
    <div className="grid gap-5 lg:grid-cols-3"><Panel title="Decisions"><div className="mt-3 space-y-2">{related(data.decisions).map(d=><div key={d.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/><Pill value={d.human_outcome||d.policy_outcome}/></div><p className="mt-2 text-neutral-400">{d.rationale||'No rationale shown.'}</p></div>)}{!related(data.decisions).length&&<div className="text-sm text-neutral-500">No decision recorded.</div>}</div></Panel><Panel title="Remedies"><div className="mt-3 space-y-2">{related(data.remedies).map(r=><div key={r.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><div className="flex justify-between gap-2"><b><WalletCards className="mr-1 inline h-4 w-4"/>{r.remedy_type?.replaceAll('_',' ')}</b><Pill value={r.status}/></div><div className="mt-2 text-neutral-400">{money(r.amount,r.currency)}</div></div>)}{!related(data.remedies).length&&<div className="text-sm text-neutral-500">No financial remedy recorded.</div>}</div></Panel><Panel title="Obligations"><div className="mt-3 space-y-2">{related(data.obligations).map(o=><div key={o.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><div className="flex justify-between gap-2"><b>{o.description||o.obligation_type}</b><Pill value={o.status}/></div><div className="mt-2 text-neutral-500">Due {when(o.due_at)}</div></div>)}{!related(data.obligations).length&&<div className="text-sm text-neutral-500">No obligations recorded.</div>}</div></Panel></div>
   </section>:<section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-10 text-center text-neutral-500">Select a URWS case.</section>}</div>
 </main>
}
export default AdminURWSWorkspace;
