'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import { Building2,CalendarClock,RefreshCw,TriangleAlert } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Row=Record<string,any>;
type Payload={facilities:Row[];closures:Row[];bookings:Row[];generated_at?:string;error?:string};
const empty:Payload={facilities:[],closures:[],bookings:[]};
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString('en-CA',{dateStyle:'medium',timeStyle:'short'}):'—';

export function AdminURWSFacilityWorkspace(){
 const[data,setData]=useState<Payload>(empty),[selectedFacilityId,setSelectedFacilityId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await authenticatedFetch('/api/admin-urws-facilities',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load facility disruption context.');const next={...empty,...j};setData(next);setSelectedFacilityId(x=>x&&next.facilities.some((f:Row)=>f.id===x)?x:(next.facilities[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Unable to load facility disruption context.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const facility=useMemo(()=>data.facilities.find(f=>f.id===selectedFacilityId)||null,[data.facilities,selectedFacilityId]);
 const closures=useMemo(()=>data.closures.filter(c=>c.facility_id===selectedFacilityId),[data.closures,selectedFacilityId]);
 const bookings=useMemo(()=>data.bookings.filter(b=>b.facility_id===selectedFacilityId),[data.bookings,selectedFacilityId]);
 const activeClosures=closures.filter(c=>!['cancelled','canceled','resolved','closed','completed','reopened'].includes(String(c.status||'').toLowerCase()));
 const affected=bookings.filter(b=>activeClosures.some(c=>new Date(b.starts_at)<new Date(c.ends_at)&&new Date(b.ends_at)>new Date(c.starts_at)&&!['cancelled','canceled'].includes(String(b.status||'').toLowerCase())));
 return <main className="min-h-full bg-[#060707] p-5 text-white lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[.16em] text-[#FA4616]"><TriangleAlert className="h-5 w-5"/>URWS Facilities</div><h1 className="mt-2 text-3xl font-black">Facility Disruption Control</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-neutral-300">Canonical facility closures automatically open URWS disruption cases. When the source closure is resolved, its linked URWS case resolves from the same canonical evidence. No disruption or financial consequence is invented.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-neutral-700 px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
  {error&&<div className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-100">{error}</div>}
  <div className="mt-6 grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border border-neutral-800 bg-[#0b0d0d]"><div className="border-b border-neutral-800 p-4"><div className="font-black">Facilities</div><div className="mt-1 text-sm text-neutral-500">{data.facilities.length} canonical facilit{data.facilities.length===1?'y':'ies'}</div></div>{data.facilities.map(f=><button key={f.id} onClick={()=>setSelectedFacilityId(f.id)} className={`w-full border-b border-neutral-800 p-4 text-left hover:bg-neutral-900 ${selectedFacilityId===f.id?'bg-[#FA4616]/10':''}`}><div className="font-black">{f.name}</div><div className="mt-1 text-xs text-neutral-500">{f.site_name||'Site not recorded'} · {String(f.status||'unknown').replaceAll('_',' ')}</div></button>)}{!loading&&!data.facilities.length&&<div className="p-6 text-sm text-neutral-500">No facilities exist. LS1 will not invent one.</div>}</aside>
   {facility?<section className="space-y-5"><section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-[#FA4616]"/><h2 className="text-xl font-black">{facility.name}</h2></div><div className="mt-2 text-sm text-neutral-400">{facility.facility_type||'Facility'} · {facility.site_name||'Site not recorded'} · {facility.timezone||'Timezone not recorded'}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-neutral-800 p-4"><div className="text-xs uppercase text-neutral-500">Active closures</div><div className="mt-2 text-2xl font-black">{activeClosures.length}</div></div><div className="rounded-xl border border-neutral-800 p-4"><div className="text-xs uppercase text-neutral-500">Affected bookings</div><div className="mt-2 text-2xl font-black">{affected.length}</div></div><div className="rounded-xl border border-neutral-800 p-4"><div className="text-xs uppercase text-neutral-500">Recorded bookings</div><div className="mt-2 text-2xl font-black">{bookings.length}</div></div></div></section>
    <section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><h3 className="text-lg font-black">Closure evidence</h3><div className="mt-4 space-y-3">{closures.map(c=><div key={c.id} className="rounded-xl border border-neutral-800 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{c.reason||'Facility closure'}</b><div className="mt-1 text-sm text-neutral-500">{when(c.starts_at)} → {when(c.ends_at)}</div></div><span className="text-xs font-black uppercase text-neutral-400">{String(c.status||'active').replaceAll('_',' ')}</span></div><div className="mt-2 text-xs text-neutral-500">{Number(c.affected_booking_count||0)} overlapping canonical booking(s)</div></div>)}{!closures.length&&<div className="text-sm text-neutral-500">No facility closures are recorded.</div>}</div></section>
    <section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-[#FA4616]"/><h3 className="text-lg font-black">Affected schedule evidence</h3></div><div className="mt-4 space-y-3">{affected.map(b=><div key={b.id} className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><b>Booking overlap</b><div className="mt-1 text-sm text-neutral-400">{when(b.starts_at)} → {when(b.ends_at)} · {String(b.status||'unknown').replaceAll('_',' ')}</div></div>)}{!affected.length&&<div className="text-sm text-neutral-500">No recorded bookings currently overlap an active closure.</div>}</div></section>
   </section>:<section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-10 text-center text-neutral-500">Select a facility.</section>}</div>
 </main>;
}
export default AdminURWSFacilityWorkspace;
