'use client';
import { useCallback,useEffect,useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';
type Row=Record<string,any>;type Area='programs'|'teams'|'seasons'|'membership';
const input='w-full rounded-lg border border-neutral-800 bg-black px-3 py-2 text-sm text-white outline-none focus:border-[#FA4616]';
const label='text-[10px] font-bold uppercase tracking-wider text-neutral-500';
const person=(r:Row)=>`${r.preferred_name||r.first_name||''} ${r.last_name||''}`.trim()||r.email||r.id;
export function AdminMasterDataActions({area,onChanged}:{area:Area;onChanged?:()=>void}){
 const[data,setData]=useState<any>({organizations:[],sports:[],programs:[],seasons:[],teams:[],people:[],governingBodies:[],memberships:[],canWrite:false});const[action,setAction]=useState(''),[form,setForm]=useState<Row>({}),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const load=useCallback(async()=>{try{const r=await authenticatedFetch('/api/admin-team-master',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load Admin master data.');setData(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load Admin master data.')}},[]);useEffect(()=>{void load()},[load]);
 if(!data.canWrite)return null;
 const select=(name:string,textLabel:string,rows:Row[],get:(r:Row)=>string)=><label><span className={label}>{textLabel}</span><select className={input} value={form[name]??''} onChange={e=>setForm(f=>({...f,[name]:e.target.value}))}><option value="">Select…</option>{rows.map(r=><option key={r.id} value={r.id}>{get(r)}</option>)}</select></label>;
 const field=(name:string,textLabel:string,type='text')=><label><span className={label}>{textLabel}</span><input className={input} type={type} value={form[name]??''} onChange={e=>setForm(f=>({...f,[name]:e.target.value}))}/></label>;
 const staticSelect=(name:string,textLabel:string,values:string[])=><label><span className={label}>{textLabel}</span><select className={input} value={form[name]??''} onChange={e=>setForm(f=>({...f,[name]:e.target.value}))}><option value="">Select…</option>{values.map(v=><option key={v} value={v}>{v}</option>)}</select></label>;
 const actions:Record<Area,Array<[string,string]>>={programs:[['create-program','Create program']],teams:[['create-team','Create team'],['set-team-status','Change team status']],seasons:[['create-season','Create season'],['set-season-status','Change season status']],membership:[['create-membership','Create membership'],['set-membership-status','Change membership status']]};
 const fields=()=>{if(action==='create-program')return <>{select('organization_id','Organization',data.organizations,r=>r.name)}{select('sport_id','Sport',data.sports,r=>r.name)}{field('code','Code')}{field('name','Name')}{field('program_type','Program type')}</>;if(action==='create-team')return <>{select('organization_id','Organization',data.organizations,r=>r.name)}{select('sport_id','Sport',data.sports,r=>r.name)}{select('program_id','Program',data.programs,r=>r.name)}{select('season_id','Season',data.seasons,r=>r.name)}{field('code','Code')}{field('name','Name')}{field('competitive_level','Competitive level')}</>;if(action==='set-team-status')return <>{select('id','Team',data.teams,r=>`${r.name} · ${r.status}`)}{staticSelect('status','Status',['active','inactive','closed'])}{field('reason','Reason')}</>;if(action==='create-season')return <>{select('organization_id','Organization',data.organizations,r=>r.name)}{select('sport_id','Sport',data.sports,r=>r.name)}{field('code','Code')}{field('name','Name')}{field('starts_on','Starts','date')}{field('ends_on','Ends','date')}</>;if(action==='set-season-status')return <>{select('id','Season',data.seasons,r=>`${r.name} · ${r.status}`)}{staticSelect('status','Status',['planned','active','closed','cancelled'])}{field('reason','Reason')}</>;if(action==='create-membership')return <>{select('organization_id','Organization',data.organizations,r=>r.name)}{select('person_id','Person',data.people,person)}{select('sport_id','Sport',data.sports,r=>r.name)}{select('governing_body_id','Governing body',data.governingBodies,r=>r.name)}{field('membership_number','Membership #')}{field('membership_type','Type')}{field('starts_on','Starts','date')}{field('ends_on','Ends','date')}</>;if(action==='set-membership-status')return <>{select('id','Membership',data.memberships,r=>`${r.membership_number||r.id} · ${r.status}`)}{staticSelect('status','Status',['active','inactive','suspended','expired','cancelled'])}{field('ends_on','Ends','date')}{field('reason','Reason')}</>;return null};
 const submit=async()=>{setSaving(true);setError('');setSuccess('');try{const r=await authenticatedFetch('/api/admin-team-master',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...form})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Admin action failed.');setSuccess('Saved. Audit evidence recorded.');setForm({});await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Admin action failed.')}finally{setSaving(false)}};
 return <section className="mb-5 rounded-2xl border border-neutral-800 bg-[#090b0b] p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-4 w-4 text-[#FA4616]"/>Governed Admin action</div><select className={input} value={action} onChange={e=>{setAction(e.target.value);setForm({});setError('');setSuccess('')}}><option value="">Choose an action…</option>{actions[area].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>{action&&<><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{fields()}</div><button disabled={saving} onClick={()=>void submit()} className="mt-4 rounded-lg bg-[#FA4616] px-4 py-2 text-sm font-black text-black disabled:opacity-50">{saving?'Saving…':'Save & audit'}</button></>}{success&&<div className="mt-3 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-300">{success}</div>}{error&&<div className="mt-3 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}</section>
}
