'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import { AlertTriangle,ClipboardCheck,FileSearch,RefreshCw,ShieldCheck,WalletCards } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';
type Row=Record<string,any>; type Payload={cases:Row[];evidence:Row[];packets:Row[];decisions:Row[];obligations:Row[];remedies:Row[];history:Row[];canCase:boolean;canFinancialDecision:boolean;error?:string};
const empty:Payload={cases:[],evidence:[],packets:[],decisions:[],obligations:[],remedies:[],history:[],canCase:false,canFinancialDecision:false};
function money(v:unknown,c='CAD'){const n=Number(v||0);return new Intl.NumberFormat('en-CA',{style:'currency',currency:c||'CAD'}).format(Number.isFinite(n)?n:0)}
function when(v:unknown){if(!v)return '—';const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-CA',{dateStyle:'medium',timeStyle:'short'})}
function Pill({value}:{value:unknown}){const s=String(value||'unknown').toLowerCase();const cls=['resolved','closed','complete','completed','approved'].includes(s)?'border-emerald-500/30 bg-emerald-500/10 text-emerald-200':['escalated','overdue','declined','failed'].includes(s)?'border-red-500/30 bg-red-500/10 text-red-200':['under_review','pending','open'].includes(s)?'border-amber-500/30 bg-amber-500/10 text-amber-100':'border-neutral-700 bg-neutral-900 text-neutral-300';return <span className={`rounded-full border px-2.5 py-1 text-xs font-black uppercase tracking-wide ${cls}`}>{s.replaceAll('_',' ')}</span>}
export function AdminURWSWorkspace(){
 const[data,setData]=useState<Payload>(empty);const[selectedId,setSelectedId]=useState('');const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[evidenceText,setEvidenceText]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await authenticatedFetch('/api/admin-urws',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load URWS.');setData(j);setSelectedId(x=>x&&j.cases.some((c:Row)=>c.id===x)?x:(j.cases[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Unable to load URWS.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();},[load]);
 const selected=useMemo(()=>data.cases.find(c=>c.id===selectedId)||null,[data.cases,selectedId]);const related=(arr:Row[])=>selected?arr.filter(r=>r.case_id===selected.id):[];
 async function act(body:Row,ok:string){setWorking(true);setError('');setMessage('');try{const r=await authenticatedFetch('/api/admin-urws',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'URWS action failed.');setMessage(ok);setEvidenceText('');await load();}catch(e){setError(e instanceof Error?e.message:'URWS action failed.')}finally{setWorking(false)}}
 async function newCase(){const org=window.prompt('Organization UUID');if(!org)return;const summary=window.prompt('Public case summary');if(!summary)return;await act({action:'create-case',organization_id:org,case_type_code:'service_failure',subject_type:'membership',public_summary:summary},'URWS case opened.');}
 const open=data.cases.filter(c=>!['resolved','closed','cancelled'].includes(String(c.status))).length;const exposure=data.cases.reduce((s,c)=>s+Number(c.financial_impact||0),0);const overdue=data.obligations.filter(o=>o.due_at&&new Date(o.due_at)<new Date()&&!['satisfied','cancelled'].includes(String(o.status))).length;
 return <main className="min-h-full bg-[#060707] p-5 text-white lg:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[.16em] text-[#FA4616]"><AlertTriangle className="h-5 w-5"/>Ugly Real-World Scenarios</div><h1 className="mt-2 text-3xl font-black">URWS Case Workspace</h1><p className="mt-2 max-w-4xl text-base leading-7 text-neutral-300">Policy → evidence → authority → exception → decision → consequence → automation → audit trail. No reconstructed memory, no fabricated evidence.</p></div><div className="flex gap-2">{data.canCase&&<button disabled={working} onClick={()=>void newCase()} className="rounded-xl bg-[#FA4616] px-4 py-3 text-sm font-black text-white disabled:opacity-50">Open case</button>}<button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-neutral-700 px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>
  {error&&<div className="mt-5 rounded-xl border border-red-500/35 bg-red-500/10 p-4 text-red-100">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-500/35 bg-emerald-500/10 p-4 text-emerald-100">{message}</div>}
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="text-3xl font-black">{open}</div><div className="mt-1 text-sm font-black uppercase tracking-wide text-neutral-400">Open cases</div></div><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="text-3xl font-black">{money(exposure)}</div><div className="mt-1 text-sm font-black uppercase tracking-wide text-neutral-400">Recorded exposure</div></div><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="text-3xl font-black">{overdue}</div><div className="mt-1 text-sm font-black uppercase tracking-wide text-neutral-400">Overdue obligations</div></div></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-2xl border border-neutral-800 bg-[#0b0d0d]"><div className="border-b border-neutral-800 p-4"><div className="font-black">Case queue</div><div className="mt-1 text-sm text-neutral-500">{data.cases.length} canonical case{data.cases.length===1?'':'s'}</div></div><div className="divide-y divide-neutral-800">{data.cases.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full p-4 text-left hover:bg-neutral-900 ${selectedId===c.id?'bg-[#FA4616]/10':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-black">{c.public_summary||c.case_type_code}</div><div className="mt-1 text-sm text-neutral-500">{c.case_type_code?.replaceAll('_',' ')} · {when(c.opened_at)}</div></div><Pill value={c.status}/></div></button>)}{!loading&&!data.cases.length&&<div className="p-6 text-neutral-400">No URWS cases exist. LS1 will not invent one.</div>}</div></aside>
   {selected?<section className="space-y-5"><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.12em] text-neutral-500">{selected.subject_type} · {selected.case_type_code?.replaceAll('_',' ')}</div><h2 className="mt-1 text-2xl font-black">{selected.public_summary||'URWS case'}</h2><div className="mt-3 flex flex-wrap gap-4 text-sm text-neutral-400"><span>Opened {when(selected.opened_at)}</span><span>Financial impact {money(selected.financial_impact,selected.currency)}</span><span>Priority {selected.priority}</span></div></div><Pill value={selected.status}/></div>{data.canCase&&<div className="mt-5 flex flex-wrap gap-2">{['under_review','escalated','resolved','closed'].map(s=><button key={s} disabled={working||selected.status===s} onClick={()=>void act({action:'set-status',case_id:selected.id,status:s},`Case moved to ${s.replaceAll('_',' ')}.`)} className="rounded-lg border border-neutral-700 px-3 py-2 text-sm font-bold disabled:opacity-40">{s.replaceAll('_',' ')}</button>)}</div>}</div>
    <div className="grid gap-5 2xl:grid-cols-2"><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center gap-2 text-lg font-black"><FileSearch className="h-5 w-5 text-cyan-300"/>Evidence</div><div className="mt-4 space-y-3">{related(data.evidence).map(e=><div key={e.id} className="rounded-xl border border-neutral-800 p-4"><div className="flex justify-between gap-3"><b>{e.evidence_type?.replaceAll('_',' ')}</b><span className="text-xs text-neutral-500">{when(e.occurred_at)}</span></div><p className="mt-2 text-sm leading-6 text-neutral-300">{e.summary}</p></div>)}{!related(data.evidence).length&&<div className="text-neutral-500">No standard evidence recorded.</div>}</div>{(data.canCase||data.canFinancialDecision)&&<div className="mt-4"><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} placeholder="Record factual, non-sensitive evidence…" className="min-h-24 w-full rounded-xl border border-neutral-700 bg-black p-3 text-sm"/><button disabled={working||!evidenceText.trim()} onClick={()=>void act({action:'add-evidence',case_id:selected.id,summary:evidenceText,evidence_type:'admin_note'},'Evidence recorded.')} className="mt-2 rounded-lg border border-cyan-500/30 bg-cyan-500/10 px-3 py-2 text-sm font-black text-cyan-100 disabled:opacity-40">Add evidence</button></div>}</div>
     <div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-lg font-black"><ClipboardCheck className="h-5 w-5 text-violet-300"/>Decision packet</div><button disabled={working} onClick={()=>void act({action:'build-packet',case_id:selected.id},'Decision packet rebuilt from canonical records.')} className="rounded-lg border border-violet-500/30 bg-violet-500/10 px-3 py-2 text-sm font-black text-violet-100">Build packet</button></div>{related(data.packets)[0]?<div className="mt-4 space-y-3 text-sm"><div className="rounded-xl border border-neutral-800 p-4"><b>Recommendation</b><div className="mt-2 text-neutral-300">{related(data.packets)[0].recommendation||'No recommendation produced.'}</div></div><div className="rounded-xl border border-neutral-800 p-4"><b>Missing evidence</b><pre className="mt-2 whitespace-pre-wrap text-neutral-400">{JSON.stringify(related(data.packets)[0].missing_evidence??{},null,2)}</pre></div></div>:<p className="mt-4 text-neutral-500">No packet has been generated yet.</p>}</div></div>
    <div className="grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck className="h-4 w-4"/>Decisions</div><div className="mt-3 space-y-2">{related(data.decisions).map(d=><div key={d.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><Pill value={d.human_outcome||d.policy_outcome}/><p className="mt-2 text-neutral-400">{d.rationale||'No rationale shown.'}</p></div>)}{!related(data.decisions).length&&<div className="text-sm text-neutral-500">No decision recorded.</div>}</div></div><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="flex items-center gap-2 font-black"><WalletCards className="h-4 w-4"/>Remedies</div><div className="mt-3 space-y-2">{related(data.remedies).map(r=><div key={r.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><div className="flex justify-between gap-2"><b>{r.remedy_type?.replaceAll('_',' ')}</b><Pill value={r.status}/></div><div className="mt-2 text-neutral-400">{money(r.amount,r.currency)}</div></div>)}{!related(data.remedies).length&&<div className="text-sm text-neutral-500">No financial remedy recorded.</div>}</div></div><div className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-5"><div className="font-black">Obligations</div><div className="mt-3 space-y-2">{related(data.obligations).map(o=><div key={o.id} className="rounded-lg border border-neutral-800 p-3 text-sm"><div className="flex justify-between gap-2"><b>{o.description||o.obligation_type}</b><Pill value={o.status}/></div><div className="mt-2 text-neutral-500">Due {when(o.due_at)}</div></div>)}{!related(data.obligations).length&&<div className="text-sm text-neutral-500">No obligations recorded.</div>}</div></div></div>
   </section>:<section className="rounded-2xl border border-neutral-800 bg-[#0b0d0d] p-10 text-center text-neutral-500">Select a URWS case.</section>}</div>
 </main>
}
export default AdminURWSWorkspace;
