'use client';
import { useEffect,useMemo,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import { Settings } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';
import { CommandCenter } from './CommandCenter'; import { OrganizationArchitecture } from './OrganizationArchitecture'; import { TeamManager } from './TeamManager'; import { RegistrarValidation } from './RegistrarValidation'; import { FinanceAccounting } from './FinanceAccounting'; import { Facilities } from './Facilities'; import { Payroll } from './Payroll'; import { Imports } from './Imports'; import { Compliance } from './Compliance'; import { Reporting } from './Reporting'; import { UsersAccess } from './UsersAccess'; import { AdminSettings } from './AdminSettings';
const ComingSoon=({title,message}:{title:string;message:string})=><div className="p-6 text-white"><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 text-neutral-400">{message}</p></div>;
const RostersView=()=> <ComingSoon title="Rosters" message="Roster management coming soon."/>;const MembershipView=()=> <ComingSoon title="Membership" message="Membership management coming soon."/>;const ProgramsView=()=> <ComingSoon title="Programs" message="Programs management coming soon."/>;const TeamsView=()=> <ComingSoon title="Teams" message="Teams management coming soon."/>;const SeasonsView=()=> <ComingSoon title="Seasons" message="Seasons management coming soon."/>;const BillingView=()=> <ComingSoon title="Billing" message="Billing management coming soon."/>;const InvoicesView=()=> <ComingSoon title="Invoices" message="Invoice management coming soon."/>;const PaymentsView=()=> <ComingSoon title="Payments" message="Payment management coming soon."/>;
const viewRegistry:Record<string,React.ComponentType>={'command-center':CommandCenter,organization:OrganizationArchitecture,hierarchy:OrganizationArchitecture,'team-manager':TeamManager,registrar:RegistrarValidation,rosters:RostersView,membership:MembershipView,programs:ProgramsView,teams:TeamsView,seasons:SeasonsView,finance:FinanceAccounting,'financial-overview':FinanceAccounting,billing:BillingView,invoices:InvoicesView,payments:PaymentsView,facilities:Facilities,payroll:Payroll,imports:Imports,compliance:Compliance,reporting:Reporting,'users-access':UsersAccess,settings:AdminSettings};
const required:Record<string,string|null>={'command-center':'admin_tasks.read',organization:'organizations.read',hierarchy:'organizations.read','team-manager':'rosters.read',registrar:'registrations.read',rosters:'rosters.read',membership:'record.read',programs:'record.read',teams:'teams.read',seasons:'record.read',finance:'finance.read','financial-overview':'finance.read',billing:'finance.read',invoices:'finance.read',payments:'finance.read',facilities:'record.read',payroll:'record.read',imports:'record.import',compliance:'record.read',reporting:'record.read','users-access':'users.read',settings:'configuration.manage'};
export function AdminWorkspace(){const searchParams=useSearchParams();const router=useRouter();const view=searchParams.get('view')||'command-center';const[checking,setChecking]=useState(true);const[allowed,setAllowed]=useState(false);const[permissions,setPermissions]=useState<string[]>([]);const ActiveComponent=useMemo(()=>viewRegistry[view]||CommandCenter,[view]);useEffect(()=>{let dead=false;(async()=>{try{const r=await authenticatedFetch('/api/access-context',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.authenticated)throw new Error('auth');const hubs=Array.isArray(j.allowedHubs)?j.allowedHubs:[];const perms=Array.isArray(j.permissions)?j.permissions:[];if(dead)return;setPermissions(perms);if(!hubs.includes('admin')){const destination=hubs[0]?`/${hubs[0]}`:'/';router.replace(destination);return;}const need=required[view]??'record.read';setAllowed(!need||perms.includes(need)||j.isPlatformSuperUser===true);}catch{if(!dead)router.replace('/');}finally{if(!dead)setChecking(false)}})();return()=>{dead=true}},[router,view]);if(checking)return <div className="p-6 text-sm text-neutral-400">Checking Admin authority…</div>;if(!allowed)return <div className="p-6 text-white"><div className="rounded-xl border border-amber-900/50 bg-amber-950/20 p-5"><h1 className="text-lg font-black">This Admin capability is not delegated to your security profile.</h1><p className="mt-2 text-sm text-neutral-400">Your login is valid. Access is restricted by role, permission and scope—not by authentication.</p></div></div>;const canConfigure=permissions.includes('configuration.manage');return <div className="relative min-h-full w-full">{canConfigure&&<button type="button" aria-label="Admin settings" title="Admin settings" onClick={()=>router.push('/admin?view=settings')} className="fixed bottom-6 right-6 z-[90] flex h-11 w-11 items-center justify-center rounded-full border border-neutral-700 bg-[#111313] text-neutral-300 shadow-xl hover:border-[#FA4616]/60 hover:text-[#FA4616]"><Settings className="h-5 w-5"/></button>}<ActiveComponent/></div>}
export default AdminWorkspace;
