'use client';

import { useEffect,useMemo,useState } from 'react';
import { createClient,type SupabaseClient } from '@supabase/supabase-js';
import { Search,RefreshCw,Users,Receipt,CreditCard,CalendarRange,Layers3 } from 'lucide-react';

type Row=Record<string,any>;
let client:SupabaseClient|null=null;
function db(){if(client)return client;const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase browser configuration is missing.');client=createClient(url,key);return client}
const text=(v:any)=>v===null||v===undefined||v===''?'—':String(v).replaceAll('_',' ');
const date=(v:any)=>v?new Date(String(v)).toLocaleDateString('en-CA',{year:'numeric',month:'short',day:'numeric'}):'—';
const money=(v:any)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(v||0));
const personName=(person:any)=>{if(!person)return'—';const first=person.preferred_name||person.first_name||'';return[first,person.last_name].filter(Boolean).join(' ')||'—'};
function Shell({title,subtitle,children,count,icon:Icon=Layers3}:{title:string;subtitle:string;children:React.ReactNode;count?:number;icon?:any}){return <main className="space-y-5 p-5 text-white lg:p-7"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-neutral-800 pb-5"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-[var(--ls1-brand)]"><Icon className="h-4 w-4"/>Admin records</div><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-1 max-w-3xl text-base leading-7 text-neutral-400">{subtitle}</p></div>{typeof count==='number'&&<div className="rounded-xl border border-neutral-800 bg-[var(--ls1-surface-2)] px-5 py-3"><div className="text-2xl font-black">{count}</div><div className="text-sm text-neutral-400">records</div></div>}</header>{children}</main>}
function Status({value}:{value:any}){const s=String(value||'unknown').toLowerCase();const tone=s==='active'||s==='paid'||s==='completed'||s==='approved'?'ls1-status-success':s.includes('pending')||s.includes('scheduled')||s.includes('review')?'ls1-status-warning':s.includes('failed')||s.includes('overdue')||s.includes('inactive')||s.includes('cancel')?'ls1-status-danger':'ls1-status-info';return <span className={`${tone} rounded-full border border-current/20 px-2.5 py-1 text-sm font-bold capitalize`}>{text(s)}</span>}
function Table({rows,columns,empty}:{rows:Row[];columns:{key:string;label:string;render?:(r:Row)=>React.ReactNode}[];empty:string}){const[q,setQ]=useState('');const filtered=useMemo(()=>rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);return <section className="overflow-hidden rounded-2xl border border-neutral-800 bg-[var(--ls1-surface-1)]"><div className="border-b border-neutral-800 p-4"><label className="flex max-w-lg items-center gap-2 rounded-xl border border-neutral-700 bg-black px-3 py-3"><Search className="h-4 w-4 text-neutral-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search records" className="w-full bg-transparent text-base text-white outline-none placeholder:text-neutral-600"/></label></div>{filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-base"><thead className="bg-[var(--ls1-surface-2)] text-sm uppercase tracking-[.08em] text-neutral-400"><tr>{columns.map(c=><th key={c.key} className="px-4 py-3 font-bold">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-neutral-800">{filtered.map((r,i)=><tr key={r.id||i} className="transition hover:bg-white/[.035]">{columns.map(c=><td key={c.key} className="px-4 py-3 text-neutral-200">{c.render?c.render(r):text(r[c.key])}</td>)}</tr>)}</tbody></table></div>:<div className="p-10 text-center"><div className="text-lg font-bold text-white">{empty}</div><div className="mt-2 text-base text-neutral-500">There is nothing requiring action in this view.</div></div>}</section>}
function useRows(table:string,select='*'){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(){setLoading(true);setError('');try{const{data,error}=await db().from(table).select(select).limit(1000);if(error)throw error;setRows((data||[]) as Row[])}catch(e:any){setError(e.message||'Unable to load records.')}finally{setLoading(false)}}useEffect(()=>{void load()},[table,select]);return{rows,loading,error,load}}
function Loading(){return <div className="flex items-center gap-2 rounded-xl border border-neutral-800 p-6 text-base text-neutral-400"><RefreshCw className="h-4 w-4 animate-spin"/>Loading authorized records…</div>}
function ErrorBox({message}:{message:string}){return <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-4 text-base text-red-200">{message}</div>}
function ZeroState({title,detail}:{title:string;detail:string}){return <section className="rounded-2xl border border-dashed border-neutral-700 bg-[#090b0b] p-10 text-center"><h2 className="text-xl font-black text-white">{title}</h2><p className="mx-auto mt-2 max-w-2xl text-base leading-7 text-neutral-400">{detail}</p></section>}

export function RostersView(){const x=useRows('team_memberships','id,team_id,athlete_id,person_id,membership_type,starts_on,ends_on,status,jersey_number,notes,person:people!team_memberships_person_id_fkey(first_name,preferred_name,last_name,email),team:teams!team_memberships_team_id_fkey(name,code)');return <Shell title="Rosters" subtitle="Live Team Engine roster assignments. This view is retained for contextual team administration; roster ownership primarily belongs with Team/Coach operations." count={x.rows.length} icon={Users}>{x.loading?<Loading/>:x.error?<ErrorBox message={x.error}/>:<Table rows={x.rows} empty="No roster assignments found" columns={[{key:'person',label:'Athlete',render:r=><div><div className="font-bold text-white">{personName(r.person)}</div>{r.person?.email&&<div className="mt-0.5 text-sm text-neutral-500">{r.person.email}</div>}</div>},{key:'team',label:'Team',render:r=><span className="font-semibold text-neutral-100">{r.team?.name||'—'}</span>},{key:'membership_type',label:'Role'},{key:'jersey_number',label:'Number'},{key:'starts_on',label:'Starts',render:r=>date(r.starts_on)},{key:'ends_on',label:'Ends',render:r=>date(r.ends_on)},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>}</Shell>}
export function MembershipView(){const x=useRows('memberships','id,person_id,membership_number,membership_type,starts_on,ends_on,status,governing_body_id,person:people!memberships_person_id_fkey(first_name,preferred_name,last_name,email),governing_body:governing_bodies!memberships_governing_body_id_fkey(name,code)');return <Shell title="Membership" subtitle="Live organization and governing-body membership records. Membership is a person’s standing with the organization or governing body; it is not the same as a team roster assignment." count={x.rows.length} icon={Users}>{x.loading?<Loading/>:x.error?<ErrorBox message={x.error}/>:<Table rows={x.rows} empty="No memberships found" columns={[{key:'person',label:'Member',render:r=><div><div className="font-bold text-white">{personName(r.person)}</div>{r.person?.email&&<div className="mt-0.5 text-sm text-neutral-500">{r.person.email}</div>}</div>},{key:'membership_number',label:'Membership #'},{key:'membership_type',label:'Type'},{key:'governing_body',label:'Governing body',render:r=><span>{r.governing_body?.name||'—'}</span>},{key:'starts_on',label:'Starts',render:r=>date(r.starts_on)},{key:'ends_on',label:'Ends',render:r=>date(r.ends_on)},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>}</Shell>}
export function ProgramsView(){const x=useRows('programs','id,code,name,program_type,status');return <Shell title="Programs" subtitle="Programs currently configured for the authorized organization." count={x.rows.length}>{x.loading?<Loading/>:x.error?<ErrorBox message={x.error}/>:<Table rows={x.rows} empty="No programs configured" columns={[{key:'name',label:'Program',render:r=><span className="font-bold text-white">{r.name}</span>},{key:'code',label:'Code'},{key:'program_type',label:'Type'},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>}</Shell>}
export function TeamsView(){const x=useRows('teams','id,code,name,competitive_level,status,program_id,season_id');return <Shell title="Teams" subtitle="Canonical Team Engine teams in the authorized organization scope." count={x.rows.length} icon={Users}>{x.loading?<Loading/>:x.error?<ErrorBox message={x.error}/>:<Table rows={x.rows} empty="No teams configured" columns={[{key:'name',label:'Team',render:r=><span className="font-bold text-white">{r.name}</span>},{key:'code',label:'Code'},{key:'competitive_level',label:'Level'},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>}</Shell>}
export function SeasonsView(){const x=useRows('seasons','id,code,name,starts_on,ends_on,status');return <Shell title="Seasons" subtitle="Season records used to organize registrations, programs and team activity." count={x.rows.length} icon={CalendarRange}>{x.loading?<Loading/>:x.error?<ErrorBox message={x.error}/>:<Table rows={x.rows} empty="No seasons configured" columns={[{key:'name',label:'Season',render:r=><span className="font-bold text-white">{r.name}</span>},{key:'code',label:'Code'},{key:'starts_on',label:'Starts',render:r=>date(r.starts_on)},{key:'ends_on',label:'Ends',render:r=>date(r.ends_on)},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>}</Shell>}

export function BillingView(){const accounts=useRows('billing_accounts','id,customer_id,currency,payment_terms_days,credit_limit,status');return <Shell title="Billing" subtitle="Live customer account terms, balances and billing controls. No demonstration transactions are substituted for missing live records." count={accounts.rows.length} icon={CreditCard}>{accounts.loading?<Loading/>:accounts.error?<ErrorBox message={accounts.error}/>:accounts.rows.length?<Table rows={accounts.rows} empty="No billing accounts" columns={[{key:'status',label:'Status',render:r=><Status value={r.status}/>},{key:'currency',label:'Currency'},{key:'payment_terms_days',label:'Terms (days)'},{key:'credit_limit',label:'Credit limit',render:r=>money(r.credit_limit)}]}/>:<ZeroState title="No billing accounts yet" detail="There are currently no live billing accounts in the authorized organization scope. When real customer billing accounts are created, they will appear here automatically."/>}</Shell>}
export function InvoicesView(){const live=useRows('invoices','id,invoice_number,invoice_date,due_date,currency,total,balance_due,status');return <Shell title="Invoices" subtitle="Live accounts-receivable invoices and outstanding balances. This screen never substitutes sample invoices for an empty ledger." count={live.rows.length} icon={Receipt}>{live.loading?<Loading/>:live.error?<ErrorBox message={live.error}/>:live.rows.length?<Table rows={live.rows} empty="No invoices" columns={[{key:'invoice_number',label:'Invoice',render:r=><span className="font-bold text-white">{r.invoice_number}</span>},{key:'invoice_date',label:'Issued',render:r=>date(r.invoice_date)},{key:'due_date',label:'Due',render:r=>date(r.due_date)},{key:'total',label:'Total',render:r=>money(r.total)},{key:'balance_due',label:'Balance',render:r=>money(r.balance_due)},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>:<ZeroState title="No invoices yet" detail="There are currently no live invoices in the authorized organization scope. LS1Sports will not display fabricated financial activity."/>}</Shell>}
export function PaymentsView(){const live=useRows('payments','id,customer_id,invoice_id,payment_date,amount,currency,method,processor_reference,status');return <Shell title="Payments" subtitle="Live payment transactions only. Receipts, disbursements, refunds and reversals must be backed by authoritative transaction records." count={live.rows.length} icon={CreditCard}>{live.loading?<Loading/>:live.error?<ErrorBox message={live.error}/>:live.rows.length?<Table rows={live.rows} empty="No payments" columns={[{key:'payment_date',label:'Date',render:r=>date(r.payment_date)},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'currency',label:'Currency'},{key:'method',label:'Method'},{key:'processor_reference',label:'Reference'},{key:'status',label:'Status',render:r=><Status value={r.status}/>} ]}/>:<ZeroState title="No payments yet" detail="There are currently no live payment transactions in the authorized organization scope. Nothing is displayed here until an authoritative transaction exists."/>}</Shell>}
