'use client';
import{useCallback,useEffect,useMemo,useState}from'react';
import{authenticatedFetch}from'@/lib/client/authenticatedFetch';
type Row=Record<string,any>;
type Queue={key:string;title:string;pillar:string;description:string;rows:Row[]};
export function CommandCenter({role='org_admin'}:{role?:string}){
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[selected,setSelected]=useState<Queue|null>(null);
 const load=useCallback(async()=>{setError('');const r=await authenticatedFetch(`/api/admin-command?role=${encodeURIComponent(role)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)},[role]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function createTask(){const title=window.prompt('Task title');if(!title)return;setSaving(true);try{const r=await authenticatedFetch('/api/admin-command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create-task',title,role})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setSaving(false)}}
 async function complete(id:string){setSaving(true);try{const r=await authenticatedFetch('/api/admin-command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete-task',id,role})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setSaving(false)}}
 const queues=useMemo<Queue[]>(()=>{if(!data)return[];const now=Date.now(),q:Queue[]=[];const overdue=(data.invoices||[]).filter((r:Row)=>r.due_date&&Number(r.balance_due)>0&&new Date(r.due_date).getTime()<now);const dq=data.controls?.dataQualityIssues||[],dupes=data.controls?.duplicateCandidates||[],tasks=data.tasks||[];
 if(overdue.length)q.push({key:'finance',title:'Financial reconciliation',pillar:'Macro-Financial Budgets & Ledger Accounting',description:`${overdue.length} past-due receivable${overdue.length===1?'':'s'} require review.`,rows:overdue});
 if(dq.length)q.push({key:'quality',title:'Data integrity review',pillar:'Risk Management & SafeSport Governance',description:`${dq.length} canonical data-quality exception${dq.length===1?'':'s'} require human review.`,rows:dq});
 if(dupes.length)q.push({key:'duplicates',title:'Duplicate resolution',pillar:'Workforce Governance & Role Delegation',description:`${dupes.length} potential duplicate person record${dupes.length===1?'':'s'} require resolution.`,rows:dupes});
 if(tasks.length)q.push({key:'tasks',title:'Organization work items',pillar:'Executive work queue',description:`${tasks.length} assigned/open work item${tasks.length===1?'':'s'} require action.`,rows:tasks});return q},[data]);
 if(!data)return <State text={error||'Loading live organization work…'}/>;
 const org=data.orgAdmin?.organizations?.[0];
 return <main className="p-5 text-white lg:p-7"><header className="border-b border-neutral-800 pb-5"><div className="text-[9px] font-black uppercase tracking-[.22em] text-[#FA4616]">{role.replaceAll('_',' ')} · {org?.name||'Organization'}</div><h1 className="mt-1 text-3xl font-black">Executive Command Center</h1><p className="mt-2 text-sm text-neutral-400">Immediate organization conditions requiring executive action. Open a queue to work the underlying canonical records.</p></header>{error&&<div className="mt-4 border border-red-900 p-3 text-red-300">{error}</div>}
 <section className="mt-5 grid gap-3 lg:grid-cols-5">{[['Facility Sourcing & Vendor Contracts',data.enterprise?.facilities?.length||0],['Risk Management & SafeSport Governance',(data.controls?.credentials?.length||0)+(data.controls?.backgroundChecks?.length||0)+(data.controls?.safeSport?.length||0)],['Workforce Governance & Role Delegation',data.orgAdmin?.assignments?.filter((x:Row)=>x.status==='active').length||0],['Macro-Financial Budgets & Ledger Accounting',(data.invoices?.length||0)+(data.vendorBills?.length||0)],['System Analytics & Overwatch Reporting',queues.reduce((n,x)=>n+x.rows.length,0)]].map(([name,count])=><div key={String(name)} className="rounded-xl border border-neutral-800 bg-[#090b0b] p-4"><div className="text-[9px] font-black uppercase tracking-[.14em] text-neutral-500">{name}</div><div className="mt-3 text-2xl font-black">{count}</div><div className="mt-1 text-xs text-neutral-600">canonical records / conditions</div></div>)}</section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-neutral-800 bg-[#090b0b]"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-neutral-800 p-4"><div><div className="text-[9px] font-black uppercase tracking-[.18em] text-[#FA4616]">Immediate action required</div><h2 className="mt-1 text-lg font-black">Today's executive work</h2><p className="mt-1 text-xs text-neutral-500">Grouped operational queues. Repeated source exceptions are consolidated instead of dumped into the landing page.</p></div><button disabled={saving} onClick={createTask} className="rounded-lg bg-[#FA4616] px-4 py-2 text-xs font-black text-black disabled:opacity-40">+ New task</button></div>
 <div className="divide-y divide-neutral-800">{queues.map(q=><button key={q.key} onClick={()=>setSelected(q)} className="flex w-full items-center justify-between gap-5 p-5 text-left hover:bg-white/[.025]"><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-[#FA4616]">{q.pillar}</div><div className="mt-1 font-black">{q.title}</div><div className="mt-1 text-sm text-neutral-500">{q.description}</div></div><div className="text-2xl font-black">{q.rows.length}</div></button>)}{!queues.length&&<div className="p-8 text-sm text-neutral-500">No current canonical conditions require executive action.</div>}</section>
 <section className="mt-5 grid gap-3 md:grid-cols-3"><Fact label="Organization" value={org?.code||org?.name||'—'}/><Fact label="People" value={data.orgAdmin?.people?.length||0}/><Fact label="Active teams" value={data.metrics.activeTeams}/></section>
 {selected&&<div className="fixed inset-0 z-[100] bg-black/70" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="absolute right-0 top-0 h-full w-full max-w-5xl overflow-y-auto border-l border-neutral-700 bg-[#080909]"><header className="sticky top-0 border-b border-neutral-800 bg-[#080909] p-5"><button onClick={()=>setSelected(null)} className="float-right text-neutral-400">Close</button><div className="text-[9px] uppercase tracking-[.2em] text-[#FA4616]">{selected.pillar}</div><h2 className="mt-1 text-2xl font-black">{selected.title}</h2><p className="mt-1 text-sm text-neutral-500">{selected.description}</p></header><div className="divide-y divide-neutral-800">{selected.rows.map((r:Row)=><div key={r.id} className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="font-bold">{r.payload?.title||r.invoice_number||r.entity_type||r.id}</div><div className="mt-1 text-sm text-neutral-500">{r.payload?.description||r.details?.message||r.status||''}</div><div className="mt-2 text-xs text-neutral-600">{r.id}</div></div>{selected.key==='tasks'&&<button disabled={saving} onClick={()=>complete(r.id)} className="rounded-lg border border-neutral-700 px-3 py-2 text-xs font-bold disabled:opacity-40">Complete</button>}</div></div>)}</div></aside></div>}</main>}
function Fact({label,value}:{label:string;value:any}){return <div className="rounded-xl border border-neutral-800 bg-[#090b0b] p-4"><div className="text-[9px] uppercase tracking-[.16em] text-neutral-600">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
function State({text}:{text:string}){return <div className="p-8 text-white"><h1 className="text-2xl font-black">Command Center</h1><p className="mt-2 text-neutral-500">{text}</p></div>}
export default CommandCenter;
