'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';
type Row=Record<string,any>; type Payload={invoices:Row[];vendorBills:Row[];metrics:any;authorization:any;generatedAt:string;error?:string};
const money=(v:any)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(v||0));
export function FinanceAccounting({role='org_admin'}:{role?:string}){const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState<'receivables'|'payables'>('receivables'),[selected,setSelected]=useState<Row|null>(null);
const load=useCallback(async()=>{setError('');const r=await authenticatedFetch(`/api/admin-command?role=${encodeURIComponent(role)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Finance data unavailable.');setData(j)},[role]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
const rows=useMemo(()=>((tab==='receivables'?data?.invoices:data?.vendorBills)||[]).filter((r:Row)=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[data,tab,query]);
if(!data)return <State text={error||'Loading canonical finance records…'}/>;
return <main className="p-5 text-white lg:p-7"><header className="border-b border-neutral-800 pb-5"><div className="text-[9px] font-black uppercase tracking-[.22em] text-[#FA4616]">Organization Administrator · Finance</div><h1 className="mt-1 text-3xl font-black">Financial control</h1><p className="mt-2 text-sm text-neutral-400">Canonical receivables and payables. No simulated balances or trends.</p></header>{error&&<div className="mt-4 border border-red-900 p-3 text-red-300">{error}</div>}
<section className="mt-5 flex flex-wrap gap-2"><button onClick={()=>setTab('receivables')} className={tab==='receivables'?'rounded-lg bg-[#FA4616] px-4 py-2 text-xs font-black text-black':'rounded-lg border border-neutral-700 px-4 py-2 text-xs'}>Accounts receivable · {money(data.metrics?.arBalance)}</button><button onClick={()=>setTab('payables')} className={tab==='payables'?'rounded-lg bg-[#FA4616] px-4 py-2 text-xs font-black text-black':'rounded-lg border border-neutral-700 px-4 py-2 text-xs'}>Accounts payable · {money(data.metrics?.apBalance)}</button><span className="px-3 py-2 text-xs text-neutral-500">{data.metrics?.pastDue||0} past-due receivables</span></section>
<section className="mt-4 overflow-hidden rounded-2xl border border-neutral-800 bg-[#090b0b]"><div className="border-b border-neutral-800 p-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter canonical records" className="w-full max-w-sm rounded-lg border border-neutral-700 bg-black px-3 py-2 text-sm"/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-neutral-500"><tr><th className="p-4">Record</th><th>Date</th><th>Due</th><th>Total</th><th>Balance</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>setSelected(r)} className="cursor-pointer border-t border-neutral-800 hover:bg-white/[.03]"><td className="p-4 font-bold">{r.invoice_number||r.bill_number||r.id}</td><td>{r.invoice_date||r.bill_date||'—'}</td><td>{r.due_date||'—'}</td><td>{money(r.total)}</td><td>{money(r.balance_due)}</td><td>{r.status||'—'}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-8 text-sm text-neutral-500">No canonical {tab} records exist in the authorized scope.</div>}</section>{selected&&<Drawer row={selected} onClose={()=>setSelected(null)}/>}</main>}
function Drawer({row,onClose}:{row:Row;onClose:()=>void}){return <div className="fixed inset-0 z-[100] bg-black/70" onClick={onClose}><aside onClick={e=>e.stopPropagation()} className="ml-auto h-full w-full max-w-2xl overflow-y-auto border-l border-neutral-700 bg-[#080909] p-6"><button onClick={onClose} className="float-right text-neutral-400">Close</button><div className="text-[9px] font-black uppercase tracking-[.2em] text-[#FA4616]">Canonical financial record</div><h2 className="mt-2 text-2xl font-black">{row.invoice_number||row.bill_number||row.id}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(row).map(([k,v])=><div key={k} className="border-b border-neutral-800 pb-2"><div className="text-[9px] uppercase text-neutral-600">{k.replaceAll('_',' ')}</div><div className="mt-1 break-words text-sm">{String(v??'—')}</div></div>)}</div></aside></div>}
function State({text}:{text:string}){return <div className="p-8 text-white"><h1 className="text-2xl font-black">Financial control</h1><p className="mt-2 text-neutral-500">{text}</p></div>} export default FinanceAccounting;