'use client';
import { useEffect,useMemo,useState } from 'react';
import { Search,ShieldCheck,X } from 'lucide-react';
import { authenticatedFetch } from '@/lib/client/authenticatedFetch';

type Person={id:string;first_name:string;last_name:string;preferred_name:string|null;email:string|null;status:string|null};
type Role={id:string;code:string;name:string;description:string|null;privilege_level:number;config:{hub_access?:string[]}};
type Assignment={id:string;person_id:string;role_definition_id:string;organization_id:string|null;team_id:string|null};
type Org={id:string;code:string;name:string}; type Team={id:string;code:string;name:string;organization_id:string|null};
type Data={people:Person[];roles:Role[];assignments:Assignment[];organizations:Org[];teams:Team[]};
type Draft={roleDefinitionId:string;organizationId:string|null;teamId:string|null};

export function UsersAccess(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[query,setQuery]=useState(''),[selected,setSelected]=useState<Person|null>(null),[draft,setDraft]=useState<Draft[]>([]),[saving,setSaving]=useState(false),[saved,setSaved]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const r=await authenticatedFetch('/api/admin/access/users',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load access administration.');setData(j);}catch(e){setError(e instanceof Error?e.message:'Unable to load access administration.');}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const people=useMemo(()=>{const q=query.trim().toLowerCase();return(data?.people||[]).filter(p=>!q||`${p.first_name} ${p.last_name} ${p.email||''}`.toLowerCase().includes(q));},[data,query]);
 function open(p:Person){setSelected(p);setSaved(null);setDraft((data?.assignments||[]).filter(a=>a.person_id===p.id).map(a=>({roleDefinitionId:a.role_definition_id,organizationId:a.organization_id,teamId:a.team_id})));}
 function toggle(role:Role){setDraft(current=>current.some(d=>d.roleDefinitionId===role.id)?current.filter(d=>d.roleDefinitionId!==role.id):[...current,{roleDefinitionId:role.id,organizationId:data?.organizations?.[0]?.id||null,teamId:null}]);}
 function patch(roleId:string,field:'organizationId'|'teamId',value:string){setDraft(current=>current.map(d=>d.roleDefinitionId===roleId?{...d,[field]:value||null}:d));}
 const hubs=useMemo(()=>{const out=new Set<string>();for(const d of draft){const r=data?.roles.find(x=>x.id===d.roleDefinitionId);for(const h of r?.config?.hub_access||[])out.add(h)}return[...out];},[draft,data]);
 async function save(){if(!selected)return;setSaving(true);setError(null);setSaved(null);try{const r=await authenticatedFetch('/api/admin/access/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({personId:selected.id,assignments:draft,reason:'Updated through Admin Users & Access'})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'Unable to save access.');setSaved('Access saved to the canonical security model and audit history.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save access.');}finally{setSaving(false)}}
 if(loading)return <div className="p-6 text-sm text-neutral-400">Loading canonical users and security roles…</div>;
 return <div className="min-h-full bg-[#080909] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-[#FA4616]">Admin Control Plane</div><h1 className="mt-2 text-2xl font-black">Users & Access</h1><p className="mt-2 max-w-3xl text-sm text-neutral-400">Assign one or multiple security roles. Effective workspace access is assembled from canonical role grants and scope; Platform SuperUser authority is never delegable here.</p></div><ShieldCheck className="h-7 w-7 text-[#FA4616]"/></div>
 {error&&<div className="mt-4 rounded-lg border border-red-900/60 bg-red-950/20 px-4 py-3 text-sm text-red-300">{error}</div>}
 <div className="mt-6 rounded-xl border border-neutral-800 bg-[#0d0f0f]"><div className="flex items-center gap-3 border-b border-neutral-800 px-4 py-3"><Search className="h-4 w-4 text-neutral-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search client users by name or email" className="w-full bg-transparent text-sm outline-none placeholder:text-neutral-600"/></div><div className="divide-y divide-neutral-900">{people.map(p=>{const count=data?.assignments.filter(a=>a.person_id===p.id).length||0;return <button key={p.id} onClick={()=>open(p)} className="flex w-full items-center justify-between px-4 py-3 text-left hover:bg-neutral-900/70"><div><div className="text-sm font-bold">{p.preferred_name||p.first_name} {p.last_name}</div><div className="mt-1 text-xs text-neutral-500">{p.email||'No login email'} · {p.status||'unknown'}</div></div><div className="rounded-full border border-neutral-800 px-2.5 py-1 text-[10px] font-bold text-neutral-400">{count} active role{count===1?'':'s'}</div></button>})}{!people.length&&<div className="px-4 py-8 text-center text-sm text-neutral-500">No matching client users.</div>}</div></div>
 {selected&&<div className="fixed inset-0 z-[140] flex justify-end bg-black/50"><div className="h-full w-full max-w-[680px] overflow-y-auto border-l border-neutral-800 bg-[#0a0c0c] shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-neutral-800 bg-[#0a0c0c]/95 p-5 backdrop-blur"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-[#FA4616]">Security Profile</div><h2 className="mt-1 text-xl font-black">{selected.preferred_name||selected.first_name} {selected.last_name}</h2><div className="mt-1 text-xs text-neutral-500">{selected.email||'No login email'}</div></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 text-neutral-500 hover:bg-neutral-900 hover:text-white"><X className="h-5 w-5"/></button></div>
 <div className="p-5"><div className="rounded-xl border border-neutral-800 bg-[#101212] p-4"><div className="text-[10px] font-black uppercase tracking-[.18em] text-neutral-500">Resulting workspace access</div><div className="mt-3 flex flex-wrap gap-2">{hubs.length?hubs.map(h=><span key={h} className="rounded-full border border-[#FA4616]/40 bg-[#FA4616]/10 px-3 py-1 text-xs font-bold capitalize text-[#FA4616]">{h}</span>):<span className="text-xs text-neutral-500">No engine access from selected roles.</span>}</div></div>
 <div className="mt-5"><div className="mb-3 text-xs font-black uppercase tracking-[.16em] text-neutral-400">Security roles</div><div className="space-y-3">{data?.roles.map(role=>{const d=draft.find(x=>x.roleDefinitionId===role.id);return <div key={role.id} className={`rounded-xl border p-4 ${d?'border-[#FA4616]/50 bg-[#FA4616]/5':'border-neutral-800 bg-[#0d0f0f]'}`}><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" checked={!!d} onChange={()=>toggle(role)} className="mt-1 accent-[#FA4616]"/><span><span className="block text-sm font-bold">{role.name}</span><span className="mt-1 block text-xs leading-5 text-neutral-500">{role.description||role.code} · privilege {role.privilege_level}</span></span></label>{d&&<div className="mt-4 grid grid-cols-2 gap-3 border-t border-neutral-800 pt-4"><label className="text-[10px] font-bold uppercase tracking-[.14em] text-neutral-500">Organization<select value={d.organizationId||''} onChange={e=>patch(role.id,'organizationId',e.target.value)} className="mt-2 w-full rounded-lg border border-neutral-800 bg-[#080909] px-3 py-2 text-xs normal-case tracking-normal text-white"><option value="">Tenant-wide</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name} ({o.code})</option>)}</select></label><label className="text-[10px] font-bold uppercase tracking-[.14em] text-neutral-500">Team<select value={d.teamId||''} onChange={e=>patch(role.id,'teamId',e.target.value)} className="mt-2 w-full rounded-lg border border-neutral-800 bg-[#080909] px-3 py-2 text-xs normal-case tracking-normal text-white"><option value="">All permitted teams</option>{data.teams.filter(t=>!d.organizationId||!t.organization_id||t.organization_id===d.organizationId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>}</div>})}</div></div>
 {saved&&<div className="mt-4 rounded-lg border border-emerald-900/60 bg-emerald-950/20 px-4 py-3 text-sm text-emerald-300">{saved}</div>}<div className="sticky bottom-0 mt-6 flex justify-end gap-3 border-t border-neutral-800 bg-[#0a0c0c] py-4"><button onClick={()=>setSelected(null)} className="rounded-lg border border-neutral-800 px-4 py-2 text-sm font-bold text-neutral-300">Cancel</button><button onClick={()=>void save()} disabled={saving} className="rounded-lg bg-[#FA4616] px-4 py-2 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':'Save Access'}</button></div></div></div></div>}
 </div>;
}
export default UsersAccess;
