import {NextRequest,NextResponse} from 'next/server';
import {CoachAuthError,requireCoach,type CoachIdentity} from '@/lib/server/requireCoach';
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://xedfstgwotzxnztpembv.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??process.env.SUPABASE_ANON_KEY;
export const dynamic='force-dynamic';export const revalidate=0;
function headers(actor:CoachIdentity,extra:HeadersInit={}){if(!KEY)throw new Error('Supabase access is not configured.');const h=new Headers(extra);h.set('apikey',KEY);h.set('Authorization',`Bearer ${actor.accessToken}`);h.set('Accept','application/json');if(!h.has('Content-Type'))h.set('Content-Type','application/json');if(!h.has('Prefer'))h.set('Prefer','return=representation');return h;}
async function rest<T>(actor:CoachIdentity,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:headers(actor,init.headers),cache:'no-store'});const t=await r.text();if(!r.ok)throw new Error(`Season Planning Agent operation failed (${r.status}) ${t.slice(0,320)}`);return(t?JSON.parse(t):null)as T;}
function authError(e:unknown){if(e instanceof CoachAuthError)return NextResponse.json({error:e.message},{status:e.status});return null;}
function csv(ids:string[]){return ids.map(id=>`\"${id}\"`).join(',')}function uniq<T>(v:T[]){return Array.from(new Set(v));}function text(v:unknown,max=4000){return String(v??'').trim().slice(0,max)}function uuid(v:unknown){const s=text(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null;}function iso(v:unknown){const s=text(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;}function at(s:string){return new Date(`${s}T12:00:00Z`)}function fmt(d:Date){return d.toISOString().slice(0,10)}function add(d:Date,n:number){const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x;}function days(a:string,b:string){return Math.max(1,Math.round((at(b).getTime()-at(a).getTime())/86400000)+1)}
async function teamsFor(actor:CoachIdentity){const assigned=uniq(actor.assignments.map(a=>a.team_id).filter(Boolean)as string[]);if(actor.isSuperUser)return rest<any[]>(actor,'teams?select=id,organization_id,sport_id,season_id,name,competitive_level,status&status=eq.active&order=name.asc&limit=200');if(!assigned.length)return[];return rest<any[]>(actor,`teams?select=id,organization_id,sport_id,season_id,name,competitive_level,status&id=in.(${csv(assigned)})&status=eq.active&order=name.asc`);}
function canUse(actor:CoachIdentity,team:any){return actor.isSuperUser||actor.assignments.some(a=>a.team_id===team.id||(!a.team_id&&a.organization_id===team.organization_id));}
async function audit(actor:CoachIdentity,team:any,action:string,entityType:string,entityId:string|null,decision:string,after:unknown){await rest(actor,'coach_decision_log',{method:'POST',body:JSON.stringify({organization_id:team.organization_id,coach_person_id:actor.personId,action,entity_type:entityType,entity_id:entityId,decision,after_data:after,source:'coach_season_planning_agent'})});}
async function context(actor:CoachIdentity,team:any){const season=team.season_id?(await rest<any[]>(actor,`seasons?select=id,organization_id,sport_id,name,starts_on,ends_on,status&id=eq.${team.season_id}&limit=1`))[0]||null:null;const methodology=actor.personId?(await rest<any[]>(actor,`coach_methodologies?select=*&coach_person_id=eq.${actor.personId}&organization_id=eq.${team.organization_id}&status=eq.active&order=updated_at.desc&limit=1`))[0]||null:null;const now=new Date(),future=new Date(now.getTime()+430*86400000);const competitions=await rest<any[]>(actor,`competitions?select=id,name,competition_type,starts_at,ends_at,city,region,country_code,status,sanction_number&organization_id=eq.${team.organization_id}&starts_at=gte.${encodeURIComponent(now.toISOString())}&starts_at=lte.${encodeURIComponent(future.toISOString())}&order=starts_at.asc&limit=100`);const plans=actor.personId?await rest<any[]>(actor,`coach_season_plans?select=*&coach_person_id=eq.${actor.personId}&team_id=eq.${team.id}&order=starts_on.desc&limit=20`):[];const proposals=actor.personId?await rest<any[]>(actor,`coach_agent_proposals?select=*&coach_person_id=eq.${actor.personId}&organization_id=eq.${team.organization_id}&agent_key=eq.season_planning&status=in.(proposed,prepared,approved,rejected)&order=created_at.desc&limit=20`):[];return{season,methodology,competitions,plans,proposals};}
function buildCycles(startsOn:string,endsOn:string,targetDate:string){const total=days(startsOn,endsOn),start=at(startsOn),end=at(endsOn),target=at(targetDate);const taperDays=Math.min(21,Math.max(7,Math.round(total*.08))),peakStart=new Date(Math.max(start.getTime(),add(target,-taperDays).getTime()));const prePeak=Math.max(1,Math.round((peakStart.getTime()-start.getTime())/86400000));const baseEnd=add(start,Math.max(6,Math.round(prePeak*.42))-1);const buildEnd=add(baseEnd,Math.max(6,Math.round(prePeak*.33)));const specificEnd=add(peakStart,-1);const safe=(d:Date)=>new Date(Math.min(end.getTime(),Math.max(start.getTime(),d.getTime())));return[
{cycle_type:'macrocycle',name:'Foundation',phase:'base',starts_on:startsOn,ends_on:fmt(safe(baseEnd)),objective:'Build technical quality, movement economy and durable aerobic capacity.',load_target:65,sort_order:10},
{cycle_type:'macrocycle',name:'Development',phase:'build',starts_on:fmt(safe(add(baseEnd,1))),ends_on:fmt(safe(buildEnd)),objective:'Increase sustainable workload and event-relevant strength/speed qualities.',load_target:80,sort_order:20},
{cycle_type:'macrocycle',name:'Competition Specific',phase:'specific',starts_on:fmt(safe(add(buildEnd,1))),ends_on:fmt(safe(specificEnd)),objective:'Convert fitness into competition-specific pace, skills and race execution.',load_target:88,sort_order:30},
{cycle_type:'macrocycle',name:'Taper & Peak',phase:'taper_peak',starts_on:fmt(safe(peakStart)),ends_on:endsOn,objective:'Reduce fatigue while preserving quality and sharpening championship execution.',load_target:55,sort_order:40}
].filter((c,i,a)=>c.starts_on<=c.ends_on&&(i===0||c.starts_on>a[i-1].starts_on));}
function proposal(input:any,ctx:any,team:any){const comp=ctx.competitions.find((c:any)=>c.id===uuid(input.primary_competition_id))||ctx.competitions[ctx.competitions.length-1]||null;const seasonStart=iso(input.starts_on)||ctx.season?.starts_on||new Date().toISOString().slice(0,10);const targetDate=comp?.starts_at?String(comp.starts_at).slice(0,10):iso(input.ends_on)||ctx.season?.ends_on||fmt(add(at(seasonStart),180));let seasonEnd=iso(input.ends_on)||ctx.season?.ends_on||targetDate;if(targetDate>seasonEnd)seasonEnd=targetDate;const cycles=buildCycles(seasonStart,seasonEnd,targetDate);return{name:text(input.name,200)||`${team.name} · ${ctx.season?.name||'Season'} Performance Plan`,starts_on:seasonStart,ends_on:seasonEnd,season_id:team.season_id||ctx.season?.id||null,sport_id:team.sport_id||ctx.season?.sport_id||null,methodology_id:ctx.methodology?.id||null,primary_competition_id:comp?.id||null,primary_competition:comp?{id:comp.id,name:comp.name,starts_at:comp.starts_at}:null,goals:[{type:'performance',statement:text(input.goal,1000)||'Arrive at the primary competition prepared to execute the coach-defined performance objectives.'}],constraints:{coach_notes:text(input.constraints,2000)||null,planning_model:'backward_from_primary_competition'},cycles,guardrails:{coach_approval_required:true,authoritative_plan:false,medical_diagnosis:false,real_data_only:true},data_quality:{methodology:Boolean(ctx.methodology),canonical_season:Boolean(ctx.season),primary_competition:Boolean(comp),competition_count:ctx.competitions.length}};}
export async function GET(request:NextRequest){try{const actor=await requireCoach(request),teams=await teamsFor(actor),requested=request.nextUrl.searchParams.get('team_id'),teamId=requested&&teams.some(t=>t.id===requested)?requested:(teams[0]?.id||null),team=teams.find(t=>t.id===teamId)||null;if(!team)return NextResponse.json({generatedAt:new Date().toISOString(),teams,selectedTeamId:null,context:null,proposals:[],plans:[]});const ctx=await context(actor,team);return NextResponse.json({generatedAt:new Date().toISOString(),teams,selectedTeamId:team.id,context:{season:ctx.season,methodology:ctx.methodology,competitions:ctx.competitions},proposals:ctx.proposals,plans:ctx.plans,source:'canonical season + Coach methodology + authoritative Competition Engine calendar'},{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(e){const a=authError(e);if(a)return a;return NextResponse.json({error:e instanceof Error?e.message:'Season Planning Agent unavailable.'},{status:500})}}
export async function POST(request:NextRequest){try{const actor=await requireCoach(request);if(!actor.personId)return NextResponse.json({error:'A canonical Coach identity is required.'},{status:409});const body=await request.json(),action=text(body.action,80),teamId=uuid(body.team_id);if(!teamId)return NextResponse.json({error:'Team is required.'},{status:400});const teams=await teamsFor(actor),team=teams.find(t=>t.id===teamId);if(!team||!canUse(actor,team))return NextResponse.json({error:'Coach is not authorized for this team.'},{status:403});
if(action==='generate-proposal'){const ctx=await context(actor,team),p=proposal(body,ctx,team);const row=(await rest<any[]>(actor,'coach_agent_proposals',{method:'POST',body:JSON.stringify({organization_id:team.organization_id,coach_person_id:actor.personId,agent_key:'season_planning',proposal_type:'season_architecture',autonomy_level:'prepare',subject_type:'teams',subject_id:team.id,proposal:p,rationale:{principle:'Coach decides. ERP executes. Agents watch.',planning_direction:'backward_from_primary_competition',methodology_name:ctx.methodology?.name||null,canonical_season:ctx.season?.name||null,competition_count:ctx.competitions.length},source_evidence:{methodology_id:ctx.methodology?.id||null,season_id:ctx.season?.id||null,primary_competition_id:p.primary_competition_id,competition_ids:ctx.competitions.map((c:any)=>c.id)},status:'prepared'})}))[0];await audit(actor,team,'COACH_SEASON_AGENT_PREPARED','coach_agent_proposals',row.id,'prepared',row);return NextResponse.json(row,{status:201});}
if(action==='approve-plan'){const proposalId=uuid(body.proposal_id);if(!proposalId)return NextResponse.json({error:'Season proposal is required.'},{status:400});const row=(await rest<any[]>(actor,`coach_agent_proposals?select=*&id=eq.${proposalId}&coach_person_id=eq.${actor.personId}&organization_id=eq.${team.organization_id}&agent_key=eq.season_planning&limit=1`))[0];if(!row)return NextResponse.json({error:'Season proposal not found.'},{status:404});const p=row.proposal||{};const plan=(await rest<any[]>(actor,'coach_season_plans',{method:'POST',body:JSON.stringify({coach_person_id:actor.personId,organization_id:team.organization_id,team_id:team.id,season_id:uuid(p.season_id),sport_id:uuid(p.sport_id),methodology_id:uuid(p.methodology_id),name:text(p.name,200)||'Agent-prepared Season Plan',starts_on:iso(p.starts_on),ends_on:iso(p.ends_on),primary_competition_id:uuid(p.primary_competition_id),goals:Array.isArray(p.goals)?p.goals:[],constraints:p.constraints||{},status:'active',approval_status:'approved',created_by_agent:true})}))[0];for(const c of Array.isArray(p.cycles)?p.cycles:[]){await rest(actor,'coach_training_cycles',{method:'POST',body:JSON.stringify({season_plan_id:plan.id,cycle_type:text(c.cycle_type,40)||'macrocycle',name:text(c.name,180)||'Training phase',starts_on:iso(c.starts_on),ends_on:iso(c.ends_on),objective:text(c.objective,1000)||null,load_target:Number(c.load_target)||null,phase:text(c.phase,80)||null,definition:{authored_by:'season_planning_agent',coach_approved:true,source_proposal_id:row.id},sort_order:Number(c.sort_order)||0,status:'active'})});}await rest(actor,`coach_agent_proposals?id=eq.${row.id}`,{method:'PATCH',body:JSON.stringify({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by_person_id:actor.personId,decision_note:text(body.decision_note,2000)||'Coach approved season architecture',executed_at:new Date().toISOString()})});await audit(actor,team,'COACH_SEASON_AGENT_APPROVED','coach_season_plans',plan.id,'approved',{plan_id:plan.id,proposal_id:row.id,cycle_count:Array.isArray(p.cycles)?p.cycles.length:0});return NextResponse.json({plan,proposalId:row.id},{status:201});}
return NextResponse.json({error:'Unsupported Season Planning Agent action.'},{status:400});}catch(e){const a=authError(e);if(a)return a;return NextResponse.json({error:e instanceof Error?e.message:'Season Planning Agent action failed.'},{status:500})}}
