'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';
import {AlertTriangle,BrainCircuit,CalendarDays,CheckCircle2,ChevronRight,ClipboardList,RefreshCw,Search,ShieldCheck,Sparkles,Target,Users} from 'lucide-react';

type CoachPayload={
 generatedAt:string;source:string;mission:string;error?:string;
 actor:{displayName:string;personId:string|null;isSuperUser:boolean};
 scope:{selectedTeamId:string|null;selectedOrganizationId:string|null;teams:any[];assignments:any[]};
 today:{calendar:any[];attendanceSessions:any[];attention:any[]};
 attention:{items:any[];counts:{now:number;soon:number;watch:number;fyi:number}};
 roster:any[];
 training:{plans:any[];sessions:any[]};
 development:{plans:any[];goals:any[];assessments:any[]};
 competition:{upcoming:any[];candidates:any[];standardsAvailable:number;rankingsAvailable:number};
 planning:{methodologies:any[];seasonPlans:any[];cycles:any[]};
 operations:{calendar:any[];facilities:any[]};
 agents:{proposals:any[]};
 notes:any[];community:any[];dataHealth:Record<string,number>;
};

type View='today'|'team'|'athletes'|'training'|'competition'|'season'|'analytics'|'community'|'ai';
const views:[View,string][]=[['today','Today'],['team','Team'],['athletes','Athletes'],['training','Training'],['competition','Competition'],['season','Season'],['analytics','Analytics'],['community','Community'],['ai','AI / Overwatch']];
const horizonLabel:{[key:string]:string}={now:'NOW',soon:'SOON',watch:'WATCH',fyi:'FYI'};
const fmtDate=(v?:string)=>v?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(v)):'—';
const fmtTime=(v?:string)=>v?new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
function Empty({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-dashed border-neutral-700 bg-neutral-950/40 px-5 py-8 text-sm leading-6 text-neutral-400">{children}</div>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-neutral-800 bg-[#0a0c0c] ${className}`}>{children}</section>}
function Kicker({children}:{children:React.ReactNode}){return <div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-400">{children}</div>}

export default function CoachOperatingSystem(){
 const[data,setData]=useState<CoachPayload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState<View>('today'),[teamId,setTeamId]=useState(''),[saving,setSaving]=useState('');
 const load=useCallback(async(nextTeam?:string)=>{setLoading(true);try{const q=nextTeam||teamId;const r=await authenticatedFetch(`/api/coach${q?`?team_id=${encodeURIComponent(q)}`:''}`,{cache:'no-store',credentials:'same-origin'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Coach operating system unavailable.');setData(j);setTeamId(j.scope.selectedTeamId||'');setError('')}catch(e){setError(e instanceof Error?e.message:'Coach operating system unavailable.')}finally{setLoading(false)}},[teamId]);
 useEffect(()=>{void load();},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function act(body:Record<string,unknown>){setSaving(String(body.action||'working'));try{const r=await authenticatedFetch('/api/coach/actions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Action failed.');await load();return true}catch(e){setError(e instanceof Error?e.message:'Action failed.');return false}finally{setSaving('')}}
 const team=data?.scope.teams.find(t=>t.id===data.scope.selectedTeamId)||null;
 const attention=useMemo(()=>data?.attention.items||[],[data]);
 const openGoals=(data?.development.goals||[]).filter(g=>!['complete','completed','closed'].includes(String(g.status||'').toLowerCase()));
 const latestAssessmentByAthlete=useMemo(()=>{const m=new Map<string,any>();for(const a of data?.development.assessments||[]){if(!m.has(a.athlete_id))m.set(a.athlete_id,a)}return m},[data]);
 const canWrite=Boolean(data?.actor.personId);

 if(!data&&loading)return <main className="min-h-[65vh] p-6"><div className="mx-auto max-w-7xl"><Card className="p-8"><Kicker>Coach OS</Kicker><h1 className="mt-3 text-3xl font-black text-white">Loading your coaching environment…</h1><p className="mt-3 text-neutral-400">Assembling athletes, training, competition, schedule and attention from canonical LS1 data.</p></Card></div></main>;
 if(!data&&error)return <main className="p-6"><div className="mx-auto max-w-5xl"><Card className="p-8"><div className="flex items-center gap-2 text-red-300"><AlertTriangle className="h-5 w-5"/><b>Coach access unavailable</b></div><p className="mt-3 text-sm text-neutral-400">{error}</p></Card></div></main>;
 if(!data)return null;

 return <main className="min-h-screen bg-[#050707] px-4 py-5 text-white sm:px-6 lg:px-8">
  <div className="mx-auto max-w-[1500px] space-y-5">
   <header className="overflow-hidden rounded-[28px] border border-neutral-800 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,.12),transparent_35%),linear-gradient(135deg,#0b1110,#070909)] p-6 lg:p-8">
    <div className="flex flex-wrap items-start justify-between gap-5">
     <div><Kicker>LS1 Coach Operating System</Kicker><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Good to see you, {data.actor.displayName}.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">{data.mission} The system assembles the operating picture; coaching judgment stays with you.</p></div>
     <div className="flex items-center gap-2"><select value={teamId} onChange={e=>{setTeamId(e.target.value);void load(e.target.value)}} className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm font-bold text-white"><option value="">Select team</option>{data.scope.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-neutral-700 bg-neutral-950 p-2.5 text-neutral-300 hover:text-white" aria-label="Refresh Coach data"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
    </div>
    <div className="mt-6 flex flex-wrap gap-2">{views.map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`rounded-full px-4 py-2 text-xs font-black transition ${view===key?'bg-emerald-400 text-black':'border border-neutral-700 bg-neutral-950/60 text-neutral-300 hover:border-neutral-500'}`}>{label}</button>)}</div>
   </header>

   {error&&<div className="flex items-center gap-2 rounded-xl border border-red-900/60 bg-red-950/20 px-4 py-3 text-sm text-red-300"><AlertTriangle className="h-4 w-4"/>{error}</div>}

   {view==='today'&&<div className="space-y-5">
    <div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]">
     <Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><Kicker>Coach Attention Queue</Kicker><h2 className="mt-2 text-2xl font-black">{data.attention.counts.now?`${data.attention.counts.now} thing${data.attention.counts.now===1?'':'s'} need you now`:'Nothing urgent is waiting on you'}</h2></div><BrainCircuit className="h-6 w-6 text-emerald-400"/></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{(['now','soon','watch','fyi'] as const).map(h=><div key={h} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="text-[10px] font-black tracking-[.16em] text-neutral-500">{horizonLabel[h]}</div><div className="mt-2 text-3xl font-black">{data.attention.counts[h]}</div></div>)}</div><div className="mt-5 space-y-2">{attention.slice(0,8).map(item=><div key={item.id} className="flex flex-col gap-3 rounded-xl border border-neutral-800 bg-neutral-950/70 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black ${item.horizon==='now'?'bg-red-500/15 text-red-300':item.horizon==='soon'?'bg-amber-500/15 text-amber-300':'bg-neutral-800 text-neutral-300'}`}>{horizonLabel[item.horizon]||item.horizon}</span>{item.requires_human_judgment&&<span className="text-[9px] font-black uppercase tracking-[.12em] text-violet-300">Human judgment</span>}</div><div className="mt-2 font-bold">{item.title}</div>{item.summary&&<p className="mt-1 text-xs leading-5 text-neutral-400">{item.summary}</p>}</div>{canWrite&&<button disabled={!!saving} onClick={()=>void act({action:'resolve-attention',id:item.id})} className="rounded-lg border border-neutral-700 px-3 py-2 text-xs font-bold text-neutral-300 hover:border-emerald-500/50 hover:text-white">Resolve</button>}</div>)}{!attention.length&&<Empty>Overwatch has no open Coach attention items. This is an honest empty state; LS1 will not manufacture alerts.</Empty>}</div></Card>
     <div className="space-y-4"><Card className="p-5"><Kicker>Today's operating picture</Kicker><div className="mt-4 space-y-3"><div className="flex items-center justify-between"><span className="text-sm text-neutral-400">Roster</span><b>{data.roster.length}</b></div><div className="flex items-center justify-between"><span className="text-sm text-neutral-400">Sessions today</span><b>{data.today.attendanceSessions.length}</b></div><div className="flex items-center justify-between"><span className="text-sm text-neutral-400">Calendar items</span><b>{data.today.calendar.length}</b></div><div className="flex items-center justify-between"><span className="text-sm text-neutral-400">Open goals</span><b>{openGoals.length}</b></div></div></Card><Card className="p-5"><Kicker>Next competition</Kicker>{data.competition.upcoming[0]?<div className="mt-3"><div className="text-xl font-black">{data.competition.upcoming[0].name}</div><div className="mt-2 text-sm text-neutral-400">{fmtDate(data.competition.upcoming[0].starts_at)} · {[data.competition.upcoming[0].city,data.competition.upcoming[0].region].filter(Boolean).join(', ')||'Location pending'}</div></div>:<Empty>No upcoming canonical competition is currently available for this team scope.</Empty>}</Card></div>
    </div>
    <Card className="p-5"><Kicker>Today</Kicker><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.today.calendar.map(item=><div key={item.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="text-xs font-black uppercase tracking-[.12em] text-neutral-500">{item.event_type}</div><div className="mt-1 font-bold">{item.title}</div><div className="mt-2 text-xs text-neutral-400">{fmtTime(item.starts_at)} – {fmtTime(item.ends_at)}</div></div>)}{!data.today.calendar.length&&<Empty>No calendar events are scheduled today in the selected scope.</Empty>}</div></Card>
   </div>}

   {view==='team'&&<div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Card className="p-5"><Kicker>Team</Kicker><h2 className="mt-2 text-2xl font-black">{team?.name||'No team selected'}</h2><div className="mt-4 space-y-2 text-sm text-neutral-400"><div className="flex justify-between"><span>Competitive level</span><b className="text-white">{team?.competitive_level||'—'}</b></div><div className="flex justify-between"><span>Active athletes</span><b className="text-white">{data.roster.length}</b></div><div className="flex justify-between"><span>Training plans</span><b className="text-white">{data.training.plans.length}</b></div><div className="flex justify-between"><span>Development plans</span><b className="text-white">{data.development.plans.length}</b></div></div></Card><Card className="p-5"><Kicker>Roster</Kicker><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.roster.map(a=><button key={a.id} onClick={()=>setView('athletes')} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4 text-left hover:border-emerald-500/40"><div className="font-bold">{a.name}</div><div className="mt-1 text-xs text-neutral-500">{a.athleteNumber||'No athlete number'} · {a.status}</div></button>)}{!data.roster.length&&<Empty>No active athletes are linked to the selected team.</Empty>}</div></Card></div>}

   {view==='athletes'&&<Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><Kicker>Athlete Development</Kicker><h2 className="mt-2 text-2xl font-black">One canonical athlete. Coaching context layered on top.</h2></div><Users className="h-6 w-6 text-emerald-400"/></div><div className="mt-5 overflow-x-auto"><div className="min-w-[850px]"><div className="grid grid-cols-[1.4fr_.6fr_.7fr_.7fr_1fr] gap-4 border-b border-neutral-800 px-3 py-3 text-[10px] font-black uppercase tracking-[.12em] text-neutral-500"><span>Athlete</span><span>Status</span><span>Goals</span><span>Plans</span><span>Latest assessment</span></div>{data.roster.map(a=>{const goals=data.development.goals.filter(g=>g.athlete_id===a.id&&!['complete','completed','closed'].includes(String(g.status).toLowerCase()));const plans=data.development.plans.filter(p=>p.athlete_id===a.id);const assessment=latestAssessmentByAthlete.get(a.id);return <div key={a.id} className="grid grid-cols-[1.4fr_.6fr_.7fr_.7fr_1fr] gap-4 border-b border-neutral-900 px-3 py-4 text-sm"><div className="font-bold">{a.name}</div><div className="text-neutral-400">{a.status}</div><div>{goals.length}</div><div>{plans.length}</div><div className="text-neutral-400">{assessment?`${assessment.assessment_type} · ${fmtDate(assessment.assessed_at)}`:'No assessment'}</div></div>})}</div></div>{!data.roster.length&&<div className="mt-4"><Empty>No athletes are available in the selected Coach scope.</Empty></div>}</Card>}

   {view==='training'&&<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><Kicker>Training Plans</Kicker><div className="mt-4 space-y-3">{data.training.plans.map(p=><div key={p.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="font-bold">{p.name}</div><div className="mt-1 text-xs text-neutral-500">{p.plan_type} · {fmtDate(p.starts_on)} → {fmtDate(p.ends_on)} · {p.status}</div></div>)}{!data.training.plans.length&&<Empty>No canonical training plans exist for this team yet.</Empty>}</div></Card><Card className="p-5"><Kicker>Sessions / Workouts</Kicker><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.training.sessions.map(s=><div key={s.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="font-bold">{s.title}</div><div className="mt-1 text-xs text-neutral-500">{s.session_type||'Session'}</div><div className="mt-3 flex gap-4 text-xs text-neutral-400"><span>Distance <b className="text-white">{s.total_distance??'—'} {s.distance_unit||''}</b></span><span>Load <b className="text-white">{s.total_load??'—'}</b></span></div></div>)}{!data.training.sessions.length&&<Empty>No workout sessions are stored for the selected team. LS1 will not generate placeholder practices.</Empty>}</div></Card></div>}

   {view==='competition'&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><Kicker>Canonical upcoming</Kicker><div className="mt-2 text-3xl font-black">{data.competition.upcoming.length}</div></Card><Card className="p-5"><Kicker>Standards loaded</Kicker><div className="mt-2 text-3xl font-black">{data.competition.standardsAvailable}</div></Card><Card className="p-5"><Kicker>Athlete ranking rows</Kicker><div className="mt-2 text-3xl font-black">{data.competition.rankingsAvailable}</div></Card></div><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="p-5"><Kicker>Competition Engine — Coach lens</Kicker><div className="mt-4 space-y-3">{data.competition.upcoming.map(c=><div key={c.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{c.name}</div><div className="mt-1 text-xs text-neutral-500">{fmtDate(c.starts_at)} · {[c.city,c.region].filter(Boolean).join(', ')||'Location pending'}</div></div><span className="rounded-full border border-neutral-700 px-2 py-1 text-[9px] font-black uppercase text-neutral-400">{c.status}</span></div></div>)}{!data.competition.upcoming.length&&<Empty>No upcoming canonical competitions exist in this organization scope.</Empty>}</div></Card><Card className="p-5"><Kicker>Discovery candidates</Kicker><p className="mt-2 text-xs leading-5 text-neutral-500">Discovered meets are candidates only. They do not become Competition Engine truth without review.</p><div className="mt-4 space-y-3">{data.competition.candidates.map(c=><div key={c.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="font-bold">{c.name}</div><div className="mt-1 text-xs text-neutral-500">{c.source_name} · {fmtDate(c.starts_at)}</div>{canWrite&&<div className="mt-3 flex gap-2"><button disabled={!!saving} onClick={()=>void act({action:'review-competition-candidate',id:c.id,decision:'accepted'})} className="rounded-lg bg-emerald-400 px-3 py-1.5 text-xs font-black text-black">Accept candidate</button><button disabled={!!saving} onClick={()=>void act({action:'review-competition-candidate',id:c.id,decision:'rejected'})} className="rounded-lg border border-neutral-700 px-3 py-1.5 text-xs font-bold text-neutral-300">Reject</button></div>}</div>)}{!data.competition.candidates.length&&<Empty>No discovered competition candidates are awaiting review.</Empty>}</div></Card></div></div>}

   {view==='season'&&<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><Kicker>Coach Methodology</Kicker>{data.planning.methodologies[0]?<div className="mt-4"><div className="text-xl font-black">{data.planning.methodologies[0].name}</div><p className="mt-3 text-sm leading-6 text-neutral-400">{data.planning.methodologies[0].philosophy||'No philosophy narrative recorded.'}</p><div className="mt-3 text-xs text-neutral-500">Version {data.planning.methodologies[0].version} · {data.planning.methodologies[0].status}</div></div>:<Empty>No Coach Methodology has been approved yet. Agent recommendations should not pretend to know the coach's philosophy until one exists.</Empty>}</Card><Card className="p-5"><Kicker>Season architecture</Kicker><div className="mt-4 space-y-3">{data.planning.seasonPlans.map(p=><div key={p.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex items-start justify-between"><div><div className="font-bold">{p.name}</div><div className="mt-1 text-xs text-neutral-500">{fmtDate(p.starts_on)} → {fmtDate(p.ends_on)}</div></div><span className="text-[10px] font-black uppercase text-amber-300">{p.approval_status}</span></div><div className="mt-3 flex flex-wrap gap-2">{data.planning.cycles.filter(c=>c.season_plan_id===p.id).map(c=><span key={c.id} className="rounded-full border border-neutral-700 px-3 py-1 text-[10px] text-neutral-300">{c.cycle_type}: {c.name}</span>)}</div></div>)}{!data.planning.seasonPlans.length&&<Empty>No Coach season plan exists yet. The platform is ready to store macro/meso/micro architecture without fabricating one.</Empty>}</div></Card></div>}

   {view==='analytics'&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.dataHealth).map(([k,v])=><Card key={k} className="p-5"><div className="text-[10px] font-black uppercase tracking-[.12em] text-neutral-500">{k.replace(/([A-Z])/g,' $1')}</div><div className="mt-2 text-3xl font-black">{v}</div></Card>)}</div>}

   {view==='community'&&<Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><Kicker>Coach Knowledge Network</Kicker><h2 className="mt-2 text-2xl font-black">Structured coaching knowledge, not a social feed.</h2></div><Search className="h-6 w-6 text-emerald-400"/></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.community.map(r=><div key={r.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-neutral-500">{r.resource_type} · {r.skill_level||'all levels'}</div><div className="mt-2 font-bold">{r.title}</div>{r.objective&&<p className="mt-2 text-xs leading-5 text-neutral-400">{r.objective}</p>}<div className="mt-3 text-[10px] text-neutral-500">{r.duration_minutes?`${r.duration_minutes} min · `:''}provenance attached</div></div>)}{!data.community.length&&<Empty>No published Coach community resources are available yet.</Empty>}</div></Card>}

   {view==='ai'&&<div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><Kicker>Agents</Kicker><h2 className="mt-2 text-2xl font-black">AI proposes. Coach reviews. ERP executes.</h2></div><Sparkles className="h-6 w-6 text-emerald-400"/></div><div className="mt-5 space-y-3">{data.agents.proposals.map(p=><div key={p.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-violet-500/15 px-2 py-1 text-[9px] font-black uppercase text-violet-300">{p.agent_key}</span><span className="rounded-full border border-neutral-700 px-2 py-1 text-[9px] font-black uppercase text-neutral-400">{p.autonomy_level}</span></div><div className="mt-3 font-bold">{p.proposal_type.replace(/_/g,' ')}</div>{p.rationale&&<p className="mt-2 text-xs leading-5 text-neutral-400">{typeof p.rationale==='string'?p.rationale:JSON.stringify(p.rationale)}</p>}{canWrite&&<div className="mt-3 flex gap-2"><button disabled={!!saving} onClick={()=>void act({action:'review-agent-proposal',id:p.id,decision:'approved'})} className="rounded-lg bg-emerald-400 px-3 py-1.5 text-xs font-black text-black">Approve</button><button disabled={!!saving} onClick={()=>void act({action:'review-agent-proposal',id:p.id,decision:'rejected'})} className="rounded-lg border border-neutral-700 px-3 py-1.5 text-xs font-bold text-neutral-300">Reject</button></div>}</div>)}{!data.agents.proposals.length&&<Empty>No agent proposals are pending. LS1 does not create fake AI recommendations to fill the screen.</Empty>}</div></Card><div className="space-y-4"><Card className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-400"/><Kicker>Autonomy contract</Kicker></div><div className="mt-4 space-y-3 text-sm text-neutral-400">{[['OBSERVE','Detect and report.'],['RECOMMEND','Explain a recommendation; coach decides.'],['PREPARE','Build the action package; coach approves.'],['EXECUTE','Act only inside an explicit policy.']].map(([a,b])=><div key={a} className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><b className="text-white">{a}</b><div className="mt-1 text-xs">{b}</div></div>)}</div></Card><Card className="p-5"><Kicker>Administrative burden removed</Kicker><p className="mt-3 text-sm leading-6 text-neutral-400">The target is not more notifications. Overwatch should reconcile schedules, deadlines, eligibility, attendance, facilities and routine operational facts, then pull the coach in only when judgment is required.</p></Card></div></div>}

   <footer className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-neutral-800 bg-neutral-950/50 px-5 py-4 text-xs text-neutral-500"><span>Source: {data.source} · Live read {new Date(data.generatedAt).toLocaleTimeString()}</span><span>{data.actor.isSuperUser?'SuperUser Coach preview':'Authorized Coach scope'} · {canWrite?'governed writes enabled':'read-only until a Coach person identity is linked'}</span></footer>
  </div>
 </main>;
}
