'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';
import {ArrowLeft,BellRing,Bot,CheckCircle2,Clock3,RefreshCw,ShieldCheck,Sparkles,TriangleAlert} from 'lucide-react';
export default function CoachAutomationCenter(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[teamId,setTeamId]=useState(''),[working,setWorking]=useState('');
 const load=useCallback(async(next?:string)=>{setLoading(true);try{const t=next||teamId;const r=await authenticatedFetch(`/api/coach${t?`?team_id=${encodeURIComponent(t)}`:''}`,{cache:'no-store',credentials:'same-origin'}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Coach automation data unavailable.');setData(j);setTeamId(j.scope?.selectedTeamId||'');setError('')}catch(e){setError(e instanceof Error?e.message:'Coach automation data unavailable.')}finally{setLoading(false)}},[teamId]);
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function post(url:string,body:any,key:string){setWorking(key);try{const r=await authenticatedFetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Action failed.');await load();return j}catch(e){setError(e instanceof Error?e.message:'Action failed.');return null}finally{setWorking('')}}
 const attention=data?.attention?.items||[],proposals=data?.agents?.proposals||[],counts=data?.attention?.counts||{now:0,soon:0,watch:0,fyi:0};
 const ordered=useMemo(()=>[...attention].sort((a:any,b:any)=>({now:0,soon:1,watch:2,fyi:3}[a.horizon as 'now'|'soon'|'watch'|'fyi']??9)-({now:0,soon:1,watch:2,fyi:3}[b.horizon as 'now'|'soon'|'watch'|'fyi']??9)),[attention]);
 const handled=Math.max(0,(data?.dataHealth?.attention||0)+(data?.dataHealth?.agentProposals||0));
 return <main className="min-h-screen bg-[#050707] px-4 py-5 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1550px] space-y-5">
 <header className="rounded-[30px] border border-neutral-800 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,.17),transparent_38%),linear-gradient(135deg,#081411,#070909)] p-6 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/coach" className="inline-flex items-center gap-2 text-xs font-black text-neutral-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Coach OS</Link><div className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-emerald-300">Overwatch · Attention · Agent Governance</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">Coach Automation Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">LS1 continuously assembles exceptions and prepared agent work so the coach can make the few decisions that require human judgment.</p></div><div className="flex flex-wrap gap-2"><select value={teamId} onChange={e=>{setTeamId(e.target.value);void load(e.target.value)}} className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm font-bold">{(data?.scope?.teams||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-neutral-700 bg-neutral-950 p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><button disabled={!teamId||!!working} onClick={()=>void post('/api/coach/overwatch',{team_id:teamId},'overwatch')} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-black text-black disabled:opacity-50"><Sparkles className="h-4 w-4"/>{working==='overwatch'?'Scanning…':'Run Overwatch'}</button></div></div></header>
 {error&&<div className="rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['NOW',counts.now,'Decide / act','text-red-300'],['SOON',counts.soon,'Prepare next','text-amber-300'],['WATCH',counts.watch,'Monitor pattern','text-cyan-300'],['FYI',counts.fyi,'Awareness','text-neutral-300'],['ASSEMBLED',handled,'Items LS1 surfaced','text-emerald-300']].map(([label,value,sub,cls]:any)=><div key={label} className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-4"><div className={`text-[10px] font-black uppercase tracking-[.16em] ${cls}`}>{label}</div><div className="mt-2 text-3xl font-black">{value}</div><div className="mt-1 text-xs text-neutral-500">{sub}</div></div>)}</section>
 <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-300">Attention Queue</div><h2 className="mt-1 text-2xl font-black">What actually needs you</h2></div><BellRing className="h-5 w-5 text-emerald-300"/></div><div className="mt-4 space-y-3">{ordered.length?ordered.map((item:any)=><div key={item.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase tracking-[.12em] ${item.horizon==='now'?'bg-red-500/20 text-red-300':item.horizon==='soon'?'bg-amber-500/20 text-amber-300':item.horizon==='watch'?'bg-cyan-500/20 text-cyan-300':'bg-neutral-800 text-neutral-300'}`}>{item.horizon}</span>{item.requires_human_judgment&&<span className="inline-flex items-center gap-1 text-[10px] font-bold text-violet-300"><ShieldCheck className="h-3.5 w-3.5"/>human judgment</span>}</div><div className="mt-2 font-black">{item.title}</div><div className="mt-1 text-xs leading-5 text-neutral-400">{item.summary||item.category}</div>{item.due_at&&<div className="mt-2 inline-flex items-center gap-1 text-[10px] text-neutral-500"><Clock3 className="h-3 w-3"/>{new Date(item.due_at).toLocaleString()}</div>}</div><button disabled={!!working} onClick={()=>void post('/api/coach/actions',{action:'resolve-attention',id:item.id,resolution_note:'Resolved from Coach Automation Center'},`resolve-${item.id}`)} className="rounded-lg border border-neutral-700 px-3 py-2 text-xs font-black hover:bg-neutral-800 disabled:opacity-50">{working===`resolve-${item.id}`?'Saving…':'Resolve'}</button></div></div>):<div className="rounded-xl border border-dashed border-neutral-700 p-8 text-center text-sm text-neutral-400">No open attention items. Run Overwatch to refresh against canonical LS1 operational data.</div>}</div></div>
 <div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-violet-300">Agent Work Queue</div><h2 className="mt-1 text-2xl font-black">Prepared for review</h2></div><Bot className="h-5 w-5 text-violet-300"/></div><div className="mt-4 space-y-3">{proposals.length?proposals.map((p:any)=><div key={p.id} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-violet-300">{String(p.agent_key||'agent').replaceAll('_',' ')}</div><div className="mt-1 font-black">{String(p.proposal_type||'proposal').replaceAll('_',' ')}</div></div><span className="rounded-full bg-neutral-800 px-2 py-1 text-[9px] font-black uppercase text-neutral-300">{p.autonomy_level}</span></div><div className="mt-3 text-xs leading-5 text-neutral-400">{p.rationale?.principle||'Prepared from canonical LS1 context.'}</div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={!!working} onClick={()=>void post('/api/coach/actions',{action:'review-agent-proposal',id:p.id,decision:'approved',decision_note:'Approved in Coach Automation Center; domain execution remains governed by owning workflow.'},`approve-${p.id}`)} className="rounded-lg bg-emerald-400 px-3 py-2 text-xs font-black text-black disabled:opacity-50">Approve</button><button disabled={!!working} onClick={()=>void post('/api/coach/actions',{action:'review-agent-proposal',id:p.id,decision:'rejected',decision_note:'Rejected in Coach Automation Center.'},`reject-${p.id}`)} className="rounded-lg border border-neutral-700 px-3 py-2 text-xs font-black disabled:opacity-50">Reject</button></div></div>):<div className="rounded-xl border border-dashed border-neutral-700 p-8 text-center text-sm text-neutral-400">No prepared agent proposals are waiting.</div>}</div><div className="mt-4 rounded-xl border border-amber-700/40 bg-amber-950/20 p-3 text-[11px] leading-5 text-amber-200"><TriangleAlert className="mr-1 inline h-3.5 w-3.5"/>Approval here records the coaching decision. Specialized execution remains inside the owning agent/workflow so LS1 never bypasses domain authority.</div></div></section>
 <section className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-300"/><b>Operating principle</b></div><p className="mt-2 max-w-4xl text-sm leading-6 text-neutral-400">Overwatch watches. Agents prepare. The queue compresses complexity. The coach decides. Authorized ERP workflows execute. This page is the control surface for that contract—not a chatbot and not a notification dump.</p></section>
 </div></main>;
}
