'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';
import {ArrowLeft,CalendarRange,CheckCircle2,RefreshCw,Sparkles,Target,Workflow} from 'lucide-react';
export default function CoachSeasonPlanningAgent(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[teamId,setTeamId]=useState(''),[saving,setSaving]=useState(''),[competitionId,setCompetitionId]=useState(''),[goal,setGoal]=useState(''),[constraints,setConstraints]=useState('');
 const load=useCallback(async(next?:string)=>{setLoading(true);try{const t=next||teamId;const r=await authenticatedFetch(`/api/coach/season-agent${t?`?team_id=${encodeURIComponent(t)}`:''}`,{cache:'no-store',credentials:'same-origin'}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Season Planning Agent unavailable.');setData(j);setTeamId(j.selectedTeamId||'');if(!competitionId&&j.context?.competitions?.length)setCompetitionId(j.context.competitions[j.context.competitions.length-1].id);setError('')}catch(e){setError(e instanceof Error?e.message:'Season Planning Agent unavailable.')}finally{setLoading(false)}},[teamId,competitionId]);
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function act(body:any){setSaving(body.action);try{const r=await authenticatedFetch('/api/coach/season-agent',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Season Planning Agent action failed.');await load();return j}catch(e){setError(e instanceof Error?e.message:'Season Planning Agent action failed.');return null}finally{setSaving('')}}
 const ctx=data?.context||{},latest=data?.proposals?.[0]||null,p=latest?.proposal||null,cycles=p?.cycles||[];
 const quality=useMemo(()=>p?.data_quality?Object.entries(p.data_quality).filter(([k,v])=>k!=='competition_count'&&Boolean(v)).length:0,[p]);
 return <main className="min-h-screen bg-[#050707] px-4 py-5 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
 <header className="rounded-[28px] border border-neutral-800 bg-[radial-gradient(circle_at_top_right,rgba(59,130,246,.18),transparent_40%),linear-gradient(135deg,#0b1220,#070909)] p-6 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/coach" className="inline-flex items-center gap-2 text-xs font-black text-neutral-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Coach OS</Link><div className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-blue-300">Agentic Season Architecture</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">Season Planning Agent</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">LS1 works backward from your priority competition and methodology to prepare a season architecture. The coach reviews and approves before it becomes authoritative.</p></div><div className="flex gap-2"><select value={teamId} onChange={e=>{setTeamId(e.target.value);void load(e.target.value)}} className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm font-bold">{(data?.teams||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-neutral-700 bg-neutral-950 p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div></header>
 {error&&<div className="rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}
 <section className="grid gap-4 lg:grid-cols-[.78fr_1.22fr]"><div className="space-y-4"><div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center gap-2"><CalendarRange className="h-5 w-5 text-blue-300"/><b>Planning context</b></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm">{[['Season',ctx.season?.name||'No canonical season'],['Methodology',ctx.methodology?.name||'Not configured'],['Competitions',ctx.competitions?.length||0],['Existing plans',data?.plans?.length||0]].map(([k,v]:any)=><div key={k} className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><div className="text-[10px] font-black uppercase tracking-[.12em] text-neutral-500">{k}</div><div className="mt-1 font-bold">{v}</div></div>)}</div></div>
 <div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="text-[10px] font-black uppercase tracking-[.16em] text-blue-300">Set the destination</div><div className="mt-4 space-y-3"><select value={competitionId} onChange={e=>setCompetitionId(e.target.value)} className="w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"><option value="">Select primary competition</option>{(ctx.competitions||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name} · {String(c.starts_at||'').slice(0,10)}</option>)}</select><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Primary season outcome / championship objective" className="min-h-24 w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><textarea value={constraints} onChange={e=>setConstraints(e.target.value)} placeholder="Known constraints: camps, school breaks, facility limits, travel, protected recovery..." className="min-h-24 w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><button disabled={!teamId||!competitionId||!!saving} onClick={()=>void act({action:'generate-proposal',team_id:teamId,primary_competition_id:competitionId,goal,constraints})} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-400 px-4 py-3 text-sm font-black text-black disabled:opacity-50"><Sparkles className="h-4 w-4"/>{saving==='generate-proposal'?'Building architecture…':'Prepare season architecture'}</button></div></div></div>
 <div className="space-y-4"><div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-400">Coach approval gate</div><h2 className="mt-2 text-2xl font-black">{p?.name||'No season proposal prepared'}</h2></div><Workflow className="h-6 w-6 text-emerald-400"/></div>{p?<><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><Target className="h-4 w-4 text-blue-300"/><div className="mt-2 text-sm font-bold">{p.primary_competition?.name||'No primary competition'}</div></div><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><CalendarRange className="h-4 w-4 text-blue-300"/><div className="mt-2 text-sm font-bold">{p.starts_on} → {p.ends_on}</div></div><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><CheckCircle2 className="h-4 w-4 text-blue-300"/><div className="mt-2 text-sm font-bold">{quality}/3 core context signals</div></div></div><div className="mt-5 space-y-3">{cycles.map((c:any,i:number)=><div key={`${c.name}-${i}`} className="rounded-xl border border-neutral-800 bg-neutral-950 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-blue-300">{c.phase}</div><div className="mt-1 text-lg font-black">{c.name}</div><div className="mt-1 text-xs text-neutral-400">{c.objective}</div></div><div className="text-right text-xs"><div className="font-bold">{c.starts_on} → {c.ends_on}</div><div className="mt-1 text-neutral-500">Load target {c.load_target}</div></div></div></div>)}</div><div className="mt-5 rounded-xl border border-amber-700/50 bg-amber-950/20 p-4 text-xs leading-5 text-amber-200">This architecture is deterministic planning support, not autonomous coaching. Review dates, objectives and load progression before approval.</div><button disabled={!!saving||latest?.status==='approved'} onClick={()=>void act({action:'approve-plan',team_id:teamId,proposal_id:latest.id})} className="mt-4 w-full rounded-xl bg-emerald-400 px-5 py-3 text-sm font-black text-black disabled:opacity-50">{saving==='approve-plan'?'Publishing…':latest?.status==='approved'?'Approved':'Approve → authoritative season plan'}</button></>:<div className="mt-5 rounded-xl border border-dashed border-neutral-700 p-8 text-sm text-neutral-400">Choose the priority competition and ask LS1 to prepare the architecture. LS1 will not invent a season plan before the coach sets the destination.</div>}</div></div></section>
 </div></main>;
}
