'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {authenticatedFetch} from '@/lib/client/authenticatedFetch';
import {ArrowLeft,BrainCircuit,CheckCircle2,RefreshCw,Sparkles,ShieldCheck,Target,Users} from 'lucide-react';

export default function CoachWorkoutAgent(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[teamId,setTeamId]=useState(''),[saving,setSaving]=useState(''),[title,setTitle]=useState(''),[objective,setObjective]=useState(''),[skill,setSkill]=useState(''),[distance,setDistance]=useState('4000'),[duration,setDuration]=useState('90'),[planId,setPlanId]=useState('');
 const load=useCallback(async(next?:string)=>{setLoading(true);try{const t=next||teamId;const r=await authenticatedFetch(`/api/coach/workout-agent${t?`?team_id=${encodeURIComponent(t)}`:''}`,{cache:'no-store',credentials:'same-origin'}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Workout Agent unavailable.');setData(j);setTeamId(j.selectedTeamId||'');setError('')}catch(e){setError(e instanceof Error?e.message:'Workout Agent unavailable.')}finally{setLoading(false)}},[teamId]);
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function act(body:any){setSaving(body.action);try{const r=await authenticatedFetch('/api/coach/workout-agent',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Workout Agent action failed.');await load();return j}catch(e){setError(e instanceof Error?e.message:'Workout Agent action failed.');return null}finally{setSaving('')}}
 const ctx=data?.context||{},latest=data?.proposals?.[0]||null,proposal=latest?.proposal||null,quality=proposal?.data_quality||null;
 const complete=useMemo(()=>quality?Object.entries(quality).filter(([k,v])=>k!=='roster_size'&&Boolean(v)).length:0,[quality]);
 return <main className="min-h-screen bg-[#050707] px-4 py-5 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
  <header className="rounded-[28px] border border-neutral-800 bg-[radial-gradient(circle_at_top_right,rgba(168,85,247,.16),transparent_38%),linear-gradient(135deg,#111019,#070909)] p-6 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/coach" className="inline-flex items-center gap-2 text-xs font-black text-neutral-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Coach OS</Link><div className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-violet-300">Agentic Training Design</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">Workout Generation Agent</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">LS1 assembles a proposal from your methodology, season architecture, roster, training history and competition context. It does not become an official workout until you approve it.</p></div><div className="flex gap-2"><select value={teamId} onChange={e=>{setTeamId(e.target.value);void load(e.target.value)}} className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm font-bold">{(data?.teams||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-neutral-700 bg-neutral-950 p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div></header>
  {error&&<div className="rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}
  <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-violet-300"/><b>Agent context</b></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm">{[['Methodology',ctx.methodology?.name||'Not configured'],['Season plan',ctx.seasonPlan?.name||'Not active'],['Active cycle',ctx.cycles?.[0]?.name||ctx.cycles?.[0]?.cycle_type||'Not active'],['Roster',ctx.rosterSize??0],['Training history',ctx.trainingLogCount??0],['Next meet',ctx.competitions?.[0]?.name||'None in 45 days']].map(([k,v]:any)=><div key={k} className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><div className="text-[10px] font-black uppercase tracking-[.12em] text-neutral-500">{k}</div><div className="mt-1 font-bold">{v}</div></div>)}</div></div>
  <div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="text-[10px] font-black uppercase tracking-[.16em] text-violet-300">Ask the agent to prepare</div><div className="mt-4 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Session title (optional)" className="w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Primary objective" className="min-h-24 w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><input value={skill} onChange={e=>setSkill(e.target.value)} placeholder="Skill / technical focus" className="w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><input value={distance} onChange={e=>setDistance(e.target.value)} inputMode="numeric" placeholder="Distance" className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><input value={duration} onChange={e=>setDuration(e.target.value)} inputMode="numeric" placeholder="Minutes" className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/></div><button disabled={!teamId||!!saving} onClick={()=>void act({action:'generate-proposal',team_id:teamId,title,primary_objective:objective,skill_focus:skill,target_distance:Number(distance),duration_minutes:Number(duration),distance_unit:'m'})} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-400 px-4 py-3 text-sm font-black text-black disabled:opacity-50"><Sparkles className="h-4 w-4"/>{saving==='generate-proposal'?'Preparing…':'Prepare workout proposal'}</button></div></div></div>
  <div className="space-y-4"><div className="rounded-2xl border border-neutral-800 bg-[#0a0c0c] p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-400">Coach approval gate</div><h2 className="mt-2 text-2xl font-black">{proposal?.title||'No proposal prepared yet'}</h2></div><ShieldCheck className="h-6 w-6 text-emerald-400"/></div>{proposal?<><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><Target className="h-4 w-4 text-violet-300"/><div className="mt-2 text-sm font-bold">{proposal.primary_objective}</div></div><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><Users className="h-4 w-4 text-violet-300"/><div className="mt-2 text-sm font-bold">{proposal.individualization?.athletes_in_scope||0} athletes</div></div><div className="rounded-xl border border-neutral-800 bg-neutral-950 p-3"><CheckCircle2 className="h-4 w-4 text-violet-300"/><div className="mt-2 text-sm font-bold">{complete}/5 context signals present</div></div></div><div className="mt-5 space-y-2">{(proposal.blocks||[]).map((b:any,i:number)=><div key={i} className="grid gap-3 rounded-xl border border-neutral-800 bg-neutral-950 p-4 sm:grid-cols-[1fr_.45fr_.45fr]"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-neutral-500">{b.block_type}</div><div className="mt-1 font-bold">{b.title}</div><div className="mt-1 text-xs text-neutral-400">{b.objective}</div></div><div className="text-sm"><div className="text-neutral-500">Distance</div><b>{b.distance} {proposal.distance_unit}</b></div><div className="text-sm"><div className="text-neutral-500">Intensity</div><b>{b.intensity}</b></div></div>)}</div><div className="mt-5 rounded-xl border border-amber-700/50 bg-amber-950/20 p-4 text-xs leading-5 text-amber-200">This is a prepared recommendation, not an authoritative session. Review the blocks, athlete context and source completeness before approval.</div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={planId} onChange={e=>setPlanId(e.target.value)} placeholder="Training plan ID to publish into" className="rounded-xl border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"/><button disabled={!planId||!!saving} onClick={()=>void act({action:'approve-to-session',team_id:teamId,proposal_id:latest.id,training_plan_id:planId})} className="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-black text-black disabled:opacity-50">{saving==='approve-to-session'?'Publishing…':'Approve → official session'}</button></div></>:<div className="mt-5 rounded-xl border border-dashed border-neutral-700 p-8 text-sm text-neutral-400">No agent proposal exists yet. LS1 will not invent a workout card until the coach asks the agent to prepare one.</div>}</div>
  </div></section>
 </div></main>;
}
