-- Organization-scoped URWS Admin authorization. Child tables scope through their parent case when needed.
do $$ declare t text; begin
 foreach t in array array['urws_cases','urws_evidence_items','urws_policy_evaluations','urws_decisions','urws_financial_commitments','urws_financial_recoveries','urws_expected_transitions','urws_decision_packets','urws_obligations','urws_remedies','urws_case_communications'] loop
   if not exists(select 1 from pg_policies where schemaname='public' and tablename=t and policyname=t||'_admin_read') then execute format('create policy %I on public.%I for select to authenticated using (app.has_admin_role(array[''org_admin'',''registrar'',''treasurer'',''operations'']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())))',t||'_admin_read',t); end if;
 end loop;
 foreach t in array array['urws_case_status_history','urws_case_participants','urws_precedent_links'] loop
   if not exists(select 1 from pg_policies where schemaname='public' and tablename=t and policyname=t||'_admin_read') then execute format('create policy %I on public.%I for select to authenticated using (app.has_admin_role(array[''org_admin'',''registrar'',''treasurer'',''operations'']) and exists(select 1 from public.urws_cases c join public.organizations o on o.id=c.organization_id where c.id=%I.case_id and o.tenant_id in (select app.current_tenant_ids())))',t||'_admin_read',t,t); end if;
 end loop;
end $$;
create policy urws_cases_admin_insert on public.urws_cases for insert to authenticated with check (app.has_admin_role(array['org_admin','operations','registrar']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
create policy urws_cases_admin_update on public.urws_cases for update to authenticated using (app.has_admin_role(array['org_admin','operations','registrar']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids()))) with check (app.has_admin_role(array['org_admin','operations','registrar']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
create policy urws_evidence_items_admin_insert on public.urws_evidence_items for insert to authenticated with check (sensitivity='standard' and app.has_admin_role(array['org_admin','operations','registrar','treasurer']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
create policy urws_decisions_admin_insert on public.urws_decisions for insert to authenticated with check (app.has_admin_role(array['org_admin','treasurer']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
create policy urws_remedies_admin_insert on public.urws_remedies for insert to authenticated with check (app.has_admin_role(array['org_admin','treasurer']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
create policy urws_remedies_admin_update on public.urws_remedies for update to authenticated using (app.has_admin_role(array['org_admin','treasurer']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids()))) with check (app.has_admin_role(array['org_admin','treasurer']) and organization_id in (select o.id from public.organizations o where o.tenant_id in (select app.current_tenant_ids())));
grant select on public.urws_cases,public.urws_case_status_history,public.urws_case_participants,public.urws_evidence_items,public.urws_policy_evaluations,public.urws_decisions,public.urws_financial_commitments,public.urws_financial_recoveries,public.urws_expected_transitions,public.urws_decision_packets,public.urws_obligations,public.urws_remedies,public.urws_case_communications,public.urws_precedent_links to authenticated;
grant insert,update on public.urws_cases to authenticated;
grant insert on public.urws_evidence_items,public.urws_decisions to authenticated;
grant insert,update on public.urws_remedies to authenticated;
