-- Parent / Family OS foundation: family permissions, task center, inbox, logistics and custody.
create table if not exists public.family_authorizations (id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,person_id uuid not null references public.people(id) on delete cascade,authority_type text not null check (authority_type in ('PRIMARY_ACCOUNT','FINANCIAL','MEDICAL','PICKUP','EMERGENCY','COMMUNICATIONS')),is_active boolean not null default true,valid_from timestamptz,valid_until timestamptz,created_at timestamptz not null default now(),unique(family_id,person_id,authority_type));
create table if not exists public.family_tasks (id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,athlete_id uuid references public.athletes(id) on delete cascade,title text not null,description text,route text not null,deadline timestamptz,consequence_tier text,priority text not null default 'NORMAL' check(priority in ('LOW','NORMAL','HIGH','URGENT')),status text not null default 'OPEN' check(status in ('OPEN','PENDING_VERIFICATION','COMPLETED','DISMISSED')),created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.family_messages (id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,athlete_id uuid references public.athletes(id) on delete cascade,category text not null check(category in ('URGENT','ACTION_REQUIRED','FINANCIAL','COACH_ANNOUNCEMENT','GENERAL')),title text not null,body text,route text,acknowledged_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.logistics_trips (id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,athlete_id uuid references public.athletes(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz,pickup_location text,dropoff_location text,transportation_mode text not null default 'PARENT_DRIVEN',assigned_driver_person_id uuid references public.people(id) on delete set null,safesport_status text,supervision_status text not null default 'PENDING',created_at timestamptz not null default now());
create table if not exists public.custody_events (id uuid primary key default gen_random_uuid(),athlete_id uuid not null references public.athletes(id) on delete cascade,family_id uuid references public.families(id) on delete cascade,occurred_at timestamptz not null default now(),event_type text not null check(event_type in ('PARENT_CHECKIN','CLUB_HANDOFF','SESSION_START','SESSION_END','PARENT_CHECKOUT')),responsible_person_id uuid references public.people(id) on delete set null,note text,created_at timestamptz not null default now());
create table if not exists public.volunteer_opportunities (id uuid primary key default gen_random_uuid(),organization_id uuid,title text not null,starts_at timestamptz,ends_at timestamptz,credits numeric not null default 0,capacity integer,status text not null default 'OPEN',created_at timestamptz not null default now());
alter table public.family_authorizations enable row level security; alter table public.family_tasks enable row level security; alter table public.family_messages enable row level security; alter table public.logistics_trips enable row level security; alter table public.custody_events enable row level security; alter table public.volunteer_opportunities enable row level security;
-- Policies intentionally absent until identity-to-family claims are wired; default deny prevents public exposure.
