create table if not exists public.membership_policy_versions (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, policy_key text not null, name text not null, version integer not null default 1, body text not null, rules jsonb not null default '{}'::jsonb, effective_from date not null, effective_to date, status text not null default 'draft' check (status in ('draft','active','retired')), created_by_person_id uuid, created_at timestamptz not null default now(), unique(organization_id,policy_key,version)
);
create table if not exists public.membership_policy_acceptances (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, policy_version_id uuid not null references public.membership_policy_versions(id), membership_id uuid references public.memberships(id), person_id uuid not null, athlete_person_id uuid, accepted_by_person_id uuid, accepted_at timestamptz not null default now(), acknowledgement_method text not null default 'electronic', evidence jsonb not null default '{}'::jsonb
);
create table if not exists public.membership_exceptions (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, membership_id uuid not null references public.memberships(id), exception_type text not null check (exception_type in ('pause','medical_pause','billing_pause','cancellation_exception','refund_exception','other')), reason_category text, requested_start_on date, requested_end_on date, approved_start_on date, approved_end_on date, billing_resume_on date, status text not null default 'requested' check (status in ('requested','approved','declined','active','completed','cancelled')), policy_version_id uuid references public.membership_policy_versions(id), policy_overridden boolean not null default false, requested_by_person_id uuid, decided_by_person_id uuid, decided_at timestamptz, decision_note text, restricted_details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.membership_lifecycle_events (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, membership_id uuid not null references public.memberships(id), event_type text not null, effective_at timestamptz not null default now(), actor_person_id uuid, source_type text, source_id uuid, summary text not null, evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.refund_requests (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, membership_id uuid references public.memberships(id), requested_by_person_id uuid, amount numeric(12,2) not null check(amount>=0), currency char(3) not null default 'CAD', requested_at timestamptz not null default now(), reason text, status text not null default 'requested' check(status in ('requested','under_review','approved','declined','escalated','processed','cancelled')), applicable_policy_version_id uuid references public.membership_policy_versions(id), policy_eligibility text not null default 'unassessed' check(policy_eligibility in ('unassessed','eligible','outside_policy','exception_required')), decision_packet jsonb not null default '{}'::jsonb, recommended_disposition text, decided_by_person_id uuid, decided_at timestamptz, decision_note text, resulting_refund_id uuid references public.refunds(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.membership_automation_events (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, membership_id uuid references public.memberships(id), event_key text not null, due_at timestamptz, status text not null default 'pending' check(status in ('pending','prepared','executed','dismissed','failed')), payload jsonb not null default '{}'::jsonb, executed_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists membership_exceptions_membership_idx on public.membership_exceptions(membership_id,status);
create index if not exists membership_lifecycle_events_membership_idx on public.membership_lifecycle_events(membership_id,effective_at desc);
create index if not exists refund_requests_membership_idx on public.refund_requests(membership_id,requested_at desc);
create index if not exists membership_automation_due_idx on public.membership_automation_events(status,due_at);
alter table public.membership_policy_versions enable row level security; alter table public.membership_policy_acceptances enable row level security; alter table public.membership_exceptions enable row level security; alter table public.membership_lifecycle_events enable row level security; alter table public.refund_requests enable row level security; alter table public.membership_automation_events enable row level security;
create policy membership_policy_versions_superuser on public.membership_policy_versions for all to authenticated using (app.is_superuser()) with check(app.is_superuser());
create policy membership_policy_acceptances_superuser on public.membership_policy_acceptances for all to authenticated using (app.is_superuser()) with check(app.is_superuser());
create policy membership_exceptions_superuser on public.membership_exceptions for all to authenticated using (app.is_superuser()) with check(app.is_superuser());
create policy membership_lifecycle_events_superuser on public.membership_lifecycle_events for all to authenticated using (app.is_superuser()) with check(app.is_superuser());
create policy refund_requests_superuser on public.refund_requests for all to authenticated using (app.is_superuser()) with check(app.is_superuser());
create policy membership_automation_events_superuser on public.membership_automation_events for all to authenticated using (app.is_superuser()) with check(app.is_superuser());