-- Scout Engine: simple talent intelligence with NCAA governance as a hard boundary.
create table if not exists public.scout_access_assignments(id uuid primary key default gen_random_uuid(),user_id uuid not null,person_id uuid,recruiting_program_id uuid references public.recruiting_programs(id) on delete set null,role text not null default 'scout',active boolean not null default true,created_at timestamptz not null default now(),unique(user_id,recruiting_program_id));
create table if not exists public.scout_watchlist(id uuid primary key default gen_random_uuid(),scout_user_id uuid not null,athlete_id uuid not null references public.athletes(id) on delete cascade,recruiting_program_id uuid references public.recruiting_programs(id) on delete set null,status text not null default 'watching' check(status in('watching','priority','contacted','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(scout_user_id,athlete_id,recruiting_program_id));
create table if not exists public.scout_notes(id uuid primary key default gen_random_uuid(),scout_user_id uuid not null,athlete_id uuid not null references public.athletes(id) on delete cascade,note text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.scout_governance_rules(id uuid primary key default gen_random_uuid(),governing_body text not null default 'NCAA',division text not null,sport_code text not null,action_type text not null,prospect_stage text not null default 'any',period_type text not null default 'any',allowed boolean not null default false,effective_from date not null,effective_to date,source_url text not null,source_label text not null,rule_reference text not null,rule_version text not null,notes text,created_at timestamptz not null default now(),unique(governing_body,division,sport_code,action_type,prospect_stage,period_type,effective_from,rule_version));
create table if not exists public.scout_governed_actions(id uuid primary key default gen_random_uuid(),scout_user_id uuid not null,athlete_id uuid not null references public.athletes(id) on delete cascade,recruiting_program_id uuid references public.recruiting_programs(id) on delete set null,action_type text not null,requested_at timestamptz not null default now(),determination text not null check(determination in('allowed','blocked')),governance_rule_id uuid references public.scout_governance_rules(id) on delete restrict,governing_body text not null default 'NCAA',division text,sport_code text,prospect_stage text,period_type text,rule_reference text,rule_version text,source_url text,reason text not null,metadata jsonb not null default '{}'::jsonb);
create index if not exists scout_watchlist_user_idx on public.scout_watchlist(scout_user_id,status);create index if not exists scout_notes_athlete_idx on public.scout_notes(athlete_id,created_at desc);create index if not exists scout_rules_lookup_idx on public.scout_governance_rules(governing_body,division,sport_code,action_type,effective_from,effective_to);create index if not exists scout_actions_audit_idx on public.scout_governed_actions(scout_user_id,requested_at desc);
alter table public.scout_access_assignments enable row level security;alter table public.scout_watchlist enable row level security;alter table public.scout_notes enable row level security;alter table public.scout_governance_rules enable row level security;alter table public.scout_governed_actions enable row level security;
create policy scout_assignment_self_read on public.scout_access_assignments for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true));
create policy scout_watchlist_self on public.scout_watchlist for all to authenticated using(scout_user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true)) with check(scout_user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true));
create policy scout_notes_self on public.scout_notes for all to authenticated using(scout_user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true)) with check(scout_user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true));
create policy scout_rules_read on public.scout_governance_rules for select to authenticated using(exists(select 1 from public.scout_access_assignments a where a.user_id=auth.uid() and a.active=true) or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true));
create policy scout_actions_self_read on public.scout_governed_actions for select to authenticated using(scout_user_id=auth.uid() or exists(select 1 from public.platform_superuser_operators p where p.auth_user_id=auth.uid() and p.active=true));
revoke insert,update,delete on public.scout_governance_rules from authenticated;revoke insert,update,delete on public.scout_governed_actions from authenticated;grant select on public.scout_governance_rules,public.scout_governed_actions,public.scout_access_assignments to authenticated;grant select,insert,update,delete on public.scout_watchlist,public.scout_notes to authenticated;
comment on table public.scout_governance_rules is 'Versioned NCAA governance source. Regulated Scout actions fail closed unless an explicit effective rule permits them.';comment on table public.scout_governed_actions is 'Immutable compliance audit. Governed actions are server-written only after NCAA rule evaluation.';
