-- Seed data applied live in migration seed_athlete_age_experience_profiles_and_challenges_v2.
-- Canonical seed definitions retained in database migration history; repository follows with deterministic inserts for HPAC.
insert into public.athlete_experience_rules (tenant_id,sport_id,code,name,age_min,age_max,skill_band,feature_key,configuration,priority)
select t.id,s.id,v.code,v.name,v.age_min,v.age_max,v.skill_band,v.feature_key,v.configuration,v.priority from public.tenants t join public.sports s on s.code='SWIMMING' cross join (values
('AGE_5_8_HOME','5-8 Home Experience',5,8,null,'home',jsonb_build_object('focus','fun'),10),('AGE_9_12_HOME','9-12 Home Experience',9,12,null,'home',jsonb_build_object('focus','guided-growth'),20),('AGE_13_17_HOME','13-17 Home Experience',13,17,null,'home',jsonb_build_object('focus','performance-awareness'),30),('AGE_18_PLUS_HOME','18+ Home Experience',18,99,null,'home',jsonb_build_object('focus','autonomy'),40)
) v(code,name,age_min,age_max,skill_band,feature_key,configuration,priority) where t.code='HPAC' and not exists(select 1 from public.athlete_experience_rules r where r.tenant_id=t.id and r.code=v.code);
insert into public.athlete_challenges (tenant_id,sport_id,code,name,description,age_band,challenge_type,target_definition,reward_definition,active)
select t.id,s.id,v.code,v.name,v.description,v.age_band,v.challenge_type,v.target_definition,v.reward_definition,true from public.tenants t join public.sports s on s.code='SWIMMING' cross join (values
('FIRST_WEEK','First Week Ready','Complete your first week of participation','5_8','attendance',jsonb_build_object('target',3,'unit','sessions'),jsonb_build_object('badge','FIRST_WEEK')),
('POOL_EXPLORER','Pool Explorer','Try three different swimming skills or activities','5_8','skill',jsonb_build_object('target',3,'unit','skills'),jsonb_build_object('badge','POOL_EXPLORER')),
('CONSISTENCY','Consistency Builder','Build a consistent training streak','9_12','attendance',jsonb_build_object('target',8,'unit','sessions'),jsonb_build_object('badge','CONSISTENCY')),
('PERSONAL_BEST','Personal Best','Improve a recorded performance','9_12','performance',jsonb_build_object('target',1,'unit','improvement'),jsonb_build_object('badge','PERSONAL_BEST')),
('OWN_YOUR_PLAN','Own Your Plan','Keep your development plan current','13_17','development',jsonb_build_object('target',1,'unit','plan_cycle'),jsonb_build_object('badge','OWN_YOUR_PLAN'))
) v(code,name,description,age_band,challenge_type,target_definition,reward_definition) where t.code='HPAC' and not exists(select 1 from public.athlete_challenges c where c.tenant_id=t.id and c.code=v.code);
insert into public.athlete_badges (tenant_id,code,name,description,age_band,badge_definition,active)
select t.id,v.code,v.name,v.description,v.age_band,v.badge_definition,true from public.tenants t cross join (values
('FIRST_WEEK','First Week','Completed the first week','5_8',jsonb_build_object('category','participation')),('POOL_EXPLORER','Pool Explorer','Explored new skills','5_8',jsonb_build_object('category','skill')),('CONSISTENCY','Consistency Builder','Built a training streak','9_12',jsonb_build_object('category','habit')),('PERSONAL_BEST','Personal Best','Improved a performance','9_12',jsonb_build_object('category','performance')),('OWN_YOUR_PLAN','Own Your Plan','Took ownership of development','13_17',jsonb_build_object('category','development'))
) v(code,name,description,age_band,badge_definition) where t.code='HPAC' and not exists(select 1 from public.athlete_badges b where b.tenant_id=t.id and b.code=v.code);
insert into public.athlete_experience_profiles (tenant_id,athlete_id,experience_mode,age_band,maturity_level,feature_profile)
select pe.tenant_id,a.id,'standard',case when extract(year from age(current_date,pe.birth_date)) between 5 and 8 then '5_8' when extract(year from age(current_date,pe.birth_date)) between 9 and 12 then '9_12' when extract(year from age(current_date,pe.birth_date)) between 13 and 17 then '13_17' else '18_plus' end,'guided','{}'::jsonb from public.athletes a join public.people pe on pe.id=a.person_id where not exists(select 1 from public.athlete_experience_profiles x where x.athlete_id=a.id);