create or replace function public.get_parent_hub(p_family_id uuid default null)
returns jsonb language sql security invoker set search_path=public as $$
with fam as (select f.id,f.name,f.status from families f where p_family_id is not null and f.id=p_family_id limit 1),
fallback as (select a.id athlete_id,coalesce(p.preferred_name,p.first_name)||' '||p.last_name name,a.athlete_number,a.athlete_status from athletes a join people p on p.id=a.person_id order by p.last_name,p.first_name limit 1),
ath_json as (select coalesce(jsonb_agg(jsonb_build_object('athleteId',a.id,'name',coalesce(p.preferred_name,p.first_name)||' '||p.last_name,'athleteNumber',a.athlete_number,'status',a.athlete_status)),'[]'::jsonb) j from athletes a join people p on p.id=a.person_id where a.primary_family_id=p_family_id),
fallback_json as (select coalesce(jsonb_agg(jsonb_build_object('athleteId',athlete_id,'name',name,'athleteNumber',athlete_number,'status',athlete_status)),'[]'::jsonb) j from fallback),
members_json as (select coalesce(jsonb_agg(jsonb_build_object('personId',p.id,'name',coalesce(p.preferred_name,p.first_name)||' '||p.last_name,'relationship',fm.relationship_type,'primaryGuardian',fm.is_primary_guardian)),'[]'::jsonb) j from family_members fm join people p on p.id=fm.person_id where fm.family_id=p_family_id),
tasks_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'description',description,'route',route,'deadline',deadline,'consequenceTier',consequence_tier,'priority',priority,'status',status,'athleteId',athlete_id) order by deadline nulls last),'[]'::jsonb) j from family_tasks where family_id=p_family_id and status in ('OPEN','PENDING_VERIFICATION')),
messages_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'category',category,'title',title,'body',body,'route',route,'createdAt',created_at,'acknowledgedAt',acknowledged_at) order by created_at desc),'[]'::jsonb) j from family_messages where family_id=p_family_id),
invoices_json as (select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'number',i.invoice_number,'date',i.invoice_date,'dueDate',i.due_date,'total',i.total,'balanceDue',i.balance_due,'currency',i.currency,'status',i.status,'lines',coalesce((select jsonb_agg(jsonb_build_object('description',l.description,'quantity',l.quantity,'unitPrice',l.unit_price,'tax',l.tax_amount,'total',l.line_total) order by l.line_no) from invoice_lines l where l.invoice_id=i.id),'[]'::jsonb))),'[]'::jsonb) j from invoices i where i.customer_id=p_family_id),
docs_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'classification',classification,'expiresAt',expires_at,'verificationStatus',verification_status) order by expires_at nulls last),'[]'::jsonb) j from documents),
trips_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'startsAt',starts_at,'endsAt',ends_at,'pickup',pickup_location,'dropoff',dropoff_location,'mode',transportation_mode,'safesportStatus',safesport_status,'supervisionStatus',supervision_status) order by starts_at),'[]'::jsonb) j from logistics_trips where family_id=p_family_id and starts_at>=now()-interval '1 day'),
custody_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'athleteId',athlete_id,'occurredAt',occurred_at,'type',event_type,'note',note) order by occurred_at desc),'[]'::jsonb) j from custody_events where family_id=p_family_id),
vol_json as (select coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'startsAt',starts_at,'endsAt',ends_at,'credits',credits,'status',status) order by starts_at),'[]'::jsonb) j from volunteer_opportunities where status='OPEN')
select jsonb_build_object('family',coalesce((select jsonb_build_object('id',id,'name',name,'status',status) from fam limit 1),jsonb_build_object('id',null,'name','Family Demo','status','DEMO')),'members',(select j from members_json),'athletes',case when p_family_id is null then(select j from fallback_json) else(select j from ath_json)end,'tasks',(select j from tasks_json),'messages',(select j from messages_json),'invoices',(select j from invoices_json),'documents',(select j from docs_json),'trips',(select j from trips_json),'custody',(select j from custody_json),'volunteer',(select j from vol_json),'metrics',jsonb_build_object('openTasks',(select count(*) from family_tasks where family_id=p_family_id and status in ('OPEN','PENDING_VERIFICATION')),'unpaidBalance',coalesce((select sum(balance_due) from invoices where customer_id=p_family_id and balance_due>0),0),'documentsExpiring',(select count(*) from documents where expires_at is not null and expires_at<=now()+interval '30 days' and expires_at>now()),'upcomingTrips',(select count(*) from logistics_trips where family_id=p_family_id and starts_at>=now())));
$$;
revoke all on function public.get_parent_hub(uuid) from public;
grant execute on function public.get_parent_hub(uuid) to service_role;