-- Live Athlete Hub Passport projection
-- Applied to LS1SportsEAM Supabase and retained here as migration source.

CREATE OR REPLACE FUNCTION public.get_athlete_hub(p_age_band text DEFAULT '5-8'::text, p_athlete_number text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v jsonb; v_id uuid; v_person uuid; v_age int; v_band text; v_stage text;
begin
 case p_age_band when '5-8' then v_age:=5; when '9-11' then v_age:=9; when '12-14' then v_age:=12; when '15-17' then v_age:=15; else v_age:=18; end case;
 select a.id,a.person_id,extract(year from age(current_date,p.birth_date))::int into v_id,v_person,v_age from athletes a join people p on p.id=a.person_id where a.athlete_status='active' and p.birth_date is not null and (p_athlete_number is null or a.athlete_number=p_athlete_number) and (case p_age_band when '5-8' then extract(year from age(current_date,p.birth_date)) between 5 and 8 when '9-11' then extract(year from age(current_date,p.birth_date)) between 9 and 11 when '12-14' then extract(year from age(current_date,p.birth_date)) between 12 and 14 when '15-17' then extract(year from age(current_date,p.birth_date)) between 15 and 17 else extract(year from age(current_date,p.birth_date))>=18 end) order by a.id limit 1;
 if v_id is null then return jsonb_build_object('athlete',null,'error','No athlete available for selected age band','availableBands','[]'::jsonb); end if;
 v_band:=case when v_age<=8 then '5-8' when v_age<=11 then '9-11' when v_age<=14 then '12-14' when v_age<=17 then '15-17' else '18+' end;
 v_stage:=case when v_age<=8 then 'Foundation' when v_age<=11 then 'Development' when v_age<=14 then 'Growth' when v_age<=17 then 'Performance' else 'Elite' end;
 select jsonb_build_object(
 'athlete',jsonb_build_object('id',v_id,'name','HPAC Athlete · '||v_band,'athleteNumber','DEMO-'||replace(v_band,'+','PLUS'),'age',v_age,'ageBand',v_band,'stage',v_stage,'identityMode','sanitized-live-record'),
 'availableBands',(select jsonb_agg(jsonb_build_object('id',x.id,'label',x.label,'count',x.cnt) order by x.ord) from (select b.*,count(a.id) cnt from (values ('5-8','Foundation · 5–8',1,5,8),('9-11','Development · 9–11',2,9,11),('12-14','Growth · 12–14',3,12,14),('15-17','Performance · 15–17',4,15,17),('18+','Elite · 18+',5,18,200)) b(id,label,ord,lo,hi) left join people p on p.birth_date is not null and extract(year from age(current_date,p.birth_date)) between b.lo and b.hi left join athletes a on a.person_id=p.id and a.athlete_status='active' group by b.id,b.label,b.ord) x),
 'sports',coalesce((select jsonb_agg(distinct jsonb_build_object('id',s.id,'name',s.name,'code',s.code)) from athlete_sport_participation asp join sports s on s.id=asp.sport_id where asp.athlete_id=v_id),'[]'::jsonb),
 'teams',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'organization',o.name,'sport',s.name)) from team_memberships tm join teams t on t.id=tm.team_id join organizations o on o.id=t.organization_id left join sports s on s.id=t.sport_id where tm.athlete_id=v_id and tm.status='active'),'[]'::jsonb),
 'goals',coalesce((select jsonb_agg(jsonb_build_object('id',id,'type',goal_type,'title',title,'status',status,'dueOn',due_on,'description',description) order by due_on nulls last) from development_goals where athlete_id=v_id),'[]'::jsonb),
 'development',coalesce((select jsonb_agg(jsonb_build_object('id',id,'assessmentType',assessment_type,'assessedAt',assessed_at) order by assessed_at desc) from development_assessments where athlete_id=v_id),'[]'::jsonb),
 'results',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'resultValue',r.result_value,'resultUnit',r.result_unit,'rank',r.rank,'recordedAt',r.recorded_at,'sourceSystem',r.source_system,'validationStatus',r.validation_status,'canonical',r.canonical,'event',jsonb_build_object('code',ce.code,'name',ce.name),'competition',c.name) order by r.recorded_at desc) from competition_results r left join competition_entries e on e.id=r.competition_entry_id left join competition_events ce on ce.id=e.competition_event_id left join competitions c on c.id=ce.competition_id where r.athlete_id=v_id and coalesce(r.canonical,true)=true limit 100),'[]'::jsonb),
 'schedule',coalesce((select jsonb_agg(jsonb_build_object('entryId',e.id,'entryStatus',e.entry_status,'event',jsonb_build_object('code',ce.code,'name',ce.name),'competition',jsonb_build_object('id',c.id,'name',c.name,'startsAt',c.starts_at,'city',c.city)) order by c.starts_at) from competition_entries e join competition_events ce on ce.id=e.competition_event_id join competitions c on c.id=ce.competition_id where e.athlete_id=v_id and c.starts_at>=now()),'[]'::jsonb),
 'badges',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'name',b.name,'code',b.code,'awardedAt',a.awarded_at) order by a.awarded_at desc) from athlete_badge_awards a join athlete_badges b on b.id=a.badge_id where a.athlete_id=v_id),'[]'::jsonb),
 'challenges',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'description',c.description,'type',c.challenge_type,'progress',coalesce(p.progress_value,0),'status',p.status)) from athlete_challenges c left join athlete_challenge_progress p on p.challenge_id=c.id and p.athlete_id=v_id where c.active=true),'[]'::jsonb),
 'recruiting',jsonb_build_object('cycles',coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',cycle_name,'status',status,'startsOn',starts_on,'endsOn',ends_on)) from recruiting_cycles where athlete_id=v_id),'[]'::jsonb),'outreachCount',(select count(*) from recruiting_crm_outreach o join recruiting_cycles rc on rc.id=o.recruiting_cycle_id where rc.athlete_id=v_id)),
 'documents',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',title,'classification',classification,'verificationStatus',verification_status,'expiresAt',expires_at)) from documents where owner_person_id=v_person),'[]'::jsonb),
 'metrics',jsonb_build_object('teams',(select count(*) from team_memberships where athlete_id=v_id and status='active'),'officialResults',(select count(*) from competition_results where athlete_id=v_id and coalesce(canonical,true)=true),'goals',(select count(*) from development_goals where athlete_id=v_id),'assessments',(select count(*) from development_assessments where athlete_id=v_id),'trainingSessions',(select count(*) from training_athlete_logs where athlete_id=v_id),'attendanceRecords',(select count(*) from attendance_records where athlete_id=v_id),'upcomingEntries',(select count(*) from competition_entries e join competition_events ce on ce.id=e.competition_event_id join competitions c on c.id=ce.competition_id where e.athlete_id=v_id and c.starts_at>=now())),
 'reconciliation',jsonb_build_object('stagingRows',(select count(*) from hpac_profile_import_staging),'canonicalAthletes',(select count(*) from athletes),'duplicateProfileRows',(select count(*)-count(distinct (lower(trim(first_name))||'|'||lower(trim(last_name))||'|'||coalesce(birthdate_text,''))) from hpac_profile_import_staging)),
 'generatedAt',now(),'source','LS1SportsEAM Supabase','projection','live-sanitized-athlete-demo') into v;
 return v;
end $function$
;
