insert into public.platform_capability_registry(capability_key,capability_name,domain,criticality,system_of_record,description) values
('canonical_communications','Communications Engine','Communications','integral','communication_*','Unified communications with safeguarding and delivery evidence.'),
('canonical_calendar','Calendar & Scheduling Engine','Scheduling','integral','calendar_events','Canonical practices, competitions, deadlines, travel, facilities, changes and conflicts.'),
('registration_membership_eligibility','Registration Membership & Eligibility','Membership','integral','registrations/memberships','End-to-end registration, waiver, membership, governing-body and eligibility lifecycle.'),
('finance_payments_accounting','Finance Payments & Accounting','Finance','integral','invoices/payments','Charges, invoices, payments, allocations, refunds, reconciliation and accounting interoperability.'),
('volunteer_workforce','Volunteer & Workforce Engine','Workforce','critical','volunteer_*','Volunteer roles, assignments, credentials, commitments, hours and shortages.'),
('documents_consent_records','Documents Consent & Records','Documents','critical','documents/consents/waivers','Versioned records, consent, waiver, acknowledgement, expiry and retention.'),
('standards_rankings_governance','Standards Rankings & Governing Body Data','Sport Intelligence','integral','swim_time_standards','Authoritative standards, rankings, records, eligibility and governing-body evidence.'),
('coach_decision_engine','Coach Decision Engine','Coach','integral','canonical projections','Decision support for training, entries, standards, relays, conflicts and championship planning.'),
('competition_hardware_integrations','Competition Hardware & Timing Integrations','Competition','integral','competition/swim_timing_devices','Timing, scoreboard, results, scoring and governing-body submission boundary.'),
('migration_interoperability','Migration & Interoperability','Data','integral','import_*','Leave-your-old-system pipelines and transitional imports, exports and APIs.'),
('event_notification_automation','Event Notification & Automation Spine','Platform','integral','platform_event_outbox/notification_events','Canonical event propagation across authorized LS1 experiences.'),
('universal_authority_audit','Universal Authority & Audit','Security','integral','RBAC/audit/consent','Cross-platform authority, minors, delegation, audit and provenance.'),
('mobile_public_competition','Mobile Public Competition Experience','Mobile','integral','mobile_* / Competition Engine','iOS and Android Meet Mobile-equivalent using canonical Competition Engine live data and alerts.')
on conflict (capability_key) do update set capability_name=excluded.capability_name,domain=excluded.domain,criticality=excluded.criticality,system_of_record=excluded.system_of_record,description=excluded.description,updated_at=now();

do $$ declare t text; begin foreach t in array array['platform_capability_registry','platform_event_outbox','mobile_app_installations','mobile_push_tokens','public_competition_subscriptions','mobile_release_channels','mobile_live_event_bookmarks','mobile_delivery_receipts','calendar_event_participants','calendar_event_changes','registration_requirements','registration_requirement_status','eligibility_decisions','volunteer_roles','volunteer_assignments','volunteer_credentials','document_acknowledgements','governing_body_data_sources','athlete_rankings','integration_endpoints','integration_sync_runs','competition_hardware_connections','notification_preferences','platform_authority_grants','communication_safeguarding_policies','communication_guardian_links','communication_moderation_events','finance_reconciliation_runs','finance_reconciliation_items','accounting_exports','accounting_mappings'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
update public.platform_capability_registry set status='schema_ready',updated_at=now() where capability_key <> 'coach_decision_engine';
