create or replace view public.v_superuser_urws_metrics as
select
 (select count(*) from public.urws_cases where status not in ('resolved','closed','cancelled')) as open_cases,
 (select count(*) from public.urws_cases where status not in ('resolved','closed','cancelled') and priority in ('urgent','critical')) as urgent_or_critical_cases,
 coalesce((select sum(financial_impact) from public.urws_cases where status not in ('resolved','closed','cancelled')),0::numeric) as open_case_financial_impact,
 (select count(*) from public.urws_financial_commitments where status not in ('recovered','cancelled','written_off')) as open_financial_commitments,
 coalesce((select sum(greatest(amount-recovered_amount,0)) from public.urws_financial_commitments where status not in ('cancelled','written_off')),0::numeric) as unrecovered_commitment_amount,
 (select count(*) from public.urws_expected_transitions where status in ('overdue','escalated')) as overdue_expected_transitions,
 (select count(*) from public.urws_decisions where policy_overridden is true) as policy_override_decisions,
 (select count(*) from public.urws_event_rules where active is true) as enabled_detection_rules,
 (select count(*) from public.urws_case_types where active is true) as active_case_types,
 (select count(*) from public.urws_evidence_items) as evidence_items,
 (select count(*) from public.urws_decisions) as decisions,
 (select count(*) from public.urws_financial_recoveries) as financial_recoveries,
 (select count(*) from public.urws_remedies where status='approved') as approved_remedies_awaiting_execution,
 (select count(*) from public.urws_financial_dispositions where status='executing') as financial_executions_in_progress,
 (select count(*) from public.urws_financial_dispositions where status='failed') as failed_financial_executions,
 (select count(*) from public.urws_financial_dispositions where status='completed') as completed_financial_dispositions,
 coalesce((select sum(amount) from public.urws_financial_dispositions where status in ('authorized','executing') and amount is not null),0::numeric) as financial_amount_awaiting_completion,
 (select count(*) from public.refund_requests where status='approved' and resulting_refund_id is null) as approved_refund_requests_not_executed,
 (select count(*) from public.urws_decision_proposals where status='pending_second_approval') as pending_decision_second_approvals,
 (select count(*) from public.urws_decision_proposals where status='ready') as ready_decision_proposals,
 (select count(*) from public.urws_cases where case_type_code in ('competition_entry_exception','competition_fee_dispute') and status not in ('resolved','closed','cancelled')) as open_competition_cases,
 (select count(*) from public.urws_financial_commitments where source_type='competition_entry_fee' and status not in ('recovered','cancelled','written_off')) as competition_financial_commitments,
 coalesce((select sum(greatest(amount-recovered_amount,0)) from public.urws_financial_commitments where source_type='competition_entry_fee' and status not in ('cancelled','written_off')),0::numeric) as competition_unrecovered_amount,
 (select count(*) from public.urws_cases where case_type_code in ('travel_commitment_exception','travel_financial_exception') and status not in ('resolved','closed','cancelled')) as open_travel_cases,
 (select count(*) from public.travel_plans) as travel_plan_count,
 (select count(*) from public.travel_participants where coalesce(guardian_required,false)) as guardian_required_travel_participants,
 (select count(*) from public.urws_cases where case_type_code in ('facility_disruption','facility_service_disruption') and status not in ('resolved','closed','cancelled')) as open_facility_cases,
 (select count(*) from public.facility_closures where lower(coalesce(status,'')) not in ('cancelled','canceled','resolved','closed','completed','reopened')) as active_facility_closures,
 coalesce((select sum(affected_booking_count) from public.v_urws_facility_operational_summary),0::numeric) as facility_affected_bookings,
 (select count(*) from public.urws_cases where case_type_code in ('staff_compliance_lapse','credential_compliance_exception') and status not in ('resolved','closed','cancelled')) as open_workforce_cases,
 coalesce((select sum(lapsed_credentials) from public.v_urws_workforce_operational_summary),0::numeric) as lapsed_staff_credentials,
 coalesce((select sum(active_staff_assignments) from public.v_urws_workforce_operational_summary),0::numeric) as active_staff_assignments,
 (select count(*) from public.urws_cases where case_type_code='registration_exception' and status not in ('resolved','closed','cancelled')) as open_registration_cases,
 (select count(*) from public.urws_cases where case_type_code='guardian_authority_dispute' and status not in ('resolved','closed','cancelled')) as open_family_authority_cases,
 (select count(*) from public.family_authority_assignments where status in ('restricted','disputed','revoked')) as family_authority_restrictions_or_disputes,
 (select count(*) from public.urws_cases where case_type_code in ('billing_dispute','billing_error','chargeback_dispute','financial_hardship','payment_failure','refund_request','membership_refund_dispute') and status not in ('resolved','closed','cancelled')) as open_finance_cases,
 (select count(*) from public.urws_cases where case_type_code in ('membership_exception','membership_pause_exception','membership_refund_dispute','membership_cancellation_request') and status not in ('resolved','closed','cancelled')) as open_membership_cases,
 (select count(*) from public.urws_cases where case_type_code='equipment_loss_damage' and status not in ('resolved','closed','cancelled')) as open_asset_cases,
 (select count(*) from public.assets where lower(coalesce(status,'')) in ('lost','damaged','missing','stolen','out_of_service')) as assets_requiring_attention,
 (select count(*) from public.urws_cases where case_type_code in ('record_correction','data_correction') and status not in ('resolved','closed','cancelled')) as open_record_correction_cases,
 (select count(*) from public.urws_record_corrections where status in ('requested','reviewing','approved')) as pending_record_corrections,
 (select count(*) from public.urws_cases where case_type_code in ('safeguarding_referral','safeguarding_report') and status not in ('resolved','closed','cancelled')) as open_safeguarding_urws_cases,
 (select count(*) from public.urws_cases where restricted is true and status not in ('resolved','closed','cancelled')) as open_restricted_urws_cases,
 (select count(*) from public.urws_cases where case_type_code in ('service_failure','attendance_dispute','organization_service_disruption') and status not in ('resolved','closed','cancelled')) as open_service_failure_cases;

create or replace view public.v_superuser_core_metrics as
select
 (select count(*) from public.tenants where status='active') as active_tenants,
 (select count(*) from public.organizations where status='active') as active_organizations,
 (select count(*) from public.people where status='active') as people,
 (select count(*) from public.athletes where athlete_status='active') as athletes,
 (select count(*) from public.teams where status='active') as teams,
 (select count(*) from public.programs where status='active') as programs,
 (select count(*) from public.seasons where status in ('planned','active')) as seasons,
 (select count(*) from public.competitions where status not in ('cancelled','archived')) as competitions,
 (select count(*) from public.communication_threads where status='active') as active_threads,
 (select count(*) from public.data_quality_issues where status='open') as open_data_quality_issues,
 (select count(*) from public.safeguarding_cases where status='open') as open_safeguarding_cases,
 (select count(*) from public.integration_runs where status='failed') as failed_integrations,
 (select count(*) from public.workflow_tasks where status='pending') as pending_workflow_tasks,
 u.open_cases as urws_open_cases,
 u.urgent_or_critical_cases as urws_urgent_or_critical_cases,
 u.open_case_financial_impact as urws_open_case_financial_impact,
 u.unrecovered_commitment_amount as urws_unrecovered_commitment_amount,
 u.overdue_expected_transitions as urws_overdue_expected_transitions,
 u.policy_override_decisions as urws_policy_override_decisions,
 u.approved_remedies_awaiting_execution as urws_approved_remedies_awaiting_execution,
 u.financial_executions_in_progress as urws_financial_executions_in_progress,
 u.failed_financial_executions as urws_failed_financial_executions,
 u.financial_amount_awaiting_completion as urws_financial_amount_awaiting_completion,
 u.approved_refund_requests_not_executed as urws_approved_refund_requests_not_executed,
 u.open_registration_cases as urws_open_registration_cases,
 u.open_family_authority_cases as urws_open_family_authority_cases,
 u.open_finance_cases as urws_open_finance_cases,
 u.open_membership_cases as urws_open_membership_cases,
 u.open_asset_cases as urws_open_asset_cases,
 u.open_record_correction_cases as urws_open_record_correction_cases,
 u.open_safeguarding_urws_cases as urws_open_safeguarding_cases,
 u.open_service_failure_cases as urws_open_service_failure_cases
from public.v_superuser_urws_metrics u;