-- Native parser registry and event execution spine
create table if not exists public.parser_definitions (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,sport_code text,source_system_id uuid references public.competition_source_systems(id) on delete set null,input_formats text[] not null default '{}',parser_version text not null default '1.0.0',parser_contract jsonb not null default '{}'::jsonb,canonical_output_contract jsonb not null default '{}'::jsonb,validation_contract jsonb not null default '{}'::jsonb,status text not null default 'active' check (status in ('draft','active','deprecated','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.parser_runs (id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,parser_id uuid not null references public.parser_definitions(id),import_file_id uuid references public.competition_import_files(id) on delete set null,package_id uuid references public.ls1_packages(id) on delete set null,status text not null default 'queued' check (status in ('queued','running','succeeded','failed','partial','cancelled')),input_checksum_sha256 text,output_checksum_sha256 text,records_read integer not null default 0,records_valid integer not null default 0,records_rejected integer not null default 0,error_summary jsonb not null default '[]'::jsonb,telemetry jsonb not null default '{}'::jsonb,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.parser_run_records (id uuid primary key default gen_random_uuid(),parser_run_id uuid not null references public.parser_runs(id) on delete cascade,sequence_no integer not null,source_locator jsonb not null default '{}'::jsonb,source_payload jsonb,normalized_payload jsonb,canonical_entity_type text,canonical_entity_id uuid,disposition text not null default 'accepted' check (disposition in ('accepted','rejected','warning','duplicate')),validation_messages jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),unique(parser_run_id,sequence_no));
create table if not exists public.event_subscriptions (id uuid primary key default gen_random_uuid(),tenant_id uuid references public.tenants(id) on delete cascade,event_pattern text not null,subscriber_type text not null check (subscriber_type in ('automation','ai_agent','workflow','notification','integration')),subscriber_id uuid,handler_key text,enabled boolean not null default true,configuration jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.event_processing_attempts (id uuid primary key default gen_random_uuid(),event_id uuid not null references public.platform_events(id) on delete cascade,subscription_id uuid not null references public.event_subscriptions(id) on delete cascade,status text not null default 'queued' check (status in ('queued','running','succeeded','failed','skipped','dead_letter')),attempt_no integer not null default 1,idempotency_key text not null,result jsonb not null default '{}'::jsonb,error jsonb,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),unique(subscription_id,idempotency_key,attempt_no));
create index if not exists idx_parser_runs_tenant_status on public.parser_runs(tenant_id,status,created_at desc);
create index if not exists idx_parser_run_records_run_disposition on public.parser_run_records(parser_run_id,disposition);
create index if not exists idx_event_subscriptions_pattern_enabled on public.event_subscriptions(event_pattern,enabled);
create index if not exists idx_event_processing_attempts_event_status on public.event_processing_attempts(event_id,status);
alter table public.parser_runs enable row level security; alter table public.parser_run_records enable row level security; alter table public.event_subscriptions enable row level security; alter table public.event_processing_attempts enable row level security; alter table public.parser_definitions enable row level security;
create policy parser_runs_tenant_access on public.parser_runs for all to authenticated using (app.is_superuser() or tenant_id in (select app.current_tenant_ids())) with check (app.is_superuser() or tenant_id in (select app.current_tenant_ids()));
create policy parser_run_records_access on public.parser_run_records for all to authenticated using (app.is_superuser() or exists (select 1 from public.parser_runs r where r.id=parser_run_records.parser_run_id and r.tenant_id in (select app.current_tenant_ids()))) with check (app.is_superuser() or exists (select 1 from public.parser_runs r where r.id=parser_run_records.parser_run_id and r.tenant_id in (select app.current_tenant_ids())));
create policy event_subscriptions_tenant_access on public.event_subscriptions for all to authenticated using (app.is_superuser() or tenant_id in (select app.current_tenant_ids())) with check (app.is_superuser() or tenant_id in (select app.current_tenant_ids()));
create policy event_processing_attempts_access on public.event_processing_attempts for all to authenticated using (app.is_superuser() or exists (select 1 from public.platform_events e where e.id=event_processing_attempts.event_id and e.tenant_id in (select app.current_tenant_ids()))) with check (app.is_superuser() or exists (select 1 from public.platform_events e where e.id=event_processing_attempts.event_id and e.tenant_id in (select app.current_tenant_ids())));
create policy parser_definitions_read on public.parser_definitions for select to authenticated using (true);
insert into public.parser_definitions (code,name,sport_code,input_formats,parser_contract,canonical_output_contract,validation_contract,status) values
('LS1-SWIM-HYTEK-HY3','HY-TEK HY3 Swimming Translator','swimming',array['hy3'],jsonb_build_object('source','hytek','format','hy3'),jsonb_build_object('target','LS1 canonical competition model'),jsonb_build_object('mode','strict-with-warnings'),'active'),
('LS1-SWIM-CL2','CL2 Swimming Translator','swimming',array['cl2'],jsonb_build_object('format','cl2'),jsonb_build_object('target','LS1 canonical competition model'),jsonb_build_object('mode','strict-with-warnings'),'active'),
('LS1-SWIM-SDIF','SDIF Swimming Translator','swimming',array['sdif'],jsonb_build_object('format','sdif'),jsonb_build_object('target','LS1 canonical competition model'),jsonb_build_object('mode','strict-with-warnings'),'active'),
('LS1-GENERIC-CSV','Structured Delimited Data Translator',null,array['csv','tsv'],jsonb_build_object('format','delimited'),jsonb_build_object('target','LS1 canonical entities'),jsonb_build_object('mode','schema-driven'),'active'),
('LS1-GENERIC-XLSX','Workbook Data Translator',null,array['xlsx','xls'],jsonb_build_object('format','workbook'),jsonb_build_object('target','LS1 canonical entities'),jsonb_build_object('mode','schema-driven'),'active')
on conflict (code) do update set name=excluded.name,input_formats=excluded.input_formats,parser_contract=excluded.parser_contract,canonical_output_contract=excluded.canonical_output_contract,validation_contract=excluded.validation_contract,status=excluded.status,updated_at=now();