create or replace view public.v_superuser_urws_metrics as
select
 (select count(*) from public.urws_cases where status not in ('resolved','closed','cancelled')) as open_cases,
 (select count(*) from public.urws_cases where status not in ('resolved','closed','cancelled') and priority in ('urgent','critical')) as urgent_or_critical_cases,
 coalesce((select sum(financial_impact) from public.urws_cases where status not in ('resolved','closed','cancelled')),0) as open_case_financial_impact,
 (select count(*) from public.urws_financial_commitments where status not in ('recovered','cancelled','void')) as open_financial_commitments,
 coalesce((select sum(greatest(amount-recovered_amount,0)) from public.urws_financial_commitments where status not in ('cancelled','void')),0) as unrecovered_commitment_amount,
 (select count(*) from public.urws_expected_transitions where status in ('overdue','escalated')) as overdue_expected_transitions,
 (select count(*) from public.urws_decisions where policy_overridden is true) as policy_override_decisions,
 (select count(*) from public.urws_event_rules where active is true) as enabled_detection_rules,
 (select count(*) from public.urws_case_types where active is true) as active_case_types,
 (select count(*) from public.urws_evidence_items) as evidence_items,
 (select count(*) from public.urws_decisions) as decisions,
 (select count(*) from public.urws_financial_recoveries) as financial_recoveries,
 (select count(*) from public.urws_remedies where status='approved') as approved_remedies_awaiting_execution,
 (select count(*) from public.urws_financial_dispositions where status='executing') as financial_executions_in_progress,
 (select count(*) from public.urws_financial_dispositions where status='failed') as failed_financial_executions,
 (select count(*) from public.urws_financial_dispositions where status='completed') as completed_financial_dispositions,
 coalesce((select sum(amount) from public.urws_financial_dispositions where status in ('authorized','executing') and amount is not null),0) as financial_amount_awaiting_completion,
 (select count(*) from public.refund_requests where status='approved' and resulting_refund_id is null) as approved_refund_requests_not_executed;

create or replace view public.v_superuser_core_metrics as
select
 (select count(*) from public.tenants where status='active') as active_tenants,
 (select count(*) from public.organizations where status='active') as active_organizations,
 (select count(*) from public.people where status='active') as people,
 (select count(*) from public.athletes where athlete_status='active') as athletes,
 (select count(*) from public.teams where status='active') as teams,
 (select count(*) from public.programs where status='active') as programs,
 (select count(*) from public.seasons where status in ('planned','active')) as seasons,
 (select count(*) from public.competitions where status not in ('cancelled','archived')) as competitions,
 (select count(*) from public.communication_threads where status='active') as active_threads,
 (select count(*) from public.data_quality_issues where status='open') as open_data_quality_issues,
 (select count(*) from public.safeguarding_cases where status='open') as open_safeguarding_cases,
 (select count(*) from public.integration_runs where status='failed') as failed_integrations,
 (select count(*) from public.workflow_tasks where status='pending') as pending_workflow_tasks,
 u.open_cases as urws_open_cases,
 u.urgent_or_critical_cases as urws_urgent_or_critical_cases,
 u.open_case_financial_impact as urws_open_case_financial_impact,
 u.unrecovered_commitment_amount as urws_unrecovered_commitment_amount,
 u.overdue_expected_transitions as urws_overdue_expected_transitions,
 u.policy_override_decisions as urws_policy_override_decisions,
 u.approved_remedies_awaiting_execution as urws_approved_remedies_awaiting_execution,
 u.financial_executions_in_progress as urws_financial_executions_in_progress,
 u.failed_financial_executions as urws_failed_financial_executions,
 u.financial_amount_awaiting_completion as urws_financial_amount_awaiting_completion,
 u.approved_refund_requests_not_executed as urws_approved_refund_requests_not_executed
from public.v_superuser_urws_metrics u;
