alter table public.urws_decision_packets add column if not exists prepared_by_auth_user_id uuid;
alter table public.urws_decision_packets add column if not exists prepared_by_operator_id uuid references public.platform_superuser_operators(id) on delete set null;

create or replace function public.urws_build_decision_packet(p_case_id uuid,p_prepared_by_person_id uuid default null)
returns uuid language plpgsql security definer set search_path=public,app as $$
declare c public.urws_cases%rowtype; v_id uuid; v_version int; v_policy_eval uuid; v_evidence jsonb; v_fin jsonb; v_authority jsonb; v_missing jsonb; v_recommendation text; v_rationale text; v_membership jsonb:='{}'::jsonb; v_auth uuid; v_operator uuid; v_person uuid; v_previous uuid;
begin
 select * into c from public.urws_cases where id=p_case_id; if not found then raise exception 'URWS case not found'; end if;
 v_auth:=auth.uid(); v_person:=p_prepared_by_person_id;
 if v_auth is not null then select id,coalesce(person_id,v_person) into v_operator,v_person from public.platform_superuser_operators where auth_user_id=v_auth and active=true limit 1; end if;
 if v_person is null then v_person:=app.current_person_id(); end if;
 select coalesce(max(packet_version),0)+1 into v_version from public.urws_decision_packets where case_id=p_case_id;
 select id into v_policy_eval from public.urws_policy_evaluations where case_id=p_case_id order by evaluated_at desc limit 1;
 select jsonb_build_object('count',count(*),'types',coalesce(jsonb_agg(distinct evidence_type),'[]'::jsonb),'latest_at',max(occurred_at)) into v_evidence from public.urws_evidence_items where case_id=p_case_id and sensitivity='standard';
 select jsonb_build_object('case_financial_impact',coalesce(c.financial_impact,0),'committed',coalesce(sum(fc.amount),0),'recovered',coalesce(sum(fc.recovered_amount),0),'unrecovered',coalesce(sum(greatest(fc.amount-fc.recovered_amount,0)),0),'currency',c.currency) into v_fin from public.urws_financial_commitments fc where fc.organization_id=c.organization_id and ((fc.subject_type=c.subject_type and fc.subject_id=c.subject_id) or fc.id in (select source_commitment_id from public.urws_remedies where case_id=p_case_id and source_commitment_id is not null));
 select coalesce(jsonb_agg(jsonb_build_object('action',ar.action,'required_authority_action',ar.required_authority_action,'min',ar.min_financial_amount,'max',ar.max_financial_amount,'second_approval',ar.requires_second_approval,'escalation_role',ar.escalation_role)),'[]'::jsonb) into v_authority from public.urws_authority_rules ar where ar.active and (ar.organization_id is null or ar.organization_id=c.organization_id) and (ar.case_type_code is null or ar.case_type_code=c.case_type_code);
 if c.subject_type='membership' and c.subject_id is not null then
  select jsonb_build_object('membership',(select to_jsonb(x) from (select id,membership_number,membership_type,status,start_date,end_date from public.memberships where id=c.subject_id) x),'exceptions',coalesce((select jsonb_agg(jsonb_build_object('id',me.id,'type',me.exception_type,'status',me.status,'requested_start_on',me.requested_start_on,'requested_end_on',me.requested_end_on,'approved_start_on',me.approved_start_on,'approved_end_on',me.approved_end_on,'billing_resume_on',me.billing_resume_on,'policy_overridden',me.policy_overridden) order by me.created_at) from public.membership_exceptions me where me.membership_id=c.subject_id),'[]'::jsonb),'refund_requests',coalesce((select jsonb_agg(jsonb_build_object('id',rr.id,'amount',rr.amount,'currency',rr.currency,'requested_at',rr.requested_at,'status',rr.status,'policy_eligibility',rr.policy_eligibility,'recommended_disposition',rr.recommended_disposition,'resulting_refund_id',rr.resulting_refund_id) order by rr.requested_at) from public.refund_requests rr where rr.membership_id=c.subject_id),'[]'::jsonb),'lifecycle_events',coalesce((select jsonb_agg(jsonb_build_object('id',le.id,'event_type',le.event_type,'effective_at',le.effective_at,'summary',le.summary) order by le.effective_at) from public.membership_lifecycle_events le where le.membership_id=c.subject_id),'[]'::jsonb)) into v_membership;
 end if;
 v_missing:='[]'::jsonb;
 if c.applicable_policy_version_id is null then v_missing:=v_missing||jsonb_build_array('applicable_policy'); end if;
 if coalesce((v_evidence->>'count')::int,0)=0 then v_missing:=v_missing||jsonb_build_array('standard_evidence'); end if;
 if v_policy_eval is null or coalesce(c.policy_outcome,'unassessed')='unassessed' then v_missing:=v_missing||jsonb_build_array('policy_evaluation'); end if;
 if jsonb_array_length(v_missing)>0 then v_recommendation:='review_required'; v_rationale:='Canonical evidence or policy evaluation is incomplete; no automated disposition should be treated as authoritative.';
 elsif c.policy_outcome in ('outside_policy','exception_required','ineligible','decline') then v_recommendation:='decline_or_escalate'; v_rationale:='Current policy outcome does not support an ordinary approval; an authorized exception may still be considered.';
 else v_recommendation:='eligible_for_authorized_review'; v_rationale:='Available canonical evidence and policy outcome support proceeding to an authorized human decision.'; end if;
 select id into v_previous from public.urws_decision_packets where case_id=p_case_id order by packet_version desc limit 1;
 update public.urws_decision_packets set status='superseded' where case_id=p_case_id and status='prepared';
 insert into public.urws_decision_packets(tenant_id,organization_id,case_id,packet_version,status,policy_evaluation_id,prepared_by,prepared_by_person_id,prepared_by_auth_user_id,prepared_by_operator_id,public_facts,restricted_facts,financial_summary,evidence_summary,authority_summary,missing_evidence,recommendation,recommendation_rationale,supersedes_packet_id)
 values(c.tenant_id,c.organization_id,c.id,v_version,'prepared',v_policy_eval,case when v_operator is not null then 'platform_operator' when v_person is null then 'system' else 'person' end,v_person,v_auth,v_operator,jsonb_build_object('case_type',c.case_type_code,'subject_type',c.subject_type,'status',c.status,'priority',c.priority,'public_summary',c.public_summary,'opened_at',c.opened_at,'requested_effective_at',c.requested_effective_at,'policy_outcome',c.policy_outcome,'membership_context',v_membership),jsonb_build_object('restricted_summary_present',c.restricted_summary is not null),v_fin,v_evidence,v_authority,v_missing,v_recommendation,v_rationale,v_previous) returning id into v_id;
 return v_id;
end $$;
