-- Privacy-safe Membership -> URWS bridge. Admins receive only operational fields; membership_exceptions.restricted_details is never projected.
create or replace function public.admin_membership_urws_snapshot(p_membership_id uuid)
returns jsonb language plpgsql security definer set search_path=public,app as $$
declare m public.memberships%rowtype; allowed boolean := false; result jsonb;
begin
 select * into m from public.memberships where id=p_membership_id; if not found then raise exception 'Membership not found'; end if;
 allowed := app.is_superuser() or (app.has_admin_role(array['org_admin','registrar','treasurer','operations']) and exists(select 1 from public.organizations o where o.id=m.organization_id and o.tenant_id in (select app.current_tenant_ids())));
 if not allowed then raise exception 'Membership scope denied' using errcode='42501'; end if;
 select jsonb_build_object(
  'membership',jsonb_build_object('id',m.id,'organization_id',m.organization_id,'person_id',m.person_id,'membership_number',m.membership_number,'membership_type',m.membership_type,'starts_on',m.starts_on,'ends_on',m.ends_on,'status',m.status),
  'exceptions',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'exception_type',x.exception_type,'reason_category',x.reason_category,'requested_start_on',x.requested_start_on,'requested_end_on',x.requested_end_on,'approved_start_on',x.approved_start_on,'approved_end_on',x.approved_end_on,'billing_resume_on',x.billing_resume_on,'status',x.status,'policy_version_id',x.policy_version_id,'policy_overridden',x.policy_overridden,'requested_by_person_id',x.requested_by_person_id,'decided_by_person_id',x.decided_by_person_id,'decided_at',x.decided_at,'decision_note',x.decision_note,'created_at',x.created_at,'updated_at',x.updated_at) order by x.created_at desc) from public.membership_exceptions x where x.membership_id=m.id),'[]'::jsonb),
  'lifecycle_events',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'event_type',e.event_type,'effective_at',e.effective_at,'actor_person_id',e.actor_person_id,'source_type',e.source_type,'source_id',e.source_id,'summary',e.summary,'evidence',e.evidence,'created_at',e.created_at) order by e.effective_at desc) from public.membership_lifecycle_events e where e.membership_id=m.id),'[]'::jsonb),
  'refund_requests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'amount',r.amount,'currency',r.currency,'requested_at',r.requested_at,'reason',r.reason,'status',r.status,'applicable_policy_version_id',r.applicable_policy_version_id,'policy_eligibility',r.policy_eligibility,'recommended_disposition',r.recommended_disposition,'decided_by_person_id',r.decided_by_person_id,'decided_at',r.decided_at,'decision_note',r.decision_note,'resulting_refund_id',r.resulting_refund_id,'created_at',r.created_at,'updated_at',r.updated_at) order by r.requested_at desc) from public.refund_requests r where r.membership_id=m.id),'[]'::jsonb),
  'policy_acceptances',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'policy_version_id',a.policy_version_id,'person_id',a.person_id,'athlete_person_id',a.athlete_person_id,'accepted_by_person_id',a.accepted_by_person_id,'accepted_at',a.accepted_at,'acknowledgement_method',a.acknowledgement_method,'evidence',a.evidence) order by a.accepted_at desc) from public.membership_policy_acceptances a where a.membership_id=m.id),'[]'::jsonb),
  'policy_versions',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'policy_key',p.policy_key,'name',p.name,'version',p.version,'rules',p.rules,'effective_from',p.effective_from,'effective_to',p.effective_to,'status',p.status,'created_at',p.created_at) order by p.effective_from desc,p.version desc) from public.membership_policy_versions p where p.organization_id=m.organization_id),'[]'::jsonb),
  'urws_cases',coalesce((select jsonb_agg(distinct jsonb_build_object('id',c.id,'case_type_code',c.case_type_code,'status',c.status,'priority',c.priority,'policy_outcome',c.policy_outcome,'public_summary',c.public_summary,'financial_impact',c.financial_impact,'currency',c.currency,'opened_at',c.opened_at,'resolved_at',c.resolved_at)) from public.urws_cases c where c.organization_id=m.organization_id and ((c.subject_type='membership' and c.subject_id=m.id) or exists(select 1 from public.urws_case_links l where l.case_id=c.id and l.linked_type='membership' and l.linked_id=m.id))),'[]'::jsonb)
 ) into result; return result;
end $$;
grant execute on function public.admin_membership_urws_snapshot(uuid) to authenticated;
create policy urws_case_links_admin_read on public.urws_case_links for select to authenticated using (app.has_admin_role(array['org_admin','registrar','treasurer','operations']) and exists(select 1 from public.urws_cases c join public.organizations o on o.id=c.organization_id where c.id=urws_case_links.case_id and o.tenant_id in (select app.current_tenant_ids())));
create policy urws_case_links_admin_insert on public.urws_case_links for insert to authenticated with check (linked_type in ('membership','refund_request','membership_exception','membership_lifecycle_event') and app.has_admin_role(array['org_admin','registrar','treasurer','operations']) and exists(select 1 from public.urws_cases c join public.organizations o on o.id=c.organization_id where c.id=urws_case_links.case_id and o.tenant_id in (select app.current_tenant_ids())));
grant select,insert on public.urws_case_links to authenticated;
