create table if not exists public.family_authority_assignments (
 id uuid primary key default gen_random_uuid(), tenant_id uuid, family_id uuid not null references public.families(id) on delete cascade, athlete_id uuid not null references public.athletes(id) on delete cascade, person_id uuid not null references public.people(id) on delete cascade,
 relationship_type text not null, authority_scopes jsonb not null default '[]'::jsonb, restrictions jsonb not null default '[]'::jsonb,
 status text not null default 'active' check(status in ('active','restricted','disputed','expired','revoked')), valid_from timestamptz not null default now(), valid_until timestamptz, source_type text not null default 'organization_record', source_id uuid, evidence jsonb not null default '{}'::jsonb, created_by_person_id uuid references public.people(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(family_id,athlete_id,person_id));
create index if not exists family_authority_athlete_idx on public.family_authority_assignments(athlete_id,status);
alter table public.family_authority_assignments enable row level security;
drop policy if exists family_authority_superuser on public.family_authority_assignments;
create policy family_authority_superuser on public.family_authority_assignments for all to authenticated using (app.is_superuser()) with check (app.is_superuser());
create or replace function app.family_has_authority(p_person_id uuid,p_athlete_id uuid,p_scope text) returns boolean language sql stable security definer set search_path=public,app as $$ select exists(select 1 from public.family_authority_assignments a where a.person_id=p_person_id and a.athlete_id=p_athlete_id and a.status='active' and a.valid_from<=now() and (a.valid_until is null or a.valid_until>now()) and a.authority_scopes ? p_scope and not (a.restrictions ? p_scope)); $$;
create or replace function app.urws_family_authority_event_trigger() returns trigger language plpgsql security definer set search_path=public,app as $$ declare v_org uuid; begin if tg_op='UPDATE' and new.status is not distinct from old.status and new.authority_scopes is not distinct from old.authority_scopes and new.restrictions is not distinct from old.restrictions then return new; end if; if new.status not in ('restricted','disputed','revoked') and jsonb_array_length(new.restrictions)=0 then return new; end if; select r.organization_id into v_org from public.registrations r where r.athlete_id=new.athlete_id order by coalesce(r.approved_at,r.submitted_at) desc nulls last limit 1; if v_org is null then return new; end if; insert into public.platform_event_outbox(tenant_id,event_type,aggregate_type,aggregate_id,payload,occurred_at,status) values(new.tenant_id,'family.guardian_authority.disputed','family_authority_assignment',new.id,jsonb_build_object('organization_id',v_org,'athlete_id',new.athlete_id,'family_id',new.family_id,'person_id',new.person_id,'authority_status',new.status,'relationship_type',new.relationship_type),now(),'pending'); return new; end; $$;
drop trigger if exists urws_family_authority_event on public.family_authority_assignments;
create trigger urws_family_authority_event after insert or update on public.family_authority_assignments for each row execute function app.urws_family_authority_event_trigger();
insert into public.urws_event_rules(organization_id,event_type,case_type_code,subject_type,priority,public_summary_template,origin_prefix,auto_open,active,conditions,metadata) values(null,'family.guardian_authority.disputed','guardian_authority_dispute','athlete','high','Guardian authority requires restricted review.','guardian-authority',true,true,'{}'::jsonb,'{"restricted":true,"bridge":"family_authority"}'::jsonb) on conflict (organization_id,event_type,case_type_code) do update set active=true,auto_open=true,priority='high',metadata=excluded.metadata;