import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin, AdminAuthError, type AdminIdentity } from '@/lib/server/requireAdmin';
import { adminRest } from '@/lib/server/adminRest';
import { writeAdminAuditEvent } from '@/lib/server/writeAdminAuditEvent';
export const dynamic='force-dynamic';export const revalidate=0;type Row=Record<string,any>;
function canWrite(a:AdminIdentity){return a.isSuperUser||a.roles.includes('org_admin')||a.roles.includes('team_engine')||a.roles.includes('registrar')}
function assertWrite(a:AdminIdentity){if(!canWrite(a))throw new AdminAuthError('Your Admin role does not allow Team Engine master-data changes.',403)}
function text(v:unknown){const s=String(v??'').trim();return s||null}
async function tenant(a:AdminIdentity){if(a.tenantIds[0])return a.tenantIds[0];const o=await adminRest<Array<{tenant_id:string}>>(a,'organizations?select=tenant_id&order=created_at.asc&limit=1');return o?.[0]?.tenant_id||null}
export async function GET(request:NextRequest){try{const actor=await requireAdmin(request);const[organizations,sports,programs,seasons,teams,people,governingBodies,memberships]=await Promise.all([
adminRest<Row[]>(actor,'organizations?select=id,name,status&order=name.asc&limit=250'),adminRest<Row[]>(actor,'sports?select=id,code,name,status&order=name.asc&limit=250').catch(()=>[]),adminRest<Row[]>(actor,'programs?select=id,organization_id,sport_id,code,name,program_type,status&order=name.asc&limit=500'),adminRest<Row[]>(actor,'seasons?select=id,organization_id,sport_id,code,name,starts_on,ends_on,status&order=starts_on.desc&limit=500'),adminRest<Row[]>(actor,'teams?select=id,organization_id,sport_id,program_id,season_id,code,name,competitive_level,status&order=name.asc&limit=500'),adminRest<Row[]>(actor,'people?select=id,first_name,last_name,preferred_name,email,status&order=last_name.asc,first_name.asc&limit=1000'),adminRest<Row[]>(actor,'governing_bodies?select=id,code,name,country_code,level&order=name.asc&limit=250').catch(()=>[]),adminRest<Row[]>(actor,'memberships?select=id,organization_id,person_id,sport_id,membership_number,membership_type,starts_on,ends_on,status,governing_body_id&limit=1000')]);return NextResponse.json({organizations,sports,programs,seasons,teams,people,governingBodies,memberships,canWrite:canWrite(actor)})}catch(e){const status=e instanceof AdminAuthError?e.status:500;return NextResponse.json({error:e instanceof Error?e.message:'Team master data unavailable.'},{status})}}
export async function POST(request:NextRequest){try{const actor=await requireAdmin(request);assertWrite(actor);const b=(await request.json()) as Row;const action=String(b.action||'');const tenantId=await tenant(actor);
if(action==='create-program'){const organization_id=String(b.organization_id||''),code=String(b.code||'').trim(),name=String(b.name||'').trim();if(!organization_id||!code||!name)throw new Error('Organization, program code and name are required.');const rows=await adminRest<Row[]>(actor,'programs',{method:'POST',body:JSON.stringify({organization_id,sport_id:text(b.sport_id),code,name,program_type:text(b.program_type),status:'active'})});await writeAdminAuditEvent(actor,{action:'PROGRAM_CREATED',entityType:'program',entityId:rows?.[0]?.id,tenantId,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='create-season'){const organization_id=String(b.organization_id||''),code=String(b.code||'').trim(),name=String(b.name||'').trim();if(!organization_id||!code||!name)throw new Error('Organization, season code and name are required.');if(b.starts_on&&b.ends_on&&String(b.ends_on)<String(b.starts_on))throw new Error('Season end must be on or after start.');const rows=await adminRest<Row[]>(actor,'seasons',{method:'POST',body:JSON.stringify({organization_id,sport_id:text(b.sport_id),code,name,starts_on:text(b.starts_on),ends_on:text(b.ends_on),status:'planned'})});await writeAdminAuditEvent(actor,{action:'SEASON_CREATED',entityType:'season',entityId:rows?.[0]?.id,tenantId,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='set-season-status'){const id=String(b.id||''),status=String(b.status||'').toLowerCase();if(!id||!['planned','active','closed','cancelled'].includes(status))throw new Error('Valid season and status are required.');const before=(await adminRest<Row[]>(actor,`seasons?select=*&id=eq.${encodeURIComponent(id)}&limit=1`))?.[0];if(!before)throw new Error('Season not found.');const rows=await adminRest<Row[]>(actor,`seasons?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});await writeAdminAuditEvent(actor,{action:'SEASON_STATUS_CHANGED',entityType:'season',entityId:id,tenantId,beforeData:before,afterData:rows?.[0],reason:text(b.reason)});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='create-team'){const organization_id=String(b.organization_id||''),code=String(b.code||'').trim(),name=String(b.name||'').trim();if(!organization_id||!code||!name)throw new Error('Organization, team code and name are required.');const rows=await adminRest<Row[]>(actor,'teams',{method:'POST',body:JSON.stringify({organization_id,sport_id:text(b.sport_id),program_id:text(b.program_id),season_id:text(b.season_id),code,name,competitive_level:text(b.competitive_level),status:'active'})});await writeAdminAuditEvent(actor,{action:'TEAM_CREATED',entityType:'team',entityId:rows?.[0]?.id,tenantId,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='set-team-status'){const id=String(b.id||''),status=String(b.status||'').toLowerCase();if(!id||!['active','inactive','closed'].includes(status))throw new Error('Valid team and status are required.');const before=(await adminRest<Row[]>(actor,`teams?select=*&id=eq.${encodeURIComponent(id)}&limit=1`))?.[0];if(!before)throw new Error('Team not found.');const rows=await adminRest<Row[]>(actor,`teams?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});await writeAdminAuditEvent(actor,{action:'TEAM_STATUS_CHANGED',entityType:'team',entityId:id,tenantId,beforeData:before,afterData:rows?.[0],reason:text(b.reason)});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='create-membership'){const organization_id=String(b.organization_id||''),person_id=String(b.person_id||'');if(!organization_id||!person_id)throw new Error('Organization and person are required.');const rows=await adminRest<Row[]>(actor,'memberships',{method:'POST',body:JSON.stringify({organization_id,person_id,sport_id:text(b.sport_id),membership_number:text(b.membership_number),membership_type:text(b.membership_type),starts_on:text(b.starts_on),ends_on:text(b.ends_on),status:'active',governing_body_id:text(b.governing_body_id)})});await writeAdminAuditEvent(actor,{action:'MEMBERSHIP_CREATED',entityType:'membership',entityId:rows?.[0]?.id,tenantId,afterData:rows?.[0]});return NextResponse.json({ok:true,record:rows?.[0]})}
if(action==='set-membership-status'){const id=String(b.id||''),status=String(b.status||'').toLowerCase();if(!id||!['active','inactive','suspended','expired','cancelled'].includes(status))throw new Error('Valid membership and status are required.');const before=(await adminRest<Row[]>(actor,`memberships?select=*&id=eq.${encodeURIComponent(id)}&limit=1`))?.[0];if(!before)throw new Error('Membership not found.');const rows=await adminRest<Row[]>(actor,`memberships?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status,ends_on:text(b.ends_on)||before.ends_on})});await writeAdminAuditEvent(actor,{action:'MEMBERSHIP_STATUS_CHANGED',entityType:'membership',entityId:id,tenantId,beforeData:before,afterData:rows?.[0],reason:text(b.reason)});return NextResponse.json({ok:true,record:rows?.[0]})}
throw new Error('Unsupported Team Engine master-data action.')}catch(e){const status=e instanceof AdminAuthError?e.status:400;return NextResponse.json({error:e instanceof Error?e.message:'Team master-data action failed.'},{status})}}
