'use client';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
let browserClient:SupabaseClient|null=null;
function getSupabaseClient(){if(browserClient)return browserClient;const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return null;browserClient=createClient(url,key);return browserClient}
export type NavigationItem={id:string;label:string;href?:string;icon?:string;description?:string;sort_order?:number;children?:NavigationItem[]};export type NavigationSection={id:string;label:string;items:NavigationItem[]};export interface SwitcherOption{id:string;label:string;description?:string}export interface SwitcherConfig{type:'age'|'official_role'|'scout'|null;displayStyle:'radio'|'dropdown'|'none';options:SwitcherOption[];defaultOption:string}type DbNavRow={nav_id:string;label:string;path:string|null;icon:string|null;description:string|null;sort_order:number|null;parent_id:string|null;is_active?:boolean|null};
const ATHLETE_NAV_BY_AGE:Record<string,string[]>={'5-8':['Overview'],'9-11':['Overview','Goals','Achievements'],'12-14':['Overview','Development','Goals','Achievements'],'15-17':['Overview','Performance','Development','Goals','Documents','Recruiting'],'18+':['Overview','Passport','Performance','Development','Documents','Recruiting']};
function buildSections(rows:DbNavRow[],hubId:string){const map=new Map<string,NavigationItem>(),roots:NavigationItem[]=[];for(const row of rows)map.set(row.nav_id,{id:row.nav_id,label:row.label,href:row.path||undefined,icon:row.icon||undefined,description:row.description||undefined,sort_order:row.sort_order||0,children:[]});for(const row of rows){const item=map.get(row.nav_id);if(!item)continue;if(row.parent_id&&map.has(row.parent_id))map.get(row.parent_id)?.children?.push(item);else roots.push(item)}roots.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));for(const item of roots)item.children?.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));const sections:NavigationSection[]=[],parents=roots.filter(i=>i.children?.length),standalone=roots.filter(i=>!i.children?.length);for(const p of parents)sections.push({id:p.id,label:p.label.toUpperCase(),items:p.children||[]});if(standalone.length)sections.unshift({id:`${hubId}-main`,label:hubId.toUpperCase(),items:standalone});return sections.filter(s=>s.items.length)}
export async function getNavigation(hubId:string,switcherValue=''){if(!hubId)return[];const supabase=getSupabaseClient();if(!supabase)return[];try{const{data,error}=await supabase.from('hub_navigation').select('nav_id,label,path,icon,description,sort_order,parent_id,is_active').eq('hub_id',hubId).eq('is_active',true).order('sort_order',{ascending:true});if(error||!data?.length)return[];let rows=data as DbNavRow[];if(hubId==='athlete'){const allowed=new Set(ATHLETE_NAV_BY_AGE[switcherValue]||ATHLETE_NAV_BY_AGE['5-8']);rows=rows.filter(r=>allowed.has(r.label))}return buildSections(rows,hubId)}catch{return[]}}
export async function getSwitcherConfig(hubId:string):Promise<SwitcherConfig>{if(hubId==='athlete')return{type:'age',displayStyle:'radio',defaultOption:'5-8',options:[{id:'5-8',label:'Foundation · Ages 5–8'},{id:'9-11',label:'Development · Ages 9–11'},{id:'12-14',label:'Growth · Ages 12–14'},{id:'15-17',label:'Performance · Ages 15–17'},{id:'18+',label:'Advanced · 18+'}]};if(hubId==='official')return{type:'official_role',displayStyle:'radio',defaultOption:'official',options:[{id:'official',label:'Official'},{id:'meet_referee',label:'Meet Referee'},{id:'starter',label:'Starter'},{id:'stroke_turn',label:'Stroke & Turn'},{id:'judge',label:'Judge'},{id:'meet_director',label:'Meet Director'}]};return{type:null,displayStyle:'none',options:[],defaultOption:''}}
